### PR TITLE
fix(auth): redirect users signing in from landing page to /learn

### LINKED ISSUE #62905: Redirect users who sign in from the landing page to /learn
While it makes sense to return users to the page they signed in from, redirecting users who sign in from / to /learn help users choose a certification and start learning.

The changes were introduced here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/61218/files

### PR DESCRIPTION
**Pull request by Jamesren64**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #62905

### CODE REVIEW

**Comment by ahmaxed** [comment]
please add tests to lock this down.

File: api/src/utils/redirection.ts [hunk 1]
```diff
@@ -156,7 +156,14 @@ export function getLoginRedirectParams(
 ): RedirectParams {
   const signedUrl = req.cookies['login-returnto'];
   const url = signedUrl ? req.unsignCookie(signedUrl).value : null;
-  return getParamsFromUrl(url, _normalizeParams);
+  const params = getParamsFromUrl(url, _normalizeParams);
+
+  if (haveSamePath(params.origin, params.returnTo)) {
+    const prefixSegment = params.pathPrefix ? `/${params.pathPrefix}` : '';
```
Comment (ahmaxed) [inline api/src/utils/redirection.ts]: prefixSegment is not necessary here.
params.returnTo = `${params.origin}/learn`; should be sufficient.

Comment (Jamesren64) [reply api/src/utils/redirection.ts]: This is done!

**Comment by ahmaxed** [comment]
The changed redirection function was interfering with the error handling, so I moved the logic to auth0 where it used to be.

**Review by ahmaxed — APPROVED** [review]
