### PR TITLE
fix: signout redirect

### LINKED ISSUE #41898: Logging out in espanol redirects to english home page
If I am signed in as a user while on freecodecamp.org/espanol and log out, I am redirected to the english home page. chinese.freecamp.org redirects to the chinese page.

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #41898

Think this should address the redirect on signout bug.

The issues I saw were:
- pathPrefix was not grabbing correct array element (the `split` call was grabbing the empty string that comes from the path starting with `/`).
- /signout redirect was not using returnTo URL. Instead it redirected to origin, which (except for chinese) will always be www.freecodecamp.org with no path.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
We can't check this locally, because there isn't a special `devLogout`. It just uses the standard `getRedirectParams` which ignores the referer since it doesn't trust `localhost`.  Not a *huge* deal for dev experience, but it does mean this is another thing we'll have to validate on staging.

Anyway, thanks for fixing the bug @nhcarrigan, this LGTM :+1:

File: api-server/src/server/component-passport.js [hunk 1]
```diff
@@ -85,13 +86,22 @@ export const devSaveResponseAuthCookies = () => {
...
+        return {
+          returnTo,
+          origin,
+          pathPrefix
+        };
+      }
     );
     returnTo += isRootPath(getRedirectBase(origin, pathPrefix), returnTo)
-      ? 'learn'
+      ? '/learn'
```
Comment (ShaunSHamilton) [inline api-server/src/server/component-passport.js:104]: Maybe it is GitPod, but this change causes:
```
https://8000-emerald-capybara-b8ln1x5v.ws-eu08.gitpod.io//learn
```

Comment (ojeytonwilliams) [reply api-server/src/server/component-passport.js:104]: Could you provide steps to reproduce?  I can't replicate the bug in Gitpod.

Comment (ShaunSHamilton) [reply api-server/src/server/component-passport.js:104]: Add this:
```javascript
returnTo += isRootPath(getRedirectBase(origin, pathPrefix), returnTo)
      ? '/learn'
      : '';
console.log(returnTo);
```
2) Navigate to the main landing page
3) Sign out
4) Sign in
5) Look in server console

Comment (ShaunSHamilton) [reply api-server/src/server/component-passport.js:104]: On `.dev`:
```console
Navigated to https://www.freecodecamp.dev//learn?messages=success%5B0%5D%3Dflash.signin-success
```

Comment (ShaunSHamilton) [reply api-server/src/server/component-passport.js:104]: It does not break anything, but it still concerns me:
```
Request URL: https://www.freecodecamp.dev//learn?messages=success%5B0%5D%3Dflash.signin-success
```

Comment (ojeytonwilliams) [reply api-server/src/server/component-passport.js:104]: For context: we discussed this in chat and realised that this behaviour is nothing to do with this PR.

**Review by raisedadead — APPROVED** [review]
