### PR TITLE
fix: tighten up ensure-env and env.js

### LINKED ISSUE #39674: Default upcoming changes to false, and do not look for it
```
freecodecamp@stg-vm-api-alpha:~/freeCodeCamp$ npm run ensure-env && npm run build:server

> @freecodecamp/freecodecamp@0.0.1 ensure-env /home/freecodecamp/freeCodeCamp
> cross-env DEBUG=fcc:* node ./tools/scripts/build/ensure-env.js

/home/freecodecamp/freeCodeCamp/tools/scripts/build/ensure-env.js:45
      throw Error(`Env. variable ${key} is missing, build cannot continue`);
      ^

Error: Env. variable showUpcomingChanges is missing, build cannot continue
    at Object.<anonymous> (/home/freecodecamp/freeCodeCamp/tools/scripts/build/ensure-env.js:45:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 ensure-env: `cross-env DEBUG=fcc:* node ./tools/scripts/build/ensure-env.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 ensure-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/freecodecamp/.npm/_logs/2020-09-24T16_38_54_905Z-debug.log
```

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@raisedadead I put in a couple of specific checks to confirm nothing deeply weird was happening.

Closes: https://github.com/freeCodeCamp/freeCodeCamp/issues/39674

### CODE REVIEW

File: tools/scripts/build/ensure-env.js [hunk 1]
```diff
@@ -45,6 +45,12 @@ if (FREECODECAMP_NODE_ENV === 'production') {
       throw Error(`Env. variable ${key} is missing, build cannot continue`);
     }
   }
+
+  if (env['environment'] !== 'production')
+    throw Error("Production environment should be 'production' ");
+
+  if (env['showUpcomingChanges'])
```
Comment (RandellDawson) [inline tools/scripts/build/ensure-env.js:52]: @ojeytonwilliams I did not dig to deep into the code, but is `showUpComdingChanges` a string (from an environment variable) or is it actually a Boolean here?  If the former, then this check would only be `false` if it is an empty string.

Comment (ojeytonwilliams) [reply tools/scripts/build/ensure-env.js:52]: It's a boolean by this point,  `showUpcomingChanges: showUpcomingChanges === 'true'`, the main thing is that it should never be truthy in production.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Review by raisedadead — APPROVED** [review]
