### PR TITLE
fix(client): reduce gap between action row and breadcrumbs

### LINKED ISSUE #66268: [Suggestion]: Remove top margin in Interactive editor
Even though the current UI is not bad, when there are only 1–2 lines between two interactive editor, the margin feels a little odd (this is my personal opinion and may vary for others). 

Also, removing the margin from the top would make the interactive editor feel more connected to the text in the line above.

<details>
  <summary>Click to expand images</summary>

  <p>
    <strong>Current</strong><br/>
    Current
  </p>

  <p>
    <strong>Suggested</strong><br/>
    Suggested
  </p>

</details>

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #66268

| Before | After |
| --- | --- |
| Screenshot 2026-03-10 at 04 34 18 | Screenshot 2026-03-10 at 04 32 26 |
| Screenshot 2026-03-11 at 04 37 38 | Screenshot 2026-03-11 at 04 37 10 |

### CODE REVIEW

**Comment by raisedadead** [comment]
For what its worth having a whole sticky row dedicated to one button doesn't sit well. Could we move the button alongside the breadcrumb so we have something like:

image

I thing that would save a lot of real estate?

**Comment by huyenltnguyen** [comment]
It... depends.

The action row can have multiple buttons, depending on the type of challenge. For example:
- Coding challenges can have five buttons

  <details>
  <summary>Screenshot</summary>
  
  Screenshot 2026-03-10 at 18 17 07

  </details>
- Reviews can have two (this is not yet available in prod - #65897)
    <details>
    <summary>Screenshot</summary>
    
  Screenshot 2026-03-10 at 18 21 30

    </details>
- Theory challenges have just one button (as shown in the PR description)

---

We are/were also considering adding more levels to the breadcrumbs (#62907):

```
Current:
superblock -> block

Proposed:
superblock -> chapter -> module -> block
```

So the breadcrumbs will be quite busy and need as much space as possible.

**Comment by ahmaxed** [comment]
I am thinking of moving the breadcrumb along with the following navigational items in a drawer menu. We could get this ine, but the breadcrumbs will be removed in an upcoming pr. I will share the mocks in an issue this week.

**Comment by moT01** [comment]
This does not appear to close the linked issue to me. It seems like that issue is talking about the space between two separate interactive editors - if it's small (1-2 lines of text), it looks weird. And I think the margin mentioned there is the margin between the paragraph text and the interactive editor.

Even though there's a big red arrow in the images here, it took me a second to notice what it was showing me. Yes, the smaller margin in the action row is better 👍

One other note - the daily challenges also have the language selector in the action row...

<details><summary>image</summary>

Screenshot 2026-03-10 at 10 42 42 AM



</details>

File: client/src/templates/Challenges/generic/show.tsx [hunk 1]
```diff
@@ -85,13 +85,9 @@ function renderNodule(
     case 'interactiveEditor':
       if (showInteractiveEditor) {
         return (
-          <>
-            <Spacer size='s' />
```
Comment (huyenltnguyen) [inline client/src/templates/Challenges/generic/show.tsx:89]: These `Spacer`s around InteractiveEditor are not needed because:
- Each `p` has a bottom margin, which should add sufficient space between the editor and the paragraph before it
- Each interactive editor has a bottom margin, which should add sufficient space between the editor and the paragraph after it.

**Review by huyenltnguyen — COMMENTED** [review]
Sorry, I misread the issue description 😅 

I had tunnel vision because I was looking at #65897 right before the issue and was focused on the gap in the action row.

PR updated and screenshots added to the description.

File: client/src/templates/Challenges/generic/show.tsx (hunk 1 above)
Comment (AdityaSingh-18) [reply client/src/templates/Challenges/generic/show.tsx:89]: Can we keep the bottom spacer? 

Like this:

559170110-b70877ea-0977-4aa6-947e-c4025aba42d7

Comment (huyenltnguyen) [reply client/src/templates/Challenges/generic/show.tsx:89]: I don't think that extra space is needed, to be honest.

**Review by Sembauke — APPROVED** [review]
