### PR TITLE
fix(tools): update error message for hints without tests

### LINKED ISSUE #63874: more clear error message (challenge parser utils)
currently, if is some of curriculum `md` files of workshop or lab has a paragraph at hints section without a tests section after it - 
it  prints not so clear to me error message at console:

Image

i think will be more clear to change it to `a paragraph must have a tests section (```js) after it`

### PR DESCRIPTION
**Pull request by MeaslyDay**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitHub Codespaces. [**I was unable to reproduce the error message, but have indeed run these changes with GitHub Codespaces**]

Closes #63874

**Requested changes:**
Update the error message in these two files:
https://github.com/freeCodeCamp/freeCodeCamp/blob/a28ff5d2cd0bc85d9b7f22eb452a33007845ce51/tools/challenge-parser/parser/plugins/add-tests.js#L11
and
https://github.com/freeCodeCamp/freeCodeCamp/blob/a28ff5d2cd0bc85d9b7f22eb452a33007845ce51/tools/challenge-parser/parser/plugins/add-tests.test.js#L45

The new error message is as follows: Hints must be in pairs: each hint text followed by a test code block

In the original issue #63874 discussion suggests the same new error message but with a period at the end. I removed this for consistency.

The requested changes were simple lines text for two errors. This change was easy enough. However, I must admit I do not know where these errors are outputted or what the challenge parser (directory for the files in question) does. I believe it has to do with dev tools. I attempted to verify the error message manually by tinkering with the --hints-- section of challenge id: 66ed41f912d0bb1dc62da5dd. However, this challenge does not seem to use this parser at all, it only uses tools/client_plugins/browser-scripts/test-runner.js. I hope that this addition can be accepted even with my inability to check the actual error message.

### CODE REVIEW

**Review by shootermv — COMMENTED** [review]
looks good to me...

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @MeaslyDay, this LGTM.

If you're curious, these errors can be thrown whenever the challenges are used. For example, when the curriculum is tested (`pnpm test`) or built (`pnpm build:curriculum`)

File: tools/challenge-parser/parser/plugins/add-tests.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ function plugin() {
   function transformer(tree, file) {
     const hintNodes = getSection(tree, '--hints--');
     if (hintNodes.length % 2 !== 0)
-      throw Error('Tests must be in (text, ```testString```) order');
+      throw Error('Hints must be in pairs: each hint text followed by a test code block');
```
Comment (huyenltnguyen) [inline tools/challenge-parser/parser/plugins/add-tests.js]: The lint check failed because the string needs to be on a different line.

```suggestion
      throw Error(
        'Hints must be in pairs: each hint text followed by a test code block'
      );
```
