### PR TITLE
fix(bug): Make table and button consistent in settings and certification page.

### LINKED ISSUE #45949: View button on new RWD certs looks out of place
### Describe the Issue

The links to projects on the new RWD certs have a 'view' button (see screenshots). All other certs have text links.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/certification/fccb1/responsive-web-design
2. See 'view' button
3. Go https://www.freecodecamp.org/mot01
4. Click on any cert
5. See text links, not view button

### Expected behavior

Change the 'view' button to two text links similar to the URL + github URL solution in the image below. I would go with `code` and `preview` or `code` and `project`.

### Screenshots

New RWD certs:
Screen Shot 2022-02-23 at 12 14 16 PM
^ landing page has a URL (codepen) solution - others have the multifile editor solution

Here's what the URL + github URL solutions look like:
Screen Shot 2022-02-23 at 12 22 35 PM

### PR DESCRIPTION
**Pull request by nayabatir1**
Affected page
- certification page
- settings page

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #45949 

Affected pages
- settings
- certification

image
image

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
Thanks for the pr. 
Quick notes:
- The buttons should say "View", and there should be <th> elements for "Project name", "Solution", and "Completed"
- Only Timeline and Certification tables would have condensed={true} striped={true}

**Comment by nayabatir1** [comment]
For long challenges with long title, it's content are wrapped. So I've also increased table width.

### Before
image


### After
image

**Review by naomi-lgbt — DISMISSED** [review]
banger pr, thanks for contributing!

File: client/src/client-only-routes/show-project-links.tsx [hunk 1]
```diff
@@ -90,6 +91,7 @@ const ShowProjectLinks = (props: ShowProjectLinksProps): JSX.Element => {
   };
 
   const renderProjectsFor = (certName: string) => {
+    console.log(certName);
```
Comment (Sboonny) [inline client/src/client-only-routes/show-project-links.tsx:94]: Stray log
```suggestion
```

File: client/src/client-only-routes/show-project-links.tsx [hunk 2]
```diff
@@ -160,7 +161,10 @@ const ShowProjectLinks = (props: ShowProjectLinksProps): JSX.Element => {
         { user: name }
       )}
       <Spacer />
-      <ul>{renderProjectsFor(certName)}</ul>
+      <Table striped>
+        <thead></thead>
```
Comment (Sboonny) [inline client/src/client-only-routes/show-project-links.tsx:165]:
```suggestion
````

How is this used and is it beneficial for you to remove them?

File: client/src/components/profile/components/time-line.tsx [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import { Button, Modal, Table } from '@freecodecamp/react-bootstrap';
 import Loadable from '@loadable/component';
-import { useStaticQuery, graphql } from 'gatsby';
+import { graphql, useStaticQuery } from 'gatsby';
```
Comment (Sboonny) [inline client/src/components/profile/components/time-line.tsx:3]: Tf why is graphql in gatspy. 🤣

File: client/src/components/profile/components/time-line.tsx [hunk 4]
```diff
@@ -165,62 +165,60 @@ function TimelineInner({
...
+      {totalPages > 1 && (
+        <TimelinePagination
+          firstPage={firstPage}
+          lastPage={lastPage}
+          nextPage={nextPage}
+          pageNo={pageNo}
+          prevPage={prevPage}
+          totalPages={totalPages}
+        />
+      )}
```
Comment (Sboonny) [inline client/src/components/profile/components/time-line.tsx:221]: > there should be elements for "Project name", "Solution", and "Completed"

How did you address this, btw? because I think I am misunderstanding it as adding `<span class='sr-only'>Project name</span>`. :thinking:

**Review by Sboonny — COMMENTED** [review]
Small nitpicks and one question about Ahmad previous comment https://github.com/freeCodeCamp/freeCodeCamp/pull/48211#issuecomment-1288818880

File: client/src/components/profile/components/time-line.tsx (hunk 3 above)
Comment (nayabatir1) [reply client/src/components/profile/components/time-line.tsx:3]: 🤷

File: client/src/components/profile/components/time-line.tsx (hunk 4 above)
Comment (nayabatir1) [reply client/src/components/profile/components/time-line.tsx:221]: The only thing I did in this file is increase the table width as all three columns were already there line:184. 
You can check `renderCompletion` function.

Comment (Sboonny) [reply client/src/components/profile/components/time-line.tsx:221]: So I was misunderstanding, thank you for conforming

https://github.com/freeCodeCamp/freeCodeCamp/blob/898a9331a6b5889f2a4122f379b2022a73aae4ea/client/src/components/profile/components/time-line.tsx#L118-L150=plain?1

**Review by moT01 — DISMISSED** [review]
I gave this some testing, it’s looking good @nayabatir1. Here's everything I found that I think is specifically related to this PR...

-One main thing I noticed is that this doesn't appear to create a common component, [as described here](https://github.com/freeCodeCamp/freeCodeCamp/issues/45949#issuecomment-1265138478), that all the tables use. I don't think that's a big issue - although, I think it would have been nice and simplified things a bit. I would be fine without it.

-On the certifications, the project name is not vertically centered in the table row:
Screen Shot 2022-10-31 at 4 43 14 PM

-On the settings page, the table has stripes - it was [mentioned above](https://github.com/freeCodeCamp/freeCodeCamp/pull/48211#issuecomment-1288818880) that only the other two places should have stripes. I think that's what that means, anyway. So, I think we want to remove them there. Can you confirm @ahmadabdolsaheb.

I think if we fixed those second two things, we could probably get this in - however...

<hr>

Here’s some other things I noticed that were likely pre-existing and not from this PR or specifically part of the issue - but I’m going to bring them up in case we want to fix any of them here.

-Probably common on all the tables, but most noticeable on the profile timeline - the view button (solution and completed column) have different widths depending on the length of the title. Sometimes quite skinny, and other times, very wide. I would like to see those two columns have a fixed width. Something that might have been easier to fix with that common component. 

-On the JavaScript certification, the links use "solution" text instead of view button:
Screen Shot 2022-10-31 at 4 54 38 PM
And actually, the titles there are vertically centered, so it must be the view button that is causing them not to be.

I gave this a rebase locally cause it didn't have the [icons added here](https://github.com/freeCodeCamp/freeCodeCamp/pull/48268) when I ran it. Noticed that the view button on the certifications don't have that icon.

<hr>

I guess one other thing related to this PR...
> For challenges with long title, its content are wrapped. So I've also increased the table width.

I don't really mind that, I think it looks good - but we have a pretty standard margin on most of the pages (not all), and this deviates from that. Maybe @ahmadabdolsaheb can weigh in on that, as well.

**Comment by ahmadabdolsaheb** [comment]
Thanks for taking a look Tom.

> For challenges with long title, its content are wrapped. So I've also increased the table width.

That would not be necessary. They will eventually wrap if you view most of the titles on smaller screens. We would need to keep the spacing similar across tables.

> One main thing I noticed is that this doesn't appear to create a common component, https://github.com/freeCodeCamp/freeCodeCamp/issues/45949#issuecomment-1265138478, that all the tables use. I don't think that's a big issue - although, I think it would have been nice and simplified things a bit. I would be fine without it.

Having one single component will also help with migration to component library. So, it would be great to have it now.

> On the settings page, the table has stripes - it was https://github.com/freeCodeCamp/freeCodeCamp/pull/48211#issuecomment-1288818880 that only the other two places should have stripes. I think that's what that means, anyway. So, I think we want to remove them there. Can you confirm @ahmadabdolsaheb.

Settings page should not be condensed or striped, the other two tables should.

**Comment by nayabatir1** [comment]
> That would not be necessary. They will eventually wrap if you view most of the titles on smaller screens. We would need to keep the spacing similar across tables.

I've reverted time-line table width to original.

> Having one single component will also help with migration to component library. So, it would be great to have it now.

I did plan to create table component but we are using bootstrap `Table` which is itself a component and each page has their own header and body. So, how are we planning to make it reusable.

> Settings page should not be condensed or striped, the other two tables should.

I've removed stripe props from settings table.

**Comment by ahmadabdolsaheb** [comment]
Thanks for implementing the changes. As you suggested all tables do not need to be in one table component.

The certification would need a <thead>, and 'solution' need to be a 'View' button similar to the timeline.

The project titles should not be bold on the certifications. Basically, similar elements should look similar on all tables.

Finally, we do have 'View' translated on buttons.view. As a result, adding a new key is not necessary.

**Comment by ahmadabdolsaheb** [comment]
You would need table header elements, here is an example:
```js
            <thead>
              <tr>
                <th>{t('profile.challenge')}</th>
                <th>{t('settings.labels.solution')}</th>
```

**Comment by nayabatir1** [comment]
image
For above links shall I convert it to button too?
Also shall I add another column for source ?

**Comment by ahmadabdolsaheb** [comment]
> image For above links shall I convert it to button too?

Yes, those are gonna become a view dropdown button. Here is an example we are using in settings: 

Screen Shot 2022-11-15 at 10 13 33 AM

File: client/src/components/solution-display-widget/index.tsx [hunk 5]
```diff
@@ -30,34 +30,44 @@ export function SolutionDisplayWidget({
...
+          <MenuItem bsStyle='primary'>
+            <a href={solution ?? ''} rel='noopener noreferrer' target='_blank'>
+              {t('certification.project.solution')}
+            </a>
+          </MenuItem>
+          <MenuItem bsStyle='primary'>
+            <a href={githubLink} rel='noopener noreferrer' target='_blank'>
+              {t('certification.project.source')}
+            </a>
+          </MenuItem>
```
Comment (Sboonny) [inline client/src/components/solution-display-widget/index.tsx:56]: `MenuItem` is an anchor element, I hope. So you don't need to add an anchor element as its child, you can move the attributes to `MenuItem`

File: client/src/components/solution-display-widget/index.tsx [hunk 6]
```diff
@@ -156,5 +166,7 @@ export function SolutionDisplayWidget({
           none: MissingSolutionComponent
         };
 
+  console.log(getSolutionDisplayType(completedChallenge));
+
```
Comment (Sboonny) [inline client/src/components/solution-display-widget/index.tsx:170]:
```suggestion
```

File: client/src/components/solution-display-widget/index.tsx (hunk 5 above)
Comment (Sboonny) [reply client/src/components/solution-display-widget/index.tsx:56]: because menuItem doesn't have href prop in it, it has button role which we don't want as it may confuse screen reader.

Comment (nayabatir1) [reply client/src/components/solution-display-widget/index.tsx:56]: Just to summarize
I've to modify menuItem component to accept href prop too and remove anchor tag child correct?

Comment (Sboonny) [reply client/src/components/solution-display-widget/index.tsx:56]: I don't think you need to modify menuItem because it accepts the href prop. But yes, please remove the anchor tag child 👍 

https://github.com/freeCodeCamp/freeCodeCamp/blob/4e14899e1ce3f1b6f3ef4a5deb24240066b4baef/client/src/components/solution-display-widget/index.tsx#L115-L130

**Comment by ahmadabdolsaheb** [comment]
> image
> 
> @ahmadabdolsaheb in certification page dropdown width is not 100% of column width, though I've reused dropdown button code. Let me know if you prefer width to be 100%

The drop-downs should look consistant across the UI. Yes it should take full width.

File: client/src/components/solution-display-widget/index.tsx [hunk 7]
```diff
@@ -7,7 +7,7 @@ import React from 'react';
 import { useTranslation } from 'react-i18next';
 import { CompletedChallenge } from '../../redux/prop-types';
 import { getSolutionDisplayType } from '../../utils/solution-display-type';
-
+import './style.css';
```
Comment (Sboonny) [inline client/src/components/solution-display-widget/index.tsx:10]:
```suggestion
```

File: client/src/components/solution-display-widget/index.tsx [hunk 8]
```diff
@@ -35,32 +35,30 @@ export function SolutionDisplayWidget({
     </Button>
   );
   const ShowProjectAndGithubLinkForCertification = (
-    <div className='solutions-dropdown'>
-      <DropdownButton
-        block={true}
+    <DropdownButton
+      block={true}
+      bsStyle='primary w-100'
+      className='btn-invert'
```
Comment (Sboonny) [inline client/src/components/solution-display-widget/index.tsx:41]:
```suggestion
      className='btn-invert col-xs-12'
```

File: client/src/components/solution-display-widget/style.css [hunk 9]
```diff
@@ -0,0 +1,4 @@
+.w-100,
+.w-100 > .dropdown-menu {
+  width: 100%;
+}
```
Comment (Sboonny) [inline client/src/components/solution-display-widget/style.css:4]:
```suggestion
```

**Review by Sboonny — COMMENTED** [review]
I have tried to use CSS module in a previous PR, too. https://github.com/freeCodeCamp/freeCodeCamp/pull/45964/files

But there is no need for it, we are still using bootstrap. className `col-xs-12` should make them alike

File: client/src/components/solution-display-widget/style.css (hunk 9 above)
Comment (nayabatir1) [reply client/src/components/solution-display-widget/style.css:4]: Hey I looked into your proposed solution `col-xs-12`, it didn't worked for `MenuItem`
`DropdownButton` and `MenuItem` both should have `width` of `100%`. Otherwise only `View` button will have full width and not `MenuItem`

using my custom css `w-100`
image


using `col-xs-12`
image

Which one you would prefer ?

Comment (Sboonny) [reply client/src/components/solution-display-widget/style.css:4]: Thank you for checking it out, if it doesn't look right. Let me see if there is a class in the codebase there with the changes, that make our life easier to update all of them later.

Comment (nayabatir1) [reply client/src/components/solution-display-widget/style.css:4]: Sure, `.dropdown-menu` is the class of `ul` element which `MenuItem` adds dom. I'm using that class  to update its width to 100%

Comment (Sboonny) [reply client/src/components/solution-display-widget/style.css:4]: Oh, I mean using the styles in `time-line.css`, as this component is doing the same thing and almost have the same style, we can use the same file

Comment (nayabatir1) [reply client/src/components/solution-display-widget/style.css:4]: from `timeline.css`
```css
.timeline-row .solutions-dropdown .dropdown {
  width: 100%;
}
```
It didn't worked as `.dropdown` don't have any parent element with class `solutions-dropdown` whose parent class is `timeline-row`

Comment (Sboonny) [reply client/src/components/solution-display-widget/style.css:4]: True, adding `<div className='.solutions-dropdown'>` as parent gives width `100%`.

image

and it will look the same as functions below it 

https://github.com/freeCodeCamp/freeCodeCamp/blob/6ad3a78db1fd6bf37a56db700fc33e3fb9cb424a/client/src/components/solution-display-widget/index.tsx#L90-L105

Comment (Sboonny) [reply client/src/components/solution-display-widget/style.css:4]: I have been checking the wrong certification the whole time?

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

File: client/src/components/solution-display-widget/style.css (hunk 9 above)
Comment (nayabatir1) [reply client/src/components/solution-display-widget/style.css:4]: Nope, adding parent element with class name as `.solutions-dropdown` didn't worked either. Check quality-assurance-v7 certification.

**Comment by bbsmooth** [comment]
So of course I'm going to rain on the parade a little here. I apologize for not evaluating this sooner for accessibility. I didn't realize there was a drop down menu button.

Concerning that drop down View button, I would recommend we not use the menu roles on the list and list items. These are really just a list of links and thus no menu roles are needed (see our main Menu navigation). When a screen reader user hears that this is a menu then they expect it to act in a certain way and be composed of action items that do something, not merely links that open a new page. 

Really, this just needs to be a button with `aria-expanded` and then a plain list with no roles. You can keep the arrow navigation if you want but it is not necessary. The user should be able to tab through the list items though. And definitely keep the `Esc` key for closing the expanded list.

But if you want to keep this as an actual "menu" interface then there are a few things that need to be fixed. I will hold off on that until I know which way you want to proceed.

**Comment by ahmadabdolsaheb** [comment]
Thank you @bbsmooth for the valuable insights. It seems like we would need to create a custom component with custom styles if we want to go with the simple button and list. 

Since the current dropdown menu is closest to what we need in the react-bootstrap component library, could you please let us know what needs to be fixed in order to make it more accessible?

Also, since the dropdown menu already exist on the settings tables, should we dedicate an issue to discuss its accessibility independently once this pr is in?

**Comment by ahmadabdolsaheb** [comment]
sorry for the double tag @bbsmooth, just wanted to make sure this pr didn't get lost in the notifications :)

**Comment by bbsmooth** [comment]
Hey @ahmadabdolsaheb, the current accessibility on these view buttons is not terrible, there are just a few things that could be improved regarding the functionality of the menu button itself and the overall accessibility of how they are being used in the table. It's probably best if I create separate issues for these things after this PR has been merged.

**Review by ahmaxed — APPROVED** [review]

**Review by Sboonny — APPROVED** [review]
