### PR TITLE
Fix the navbar links so control-clicking opens them in a new tab

### LINKED ISSUE #7493: Control-clicking links should open them in a new tab
This applies to the Map, Chat and Wiki links in the menu bar.

### PR DESCRIPTION
**Pull request by george-stepanek**
The default behaviour for control-clicking links is to open them in a new tab., but this behaviour is currently broken in FCC's navbar for the Map, Chat and Wiki links when the page is viewed on a larger screen.

(closes #7493) 

This change fixes it by checking the event.ctrlKey flag, and if true it allows the default behaviour for the link and does not pull out the side bar.

### CODE REVIEW

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Tested on Chrome, Firefox & IE on Windows.
Can anyone confirm if this works on Safari, etc. on OSX

/cc @hallaathrad

**Comment by BerkeleyTrue** [comment]
Hey @george-stepanek 
Nice work. One more thing is needed to get this into production. 

On OSX, the `cmd` key is used instead of `ctrl` so in order to get it to work for both, you'll need to check for the `ctrlKey` and the `metaKey` attributes. You can read about it [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey)

**Comment by george-stepanek** [comment]
Thanks, @BerkeleyTrue, I have amended the commit per your recommendation...

File: client/main.js [hunk 1]
```diff
@@ -97,7 +97,11 @@ main = (function(main, global) {
     });
 
 
-    $('#nav-chat-btn').on('click', toggleMainChat);
+    $('#nav-chat-btn').on('click', function(event) {
+      if (!event.ctrlKey && !event.metaKey) {
```
Comment (BerkeleyTrue) [inline client/main.js]: These should be `(!event.ctrlKey || !event.metaKey)` as they will never be both.

Comment (george-stepanek) [inline client/main.js]: Um, surely you mean ```!(event.ctrlKey || event.metaKey)``` -- which is equivalent to ```(!event.ctrlKey && !event.metaKey)``` ?

Comment (hallaathrad) [inline client/main.js]: yeah @george-stepanek. What you've said :)
Please?

Comment (BerkeleyTrue) [inline client/main.js]: @george-stepanek Ah you are correct. But `!(event.ctrlKey || event.metaKey)` IMHO is much more descriptive than `(!event.ctrlKey && !event.metaKey)` @hallaathrad What do you think?

Comment (hallaathrad) [inline client/main.js]: Agreed. You know I'll always prefer declarative coding. And it's worth considering it may not be both, but one at a time... so :+1: I'm in for that change

Comment (BerkeleyTrue) [inline client/main.js]: Awesome, @george-stepanek if you can make that change than this PR can be merged.

**Comment by george-stepanek** [comment]
Thanks, @BerkeleyTrue and @hallaathrad, I've just now included that change...
