### PR TITLE
Handle invalid unsubscriptions

### LINKED ISSUE #7686: Check for returned user object in unsubscribe logic
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/randomAPIs.js#L295 and https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/randomAPIs.js#L309 does not verify whether the query actually returns a user instance, causing the server to crash hard and reboot.

Anyone up to adding a check for the user object on these?

### PR DESCRIPTION
**Pull request by BKinahan**
Add logic to handle requests to server for e-mail unsubscribe URLs when a matching user is not found.

Redirects to /map and informs the user to update e-mail settings from their profile.

Tested locally for each link, for both valid and invalid e-mail addresses, and passes `npm test`.

Closes #7686.

### CODE REVIEW

**Comment by virus79** [comment]
Den 21 mar 2016 23:25 skrev "BKinahan" <notifications@github.com>:
>
> Add logic to handle requests to server for e-mail unsubscribe URLs when a
matching user is not found.
>
> Redirects to /map and informs the user to update e-mail settings from
their profile.
>
> Tested locally for each link, for both valid and invalid e-mail
addresses, and passes npm test.
>
> Closes #7686.
>
> ________________________________
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7690
>
> Commit Summary
> Handle invalid unsubscriptions
http://www.pornhub.com/video?o=ht

File: server/boot/randomAPIs.js [hunk 1]
```diff
@@ -292,13 +292,21 @@ module.exports = function(app) {
...
         req.flash('info', {
-          msg: 'We\'ve successfully updated your Email preferences.'
+          msg: 'Email address not found. ' +
+          'Please update your Email preferences from your profile.'
         });
-        return res.redirect('/unsubscribed');
-      });
+        return res.redirect('/map');
+      } else {
+        return user.updateAttribute('sendMonthlyEmail', false, (err) => {
```
Comment (BerkeleyTrue) [inline server/boot/randomAPIs.js]: This `else` is unnecessary. You can remove it and outdent the content. Same goes for the block below.

**Comment by BerkeleyTrue** [comment]
LGTM
