### PR TITLE
fix: add spacer above footer

### LINKED ISSUE #35061: Whitespacing on footer
The footer is crammed on the Curriculum and the Guide pages:

image

This needs to be uniform with whitespace like on th welcome page:
image

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35061

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

File: client/src/components/layouts/Default.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ import { bindActionCreators } from 'redux';
 import { createSelector } from 'reselect';
 import Helmet from 'react-helmet';
 import fontawesome from '@fortawesome/fontawesome';
+import { Grid, Col, Row } from '@freecodecamp/react-bootstrap';
```
Comment (ValeraS) [inline client/src/components/layouts/Default.js]: Where is it used?

**Review by ValeraS — CHANGES_REQUESTED** [review]

**Comment by raisedadead** [comment]
@ahmadabdolsaheb lets address the comment on this PR and get this in. This looks fine enough to me. We can iterate as we progress.

Thanks.

File: client/src/components/layouts/Default.js (hunk 1 above)
Comment (ahmadabdolsaheb) [reply client/src/components/layouts/Default.js]: thanks for noticing it. @ValeraS  I removed that line.
