### PR TITLE
fix(curriculum): use mediaText for CSSHelp

### LINKED ISSUE #42354: I think we broke something with Safari...again.
Challenge: https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/create-a-media-query

Forum Post: https://forum.freecodecamp.org/t/no-idea-why-is-not-giving-me-the-pass/463327

I have only tested this using LambdaTest.

macOS Mojave Safari
macOS-Mojave-Safari

macOS Mojave Chrome
macOS-Mojave-Chrome

I assume it's related to https://github.com/freeCodeCamp/freeCodeCamp/pull/42148 but I can't really do much testing with Safari or MacOS (just have a few free minutes on lambda test).

@moT01 can you help take a look at this when you have time?

---

Speaking of which, I really wish we had a deal with one of the cross-browser testing places (BrowserStack, LambdaTest, whatever). It would really help us do better cross-browser testing.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42354

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1:

**Review by lasjorg — COMMENTED** [review]
Edit: Not sure what happened.

File: client/src/utils/css-help.ts [hunk 1]
```diff
@@ -86,6 +86,7 @@ class CSSHelp {
     const link: HTMLLinkElement | null = this.doc?.querySelector(
       "link[href*='styles']"
     );
+    // Most* browser extensions inject styles with class/media attributes
     const style: HTMLStyleElement | null = this.doc?.querySelector(
       'style:not([class][media])'
     );
```
Comment (lasjorg) [inline client/src/utils/css-help.ts]: Not sure what happened to my code selection, I'm talking about this selector

**Review by lasjorg — COMMENTED** [review]
Just so I'm clear.

Is this selector meant to only match when the style element doesn't have *both* attributes? Or should it be either and/or both?

File: client/src/utils/css-help.ts (hunk 1 above)
Comment (ShaunSHamilton) [reply client/src/utils/css-help.ts]: It must not have either.

Comment (lasjorg) [reply client/src/utils/css-help.ts]: Maybe I can make it more clear.

As it is now, your selector will *not* return the style element only if the element has both attributes. If either of the attributes is present it will return the style element.

Comment (ShaunSHamilton) [reply client/src/utils/css-help.ts]: @lasjorg I have been trying to figure this out, but I am not too sure...

Comment (lasjorg) [reply client/src/utils/css-help.ts]: I think you got it :+1:

Comment (lasjorg) [reply client/src/utils/css-help.ts]: Just as information, in Selectors Level 4 `:not()` accepts a list of selectors. I'm just not sure how great the support is. As far as I can tell it should be supported in Chrome, Firefox, and WebKit

> https://caniuse.com/?search=%3Anot()
> 
> Selectors Level 4 allows `:not()` to accept a list of selectors. Thus, `:not(a):not(.b):not([c])` can instead be written as `:not(a, .b, [c])` and `:not(a.b[c])` works as intended.

So this should work as well:

`document.querySelector('style:not([class], [media])');`

But I think your selector is safer. From the testing I did it works as intended.

**Review by lasjorg — APPROVED** [review]
LGTM.

I tested the Create a Media Query challenge in Safari using LambdaTest with the PR code and it passes. But that is all the testing I did.

Might be nice to get @moT01 to confirm as well though.

**Review by moT01 — APPROVED** [review]
Worked for me 👍
