### PR TITLE
fix: now pane remembers state

### LINKED ISSUE #55619: Console (+ layout) should stick between lessons
### Describe the Issue

I was going through this step of [the date formatter project,](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-18) and it asks me to log something to the console. So I opened the console to check it out. When I submit and get taken to the next step, the console automatically closes. In that, and subsequent steps, I also want to look at the console.

It would be nice if the layout stayed how you had it when you move between steps. I know the preview portal stays open and how you had it when you move between steps, but it seems like most things get reverted. Here's a list:

The console should stay open if you had it open
The panes should stay the same size
The same files should be open (if applicable)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-23

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-23
2. Open the console, resize the panes, open the index.html file
3. Complete and submit the challenge to go to the next step.
4. See everything reverted to the default

### Expected behavior

It to remember my layout.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by X1Vi**
…s open or closed as per the previous setting

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55619

Now panes remain open or close when we shift to the next step as per our previous preferences

### CODE REVIEW

**Comment by X1Vi** [comment]
> Hey there,
> 
> Thanks for your interest in contributing. We appreciate your efforts, but this PR doesn't follow [our guidelines](https://contribute.freecodecamp.org/how-to-open-a-pull-request).
> 
> Do not worry, you should join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the `#contributors` channel. That will help other contributors guide you to get your PR ready for a review.
> 
> Happy Contributing!

fixed

**Review by Sembauke — CHANGES_REQUESTED** [review]
We should use `store` not `sessionStorage` to keep it consistent.

Maybe change the key to `challenge-pane-layout` to conform with stored `challenge-layout` that remembers the size of the panes. 

Maybe even combine them.

**Comment by X1Vi** [comment]
> We should use `store` not `sessionStorage` to keep it consistent.
> 
> Maybe change the key to `challenge-pane-layout` to conform with stored `challenge-layout` that remembers the size of the panes.
> 
> Maybe even combine them.

Which one should I put the functionality in ? 
```
export default combineReducers({
  [appNameSpace]: app,
  [challengeNameSpace]: challenge,
  [curriculumMapNameSpace]: curriculumMap,
  [flashNameSpace]: flash,
  [searchNameSpace]: search,
  [settingsNameSpace]: settings
});

```

**Comment by Sembauke** [comment]
Sorry I don't understand what you are refering to.

**Comment by X1Vi** [comment]
> Sorry I don't understand what you are refering to.

Where do I store the state of then panes in store ? There are bunch of reducers ?

**Comment by Sembauke** [comment]
`store` is a package we use to get, set and remove variables from local storage. 

There is a pretty good example in `client/src/templates/Challenges/classic/show.tsx`

**Comment by X1Vi** [comment]
> `store` is a package we use to get, set and remove variables from local storage.
> 
> There is a pretty good example in `client/src/templates/Challenges/classic/show.tsx`

I think it is done

File: client/src/templates/Challenges/classic/desktop-layout.tsx [hunk 1]
```diff
@@ -99,9 +100,70 @@ const DesktopLayout = (props: DesktopLayoutProps): JSX.Element => {
...
+    };
+    store.set('layoutPaneBooleans', JSON.stringify(layoutPaneBooleans));
+  }, [
+    showNotes,
+    showConsole,
+    showInstructions,
+    showPreviewPane,
+    showPreviewPortal
+  ]);
+  /* eslint-disable react-hooks/exhaustive-deps */
```
Comment (moT01) [inline client/src/templates/Challenges/classic/desktop-layout.tsx:148]: These comments seem a little inconsistent. I don't think we need them on the effect above this one, but we do on the one below.

File: client/src/templates/Challenges/classic/desktop-layout.tsx [hunk 2]
```diff
@@ -99,9 +100,70 @@ const DesktopLayout = (props: DesktopLayoutProps): JSX.Element => {
     startWithConsoleShown
   } = props;
 
-  const [showNotes, setShowNotes] = useState(false);
-  const [showConsole, setShowConsole] = useState(startWithConsoleShown);
-  const [showInstructions, setShowInstructions] = useState(true);
+  const initialShowState = (key: string, defaultValue: boolean): boolean => {
+    const savedState: string = store.get('layoutPaneBooleans') as string;
+    if (savedState) {
+      const parsedState: Record<string, boolean> = JSON.parse(
```
Comment (moT01) [inline client/src/templates/Challenges/classic/desktop-layout.tsx:106]: Not sure what it wouldn't be JSON, but if JSON.parse fails here, I get a runtime error. We should probably handle that. Same with the json.parse below.

File: client/src/templates/Challenges/classic/desktop-layout.tsx [hunk 3]
```diff
@@ -99,9 +100,70 @@ const DesktopLayout = (props: DesktopLayoutProps): JSX.Element => {
     startWithConsoleShown
   } = props;
 
-  const [showNotes, setShowNotes] = useState(false);
-  const [showConsole, setShowConsole] = useState(startWithConsoleShown);
-  const [showInstructions, setShowInstructions] = useState(true);
+  const initialShowState = (key: string, defaultValue: boolean): boolean => {
+    const savedState: string = store.get('layoutPaneBooleans') as string;
```
Comment (moT01) [inline client/src/templates/Challenges/classic/desktop-layout.tsx:104]: Do we need to cast it and give it a type?

**Review by moT01 — COMMENTED** [review]
Looking good @X1Vi 🎉 I left a few comments on some things I think could maybe be a little better. Let me know if you want to discuss any of it.

File: client/src/templates/Challenges/classic/desktop-layout.tsx (hunk 3 above)
Comment (X1Vi) [reply client/src/templates/Challenges/classic/desktop-layout.tsx:104]: if you are talking bout `store.get('layoutPaneBooleans') as string` then yes I think

File: client/src/templates/Challenges/classic/desktop-layout.tsx (hunk 1 above)
Comment (X1Vi) [reply client/src/templates/Challenges/classic/desktop-layout.tsx]: In the new commit I think I have remove all the unnecessary ones I think but I think you should review it once more if you want

File: client/src/templates/Challenges/classic/desktop-layout.tsx (hunk 2 above)
Comment (X1Vi) [reply client/src/templates/Challenges/classic/desktop-layout.tsx]: I have added try catch blocks now if there is anything more you need me to do then do ping me

File: client/src/templates/Challenges/classic/desktop-layout.tsx (hunk 3 above)
Comment (X1Vi) [reply client/src/templates/Challenges/classic/desktop-layout.tsx:104]: if you are talking about this `store.get('layoutPaneBooleans') as string` then probably yeah

**Review by moT01 — APPROVED** [review]
LGTM @X1Vi 🎉

**Review by houssam-12bboo — COMMENTED** [review]
Y

**Review by houssam-12bboo — COMMENTED** [review]
F

**Comment by ilenia-magoni** [comment]
@houssam-12bboo it's great you want to help reviewing the PRs, but please be aware that your positive review has no effect on the PR and only cause noise. If you have constructive criticism instead you could point out what need to be bettered in a PR.

**Review by Sembauke — APPROVED** [review]
