### PR TITLE
fix(user): Update email pre-confirm config

### LINKED ISSUE #15822: Update email should not modify user object before its confirmed
After passwordless #9660 has landed, the reset logic on accounts will be removed.
 
This means that we should not be updating the email on records with an update unless it's confirmed via the update email sent.

This needs a minor refactoring to the updating logic.

### PR DESCRIPTION
**Pull request by raisedadead**
This request aims to make the following changes to the user model and email auth:

- [x] Re-add the native LoopBack email validation support.
- [x] Align the naming convention for the brand in the email templates.
- [x] Not update the user email, unless its confirmed.
- [ ] ~~Refactor common code for creating verification tokens for update and login paths.~~ This can be taken up in a separate pull request.

Closes #15822

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I just talked with @raisedadead and he said this is ready to QA - could you take a quick look and comment or merge if it's ready?

File: common/models/user.js [hunk 1]
```diff
@@ -83,11 +83,6 @@ function getWaitPeriod(ttl) {
   return 0;
 }
 module.exports = function(User) {
-  // NOTE(berks): user email validation currently not needed but build in. This
-  // work around should let us sneak by
-  // see:
-  // https://github.com/strongloop/loopback/issues/1137#issuecomment-109200135
-  delete User.validations.email;
```
Comment (BerkeleyTrue) [inline common/models/user.js]: We will need to keep this in mind as not everyone has an email address listed. For users who exclusively sign in using github may have issues here. I think we can move forward with this and watch our final QA for issues with Github Oauth.

Comment (raisedadead) [reply common/models/user.js]: Thanks I have created a new issue to track this. https://github.com/freeCodeCamp/freeCodeCamp/issues/16126
