### PR TITLE
fix: update upper jaw view zone when upper jaw height changes

### LINKED ISSUE #55880: Collapsible code blocks do not resize the editor
**Describe the bug**

The collapsible code blocks introduced by https://github.com/freeCodeCamp/freeCodeCamp/pull/54561 do not re-render the editor when they're expanded or contracted.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Click on Example Code
3. See large gap below instructions
4. Scroll the editor window
5. See large gap _above_ instructions
6. Click on Example Code
7. See description cover editor (lines 3 and 4)

**Expected behavior**
The editor should resize whenever the description changes size. 

**Screenshots**
image

after scrolling

image

after second click

image

**Additional context**

The collapsible code should probably be a React controlled component. There is an open issue https://github.com/facebook/react/issues/15486, but it's easily worked around https://github.com/facebook/react/issues/15486#issuecomment-488028431

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55880

### CODE REVIEW

File: client/src/templates/Challenges/classic/editor.tsx [hunk 1]
```diff
@@ -814,6 +814,12 @@ const Editor = (props: EditorProps): JSX.Element => {
     Prism.hooks.add('complete', makePrismCollapsible);
     Prism.highlightAllUnder(desc);
 
+    const obs = new ResizeObserver(() => {
+      updateDescriptionZone();
+    });
+
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:820]:
```suggestion
    // Since the description can be resized without React knowing about it, the
    // zone needs updating in response.
    const obs = new ResizeObserver(() => updateDescriptionZone());
```
Some clarification might help.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
The `updateDescriptionZone` call on line 1298 is redundant, now, since all size changes are caught by the new code.

**Review by ojeytonwilliams — APPROVED** [review]
Nice work. LGTM 👍

**Review by ahmaxed — APPROVED** [review]
