### PR TITLE
fix(ui): ensure terminal takes full viewport height on all devices

### LINKED ISSUE #58725: Python output is cut off
### Describe the Issue

On the python challenges, the shell / terminal thing looks like it's cut off...

Image

The area with the black background feels like it should go down to the top of the console - or if the console is collapsed, to the bottom of the page.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-1

### Steps to Reproduce

1. Go to [python challenge](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-1) or [python project](https://www.freecodecamp.org/learn/scientific-computing-with-python/build-an-arithmetic-formatter-project/build-an-arithmetic-formatter-project)
4. See terminal output

### Expected behavior

Terminal to be full height.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tanmaygautam11**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #58725

## What does this PR do?

This PR ensures that the terminal fills the entire height of the viewport on both desktop and mobile devices. By dynamically injecting a style element into the page, the `.xterm-screen` class is set to `height: 100vh !important;`, making the terminal always occupy the full available vertical space.

## Why is this needed?

Previously, the terminal component did not utilize the full page height, especially on mobile devices.

## How does it work?

The following code is added to dynamically update the terminal height:

```js
// Create a style element to ensure the terminal takes up the full viewport height.
const terminalHeight = document.createElement('style');
terminalHeight.innerHTML = `.xterm-screen { height: 100vh !important; }`;
document.head.appendChild(terminalHeight);
```

- A `<style>` tag is created and appended to the document head.
- The `.xterm-screen` class is forced to have a height of `100vh`, overriding any previous styling.

## Screenshots

| Before | After |
|:------:|:-----:|
| Before: iPhone-14-Pro | After: iPhone-14-Pro |

---

### CODE REVIEW

File: client/src/templates/Challenges/classic/xterm.tsx [hunk 1]
```diff
@@ -35,6 +35,12 @@ export const XtermTerminal = ({
       const disposables: IDisposable[] = [];
       const { Terminal } = await import('xterm');
       const { FitAddon } = await import('xterm-addon-fit');
+
+      // Create a style element to ensure the terminal takes up the full viewport height.
+      const terminalHeight = document.createElement('style');
+      terminalHeight.innerHTML = `.xterm-screen { height: 100vh !important; }`;
+      document.head.appendChild(terminalHeight);
+
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/xterm.tsx]: Is it necessary to create a style element? Can't we just add some css?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: client/src/templates/Challenges/classic/xterm.tsx (hunk 1 above)
Comment (tanmaygautam11) [reply client/src/templates/Challenges/classic/xterm.tsx]: I added the `xterm.css` file to set the terminal height to `100vh`. Since `xterm` is an external package, overriding its default styles requires the use of `!important`.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM, thanks @tanmaygautam11  👍

**Review by moT01 — APPROVED** [review]
LGTM @tanmaygautam11 🎉 Thanks for contributing to freeCodeCamp 🎉
