### PR TITLE
fix: make github url optional for backend projects

### LINKED ISSUE #37771: Inconsistent behavior in the "Solution" and "Github Link" texboxes of the APIs and Microservices projects
If I fill the "Solution" textbox only, providing a Glitch project URL, and leave the other one blank, then when I click the "I've completed this challenge" button, it complains about having to fill in the "Github Link" textbox. What I did was to put the same Glitch URL in both textboxes, the "Solution" and the "Github Link", and it worked like a charm. I did that to complete 4 of 5 projects (since the Timestamp Microservice is broken).

Sin título2

Sin título

* Browser Name: Google Chrome
* Browser Version: 72.0.3626.81 (Official build) (64 bits)
* Operating System: Windows 10 Pro

### PR DESCRIPTION
**Pull request by moT01**
Well, this is what I came up with for the issue - not sure if it's the best way, but it seems to be working and I don't think there will be any side effects.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37771

### CODE REVIEW

File: client/src/components/settings/Certification.js [hunk 1]
```diff
@@ -190,14 +190,16 @@ export class CertificationSettings extends Component {
...
             </MenuItem>
-            <MenuItem
-              bsStyle='primary'
-              href={githubLink}
-              rel='noopener noreferrer'
-              target='_blank'
-            >
-              Back End
-            </MenuItem>
+            {githubLink !== 'empty' && (
```
Comment (raisedadead) [inline client/src/components/settings/Certification.js]: I do not like that we would have to keep a comparison with `'empty'`? How can we make this cleaner? Should we be able to simply check against `''`?

Comment (moT01) [reply client/src/components/settings/Certification.js]: I tried an empty string and null, but I was getting errors. I can take a deeper look.

Comment (raisedadead) [reply client/src/components/settings/Certification.js]: Can you elaborate on the errors when you get a chance? Thanks.

Comment (moT01) [reply client/src/components/settings/Certification.js]: I guess the error wasn't with the comparison here, It was when trying to send those values (an empty string or null) to the backend. Meaning when I set it as one of those in the completion-epic, the `github` value wouldn't be found I guess, and throw back a server error. "Cannot reach the server to update your progress" is what the flash message says I think; it disappears quickly.

So are you concerned with the comparison here, or storing the string `empty` in the db?

Comment (raisedadead) [reply client/src/components/settings/Certification.js]: > So are you concerned with the comparison here, or storing the string `empty` in the db?

Yes, I am concerned about the db values. I would imagine we would want to have a standard value instead of the string `empty`, which could get lost in time down the lane, leading to confusion.

Comment (ojeytonwilliams) [reply client/src/components/settings/Certification.js]: What about just not storing anything?  The api-server currently rejects challenges with no `githubLink`, so that would have to change, but I think it's fine to omit keys from documents.

As long as everything that looks for them can cope with them being missing, it should be okay.  I'm not a Mongo expert, though.

**Comment by moT01** [comment]
Alright, this seems to be working.
DB entry when no github link entered...
Screen Shot 2019-12-18 at 10 00 36 AM
is entered...
Screen Shot 2019-12-18 at 10 00 46 AM

File: client/src/components/settings/Certification.js (hunk 1 above)
Comment (raisedadead) [reply client/src/components/settings/Certification.js]: > As long as everything that looks for them can cope with them being missing, it should be okay.

Yes, it should be. Ideally we can store `null` and update the api to not reject empty values as it does currently for GitHub.

**Review by raisedadead — APPROVED** [review]
