### PR TITLE
Fix(challenges): Bug cancel not working

### LINKED ISSUE #10632: Cancel doesn't work on Bug report modal
#### Challenge Name

All challenges

#### Issue Description

Click "bug" on any challenge. Neither the cancel or "x" will allow you to cancel the popup.
 Reported by manosziogou on the forums
#### Browser Information

* Browser Name, Version: Cross-browser
* Operating System: Mac, Ubuntu, Manjaro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```
#### Screenshot

truncate a string free code camp

### PR DESCRIPTION
**Pull request by arialaurel**
The modal level onHide prop is used when you're using the modal's built-in hide buttons, but since we're rolling our own we just need to pass the action to the onClick handlers for each button.

Closes #10632

### CODE REVIEW

File: common/app/routes/challenges/components/Bug-Modal.jsx [hunk 1]
```diff
@@ -25,12 +25,11 @@ export class BugModal extends PureComponent {
     } = this.props;
     return (
       <Modal
-        onHide={ closeBugModal }
         show={ isOpen }
         >
         <Modal.Header className='challenge-list-header'>
           Did you find a bug?
-          <span className='close closing-x'>×</span>
+          <span className='close closing-x' onClick={ closeBugModal }>×</span>
```
Comment (BerkeleyTrue) [inline common/app/routes/challenges/components/Bug-Modal.jsx]: Multi-attributes must be spread across lines. I'm surprised the linter didn't throw an error.

**Comment by BerkeleyTrue** [comment]
@ltegman Thanks for putting this together!

**Comment by ltegman** [comment]
@BerkeleyTrue Not a problem! Feels good to dip a toe back into the OSS world after too much time off from RSI! Let me know if the current code style looks better or if it's still off the mark a bit 😄

File: common/app/routes/challenges/components/Bug-Modal.jsx [hunk 2]
```diff
@@ -25,12 +25,15 @@ export class BugModal extends PureComponent {
...
-        onHide={ closeBugModal }
         show={ isOpen }
         >
         <Modal.Header className='challenge-list-header'>
           Did you find a bug?
-          <span className='close closing-x'>×</span>
+          <span
+            className='close closing-x'
+            onClick={ closeBugModal }
+            >×
```
Comment (BerkeleyTrue) [inline common/app/routes/challenges/components/Bug-Modal.jsx]: Can you move the `x` right under the `>`? Sorry to be nit-picky.

**Comment by ltegman** [comment]
@BerkeleyTrue Don't know how I missed that detail. Should be good now.

**Comment by marhyorh** [comment]
This should be merged. Didn't know it got fixed :+1:

**Comment by dhcodes** [comment]
Tested on Chrome, FF, and Safari. Meets @BerkeleyTrue's requests. LGTM! 👍
