### PR TITLE
Fix/invalid challenge url

### LINKED ISSUE #16257: Navigating to an invalid challenge URL just loads a blank page with a navbar - not a 404 page
#### Issue Description
When I attempt to visit an invalid challenge URL, I don't get a 404 error - instead I get just a navbar with nothing below it.

For example: http://beta.freecodecamp.org/en/challenges/javascript-algorithms-and-data-structures-projects/i-am-the-black-knight

#### Browser Information
Using Chrome Version 63.0.3239.84 (Official Build) (64-bit) on MacOS

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Screenshot

learn_to_code___freecodecamp

### PR DESCRIPTION
**Pull request by anhtran1906**
#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16257 

#### Description
Added new NotFound React component and added redux states for invalid challenge. Now navigating to invalid URL will load an error message and a button to navigate back to Map

### CODE REVIEW

File: common/app/routes/Challenges/views/invalid/NotFound.jsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import React, { PureComponent } from 'react';
+
+// import PropTypes from 'prop-types';
+/* eslint max-len: ["error", { "ignoreStrings": true }] */
+
+
+const propTypes = {};
+
+export class NotFound extends PureComponent {
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/invalid/NotFound.jsx]: We already have a `NotFound` component [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/92da7987d99fdf92f24e063fa512db52f30d5ccb/common/app/NotFound/Not-Found.jsx#L7). Please develop the existing component.

File: common/app/routes/Challenges/views/invalid/NotFound.jsx [hunk 2]
```diff
@@ -0,0 +1,34 @@
+import React, { PureComponent } from 'react';
+
+// import PropTypes from 'prop-types';
+/* eslint max-len: ["error", { "ignoreStrings": true }] */
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/invalid/NotFound.jsx]: I understand why you need this currently, but long strings and be broken up to be concatenated via javascript

```jsx
<Component
  prop1={ true }
  prop2={ someFn }
  reallyLongStringProp={
    'The first part of the string ' +
    'the second part of the string. ' +
    'and so on'
  }
  />
```

File: common/app/routes/Challenges/views/invalid/NotFound.jsx [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+  render() {
+    return (
+        <div className='container'>
+          <div className='row'>
+            <div className='col-sm'>
+            <div className='alert alert-danger' role='alert'>
+              <h4 className='alert-heading' className='mb-12'>
+                This challenge is not found.</h4>
+               <p>Head back to <a className='alert-link'
+                   href='/en/challenges/basic-html-and-html5/learn-how-freecodecamp-works'
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/invalid/NotFound.jsx]: Re: comment on eslint rule disabling

File: common/app/routes/Challenges/views/invalid/NotFound.jsx [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+export class NotFound extends PureComponent {
+  render() {
+    return (
+        <div className='container'>
+          <div className='row'>
+            <div className='col-sm'>
+            <div className='alert alert-danger' role='alert'>
+              <h4 className='alert-heading' className='mb-12'>
+                This challenge is not found.</h4>
+               <p>Head back to <a className='alert-link'
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/invalid/NotFound.jsx]: We have a `<Link />` component to handle link navigation, It is available in `common/app/Router`

```jsx
<Link
  to='/challenges/current-challenge'
/>
```

File: common/app/routes/Challenges/views/invalid/NotFound.jsx (hunk 3 above)
Comment (Bouncey) [inline common/app/routes/Challenges/views/invalid/NotFound.jsx]: Using the `<Link />` means we don't have to tie this component to a language

**Review by Bouncey — CHANGES_REQUESTED** [review]

File: common/app/routes/Challenges/views/invalid/NotFound.jsx (hunk 1 above)
Comment (anhtran1906) [reply common/app/routes/Challenges/views/invalid/NotFound.jsx]: Gotcha. I added the code to modify NotFound component

File: common/app/routes/Challenges/views/invalid/NotFound.jsx (hunk 2 above)
Comment (anhtran1906) [reply common/app/routes/Challenges/views/invalid/NotFound.jsx]: Thank you! I fixed the long string and deleted the ignore error eslint comment

File: common/app/routes/Challenges/views/invalid/NotFound.jsx (hunk 3 above)
Comment (anhtran1906) [reply common/app/routes/Challenges/views/invalid/NotFound.jsx]: I am not sure what you meant by "we don't have to tie this component to a language". I used the <Link /> component instead of <a>. However, I kept other styling parts. Is this OK?

File: common/app/NotFound/Not-Found.jsx [hunk 5]
```diff
@@ -1,15 +1,29 @@
...
 
 export default function NotFound() {
   return (
-    <div>404 Not Found</div>
+    <div className='container'>
+          <div className='row'>
+            <div className='col-sm'>
+            <div className='alert alert-danger' role='alert'>
+              <h4 className='alert-heading' className='mb-12'>
+                This challenge is not found.</h4>
```
Comment (Bouncey) [inline common/app/NotFound/Not-Found.jsx]: We shouldn't tie this down to a particular route. Please use a more generic 'page not found' message.

File: common/app/NotFound/Not-Found.jsx [hunk 6]
```diff
@@ -1,15 +1,29 @@
...
+                Head back to <Link className='alert-link'
+                   to={'/en/challenges/basic-html-and-html5/' +
```
Comment (Bouncey) [inline common/app/NotFound/Not-Found.jsx]: This should link to '/challenges/current-challenge', that way, we are not tying this component down to a single language, or a specific challenge.

File: common/app/NotFound/Not-Found.jsx [hunk 7]
```diff
@@ -1,15 +1,29 @@
...
-
 // import PropTypes from 'prop-types';
+import Link from '../Router/Link.jsx';
 
 const propTypes = {};
 
 export default function NotFound() {
   return (
-    <div>404 Not Found</div>
+    <div className='container'>
```
Comment (Bouncey) [inline common/app/NotFound/Not-Found.jsx]: Please use `react-bootstrap` for all bootstrap components

File: common/app/NotFound/Not-Found.jsx [hunk 8]
```diff
@@ -1,15 +1,29 @@
...
+          <div className='row'>
+            <div className='col-sm'>
+            <div className='alert alert-danger' role='alert'>
+              <h4 className='alert-heading' className='mb-12'>
+                This challenge is not found.</h4>
+                Head back to <Link className='alert-link'
+                   to={'/en/challenges/basic-html-and-html5/' +
+                   'learn-how-freecodecamp-works'}
+                   >
+                    Map
```
Comment (Bouncey) [inline common/app/NotFound/Not-Found.jsx]: The Map as it is in production is depreciated, we no longer have a map page, it is just a panel in the view.

The link text should reflect the fact that we are taking them to a challenge

**Review by Bouncey — CHANGES_REQUESTED** [review]

File: common/app/NotFound/Not-Found.jsx (hunk 6 above)
Comment (anhtran1906) [reply common/app/NotFound/Not-Found.jsx]: Gotcha. I tried putting in ' /challenges/current-challenge' but it would not redirect to the home page. However, when I do it in a separate browser, it automatically redirects to /en/challenges/basic-html...

Comment (BerkeleyTrue) [reply common/app/NotFound/Not-Found.jsx]: To make that work, you need to either use a regular anchor tag or dispatch the currentChallenge action on click.

File: common/app/routes/Challenges/utils/index.js [hunk 9]
```diff
@@ -24,7 +24,8 @@ export const viewTypes = {
   [ challengeTypes.step ]: 'step',
   [ challengeTypes.quiz ]: 'quiz',
   backend: 'backend',
-  modern: 'modern'
+  modern: 'modern',
+  invalid: 'invalid'
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/utils/index.js]: This should be a top level route, there is no reason this should be in the Challenges route

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/NotFound/Not-Found.jsx (hunk 6 above)
Comment (anhtran1906) [reply common/app/NotFound/Not-Found.jsx]: I see. I'll just use a regular anchor tag for the simplicity.

**Comment by anhtran1906** [comment]
@BerkeleyTrue @Bouncey Please take a look at my PR. Thank you!

**Comment by BerkeleyTrue** [comment]
> This should be a top level route, there is no reason this should be in the Challenges route

**Comment by anhtran1906** [comment]
I fixed that problem in the most updated PR. Please take a look. If that's not the problem with the Challenges/utils/index.jsx file, please clarify which "this" you're mentioning.

**Comment by BerkeleyTrue** [comment]
The not found route is currently at the at the challenges route. This should be a top level route, not a sub route

**Comment by anhtran1906** [comment]
@BerkeleyTrue I put the not found route within the challenges route because when the challenge.id is not valid in the redux state tree, it will render the not found component for invalid challenge ids. However, for actual not-found routes, there's already a 404 Page Not Found jade file that renders this situation. Thus, personally, I think it's sensible to put the Not found route under the challenges route. 

If you don't agree with this, please give me more detailed instruction on how I should update my PR since I don't know how to go about it now with your above comments. Thank you.

**Comment by BerkeleyTrue** [comment]
If there already is a 404 route, then the issue isn't "we need a 404 route", but "Why is an invalid challenge rendering the react page instead of rending the 404 page".

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
I'm gonna go ahead and merge this with the caveat that this may be removed in the future. Rendering a 404 page in react is quite expensive and could leave us vulnerable in the future. 

with that said, this PR looks good and I'd like to see our current 404 modified to look like this.


Happy Coding
