### PR TITLE
fix optimizely csp for script-src

### LINKED ISSUE #9980: CSP Issues on beta website
image

To be looked into, depending if this is just a beta issue, or will actually cause issues on production

### PR DESCRIPTION
**Pull request by ivantedja**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9980
#### Description

It appears that `default-src` is ignored if `script-src` is specified

https://developers.google.com/web/fundamentals/security/csp/

> You can override this default behavior by specifying a default-src directive. This directive defines the defaults for most directives that you leave unspecified.

### CODE REVIEW

**Comment by Bouncey** [comment]
@ivantedja does couldflare need to be moved to `scriptSrc` also as the `defaultSrc` is being overridden?

File: server/middlewares/csp.js [hunk 1]
```diff
@@ -33,7 +32,9 @@ export default function csp() {
         '*.twimg.com',
         'https://*.twimg.com',
         '*.youtube.com',
-        '*.ytimg.com'
+        '*.ytimg.com',
+        'https://*.optimizely.com',
+        '*.optimizely.com'
```
Comment (BerkeleyTrue) [inline server/middlewares/csp.js]: Only add the https url.

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Comment by ivantedja** [comment]
@Bouncey `cloudflare` has already been defined in `script-src`

`default-src` is a fallback for:
- child-src
- connect-src
- font-src
- img-src
- manifest-src
- media-src
- object-src
- script-src
- style-src

not everything (`*-src`) has already been "re-defined" so I keep `cloudflare` in `default-src` instead of removing it

@BerkeleyTrue has been updated

File: server/middlewares/csp.js [hunk 2]
```diff
@@ -14,7 +14,6 @@ export default function csp() {
   return helmet.contentSecurityPolicy({
     directives: {
       defaultSrc: trusted.concat([
-        '*.optimizely.com',
```
Comment (BerkeleyTrue) [inline server/middlewares/csp.js]: According to https://help.optimizely.com/Troubleshoot_Problems/Update_your_site's_Content_Security_Policies_(CSP)

We need optimizely to be in the default. The only change is needed is to change this line to use https

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: server/middlewares/csp.js (hunk 2 above)
Comment (BerkeleyTrue) [inline server/middlewares/csp.js]: I believe it may need exist in both place as optimizely will also add css and fonts.

Comment (ivantedja) [inline server/middlewares/csp.js]: you're right, there is a possibility optimizely will also add css and fonts. has been updated:
- `font-src`: because `default-src` is ignored as well for the same reason with `script-src`
- `style-src`: because `default-src` is ignored as well for the same reason with `script-src`
- `default-src`: added for fallback just to be safe but still the key point is `script-src`, `style-src`, `font-src`

**Comment by Bouncey** [comment]
## LGTM :+1: 

Pulled down and tested - no CSP error in the console and optimizely cookies loaded to the browser

@BerkeleyTrue to approve changes

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
@ivantedja Nice work!

Happy Coding
