### PR TITLE
fix: Update email action should hit API

### LINKED ISSUE #15965: Update email - Browser's console errors
#### Issue Description

I was testing staging branch and noticed that browser's console shows some warnings and errors in the Update email page (http://localhost:3000/en/settings/update-email).

#### Browser Information

* Browser Name, Version: Google Chrome, Version 61.0.3163.100
* Operating System: Ubuntu 16.04 (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

screenshot_2017-10-15_22-54-43

### LINKED ISSUE #16145: [beta] request from react view is not hitting the update email API

### PR DESCRIPTION
**Pull request by raisedadead**
Closes #16145
Closes #15965
Closes #15966

### CODE REVIEW

File: common/app/routes/Settings/redux/update-user-epic.js [hunk 1]
```diff
@@ -27,25 +26,37 @@ const urlMap = {
...
-    .flatMap(({ payload: email }) => {
-      const {
-        app: { user: username, csrfToken: _csrf },
-        entities: { user: userMap }
-      } = getState();
-      const { email: oldEmail } = userMap[username] || {};
+  const updateEmail = actions
+    .filter(({ type, payload }) => (
+      type === types.updateMyEmail && payload
+    ))
```
Comment (BerkeleyTrue) [inline common/app/routes/Settings/redux/update-user-epic.js]: I would keep the ofType operator and just add a second filter for the payload.

File: common/app/routes/Settings/redux/update-user-epic.js [hunk 2]
```diff
@@ -27,25 +26,37 @@ const urlMap = {
...
-          null
-        ));
-      return Observable.merge(optimisticUpdate, ajaxUpdate);
+      return postJSON$('/update-my-email', body)
+        .flatMap(({ message }) => {
+          return Observable.of(
+            // show user that we have updated their email
+            makeToast({ message })
+          );
+        })
```
Comment (BerkeleyTrue) [inline common/app/routes/Settings/redux/update-user-epic.js]: Since flatmap here is only maping to a single action it can be swapped for a map

`map(makeToast)`

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Comment by raisedadead** [comment]
Sorry, I was supposed to just rename the method. This should be back to the original code, with just a rename from `updateUserFlag` to `updateUserEmail`

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
✨  👍
