### PR TITLE
fix(client): daily challenge calendar

### LINKED ISSUE #63944: The new coding challenge archive UI is less usable
### Describe the Issue

For the better part of the last 2 months, I've been attempting the daily coding challenge. I've a tendency of skipping some because they require more time to complete. The previous UI made it easy for me to locate the skipped challenges. You can see in the screenshot below.

Image

To my disappointment, the simple UI above has been replace with the UI below.

Image

The redesign in my opinion is displaying lots of unnecessary information. I think including the  date, challenge number, challenge name, programming language, and language icons make the UI congested. Therefore, wading through all that congestion to locate what I need becomes much more difficult. 

When you look at the second screenshot, there are about 4 challenges(I hope I counted right) that I haven't attempted but it will take a bit of time to locate them, something I will do instantly in the previous screenshot.

### Affected Page

https://www.freecodecamp.org/learn/daily-coding-challenge/archive

### Steps to Reproduce

Navigate to the daily coding challenge archive using the above link.

### Expected behavior

The UI should be less congested to easily locate what I need.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### LINKED ISSUE #65847: Daily Coding Challenge Title text overlapping with completion checkmark icon and break line
### Describe the Issue

When hovering over challenges with longer title text, the text overlaps with the break line. Additionally, when the challenge is completed in both the languages the completion checkmark icon overlaps with the title text.

### Affected Page

https://www.freecodecamp.org/learn/daily-coding-challenge/archive

### Steps to Reproduce

1. Go to daily coding challenge page
2. Hover over a challenge with long name like 3 or more lines
3. See break line overlapping with the challenge title text
4. Complete that challenge in both languages
5. See completion checkmark icon overlapping with challenge title text

### Expected behavior

The challenge completion tick and the break line can be adjusted a little lower or made flexible according to the challenge title text.

Maybe something like this:

Image

### Screenshots

Image

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by moT01**
This simplifies the daily challenge calendar UI and fixes some issues.

<details><summary>images</summary>

| | |
| - | - |
| Before | Screenshot 2026-03-02 at 1 17 52 PM |
| After | Screenshot 2026-03-02 at 1 16 25 PM |

^ one main difference - now you get the big checkmark for completing any language, and the languages you've completed the challenge in show up at the bottom. This reflects how it behaves in the database. Formerly, you needed to complete both languages to get the big checkmark.

</details>

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #65847
Closes #63944 - it's not the exact solution discussed here, but I think this new UI simplifies things and solves the issue.

### CODE REVIEW

File: client/src/components/daily-coding-challenge/calendar-day.tsx [hunk 1]
```diff
@@ -1,12 +1,11 @@
 import React from 'react';
 import { useTranslation } from 'react-i18next';
-import { Spacer } from '@freecodecamp/ui';
 import { Link } from '../helpers';
 import GreenPass from '../../assets/icons/green-pass';
 import GreenNotCompleted from '../../assets/icons/green-not-completed';
 import JavaScriptIcon from '../../assets/icons/javascript';
 import PythonIcon from '../../assets/icons/python';
-import { formatDisplayDate } from './helpers';
+import { formatDisplayDate, truncateTitle } from './helpers';
```
Comment (ojeytonwilliams) [inline client/src/components/daily-coding-challenge/calendar-day.tsx]:
```suggestion
import { formatDisplayDate, truncate } from './helpers';
```
It's not specific to titles.

File: client/src/components/daily-coding-challenge/helpers.ts [hunk 2]
```diff
@@ -33,3 +33,11 @@ export function formatDisplayDate(dateString: string) {
   }
   return format(parsedDate, 'MMMM d, yyyy');
 }
+
+export function truncateTitle(title: string) {
+  const maxLength = 35;
+  if (title.length <= maxLength) {
+    return title;
+  }
+  return title.slice(0, maxLength) + '...';
```
Comment (ojeytonwilliams) [inline client/src/components/daily-coding-challenge/helpers.ts]:
```suggestion
export function truncate(str: string, maxLength = 35) {
  if (str.length <= maxLength) {
    return str;
  }
  return str.slice(0, maxLength) + '...';
```
Same thing, but a little more flexible.

File: client/src/components/daily-coding-challenge/calendar-day.tsx [hunk 3]
```diff
@@ -17,29 +16,11 @@ interface CalendarDayProps {
...
-    </span>
-  ) : (
-    <span
-      className='dc-checkmark dc-small-checkmark not-completed'
-      data-playwright-test-label='calendar-day-not-completed'
-    >
-      <GreenNotCompleted />
-    </span>
-  );
-}
```
Comment (ojeytonwilliams) [inline client/src/components/daily-coding-challenge/calendar-day.tsx:36]: I would keep this, it makes the rest easier to read. Maybe refactor as

```tsx
function Checkmark({ completed }: CheckmarkProps): JSX.Element {
  return (
    <span
      className={`dc-checkmark ${completed ? 'completed' : 'not-completed'}`}
      data-playwright-test-label={`calendar-day-${completed ? 'completed' : 'not-completed'}`}
    >
      {completed ? <GreenPass /> : <GreenNotCompleted />}
    </span>
  );
}
```

If you do that the dc-info div becomes quite nice

```tsx
      <div className='dc-info'>
        <div className='dc-title-wrap'>
          <div className='dc-title'>{truncate(title)}</div>
        </div>

        <Checkmark completed={completed} />
        {completed && (
          <div className='dc-languages'>
            {completedLanguages.includes('javascript') && (
              <div className='dc-language-icon'>
                <JavaScriptIcon />
                <span className='sr-only'>JavaScript</span>
              </div>
            )}
            {completedLanguages.includes('python') && (
              <div className='dc-language-icon'>
                <PythonIcon />
                <span className='sr-only'>Python</span>
              </div>
            )}
          </div>
        )}
      </div>
```

where `const completed = completedLanguages.length > 0;`

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
The UI looks loads better 👍 I think we can clean the code up a little, though:

**Review by ojeytonwilliams — APPROVED** [review]
LGTM 👍
