### PR TITLE
fix(client):make menu bar disappear after user chooses item from it on landing page

### LINKED ISSUE #43448: menu bar items doesn't disappear when pressing on certain item only in home page
## Affected page

https://freecodecamp.org/

## To reproduce

1. Go to 'Home page'
2. Click on 'menu'
3. Scroll down to 'any item'
4. press on any item
5. The menu bar should disappear but it doesn't

## Expected behavior

After the user chooses a certain option like "Profile or Donate", the menu bar should disappear

## Actual Behavior

The menu bar doesn't disappear, which is annoying UX wise

## Screenshots

Screenshot (197)
Screenshot (198)
Screenshot (199)

## System

- Device: [Laptop]
- OS: [Windows 10,]
- Browser: [e.g. chrome, Edge]
- Version: [don't know]
I only tried it on a laptop windows, so I don't know about the others

### PR DESCRIPTION
**Pull request by NoorFakhry**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43448

I found out that what was causing this problem is that React for some reason doesn't create a ref for the search bar on the first render(still digging on why it does so), so when the function handleClickOutside is triggered the menu bar doesn't close because it has a condition that says close it only if there is a seearchBarRef.current.
What I did here is that I removed the searchBarRef from the logic, I understand this might not be the best solution, I am just opening a discussion here to find out the importance of the searchBarRef in the codebase logic and then try to find a better solution.

### CODE REVIEW

**Comment by moT01** [comment]
It looks like the reason for that check is because on small windows the search bar is moved to that submenu with the rest of the menu buttons. Without it, clicking on the search bar would close the menu, hiding it all. I'm not sure on the solution, but here's [a related post about it](https://stackoverflow.com/questions/55248483/react-ref-current-is-null)

File: client/src/components/Header/index.tsx [hunk 1]
```diff
@@ -43,9 +42,7 @@ export class Header extends React.Component<
     if (
```
Comment (ojeytonwilliams) [inline client/src/components/Header/index.tsx:42]: Since it's not so obvious why this is necessary, could you add a comment explaining why the `searchBarRef` needs checking here?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
> It looks like the reason for that check is because on small windows the search bar is moved to that submenu with the rest of the menu buttons. Without it, clicking on the search bar would close the menu, hiding it all. I'm not sure on the solution, but here's a related post about it

Good catch, @moT01 I'd completely forgotten about that.  @NoorFakhry with that in mind, what I recommend is to convert `SearchBarOptimized` to a React.ForwardRef and then pass the `innerRef` to it.

**Comment by NoorFakhry** [comment]
> It looks like the reason for that check is because on small windows the search bar is moved to that submenu with the rest of the menu buttons. Without it, clicking on the search bar would close the menu, hiding it all. I'm not sure on the solution, but here's [a related post about it](https://stackoverflow.com/questions/55248483/react-ref-current-is-null)

@moT01 as @ojeytonwilliams said, Great catch, now I got it after I experimented it on small screens it turns out to be doing a strange behavior after I removed this check which is when I press on the search bar the whole menu is hidden as you said!!

**Comment by NoorFakhry** [comment]
> > It looks like the reason for that check is because on small windows the search bar is moved to that submenu with the rest of the menu buttons. Without it, clicking on the search bar would close the menu, hiding it all. I'm not sure on the solution, but here's a related post about it
> 
> Good catch, @moT01 I'd completely forgotten about that. @NoorFakhry with that in mind, what I recommend is to convert `SearchBarOptimized` to a React.ForwardRef and then pass the `innerRef` to it.

@ojeytonwilliams , I want to make sure I understood it right, You mean that I change the searchBarOptimied component to React.ForwardRef, Right?
and If so I have to read about React refs first, right?
Also I have another idea, what about we do a javascript media query(if something like that exists, I will still look into it),in such that with large screens we will remove the check and in small screens we will keep the check?

**Comment by ojeytonwilliams** [comment]
> You mean that I change the searchBarOptimized component to React.ForwardRef, Right?

Exactly that, yep.  If you do that, then `<SearchBarOptimized ref={innerRef}>` will pass the ref to the component, letting you use it the same way as `SearchBar` does.

> Also, I have another idea, what about we do a javascript media query(if something like that exists, I will still look into it), in such that with large screens we will remove the check and with small screens, we will keep the check?

Sure, the fact that the menu _doesn't_ close when you click on the search bar, for large viewports, is a small bug. So, that could be useful in addition to fixing the ref problem.

**Comment by NoorFakhry** [comment]
> Sure, the fact that the menu _doesn't_ close when you click on the search bar, for large viewports, is a small bug. So, that could be useful in addition to fixing the ref problem.

No, Actually what I meant is that we will let the menu close in large screens if the user clicks on search bar and it doesn't close if he does that on small screens.
But giving it a second thought I realized this will not fix the original issue in small screens, in fact it will be more bad UX in small screens because the menu bar covers almost all the height of the screen.
So, I think I will try to do as you suggested, but first I need to read about refs in react as I didn't deal with it before.

File: client/src/components/Header/index.tsx [hunk 2]
```diff
@@ -44,6 +44,12 @@ export class Header extends React.Component<
       this.state.displayMenu &&
       this.menuButtonRef.current &&
       !this.menuButtonRef.current.contains(event.target) &&
+      // here we are making this check
+      // to know if the user is using the search bar or not
+      // and if he does we won't invoke the function
+      // becasue if we don't do this check
+      // clicking on the search bar will close the menu bar in small screens
+      // including the search bar itself as it was moved to the menu bar in small screens
```
Comment (ojeytonwilliams) [inline client/src/components/Header/index.tsx:52]:
```suggestion
      // since the search bar is part of the menu on small screens, clicks on
      // the search bar should not toggle the menu
```
I think we can get the point across a little more concisely.

File: client/src/components/search/searchBar/search-bar-optimized.tsx [hunk 3]
```diff
@@ -3,7 +3,11 @@ import { useTranslation } from 'react-i18next';
 import Magnifier from '../../../assets/icons/Magnifier';
 import { searchPageUrl } from '../../../utils/algolia-locale-setup';
 
-const SearchBarOptimized = (): JSX.Element => {
+type innerRefPrototype = {
```
Comment (ojeytonwilliams) [inline client/src/components/search/searchBar/search-bar-optimized.tsx:6]:
```suggestion
type Props = {
```
It's more conventional to name a type according to what it _is_, rather than what it _contains_

File: client/src/components/search/searchBar/search-bar-optimized.tsx [hunk 4]
```diff
@@ -3,7 +3,11 @@ import { useTranslation } from 'react-i18next';
...
+  innerRef?: React.RefObject<HTMLDivElement>;
+};
+
+const SearchBarOptimized = ({ innerRef }: innerRefPrototype): JSX.Element => {
```
Comment (ojeytonwilliams) [inline client/src/components/search/searchBar/search-bar-optimized.tsx:10]:
```suggestion
const SearchBarOptimized = ({ innerRef }: Props): JSX.Element => {
```

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Thanks @NoorFakhry this works nicely :+1:   I just have a few recommendations about the wording:

**Review by ojeytonwilliams — APPROVED** [review]
Thanks @NoorFakhry!

LGTM :+1:

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
LGTM 👍  

Thank you for working on this!
