### PR TITLE
fix(client): fix backend code source submission

### LINKED ISSUE #55279: Improperly handled challenge submission error
If you submit a backend project with `localhost:3000` as the **Source Code Link** url, and a valid solution url such that the tests pass, the client will show the submission modal and accept your links. Returning to the learn map shows the challenge completed.

Refreshing the page, however, shows the challenge as incomplete again. The API is returning a 403 on the request:

image
image
image

But the client is not handling this error properly and not indicating to the camper that the submission was invalid.

This is creating some confusion: https://forum.freecodecamp.org/t/not-able-to-claim-the-certifications/688322/17

### PR DESCRIPTION
**Pull request by Arif-Khalid**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #55279 

Handling of failed project submission, error message is what is returned from endpoint
image

Handling of invalid private URLs for source code links, new invalidation message
image

### CODE REVIEW

File: client/src/components/formHelpers/form-fields.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ function FormFields({ formFields, options }: FormFieldsProps): JSX.Element {
     if (isSourceCodeLinkRequired && name === 'githubLink') {
       validators.push(sourceCodeLinkExistsValidator);
     }
-    if (!isLocalLinkAllowed) {
+    if (!isLocalLinkAllowed || name === 'githubLink') {
```
Comment (Arif-Khalid) [inline client/src/components/formHelpers/form-fields.tsx:73]: I try to reduce code duplication as much as possible by re-using the localhostValidator for client side checking of private urls.  
An issue with this approach is an understandable but incorrect validation message as seen below
image
Would it be better to create a new validator and corresponding validation message?

Comment (ilenia-magoni) [reply client/src/components/formHelpers/form-fields.tsx:73]: you should show a message that explain the issue there

Comment (Arif-Khalid) [reply client/src/components/formHelpers/form-fields.tsx]: > you should show a message that explain the issue there

Thanks for the input, I have created a new validator and updated the english translation file appropriately.
image
Should I populate the other translation files with the english placeholder for the new translation key as well?

File: client/i18n/locales/english/translations.json [hunk 2]
```diff
@@ -969,7 +969,8 @@
     "publicly-visible-url": "Remember to submit a publicly visible app URL.",
     "ms-learn-link": "Please use a valid Microsoft Learn trophy link.",
     "path-url": "You probably want to submit the root path i.e. https://example.com, not https://example.com/path",
-    "source-code-link-required": "Remember to submit the link to your source code."
+    "source-code-link-required": "Remember to submit the link to your source code.",
+    "source-code-link-public": "Source code links must be publicly visible."
```
Comment (ilenia-magoni) [inline client/i18n/locales/english/translations.json:973]:
```suggestion
    "source-code-link-public": "Source code link must be publicly visible."
```

Comment (Arif-Khalid) [reply client/i18n/locales/english/translations.json]: I have changed it accordingly

**Review by Sembauke — CHANGES_REQUESTED** [review]
Hey @Arif-Khalid,

Thank you for your contribution, this is looking great. Could you add a Playwright test for this change.

**Comment by Arif-Khalid** [comment]
Thanks for your review @Sembauke .
I have looked into implementing a playwright test and need some guidance. 

Should I be writing tests for the failed submission error or the client side invalidation message?

If I need to write a test for the failed submission error, i.e., the error that occurs when the source code link is invalid, I would need to submit a valid solution link that passes the tests, otherwise it would never be submitted. 
I can't find an example among the current tests that does this and so would appreciate some guidance on how to achieve it if necessary.

**Comment by Arif-Khalid** [comment]
Preliminarily I have added a test for the client side invalidation message

**Review by Sembauke — APPROVED** [review]

**Review by naomi-lgbt — APPROVED** [review]
