### PR TITLE
fix(challenges): Add key prop jsx element to diff between quiz questions

### LINKED ISSUE #16483: [beta] Question 1 code gets appended to every other subsequent question.
#### Challenge Name

[System Design and Concept Questions](https://beta.freecodecamp.org/en/challenges/system-design-and-concept-questions/arrayprototypemap)

#### Issue Description

The code of Question 1 gets appended to all the other Questions.

#### Browser Information

* Browser Name, Version: Firefox 57.0.4 64-bit
* Operating System: Mac OSX Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

Image

References #16229

### PR DESCRIPTION
**Pull request by warborn**
Closes #16483

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16483

#### Description

The key prop was added to the root element returned by the renderQuiz function to solve the issue of the first question being added to subsequent questions due to the behaviour of the dangerouslySetInnerHTML property

### CODE REVIEW

File: common/app/routes/Challenges/views/quiz/Quiz.jsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ export class QuizChallenge extends PureComponent {
     const currentIndex = this.props.currentIndex;
     const question = this.props.description[currentIndex];
     return (
-      <div>
+      <div key={currentIndex.toString()} >
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/quiz/Quiz.jsx]: We should avoid using an index as a key where possible, as they are only unique within the context of the current array. We could use the challenge `dashedName` Appended with the current index. `dashedName` should be available under `this.props.meta`

To expand on the index thing. Say we have the first question rendered, then the user changes challenge, react would see that the keys haven't changed so it could skip the render of the new question.

**Review by Bouncey — CHANGES_REQUESTED** [review]

**Review by Bouncey — COMMENTED** [review]
Sorry @warborn I thought I had commented on this, but it has been pending for 10 days. My bad.

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
Thanks @warborn :+1:
