### PR TITLE
Current and Longest streak calculation fixed

### LINKED ISSUE #5096: Streak still seems to be broken
Here's a screen shot. Note that it is showing longest streak as only 3 days: 

Here's the camper's code portfolio: http://www.freecodecamp.com/bipeen

### PR DESCRIPTION
**Pull request by LenaBarinova**
1. `Current` and `Longest` streak calculation fixed
2. `day/days` text corrected in user profile next to longest and current streak

While fixing streak calculation functions I've created tests and refactored some code to be testable. Not sure whether I should add these changes to this pull request. You can check refactored code and unit tests in this branch: [fix/streak-still-seems-to-be-broken-with-tests](https://github.com/LenaBarinova/FreeCodeCamp/tree/fix/streak-still-seems-to-be-broken-with-tests)

closes #5096

### CODE REVIEW

**Comment by SaintPeter** [comment]
@BerkeleyTrue The tests look good, but I'd defer to you on if we want to use Mocha.  Is there any way we could see this on Beta?  I'd hate to push it live with the trouble we had last time.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue, @SaintPeter I though Mocha was the library of chose for testing, since all challenge tests were running on Mocha. Am I missing something?

**Comment by SaintPeter** [comment]
@LenaBarinova I was under the impression we were moving to Tape.  I honestly don't know, which is why I'm deferring to @BerkeleyTrue  - I'm primarily an issue mod, not a developer.  I do QA and minor fixes.

BTW, thanks for the incredibly quality of PRs you've been turning in.  Solid work. :smile: - You're not even a Free Code Camp student?  I tried to chat to you on our Gitter, but could not find you.

**Comment by LenaBarinova** [comment]
@SaintPeter thanks for the feedback ;) I appreciate it. I joined HelpContributors room on Gitter.

**Comment by BerkeleyTrue** [comment]
@LenaBarinova Yes, we are moving to Tape. While we still use Mocha in the challenges, the testing suite uses Tape.

This looks great. If you could move over the tests to Tape and add them to this repo. I'll through it up on Beta afterwards

**Comment by LenaBarinova** [comment]
Thanks @BerkeleyTrue ! I'll do all the refactoring changes and rewrite tests in Tape and squash them to this branch then. 
Though, I have one more question: I haven't found any unit tests (I mean for code, not challenges) in ```staging``` branch, are there any other unit tests written, I could add mine too? Now, I just have created a folder for tests and ```test``` task in ```gulp```.

**Comment by BerkeleyTrue** [comment]
Yes, they are well hidden :)

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/test-challenges.js

I think where you placed them is fine for now

**Comment by LenaBarinova** [comment]
Oh I see :) ok, thanks. I'll leave them where they are.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue, @SaintPeter, I have rewritten my tests on Tape, added one more test and created a gulp task to run Tape tests as ```gulp test```.

File: server/boot/user-stats.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
+import moment from 'moment';
+import { dayCount } from '../utils/date-utils';
```
Comment (BerkeleyTrue) [inline server/boot/user-stats.js]: This file should be in server/utils as boot is reserved for function exports that require the server object at runtime.

File: server/boot/user-stats.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    return longest;
+  }, [cals[0], cals[0]]);
+
+  return dayCount(longest);
+}
+
+export {
+  calcCurrentStreak,
+  calcLongestStreak
+};
```
Comment (BerkeleyTrue) [inline server/boot/user-stats.js]: Try explicitly exporting each function instead. This is technically not allowed by the spec, even though it will still work in babel. 

```js
export function calcCurrentStreak() {/*... do stuff ....*/}

export function calcLongestStreak() {/*... do stuff ...*/}
```

Here is a good article on the module syntax. It only briefly mentions the above but is a good read nonetheless.

File: gulpfile.js [hunk 3]
```diff
@@ -533,3 +536,10 @@ gulp.task('default', [
   'watch',
   'sync'
 ]);
+ 
+gulp.task('test', function() {
+  return gulp.src('test/**/*.js')
+    .pipe(tape({
+      reporter: tapSpec()
+    }));
+});
```
Comment (BerkeleyTrue) [inline gulpfile.js]: Files should end with a newline

**Comment by BerkeleyTrue** [comment]
This PR is live on beta.

**Comment by SaintPeter** [comment]
Doesn't seem immediately broken to me on Beta, so that's good.  I posted it for comments in chat and didn't get any complaints . . . It's probably "safe", once the changed @BerkeleyTrue requested are made.

**Comment by BerkeleyTrue** [comment]
@LenaBarinova stated that it did not seem correct.

**Comment by LenaBarinova** [comment]
Actually it's not perfect.. I have found whether the streak calculation is broken or heatmap or list of completed challenges in user profile. For my profile I see streak equals 3 days, but on the heatmap only two days are colored Nov 16 and Nov 17, in a list I see Nov 16 and Nov 18 as a date of completion.
screen shot 2015-12-15 at 2 05 34 pm
screen shot 2015-12-15 at 2 06 32 pm

My guess would be something with time zones.

**Comment by BerkeleyTrue** [comment]
Streak/heat map de-sync is a known issue. Partly cause by the streak being created in EST and the heat-map being generated local to the client.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue, that's right. Streak is calculated in EST, times in a table of completed challenges are showed in EST and in a heatmap we have local time.

I've made changes after code review. 

I guess this version though not perfect, works a bit better than previous.
