### PR TITLE
Fix (settings) : Duplicate social labels

### LINKED ISSUE #9848: [beta] Duplicate social labels in settings
image

### PR DESCRIPTION
**Pull request by raisedadead**
closes #9848

### CODE REVIEW

File: common/app/routes/settings/components/Social-Settings.jsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function SocialSettings({
         key='twitter'
         >
         <FA name='twitter' />
-        Add my LinkedIn to my portfolio
+        Add Twitter to my portfolio
```
Comment (atjonathan) [inline common/app/routes/settings/components/Social-Settings.jsx]: Do we want to remove my? cc/ @QuincyLarson

Comment (BerkeleyTrue) [inline common/app/routes/settings/components/Social-Settings.jsx]: @raisedadead  It should still say 'my'

**Comment by BerkeleyTrue** [comment]
Thanks!
