### PR TITLE
fix: make help button use subforum topics

### LINKED ISSUE #37691: Make the "ask for help" button use new subforum
Refers: https://github.com/freeCodeCamp/freeCodeCamp/pull/37669

### PR DESCRIPTION
**Pull request by moT01**
Not sure if this is what you had in mind @raisedadead, but it's what I came up with. There may be issue's in the future if a block name changes, but it seems like it's either this or go and change the challengeType of a bunch of the challenges since they are kind of scattered and mixed up in places. Would that be fine to do, or would it potentially cause issues? I'll keep this as a draft for now, in case you want to go in that or another direction.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37691

### CODE REVIEW

**Comment by raisedadead** [comment]
I am fine with the current approach on the PR. We should add tests so that it is caught if a challenge block name changes. 

For example a simple test for all the current block names in to go with this help button util component will cross tie them both?

Anyway I do not think it would be a very nice idea to change the challenge types now that the new curriculum is headed our way. Might as well deal them then

File: curriculum/test/test-challenges.js [hunk 1]
```diff
@@ -160,9 +174,14 @@ function populateTestsForLang({ lang, challenges }) {
       describe(challenge.title || 'No title', function() {
         it('Common checks', function() {
           const result = validateChallenge(challenge);
+          const invalidBlock = validateBlock(challenge);
+
           if (result.error) {
             throw new AssertionError(result.error);
           }
+          if (challenge.challengeType !== 7 && invalidBlock) {
+            throw new AssertionError(invalidBlock);
```
Comment (ojeytonwilliams) [inline curriculum/test/test-challenges.js]:
```suggestion
            throw new Error(invalidBlock);
```
I doubt error type really matters, but just in case.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Looks great!

Just the one nitpick:

**Comment by ojeytonwilliams** [comment]
I've checked it locally and the tests work nicely.  If you create a block that's not in `helpCategory` it won't pass the tests.

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by moT01** [comment]
I committed your suggestion @ojeytonwilliams, the only other thing that might be an issue...
`if (challenge.challengeType !== 7 && invalidBlock) {`
I added the check for challengeType 7, those are the certificates which have no challenge page or help button - they were throwing an error because nothing was added for them as a helpCategory. There's also types 8 (quiz) and 9 (invalid) - there must not be any of those types in the current curriculum, but if there ever is, it would probably throw that error.

**Comment by ojeytonwilliams** [comment]
@moT01 I think that's fine.  The error you've created should tell anyone that triggers it why it's happening and how to fix it.  They can either create another exception or a new helpCategory.

Any idea what those challengeTypes are supposed to be used for?

**Comment by moT01** [comment]
quizzes and invalid challenges 😛

**Review by raisedadead — APPROVED** [review]
