### PR TITLE
Fix commit redirect for non signed user.

### LINKED ISSUE #5531: pass unauthenticated Commit params on through even for email signup

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Now users will be directed to sign in page and on sign in
will have pledge completed

closes #5531

### CODE REVIEW

File: common/models/user.js [hunk 1]
```diff
@@ -91,9 +92,10 @@ module.exports = function(User) {
...
 
         req.flash('error', {
-          msg:
-            `The ${req.body.email} email address is already associated with an account. 
-            Try signing in with it here instead.`
+          msg: dedent`
+      The ${req.body.email} email address is already associated with an account.
+      Try signing in with it here instead.
+          `
         });
```
Comment (BerkeleyTrue) [inline common/models/user.js]: This fixes a linting error

File: server/boot/commit.js [hunk 2]
```diff
@@ -22,11 +22,16 @@ import {
...
+const sendNonUserToSignIn = ifNoUserRedirectTo(
+  '/login',
+  'You must be signed in to commit to a non-profit'
+);
+
 const sendNonUserToCommit = ifNoUserRedirectTo(
   '/commit',
-  'Must be signed in to update commit'
+  'You must be signed in to update commit'
 );
```
Comment (BerkeleyTrue) [inline server/boot/commit.js]: Changes message shown to user

File: server/middlewares/add-return-to.js [hunk 3]
```diff
@@ -35,7 +36,7 @@ export default function addReturnToUrl() {
     ) {
       return next();
     }
-    req.session.returnTo = req.path;
+    req.session.returnTo = req.originalUrl;
     next();
```
Comment (BerkeleyTrue) [inline server/middlewares/add-return-to.js]: Preserves queries on sign in redirect.
