### PR TITLE
fix(deps): update monaco-editor to v0.52.2

### LINKED ISSUE #67139: code editor showing broken code indicators where none exist
### Describe the Issue

Please see the screenshot, all pages seem to be affected. The code editor shows red squiggly marks beneath code for no reason.

Image

Sample link (but all workshops are affected): 
https://www.freecodecamp.org/learn/responsive-web-design-v9/workshop-colored-markers/step-9

### System

Chrome, Windows 11
Also reported on Mac OS Sequoia 15.6.1, Firefox Developer Edition 150.0b10(64bit)

Additional Context:
User reporting this says it didn't exhibit this behavior this morning his time. Perhaps a recent update caused this.

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #67139

Updates `monaco-editor` to match the `react-monaco-editor` peer dependency range. This also adjusts the classic challenge editor for Monaco 0.52 API changes and passes the active file language to prevent valid HTML/CSS from being diagnosed as JavaScript.

Tested with:

- `pnpm --filter @freecodecamp/client exec tsc --noEmit --pretty false`
- Local Playwright check on `/learn/responsive-web-design-v9/workshop-colored-markers/step-9/` confirmed no Monaco squiggle decorations.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

File: client/src/templates/Challenges/classic/editor.tsx [hunk 1]
```diff
@@ -577,28 +577,28 @@ const Editor = (props: EditorProps): JSX.Element => {
     // @ts-ignore
     editor._standaloneKeybindingService.addDynamicKeybinding(
       '-editor.action.triggerSuggest',
-      null,
+      0,
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:580]: I'm not 100% clear what these are for, but nothing seems to have changed wrt. production, so it seems fine for now.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM 👍

**Comment by Sembauke** [comment]
@ojeytonwilliams for your query about the keybindings: 
https://github.com/microsoft/vscode/blob/bdc70906e7dd7d36972dc90355052e326b5ea943/src/vs/editor/standalone/browser/standaloneServices.ts#L504

to

https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindings.ts#L31-L34

This should be the correct way to handle it now.
