### PR TITLE
fix: remove tool panel buttons from mobile layout

### LINKED ISSUE #47597: Remove bottom buttons in mobile layout for steps in RWD
### Describe the Issue

Hey, what do you all say to removing the bottom buttons for the steps in the RWD course when in the mobile layout? There are three of them (Help, Reset, and Run) and these functions are already offered in the Step itself. So it's unnecessary duplication and will also free up just a little more screen space at the bottom.

### Affected Page

All steps in RWD course when in the mobile layout

### Steps to Reproduce

1. Open any step in any course in the new RWD course
2. Narrow your browser enough to trigger the mobile layout
3. Notice the three buttons anchored at the very bottom of the screen.

### Expected behavior

Don't display the three bottom buttons in the steps for RWD when in the mobile layout.

### Screenshots

_No response_

### System

- Device: Desktop
- OS: Linux (Fedora 36)
- Browser: Firefox
- Version: 106

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes locally on my machine.

Closes #47597

Removes the tool panel buttons at the bottom of the mobile layout for the Steps since they already have these buttons built into the editor. Not sure if this is the best way to do it? I was originally going to place the new data attributes on the `#mobile-layout` div but that is created using the Tabs component in react-bootstrap and I could not find a way to place them on that div.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @bbsmooth,

Is everything going as planned?

Do you  need any help?

**Comment by bbsmooth** [comment]
@Sembauke I believe this is working properly, I just wasn't sure if this was the best way to implement it. I guess I shouldn't have left it as a draft? Please feel free to test it and give me feedback.

File: client/src/components/layouts/learn.tsx [hunk 1]
```diff
@@ -86,7 +90,13 @@ function LearnLayout({
       <Helmet>
         <meta content='noindex' name='robots' />
       </Helmet>
-      <main id='learn-app-wrapper'>{children}</main>
+      <main
+        id='learn-app-wrapper'
+        {...(hasEditableBoundaries && { 'data-has-editable-boundaries': true })}
+        {...(usesMultifileEditor && { 'data-uses-multifile-editor': true })}
```
Comment (ahmadabdolsaheb) [inline client/src/components/layouts/learn.tsx:96]: adding `data-uses-multifile-editor` and `data-has-editable-boundaries` attributes might not needed for styling since tool panel is shown only when hasEditableBoundaries and usesMultifileEditor are True.

File: client/src/templates/Challenges/classic/mobile-layout.tsx [hunk 2]
```diff
@@ -73,6 +73,9 @@ class MobileLayout extends Component<MobileLayoutProps, MobileLayoutState> {
     // Unlike the desktop layout the mobile version does not have an ActionRow,
     // but still needs a way to switch between the different tabs.
 
+    const showToolPanel =
+      !usesMultifileEditor || (usesMultifileEditor && !hasEditableBoundaries);
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/classic/mobile-layout.tsx:77]: This could be simplified to check if `!hasEditableBoundaries`

File: client/src/templates/Challenges/classic/mobile-layout.tsx [hunk 3]
```diff
@@ -125,7 +128,9 @@ class MobileLayout extends Component<MobileLayoutProps, MobileLayoutState> {
             </TabPane>
           )}
         </Tabs>
-        <ToolPanel guideUrl={guideUrl} isMobile={true} videoUrl={videoUrl} />
+        {showToolPanel && (
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/classic/mobile-layout.tsx:131]:
```suggestion
        {!hasEditableBoundaries && (
```

File: client/src/templates/Challenges/classic/classic.css [hunk 4]
```diff
@@ -91,6 +91,14 @@
   overflow-y: auto;
 }
 
+[data-uses-multifile-editor='true'][data-has-editable-boundaries='true']
+  #mobile-layout
+  .tab-content {
+  height: calc(
+    100vh - var(--header-height, 0px) - var(--flash-message-height, 0px) - 33px
+  ); /* What does 33px represent? */
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/classic/classic.css:99]: Is this addressing a specific issue?

File: client/src/templates/Challenges/classic/mobile-layout.tsx (hunk 2 above)
Comment (bbsmooth) [reply client/src/templates/Challenges/classic/mobile-layout.tsx]: Thanks for the tip. Basically, I don't need `showToolPanel` any more so I've removed this completely.

File: client/src/components/layouts/learn.tsx (hunk 1 above)
Comment (bbsmooth) [reply client/src/components/layouts/learn.tsx]: I've removed `data-uses-multifile-editor` since we aren't relying on that anymore. Still need to look into `data-has-editable-boundaries`.

File: client/src/templates/Challenges/classic/classic.css (hunk 4 above)
Comment (bbsmooth) [reply client/src/templates/Challenges/classic/classic.css]: Yes, it fixes the double scroll bar issue in the steps while viewing in the mobile layout. Something changed though recently (I think it has to do with the bread crumb links being moved in the DOM) and so the `33px` value was no longer correct and I updated it. You will notice that when viewing the steps in the mobile layout there is only one vertical scroll bar now (on the editor).

I also adjusted the height for the non-steps in mobile layout but it only works correctly in Firefox. In Chrome-based browsers there is something else going on that is causing a very big vertical scroll bar that doesn't need to be there. Do you want me to try and fix that in this PR?

File: client/src/components/layouts/learn.tsx (hunk 1 above)
Comment (bbsmooth) [reply client/src/components/layouts/learn.tsx]: Regarding `data-has-editable-boundaries`, this is used to allow us to set a different height on the tab content when the tool panel buttons aren't displayed in order to prevent double vertical scroll bars.

Comment (ahmadabdolsaheb) [reply client/src/components/layouts/learn.tsx]: That makes sense.

File: client/src/templates/Challenges/classic/classic.css (hunk 4 above)
Comment (ahmadabdolsaheb) [reply client/src/templates/Challenges/classic/classic.css]: Thanks for looking into that. 

I see that the tool panel no longer sticks to the bottom of the display and would require extra scrolling.

I could not replicate the double scroll bar issue on the new responsive web design challenges. 

The behavior seems to be the same when I disable the newly added styles completely. 

If the fix is more involved,  I think we should open an issue for the double scroll and the hidden tool panel and tackle it in another PR.

Comment (bbsmooth) [reply client/src/templates/Challenges/classic/classic.css]: > If the fix is more involved, I think we should open an issue for the double scroll and the hidden tool panel and tackle it in another PR.

Yes, I think it might be best to fix all of the scrolling issues first and then we can remove the tool panel from the mobile layout. I will open a new issue to document all of the current scrolling issues.

**Comment by naomi-lgbt** [comment]
ezgif com-gif-maker

Is this intentional behaviour?

**Comment by ahmadabdolsaheb** [comment]
> ezgif com-gif-maker [ ezgif com-gif-maker ](https://user-images.githubusercontent.com/63889819/198740663-0ce707c8-9133-4174-999a-ff9169d419c5.gif) [ ](https://user-images.githubusercontent.com/63889819/198740663-0ce707c8-9133-4174-999a-ff9169d419c5.gif)
> 
> Is this intentional behaviour?

That is an issue that #48231 should be fixing

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by scissorsneedfoodtoo** [comment]
Hey @bbsmooth, thanks again for all of your help removing the buttons from the mobile layout here.

There are some merge conflicts, though. Would you be able to resolve those?

**Comment by bbsmooth** [comment]
@scissorsneedfoodtoo I'm waiting for [#48586](https://github.com/freeCodeCamp/freeCodeCamp/pull/48586) to merge before I complete this PR.

File: client/src/templates/Challenges/classic/classic.css (hunk 4 above)
Comment (bbsmooth) [reply client/src/templates/Challenges/classic/classic.css]: This scrolling issue has been fixed in another PR and this discussion is no longer applicable.

**Comment by bbsmooth** [comment]
At long last, I think I've got something for you all to review. I've tested it on my android phone with both Chrome and Firefox and it seems to work fine. Would be great if someone with an iPhone could test it with Safari.

**Review by Sembauke — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
