### PR TITLE
fix: navlinks reduce gets type error with empty links.json array

### LINKED ISSUE #16940: [BETA] TypeError: Reduce of empty array with no initial value
#### Issue Description
When the `links.json` file has an empty array `[]`, the NavLinks.jsx code will fail with error "TypeError: Reduce of empty array with no initial value". 

I will have a PR with a fix for this shortly.

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes #16940 

#### Description
Edge case of empty array in `links.json` file causes a type error when NavLinks.jsx tries to build the links.

### CODE REVIEW

File: common/app/Nav/components/NavLinks.jsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ function mapDispatchToProps(dispatch) {
           const handler = `handle${capitalize(content)}Click`;
           mdtp[handler] = createNavLinkActionCreator(content);
           return mdtp;
-        }),
+        }, []),
```
Comment (Bouncey) [inline common/app/Nav/components/NavLinks.jsx]: `mapDispatchToProps` is expected to return an object.

With this change we will be destructuring an array into an object and it would look like
```js
{
  0: [handler],
  1: [handler]
  // ...
}
```

This reduce function should be initialized with an object.

**Review by Bouncey — CHANGES_REQUESTED** [review]

File: common/app/Nav/components/NavLinks.jsx (hunk 1 above)
Comment (tchaffee) [reply common/app/Nav/components/NavLinks.jsx]: Ah yes, the bracket notation for object properties had me fooled into thinking it was an array. I'm assuming I can initialized with an empty object `{}`? It means if the links array is empty, then an empty object will be returned by the `reduce`. If you can confirm I'll get this fixed up. Thanks for the review!

**Comment by musicbanglatv** [comment]
Don't taking legal permission to Brodcast.  Please apply for permission

File: common/app/Nav/components/NavLinks.jsx (hunk 1 above)
Comment (Bouncey) [reply common/app/Nav/components/NavLinks.jsx]: Yes, you can initalise it with an empty object.
One question, why would we have an empty links array? I'm a bit sketchy in this area of the code, it has been a while

Comment (tchaffee) [reply common/app/Nav/components/NavLinks.jsx]: Fixed, and I think this is ready for merge now.

To answer your question, the links array will probably never be empty in practice, but if for some reason you needed to temporarily remove the links in production, the app would crash. With this fix it will just work in all cases.

**Review by Bouncey — APPROVED** [review]

**Comment by Bouncey** [comment]
Thanks @tchaffee :+1:
