### PR TITLE
Fix/Replace nbsp in campers code

### LINKED ISSUE #7753: CSS Rendering issue on Chrome on Android
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; SM-T231 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.105 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

### LINKED ISSUE #11086: Give background color of silver to div element.. Code appears to pass, however results not displaying.
Challenge [Give a Background Color to a Div Element](https://www.freecodecamp.com/challenges/give-a-background-color-to-a-div-element#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20%0A.silver-background%20%7B%0A%C2%A0%C2%A0background-color%3A%20silver%3B%0A%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cdiv%20class%3D%22silver-background%22%3E%0A%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%3C%2Fdiv%3E%0A%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%20checked%3E%20Indoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%20checked%3E%20Loving%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Energetic%3C%2Flabel%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3C%2Fform%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screens

``` html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

.silver-background {
  background-color: silver;
 }

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="silver-background">

  <p>Things cats love:</p>  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
```

### LINKED ISSUE #11400: Coded everything but then also it is not running.
Using from my mobile
Using Google browser
Here is my code...

``` html
<style>
  .red-text {
    color: red;
  }
  p{
    font-size:16px;
  }

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): 

Closes #11400
Closes #7753
Closes #11086  

#### Description

Replaces `nbsp` in campers code before tests are run

### CODE REVIEW

**Comment by Bouncey** [comment]
The code from [this link](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) contains a `&nbsp;`

File: client/sagas/execute-challenge-saga.js [hunk 1]
```diff
@@ -99,29 +99,34 @@ export default function executeChallengeSaga(action$, getState) {
       const { files } = state.challengesApp;
```
Comment (BerkeleyTrue) [inline client/sagas/execute-challenge-saga.js]: This might be better placed as a transformer. Is there a reason you did it directly in the build?

File: client/sagas/execute-challenge-saga.js [hunk 2]
```diff
@@ -99,29 +99,34 @@ export default function executeChallengeSaga(action$, getState) {
...
+      const nbspRegExp = new RegExp(String.fromCharCode(160), 'g');
       return createFileStream(files)
         ::throwers()
         ::transformers()
         // createbuild
         .flatMap(file$ => file$.reduce((build, file) => {
           let finalFile;
+          let newFile = {
+            ...file,
+            contents: file.contents.replace(nbspRegExp, ' ')
```
Comment (BerkeleyTrue) [inline client/sagas/execute-challenge-saga.js]: You don't need a regex when replacing an exact match.

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: client/sagas/execute-challenge-saga.js (hunk 1 above)
Comment (Bouncey) [inline client/sagas/execute-challenge-saga.js]: If I'm honest its the first place I tried. The transformers didn't even come into my thought process. I will refactor.

File: client/sagas/execute-challenge-saga.js (hunk 2 above)
Comment (Bouncey) [inline client/sagas/execute-challenge-saga.js]: Every day is a school day :+1:

File: client/rechallenge/transformers.js [hunk 3]
```diff
@@ -26,6 +26,13 @@ const transformersForHtmlJS = {
       transformer: function addLoopProtect(file) {
         return updateContents(loopProtect(file.contents), file);
       }
+    },
+    {
+      name: 'replace-nbsp',
+      transformer: function replaceNBSP(file) {
+        const nbspRegExp = new RegExp(String.fromCharCode(160), 'g');
```
Comment (Bouncey) [inline client/rechallenge/transformers.js]: Needs to be a RegExp to ensure all `&nbsp;`'s are removed

From [w3schools](http://www.w3schools.com/jsref/jsref_replace.asp)

> If you are replacing a value (and not a regular expression), only the first instance of the value will be replaced.

Comment (BerkeleyTrue) [inline client/rechallenge/transformers.js]: Nice catch.

Can you add this as a property of the object instead of creating per function call.

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Review by BerkeleyTrue — APPROVED** [review]

**Review by ghost — APPROVED** [review]
### LGTM :+1:

Sorry for the wait @Bouncey :smile:
