### PR TITLE
fix: store accessibility for screenreaders

### LINKED ISSUE #42396: Editor - Ability to detect when a screen reader is running
I'm a blind user of FreeCodeCamp. I love that the editor you use has accessibility support, but as of now, you have to turn on screen reader optimization manually each time you use the editor. This can get quite tedious when you're switching between the info and code tabs on challenges, or completing easier challenges quickly.
When I looked at the help documentation for the editor you use, the guide for developers suggests to automatically detect if a screen reader is running, which will allow the editor to automatically turn on accessibility support. That guide can be found [here](https://github.com/microsoft/monaco-editor/wiki/Accessibility-Guide-for-Integrators).
The relevant portion of the guide is quoted below:

> 5. Do you have a way to detect screen readers on your runtime / Do you have a user setting for it?
> Accessibility best practices dictate that applications should be accessible by default, and that no special behaviour should be implemented for accessibility purposes. I would invite the authors of the best practices to try to write a Screen Reader friendly code editor using w3c's ARIA :).
> Anyways, the state of the art is lacking. Here's an example: there is no way to communicate editor wrapping points to Screen Readers, and they will quickly get confused when pressing for example arrow down in a wrapped line; they will expect the system caret to move to the next line, and we will move the system caret to the same model line, at a different column (since the line is wrapped); so, when we know a Screen Reader is connected to an editor, we disable wrapping.
> If you have a user setting (like e.g. Google Docs) or run in an environment where it is possible to find out if a Screen Reader is attached (like e.g. Electron or a WebBrowser control), then please configure the editor with accessibilitySupport: "on". Even if you don't do this, your users will be let know in the editor's aria label that they can optimize the editor by themselves using Alt+F1 (or Ctrl+F1 in IE) and following the directions in there.

Can such a user setting be added so that accessibility support will be enabled automatically? Failing that, can you add a way for the editor to remember the setting for accessibility support once you toggle it?

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42396

### CODE REVIEW

File: client/src/templates/Challenges/classic/editor.tsx [hunk 1]
```diff
@@ -290,6 +290,21 @@ const Editor = (props: EditorProps): JSX.Element => {
...
+
+    if (!store.get('accessibilityMode')) {
+      store.set('accessibilityMode', accessibilityMode);
+    }
+
+    /* eslint-disable */
+    const accesibility = store.get('accessibilityMode').isAccessibilityModeOn;
+
+    return accesibility;
+  };
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/classic/editor.tsx:306]:
```suggestion
  const setAccessibilityMode = () => {
    const accessibilityMode = {
      isAccessibilityModeOn: props.inAccessibilityMode
    };
    type AccessibilityMode = typeof accessibilityMode;

    function accessibilityModeOrNull(mode: unknown): AccessibilityMode | null {
      const access = mode as AccessibilityMode;
      return access.isAccessibilityModeOn ? access : null;
    }
    const accessibility = accessibilityModeOrNull(store.get('accessibility'));
    if (!accessibility) {
      store.set('accessibilityMode', accessibilityMode);
    }
    return accessibility?.isAccessibilityModeOn ?? false;
  };
```

Comment (ShaunSHamilton) [reply client/src/templates/Challenges/classic/editor.tsx:306]: This is probably a bit redundant, as you might as well:
```suggestion
  const setAccessibilityMode = () => {
    const accessibilityMode = {
      isAccessibilityModeOn: props.inAccessibilityMode
    };
    type AccessibilityMode = typeof accessibilityMode;

    const accessibility = store.get('accessibilityMode') as AccessibilityMode;
    if (!accessibility) {
      store.set('accessibilityMode', accessibilityMode);
    }
    return accessibility?.isAccessibilityModeOn ?? false;
  };
```

**Comment by Sembauke** [comment]
probably should translate the set aria-label, that announces the state of the accessibility mode.

**Review by ShaunSHamilton — COMMENTED** [review]
Something I am not sure with this is we are using  `inAccessibilityModeSelector`, and storing changed values in localStorage, but are not updating the Redux store.

That is, we have now changed to using an internal `setAccessibilityMode`, instead of using the `setAccessibilityMode` action from Redux. Application localStorage vs application state

**Comment by Sembauke** [comment]
You are right, I will look into it!

**Comment by Sembauke** [comment]
@ShaunSHamilton  What would you suggest?

**Comment by ShaunSHamilton** [comment]
> @ShaunSHamilton What would you suggest?

Accessibility-wise, I am rather useless. It sounds like ensuring the `aria` labels are correct is enough 🤷‍♂️ 

As for Redux:
- We need to figure out where the `inAccessibilityMode` state is used, (if at all).
- If it is not used anywhere else (outside the editor), we can probably remove it to make use of the the localstorage
- If it is used elsewhere, we need the `setAccessibilityMode` function you have created to also dispatch an action (unfortunately also called `setAccessibilityMode`) changing the Redux store state - **this is currently what is not happening**

**Comment by Sembauke** [comment]
Should be good.
1. setAccessibility and inAcessibility mode are basically the same.
2. The redux state gets updated on editormount

File: client/src/templates/Challenges/classic/editor.tsx [hunk 2]
```diff
@@ -297,9 +297,35 @@ const Editor = (props: EditorProps): JSX.Element => {
...
+        editor.updateOptions({
+          ariaLabel:
+            'Accessibility mode set to true press ctrl + e to disable; Press alt F1 for more options'
+        });
+      }
+
+      return accessibility?.isAccessibilityModeOn ?? false;
+    };
+
     editor.updateOptions({
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/classic/editor.tsx:324]:
```suggestion

    const accessibilityMode = storedAccessibilityModes();
    editor.updateOptions({
```

File: client/src/templates/Challenges/classic/editor.tsx [hunk 3]
```diff
@@ -297,9 +297,35 @@ const Editor = (props: EditorProps): JSX.Element => {
...
-      accessibilitySupport: props.inAccessibilityMode ? 'on' : 'auto'
+      accessibilitySupport: storedAccessibilityModes() ? 'on' : 'off'
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/classic/editor.tsx:325]:
```suggestion
      accessibilitySupport: accessibilityMode ? 'on' : 'off'
```

File: client/src/templates/Challenges/classic/editor.tsx [hunk 4]
```diff
@@ -297,9 +297,35 @@ const Editor = (props: EditorProps): JSX.Element => {
...
     });
+
+    props.setAccessibilityMode(storedAccessibilityModes());
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/classic/editor.tsx:328]:
```suggestion
    props.setAccessibilityMode(accessibilityMode);
```

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Just to call the function less.

I do not know if it should change in this PR, but the ideal workflow would probably be:
- Camper toggles accessibilityMode
- This triggers dispatch to Redux
- Redux updates store, and hands off to epic
- Epic updates localStorage

_I think we do something similar for saving code_. The idea is less is apparently going on in the one component - the editor is big enough.

**Comment by Sembauke** [comment]
Sure I would love to look into epic,  or we can just go with this for now.

**Comment by ShaunSHamilton** [comment]
> Sure I would love to look into epic though it would require a lot more time, or we can just go with this for now.

Let us see what others think. If others are happy this closes the issue, then I am happy with this as is.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 5]
```diff
@@ -297,9 +298,36 @@ const Editor = (props: EditorProps): JSX.Element => {
...
+        });
+      }
+
+      return accessibility?.isAccessibilityModeOn ?? false;
+    };
+
+    const accessibilityMode = storedAccessibilityModes();
     editor.updateOptions({
-      accessibilitySupport: props.inAccessibilityMode ? 'on' : 'auto'
+      accessibilitySupport: accessibilityMode ? 'on' : 'off'
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:327]: Do we need to change from a default of `auto`?  It seems to be fine and is recommended by the Monaco docs: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#accessibilitysupport
```suggestion
      accessibilitySupport: accessibilityMode ? 'on' : 'auto'
```

File: client/src/templates/Challenges/classic/editor.tsx [hunk 6]
```diff
@@ -343,28 +371,19 @@ const Editor = (props: EditorProps): JSX.Element => {
...
-        const currentAccessibility = props.inAccessibilityMode;
-        // The store needs to be updated first, as onDidChangeConfiguration is
-        // called before updateOptions returns
+        const currentAccessibility = storedAccessibilityModes();
+        
+        store.set( 'accessibilityMode', { isAccessibilityModeOn: !currentAccessibility });
         props.setAccessibilityMode(!currentAccessibility);
         editor.updateOptions({
-          accessibilitySupport: currentAccessibility ? 'auto' : 'on'
+          accessibilitySupport: storedAccessibilityModes() ? 'on' : 'off',
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:381]:
```suggestion
          accessibilitySupport: storedAccessibilityModes() ? 'on' : 'auto',
```
Same argument as above.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 7]
```diff
@@ -297,9 +298,36 @@ const Editor = (props: EditorProps): JSX.Element => {
...
+      const accessibility = store.get('accessibilityMode') as AccessibilityMode;
+      if (!accessibility) {
+        store.set('accessibilityMode', accessibilityMode);
+      }
+      // Only able to set the arialabel when it is set to true
+      // Otherwise it gets overwritten by the monaco default aria-label
+      if (accessibility?.isAccessibilityModeOn) {
+        editor.updateOptions({
+          ariaLabel:
+            'Accessibility mode set to true press ctrl + e to disable; Press alt F1 for more options'
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:318]:
```suggestion
            'Accessibility mode set to true. Press ctrl + e to disable;'
```
Isn't `alt F1` system specific?  On Ubuntu that shows all windows at once.  `F1` brings up the list of commands on my system, but I don't know if that's universal.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 8]
```diff
@@ -297,9 +298,36 @@ const Editor = (props: EditorProps): JSX.Element => {
     // TODO this should *probably* be set on focus
     editorRef.current = editor;
     data.editor = editor;
+
+    const storedAccessibilityModes = () => {
+      const accessibilityMode = {
+        isAccessibilityModeOn: props.inAccessibilityMode
+      };
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:305]:
```suggestion
      const accessibilityMode = props.inAccessibilityMode;
```
It seems simpler just to use a boolean here.  The rest of the code naturally becomes cleaner if you do.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 9]
```diff
@@ -297,9 +298,36 @@ const Editor = (props: EditorProps): JSX.Element => {
...
+      // Only able to set the arialabel when it is set to true
+      // Otherwise it gets overwritten by the monaco default aria-label
+      if (accessibility?.isAccessibilityModeOn) {
+        editor.updateOptions({
+          ariaLabel:
+            'Accessibility mode set to true press ctrl + e to disable; Press alt F1 for more options'
+        });
+      }
+
+      return accessibility?.isAccessibilityModeOn ?? false;
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:322]:
```suggestion
      return accessibility;
```
For example, you can do this if `accessibility` is a boolean.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey Sem, I can't see a reason to keep the redux stuff around any more.  If you could rip all of that out, that would be awesome - your approach with local storage is much nicer anyway.

That said, if you're not sure about messing with redux, I can handle that.  I'm a big fan of deleting stuff.

**Comment by Sembauke** [comment]
Hey @ojeytonwilliams,
I'll take a look!

File: client/src/templates/Challenges/classic/editor.tsx (hunk 8 above)
Comment (Sembauke) [reply client/src/templates/Challenges/classic/editor.tsx:305]: Not sure about this, this is only to store the key in the local storage, for example: when a new user starts for the first time, or when local storage gets deleted.

File: client/src/templates/Challenges/classic/editor.tsx (hunk 7 above)
Comment (Sembauke) [reply client/src/templates/Challenges/classic/editor.tsx:316]: The default message when accessibility mode is disabled is:

"The editor is not accessible at this time. Press Alt+F1 for options."

Just to be sure can you take a look at your Ubuntu system if it is the same?

To get there easily:
1. Open dev tools in Chrome
2. If you are not already go to the elements page
3. Press CTRL + F and search for textarea

File: client/src/templates/Challenges/classic/editor.tsx (hunk 5 above)
Comment (ojeytonwilliams) [reply client/src/templates/Challenges/classic/editor.tsx:318]: 'auto' is effectively 'off' for me.  I'm not sure exactly why that's the default, but that's what they suggest in their docs :man_shrugging:

File: client/src/templates/Challenges/classic/editor.tsx (hunk 7 above)
Comment (ojeytonwilliams) [reply client/src/templates/Challenges/classic/editor.tsx:309]:
```suggestion
            'Accessibility mode set to true. Press Ctrl+e to disable or press Alt+F1 for more options'
```
That's unfortunate, but I guess it would be more confusing if we did something custom.  Thanks for explaining, I've updated the suggestion to just tweak the wording.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 10]
```diff
@@ -297,8 +291,31 @@ const Editor = (props: EditorProps): JSX.Element => {
...
     data.editor = editor;
+
+    const storedAccessibilityModes = () => {
+      const accessibilityMode = false;
+
+      type AccessibilityMode = typeof accessibilityMode;
+
+      const accessibility = store.get('accessibilityMode') as AccessibilityMode;
+      if (!accessibility) {
+        store.set('accessibilityMode', accessibilityMode);
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/editor.tsx:302]:
```suggestion
      const accessibility = store.get('accessibilityMode') as boolean;
      if (!accessibility) {
        store.set('accessibilityMode', false);
```
Just a bit simpler.

File: client/src/templates/Challenges/components/Tool-Panel.js [hunk 11]
```diff
@@ -53,7 +53,12 @@ function ToolPanel({
         isMobile ? 'tool-panel-group-mobile' : ''
       }`}
     >
-      <Button block={true} bsStyle='primary' onClick={handleRunTests}>
+      <Button
+        aria-label='Run the tests use shortcut ctrl enter'
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/components/Tool-Panel.js:57]:
```suggestion
        aria-label='Run the tests use shortcut Ctrl+enter'
```
Nitpick

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
On line 322, we use the `inAccessibilityMode` prop to control focus, so that should depend on `storedAccessibilityModes()`, but GitHub doesn't let me suggest it.

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1:

File: client/src/templates/Challenges/classic/editor.tsx [hunk 12]
```diff
@@ -343,28 +355,18 @@ const Editor = (props: EditorProps): JSX.Element => {
...
-      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.F1],
+      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_E],
       run: () => {
-        const currentAccessibility = props.inAccessibilityMode;
-        // The store needs to be updated first, as onDidChangeConfiguration is
-        // called before updateOptions returns
-        props.setAccessibilityMode(!currentAccessibility);
+        const currentAccessibility = storedAccessibilityMode();
+        
+        store.set( 'accessibilityMode', !currentAccessibility);
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/classic/editor.tsx:362]:
```suggestion
        store.set('accessibilityMode', !currentAccessibility);
```

**Review by ShaunSHamilton — DISMISSED** [review]
This LGTM 👍 . However, I am shocked Linty did not complain about this 🤷‍♂️

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by ojeytonwilliams — APPROVED** [review]
