### PR TITLE
fix: prevent dev tools from accessing state in prod

### LINKED ISSUE #38638: Redux Dev Tool Extension can access the state in production
**Describe the bug**
In the freecodecamp.org website, Redux dev tools extension can be used to access the current and previous state. It may be noted that, actions can not be dispatched through the Redux Dev Tool extension.

**To Reproduce**
1. Go to 'freecodecamp.org'
2. Click on the Redux Dev Tools Extension

**Expected behavior**
It is widely accepted as a best practice to not have development/debugging features in the production codebase. So, in the current context the Redux Dev Tools shouldn't be able to access the state.

**Screenshots**
Capture

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 Bit)
 - Browser: Google Chrome
 - Version: Version 81.0.4044.122 (Official Build) (64-bit)

**Additional context**
Redux Dev Tools Extension can be found [here](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).

It seems that the `__REDUX_DEVTOOLS_EXTENSION__` was exposed to the global `window` object
which allows the Redux Dev Tool extension to read state. While bundling for the production codebase, this should be removed to avoid such behaviour.

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38638

In the freecodecamp.org website, Redux dev tools extension can be used to access the current and previous state. This problem was fixed in this PR.

### CODE REVIEW

File: client/src/redux/createStore.js [hunk 1]
```diff
@@ -29,10 +29,18 @@ const composeEnhancers = composeWithDevTools({
 });
 
 export const createStore = () => {
-  const store = reduxCreateStore(
-    rootReducer,
-    composeEnhancers(applyMiddleware(sagaMiddleware, epicMiddleware))
-  );
+  let store;
+  if (process.env.FREECODECAMP_NODE_ENV === 'development') {
```
Comment (moT01) [inline client/src/redux/createStore.js:33]:
```suggestion
  if (process.env.FREECODECAMP_NODE_ENV === 'production') {
```

File: client/src/redux/createStore.js [hunk 2]
```diff
@@ -29,10 +29,18 @@ const composeEnhancers = composeWithDevTools({
...
+    store = reduxCreateStore(
+      rootReducer,
+      composeEnhancers(applyMiddleware(sagaMiddleware, epicMiddleware))
```
Comment (moT01) [inline client/src/redux/createStore.js:36]:
```suggestion
      applyMiddleware(sagaMiddleware, epicMiddleware)
```

File: client/src/redux/createStore.js [hunk 3]
```diff
@@ -29,10 +29,18 @@ const composeEnhancers = composeWithDevTools({
...
+    );
+  } else {
+    store = reduxCreateStore(
+      rootReducer,
+      applyMiddleware(sagaMiddleware, epicMiddleware)
```
Comment (moT01) [inline client/src/redux/createStore.js:41]:
```suggestion
      composeEnhancers(applyMiddleware(sagaMiddleware, epicMiddleware))
```

**Review by moT01 — COMMENTED** [review]
Were you able to test this locally @Twaha-Rahman? I could not get my dev tools working after setting the env variables. I think it should be switched around to check for `production`. What do you think?

**Comment by Twaha-Rahman** [comment]
Added the commits to reflect the suggestions.

File: client/src/redux/createStore.js [hunk 4]
```diff
@@ -29,10 +29,18 @@ const composeEnhancers = composeWithDevTools({
 });
 
 export const createStore = () => {
-  const store = reduxCreateStore(
-    rootReducer,
-    composeEnhancers(applyMiddleware(sagaMiddleware, epicMiddleware))
-  );
+  let store;
+  if (process.env.FREECODECAMP_NODE_ENV === 'production') {
```
Comment (ojeytonwilliams) [inline client/src/redux/createStore.js:33]:
```suggestion
  if (ENVIRONMENT === 'production') {
```
`process` is not available in the browser, but `ENVIRONMENT` is defined globally.

Could you also add `/* global ENVIRONMENT */` at the start of the file?  Otherwise it will fail during linting.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
I've checked this out locally and (with the changes) it looks good.  As far as QAing, I just set 

```
    "develop": "cross-env FREECODECAMP_NODE_ENV=production node --inspect=0.0.0.0:9228 node_modules/gatsby-cli develop",
```
in the `package.json` and commented out lines 43 to 66 in `gatsby-node.js`.

File: client/src/redux/createStore.js (hunk 4 above)
Comment (raisedadead) [reply client/src/redux/createStore.js:33]: I think this will have to go thru our config setup for env variables using the `env.json`, I can take a look later this week, unless someone beats me to it.

Comment (ojeytonwilliams) [reply client/src/redux/createStore.js:33]: I think this *should* work, but avoiding globals entirely seems like a good plan.

**Comment by Twaha-Rahman** [comment]
> Could you also add `/* global ENVIRONMENT */` at the start of the file? Otherwise it will fail during linting.

@ojeytonwilliams Do you want me to add `/* global ENVIRONMENT */` at the beginning of the file `createStore.js`?

**Comment by ojeytonwilliams** [comment]
@Twaha-Rahman I would fix the lint error in this PR and then create an issue to remind us we want to move to using `env.json` exclusively.  @raisedadead sound like a plan?

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams Okay. Thanks for your help!

**Comment by raisedadead** [comment]
Bump.

**Comment by ojeytonwilliams** [comment]
@raisedadead you're okay with the plan I outlined?

**Comment by raisedadead** [comment]
Oh - I missed clarifying your previous request. Yes, it should be fine to add it to the `env.json` after the fact.

**Comment by Twaha-Rahman** [comment]
Umm... guys, any progress?

**Comment by ojeytonwilliams** [comment]
Sorry @Twaha-Rahman, I think I should have clarified.  Could you fix the lint error to make Travis happy?  Don't worry about creating a new issue, I'll do that now.

**Comment by ojeytonwilliams** [comment]
> > Could you also add `/* global ENVIRONMENT */` at the start of the file? Otherwise it will fail during linting.
> 
> @ojeytonwilliams Do you want me to add `/* global ENVIRONMENT */` at the beginning of the file `createStore.js`?

Yep, that should work.

**Comment by Twaha-Rahman** [comment]
> Sorry @Twaha-Rahman, I think I should have clarified. Could you fix the lint error to make Travis happy? Don't worry about creating a new issue, I'll do that now.

Thanks for the quick reply! I'm on it right now.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
These changes should stop the linter complaining.

**Review by raisedadead — COMMENTED** [review]
You should run the `npm run lint` locally/GitPod to catch them all at one go.

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams I actually tried the things you've said, it passes the linting section but fails on the tests section.

@raisedadead Thanks for the tip.

**Comment by ojeytonwilliams** [comment]
Hey @Twaha-Rahman, I finally see the problem.

Turns out that using a global `ENVIRONMENT` would make the tests needlessly complicated. So, since we're planning to remove globals anyway, I went ahead and removed this one.  Let me know what you think.

(apologies for the rebase - I needed to do that to fix an unrelated issue)

**Review by ojeytonwilliams — APPROVED** [review]
