### PR TITLE
fix(client): accuracy issue with heatmap

### LINKED ISSUE #38037: Longest Streak is inaccurate
I'm a new camper. Last days I did challenges every day

My longest streak should be 4, but it's 1. I think January 8 is missing.

In 7 and 9 January I did challenges at night, may be 2 or 3 AM. January 8 I did 3 challenges in the evening, about 22 PM. My timezone UTC+3.

**Desktop (please complete the following information):**
 - Ubutnu
 - Chrome and Firefox
 - Version 78 and 71

### PR DESCRIPTION
**Pull request by moT01**
This seems like it fixes the issue. There's some comments in the code with more description.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to #38037
I'm actually not sure if this will fix the problems with the streak described in the issue, but it will make the calendar accurate. Right now the calendar shows the most recent day as yesterday and not today. This will adjust for that.

### CODE REVIEW

File: client/src/components/profile/components/HeatMap.js [hunk 1]
```diff
@@ -22,7 +22,22 @@ const propTypes = {
...
 function HeatMap({ calendar, streak }) {
-  const startOfToday = startOfDay(Date.now());
+  // an issue with react-calendar-heatmap makes the days off by one
+  // see this https://github.com/kevinsqi/react-calendar-heatmap/issues/112
+  // I have added one day in the marked places to account for the offset
+
+  // this logic adds a day to all the timestamps (remove if issue gets fixed)
+  let tempCalendar = {};
+  const secondsInADay = 60 * 60 * 24;
+  for (let timestamp in calendar) {
```
Comment (ojeytonwilliams) [inline client/src/components/profile/components/HeatMap.js]: Maybe use `forEach` as `for...in` [isn't the best for this sort of thing](https://stackoverflow.com/a/3010848).

If you are going to change this, probably best to use `forEach`  here https://github.com/freeCodeCamp/freeCodeCamp/blob/c86903a0e121a543627a071658667ee5991bed80/client/src/components/profile/components/HeatMap.js#L53
as well.  It should all end up a little more concise, as you don't need to check if the ids exist and so on.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Since this will need changing if `react-calendar-heatmap` gets fixed, could you add a test that will fail if this isn't updated accordingly?  It's probably enough to take a snapshot, since that should change if the library changes.

File: client/src/components/profile/components/HeatMap.js (hunk 1 above)
Comment (moT01) [reply client/src/components/profile/components/HeatMap.js]: Thanks for looking at this, `calendar` is simply an object and not an array that looks like this...
```
{
  1567696744262: 1,
  1567696744264: 1,
  ...
}
```
So I can't use the array methods. I would have to grab the keys or something - I can take a look and see if I can find a better way.

Comment (ojeytonwilliams) [reply client/src/components/profile/components/HeatMap.js]: Oh, I assumed it was an array - my mistake.  Weird that it's done this way, but it is what it is.

In that case, is there any need for the following?
https://github.com/freeCodeCamp/freeCodeCamp/blob/c86903a0e121a543627a071658667ee5991bed80/client/src/components/profile/components/HeatMap.js#L54

Anyway, sorry for the misunderstanding.

Comment (moT01) [reply client/src/components/profile/components/HeatMap.js]: I agree that it does look a little sloppy and could probably be better somehow. I was thinking about taking a deeper look at where that data is coming from and maybe trying to make things a little more efficient or something. It just feels a little weird and like it could be better.

> In that case, is there any need for the following?

I didn't think so, but eslint was having a fit when I didn't put it in...
Screen Shot 2020-01-30 at 5 33 30 PM

Comment (ojeytonwilliams) [reply client/src/components/profile/components/HeatMap.js]: `calendar` comes from here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/2f39dd07d66c55d498399a6fc6cfe21e196ebd2f/api-server/server/utils/publicUserProps.js#L70-L75
so it's just a plain object of the form
```js
{
  "<time-in-seconds>": 1,
  ...
}
```

How about:
```js
  for (let timestamp of Object.keys(calendar)) {
```
since we only want keys and `Object.keys` ignores everything that's not directly on the object.

Comment (moT01) [reply client/src/components/profile/components/HeatMap.js]: Well, I tried to simplify some of the logic and cut out a step. Seems a little better.

I don't think a simple snapshot will work here because the days of the heatmap will always change. Meaning the snapshot taken today will show 2/1 as the most recent day on the calendar/snapshot. But tomorrow the snapshot won't match anymore.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by raisedadead — APPROVED** [review]

**Comment by RandellDawson** [comment]
FYI - Ever since this PR was merged, I can not run `npm run test` on the master branch without getting the following failures:
```
Summary of all failing tests
 FAIL  ./jest.test.js
  ● Timezones › should always be UTC

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 420

      2 | describe('Timezones', () => {
      3 |   it('should always be UTC', () => {
    > 4 |     expect(new Date().getTimezoneOffset()).toBe(0);
        |                                            ^
      5 |   });
      6 | });
      7 | 

      at Object.toBe (jest.test.js:4:44)

 FAIL  src/components/profile/components/HeatMap.test.js
  ● <HeatMap/> › renders correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `<HeatMap/> renders correctly 1`

    - Snapshot
    + Received

    @@ -11,54 +11,61 @@
              <div
                class="col-sm-8 col-sm-offset-2 col-xs-12"
              >
                <svg
                  class="react-calendar-heatmap"
    -             viewBox="0 0 296 90"
    +             viewBox="0 0 307 90"
                >
                  <g
                    class="react-calendar-heatmap-month-labels"
                    transform="translate(0, 0)"
                  >
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="33"
    +                 x="0"
    +                 y="10"
    +               >
    +                 Aug
    +               </text>
    +               <text
    +                 class="react-calendar-heatmap-month-label"
    +                 x="44"
                      y="10"
                    >
                      Sep
                    </text>
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="88"
    +                 x="99"
                      y="10"
                    >
                      Oct
                    </text>
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="132"
    +                 x="143"
                      y="10"
                    >
                      Nov
                    </text>
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="176"
    +                 x="187"
                      y="10"
                    >
                      Dec
                    </text>
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="231"
    +                 x="242"
                      y="10"
                    >
                      Jan
                    </text>
                    <text
                      class="react-calendar-heatmap-month-label"
    -                 x="275"
    +                 x="286"
                      y="10"
                    >
                      Feb
                    </text>
                  </g>
    @@ -67,10 +74,26 @@
                    transform="translate(0, 14)"
                  >
                    <g
                      class="react-calendar-heatmap-week"
                      transform="translate(0, 0)"
    +               >
    +                 <rect
    +                   class="color-empty"
    +                   currentItem="false"
    +                   data-tip="<b>No points</b> on Aug 3, 2019"
    +                   height="10"
    +                   width="10"
    +                   x="0"
    +                   y="66"
    +                 >
    +                   <title />
    +                 </rect>
    +               </g>
    +               <g
    +                 class="react-calendar-heatmap-week"
    +                 transform="translate(11, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Aug 4, 2019"
    @@ -148,11 +171,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(11, 0)"
    +                 transform="translate(22, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Aug 11, 2019"
    @@ -230,11 +253,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(22, 0)"
    +                 transform="translate(33, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Aug 18, 2019"
    @@ -312,11 +335,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(33, 0)"
    +                 transform="translate(44, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Aug 25, 2019"
    @@ -394,11 +417,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(44, 0)"
    +                 transform="translate(55, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Sep 1, 2019"
    @@ -476,11 +499,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(55, 0)"
    +                 transform="translate(66, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Sep 8, 2019"
    @@ -558,11 +581,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(66, 0)"
    +                 transform="translate(77, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Sep 15, 2019"
    @@ -640,11 +663,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(77, 0)"
    +                 transform="translate(88, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Sep 22, 2019"
    @@ -722,11 +745,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(88, 0)"
    +                 transform="translate(99, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Sep 29, 2019"
    @@ -804,11 +827,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(99, 0)"
    +                 transform="translate(110, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Oct 6, 2019"
    @@ -886,11 +909,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(110, 0)"
    +                 transform="translate(121, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Oct 13, 2019"
    @@ -968,11 +991,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(121, 0)"
    +                 transform="translate(132, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Oct 20, 2019"
    @@ -1050,11 +1073,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(132, 0)"
    +                 transform="translate(143, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Oct 27, 2019"
    @@ -1132,11 +1155,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(143, 0)"
    +                 transform="translate(154, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Nov 3, 2019"
    @@ -1214,11 +1237,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(154, 0)"
    +                 transform="translate(165, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Nov 10, 2019"
    @@ -1296,11 +1319,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(165, 0)"
    +                 transform="translate(176, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Nov 17, 2019"
    @@ -1378,11 +1401,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(176, 0)"
    +                 transform="translate(187, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Nov 24, 2019"
    @@ -1460,11 +1483,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(187, 0)"
    +                 transform="translate(198, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Dec 1, 2019"
    @@ -1542,11 +1565,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(198, 0)"
    +                 transform="translate(209, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Dec 8, 2019"
    @@ -1624,11 +1647,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(209, 0)"
    +                 transform="translate(220, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Dec 15, 2019"
    @@ -1706,11 +1729,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(220, 0)"
    +                 transform="translate(231, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Dec 22, 2019"
    @@ -1788,11 +1811,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(231, 0)"
    +                 transform="translate(242, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Dec 29, 2019"
    @@ -1870,11 +1893,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(242, 0)"
    +                 transform="translate(253, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Jan 5, 2020"
    @@ -1952,11 +1975,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(253, 0)"
    +                 transform="translate(264, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Jan 12, 2020"
    @@ -2034,11 +2057,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(264, 0)"
    +                 transform="translate(275, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Jan 19, 2020"
    @@ -2116,11 +2139,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(275, 0)"
    +                 transform="translate(286, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Jan 26, 2020"
    @@ -2198,11 +2221,11 @@
                        <title />
                      </rect>
                    </g>
                    <g
                      class="react-calendar-heatmap-week"
    -                 transform="translate(286, 0)"
    +                 transform="translate(297, 0)"
                    >
                      <rect
                        class="color-empty"
                        currentItem="false"
                        data-tip="<b>No points</b> on Feb 2, 2020"

      33 |   it('renders correctly', () => {
      34 |     const { container } = render(<HeatMap {...props} />);
    > 35 |     expect(container).toMatchSnapshot();
         |                       ^
      36 |   });
      37 | });
      38 | 

      at Object.toMatchSnapshot (src/components/profile/components/HeatMap.test.js:35:23)
```

**Comment by moT01** [comment]
Yea, there was issues all over the place with this heatmap and streak @RandellDawson. [I have a PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/38318) that's ready for some feedback to hopefully fix this stuff once and for all - which includes some changes to the tests. You should check it out and see if the tests are failing for you with those changes. If they still are we can maybe tweak things over there.

**Comment by RandellDawson** [comment]
@moT01 I will pull down the other PR now and test.
