### PR TITLE
fix(client): typo in top contributer badge component

### LINKED ISSUE #60743: typo at camper.tsx component code( TopContibutorBadgeEmblem -> TopContributorBadgeEmblem)
### Describe the Issue

Image

### Affected Page

profile

### Steps to Reproduce

1. Go to file  'client/src/components/profile/components/camper.tsx' at codebase
4. See error:` import TopContibutorBadgeEmblem`

### Expected behavior

should be :` import TopContributorBadgeEmblem` (with r after t)

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by forge34**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #60743

fixed typo in `camper.tsx` and `top-contributor-badge-emblem.tsx` 
from `TopContibutorBadgeEmblem` to `TopContributorBadgeEmblem`

### CODE REVIEW

File: client/src/assets/icons/top-contributor-badge-emblem.tsx [hunk 1]
```diff
@@ -419,6 +419,6 @@ function TopContibutorBadgeEmblem(
   );
 }
 
-TopContibutorBadgeEmblem.displayName = 'TopContibutorBadgeEmblem';
+TopContributorBadgeEmblem.displayName = 'TopContibutorBadgeEmblem';
```
Comment (huyenltnguyen) [inline client/src/assets/icons/top-contributor-badge-emblem.tsx]:
```suggestion
TopContributorBadgeEmblem.displayName = 'TopContributorBadgeEmblem';
```

**Review by majestic-owl448 — APPROVED** [review]
LGTM

**Review by a2937 — APPROVED** [review]

**Comment by a2937** [comment]
Hi @forge34 . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

**Comment by forge34** [comment]
Thanks! Happy to contribute.
