### PR TITLE
fix(client): give useful error in solutionform

### LINKED ISSUE #39729: Project Submission Throws Uncaught Error
Submitting an invalid URL for the Front End projects does not behave as expected:
image

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

**Expected**:
- No uncaught errors
- Camper is notified about misshapen URL

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39729 

This PR includes a bit of groundwork for better error handling, but would require a bit too much refactoring. So, I would prefer this to be a PR relating more to helping with the case where Campers try to pass the incorrect URLs.

**QUESTION:** Should I expand this to validate whether the camper has submitted the example URLs? It would remove the need to keep updating the first user-story tests for each project.

### CODE REVIEW

**Comment by Sky020** [comment]
@ahmadabdolsaheb  I would appreciate your opinion on the wording/styling of the hint:
image

**Comment by nhcarrigan** [comment]
What about `Please submit the link to the live version of your app`?

**Comment by Sky020** [comment]
@nhcarrigan It would need to be shorter than it already is, not longer; I do not want it wrapping on smaller screens.

**Review by kbakdev — DISMISSED** [review]

**Comment by Sky020** [comment]
Currently, this is at a point where I could see it being merged. All it would help with is warnings about invalid URLs, and I have set up the ground work I would expect for better error handling, and URL validation.

**Comment by Sky020** [comment]
I cannot seem to pass the Cypress test. Here is the failure:
```text
 2) A certification,
       while viewing someone else's,
         "before all" hook for "should not render a LinkedIn button":
     AssertionError: Timed out retrying: Expected to find content: 'Sign me out of freeCodeCamp' but never did.
```

I am still busy trying to setup tests for GitPod, so cannot test this locally (laptop is struggling). Otherwise, I do not think I touched anything related in this PR, anyway.

**Comment by ojeytonwilliams** [comment]
Hey @Sky020, there's one issue stemming from the change to `formatUrlValues`.  That's used in `handleSubmitLegacy`, so that also needs to handle the `{ values: ...}` object.

**Comment by ahmadabdolsaheb** [comment]
> @ahmadabdolsaheb I would appreciate your opinion on the wording/styling of the hint:


The message is descriptive. I would add a dot to the end of the message for consistency 👍 
Although we are using different elements, we should unify the padding between the form and hint/error across our UI at some point.


image

image

File: client/src/templates/Challenges/projects/frontend/Show.js [hunk 1]
```diff
@@ -95,6 +109,13 @@ export class Project extends Component {
     }
   }
 
+  handleSubmit({ openCompletionModal }) {
+    console.log(openCompletionModal);
+    if (openCompletionModal) {
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/projects/frontend/Show.js:114]:
```suggestion
  handleSubmit({ isOpenCompletionModal }) {
    if (isOpenCompletionModal) {
```

Comment (ahmadabdolsaheb) [reply client/src/templates/Challenges/projects/frontend/Show.js]: isOpenCompletionModal should be passed instead of openCompletionModal

**Comment by ahmadabdolsaheb** [comment]
Since only SolutionForm sets the DisplayError and only FormFields gets it and FormFields is the direct descendent of  SolutionForm (SolutionForm > Form > FormFields), I think it would be better to have DisplayError as a state on SolutionForm and pass it down as props. 

We could use Context to avoid passing it down one component at a time.

That way FormFields does not need to be a connected component and we can free up some space on the redux store.

**Comment by ahmadabdolsaheb** [comment]
Some e2e tests are also appreciated.

File: client/src/redux/index.js [hunk 2]
```diff
@@ -43,6 +43,7 @@ const initialState = {
   canRequestProgressDonation: true,
   completionCount: 0,
   currentChallengeId: store.get(CURRENT_CHALLENGE_KEY),
+  errors: [],
```
Comment (ahmadabdolsaheb) [inline client/src/redux/index.js:46]:
```suggestion
```

File: client/src/components/formHelpers/FormFields.js [hunk 3]
```diff
@@ -10,8 +10,24 @@ import {
...
 const propTypes = {
+  errors: PropTypes.arrayOf(
+    PropTypes.shape({
+      error: PropTypes.shape({
+        message: PropTypes.string,
+        stack: PropTypes.string
+      }),
+      value: PropTypes.string
+    })
+  ),
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/FormFields.js:30]:
```suggestion
```

Comment (ShaunSHamilton) [reply client/src/components/formHelpers/FormFields.js:30]: Is there a better way to represent the shape of this data?

File: client/src/templates/Challenges/projects/SolutionForm.js [hunk 4]
```diff
@@ -9,9 +9,12 @@ import {
   pythonProject
 } from '../../../../utils/challengeTypes';
 
+export const SolutionFormContext = createContext({ displayErrors: [] });
+
 const propTypes = {
   challengeType: PropTypes.number,
   description: PropTypes.string,
+  displayErrors: PropTypes.func,
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/projects/SolutionForm.js:17]:
```suggestion
```

**Comment by ahmadabdolsaheb** [comment]
Since we already have all the info we need for opening the completion modal in execute-challenge-saga, I cannot think of a good reason to have challenge-modal-epic, what do you think?

File: client/src/templates/Challenges/projects/frontend/Show.js [hunk 5]
```diff
@@ -42,6 +43,15 @@ const propTypes = {
...
   }),
+  errors: PropTypes.arrayOf(
+    PropTypes.shape({
+      error: PropTypes.shape({
+        message: PropTypes.string,
+        stack: PropTypes.string
+      }),
+      value: PropTypes.string
+    })
+  ),
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/projects/frontend/Show.js:54]:
```suggestion
```

Comment (ahmadabdolsaheb) [reply client/src/templates/Challenges/projects/frontend/Show.js:54]: I don't think we need this

**Comment by ahmadabdolsaheb** [comment]
We are setting `isCompletionModalShouldOpen` to the redux store with the executeChallenge. Then we would read  `isCompletionModalShouldOpen` from store in `execute-challenge-saga` when `executeChallenge` is called. 

Since  `isCompletionModalShouldOpen` is supplied to `executeChallenge` as payload and it is only used in this context, It might make more sense to just use as payload directly in execute-challenge-saga and not set it in the store.

Also, what do you think of `shouldCompletionModalOpen` as an alternative name?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb I have compromised on the name of the variable - now `isShouldCompletionModalOpen`

Also, I have passed it as an argument directly (bypassing the store). However, it is currently in the payload as `true`, and not `{ isShouldCompletionModalOpen: true }`. I have mixed thoughts about the clarity of this, so what do you think?

File: client/src/components/formHelpers/Form.test.js [hunk 6]
```diff
@@ -4,6 +4,10 @@ import React from 'react';
 import { render, fireEvent } from '@testing-library/react';
 
 import Form from './Form';
+import { Provider } from 'react-redux';
+import { createStore } from '../../redux/createStore';
+
+const store = createStore();
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/Form.test.js:10]: We would not be needing these.

**Comment by ahmadabdolsaheb** [comment]
Quick note (we don't have to fix it on this pr IIMHO) : unvalidated (localhost) submissions to the legacy cert section of the settings page would go through, and the hints would show up for all previous submissions.

File: client/src/components/formHelpers/FormFields.js [hunk 7]
```diff
@@ -33,46 +40,72 @@ function FormFields(props) {
...
-                    ) : null}
-                  </FormGroup>
-                </Col>
-              );
-            }}
-          </Field>
-        ))}
-    </div>
+    <SolutionFormContext.Consumer>
+      {({ displayErrors }) => {
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/FormFields.js:53]: The displayErrors state does not seem to be propagating.

Since we are checking and displaying errors from the validators in `nullOrWarning`, I was wondering if we would need to pass this state down here at all.

So `solutionForm` would be in charge of opening modal using the validation check in `Form`, and
`FormFields` would be in charge of showing the error since it validates on each input change.

It would be nice to find the way to run the validations once, but that could wait for another optimization pr.

File: client/src/components/formHelpers/FormValidators.js [hunk 8]
```diff
@@ -0,0 +1,29 @@
+// Matches editor links for: Repl.it, Glitch, CodeSandbox
+const editorRegex = /repl\.it\/@|edit\/#!|codesandbox\.io\/s\//;
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/FormValidators.js:2]: We could add the domain for the glitch check just to avoid confusion. ( completely your call)

Comment (ShaunSHamilton) [reply client/src/components/formHelpers/FormValidators.js:2]: The `edit/#!` is Glitch

File: client/src/components/formHelpers/FormValidators.js [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+const localhostRegex = /localhost/;
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/FormValidators.js:3]: I think this would catch /localhost/ if it is present anywhere in the url. It would be better if we could make it more specific.

File: client/src/components/formHelpers/FormValidators.js [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+
+export const editorValidator = value =>
+  editorRegex.test(value) ? 'Remember to submit the Live App URL.' : null;
+
+export const localhostValidator = value =>
+  localhostRegex.test(value)
+    ? 'Remember to submit a publicly visible app URL.'
+    : null;
+
+export const validURLValidator = value => {
```
Comment (ahmadabdolsaheb) [inline client/src/components/formHelpers/FormValidators.js:22]: Are you thinking of adding this or is it for future proofing the validators?

**Comment by ahmadabdolsaheb** [comment]
I have tested submitting front/backend projects with this pr and it works as expected. Other than the nit-picks mentioned above it is LGMT.

**Comment by ShaunSHamilton** [comment]
> Quick note (we don't have to fix it on this pr IIMHO) : unvalidated (localhost) submissions to the legacy cert section of the settings page would go through, and the hints would show up for all previous submissions.

For the most part, this looks like wanted behaviour. I think we do have an issue up which intends to add checks to submissions from the settings page. So, this would be resolved in that PR (perhaps, I can take a look).

File: client/src/components/formHelpers/FormFields.js (hunk 7 above)
Comment (ShaunSHamilton) [reply client/src/components/formHelpers/FormFields.js:53]: I am not sure I understand...
- The state appears to be behaving as expected.
- Do you mean for this logic: https://github.com/freeCodeCamp/freeCodeCamp/pull/40225/files#diff-0f43bd67cd3701ceb7d5e86576b27ac0988e55d3d34e43cfbef44d520911e102R28-R35
to be handled within `FormFields.js`?

File: client/src/components/formHelpers/FormValidators.js (hunk 10 above)
Comment (ShaunSHamilton) [reply client/src/components/formHelpers/FormValidators.js:22]: I added this, but then wondered:
a) I am not convinced with my RegEx
b) Is it at all useful

So, I left it to be up for discussion. Shall I remove them?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Thanks a tonne, for the suggestion about removing the `displayErrors` state. This is simpler.

File: client/src/components/formHelpers/FormValidators.js (hunk 10 above)
Comment (ahmadabdolsaheb) [reply client/src/components/formHelpers/FormValidators.js:22]: I think we should remove them if we are not using them since the current form checks the validity of the urls to an extent. 

I will be using a library to validate urls in an upcoming pr, maybe we could incorporate instead of custom regex.

**Review by ahmaxed — DISMISSED** [review]

**Review by raisedadead — COMMENTED** [review]
Hi @ahmadabdolsaheb can you sanity check this again. I just rebased/squashed a lot of commits here.

If it looks good please merge.

**Review by ahmaxed — DISMISSED** [review]
