### PR TITLE
fix: make donate modal scrollable

### LINKED ISSUE #36756: Unable to close donate modal
image

The modal is humongous and also does not scroll. I am unable to scroll to the rest of it.

### PR DESCRIPTION
**Pull request by moT01**
I'm not quite sure what you all had in mind for this @raisedadead - but this seems like a quick and easy fix to the scrolling issue - which allows you to get to the `close` button.

Also, the `close` button text was underlined - so I got rid of that.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36756

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks, can you also reduce the font size on the buttons a notch.

**Review by raisedadead — CHANGES_REQUESTED** [review]
~See~ Ignore previous comments

File: client/src/components/Donation/components/DonateModal.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ class DonateModal extends Component {
     };
     return (
       <div className='modal-close-btn-container'>
-        <Button bsStyle='link' onClick={handleClick}>
+        <Button className='btn btn-lg btn-primary' onClick={handleClick}>
```
Comment (raisedadead) [inline client/src/components/Donation/components/DonateModal.js]: You can revert this. This is intentionally a link.

**Review by raisedadead — CHANGES_REQUESTED** [review]

**Comment by raisedadead** [comment]
@ahmadabdolsaheb will you be adding the changes like we discussed?

**Comment by ahmadabdolsaheb** [comment]
screenshot

image

**Review by raisedadead — APPROVED** [review]
