### PR TITLE
fix(api): return usernameDisplay

### LINKED ISSUE #61565: edit profile not available
I have seen a few reports of people not seeing the pencil icon to edit their profile

This one:

Image

Instead they do not have an edit option

here an user report: https://forum.freecodecamp.org/t/after-completing-my-course-i-want-to-get-my-certificate-but-it-said-you-have-to-give-your-name-but-i-cant-see-my-name-field-in-the-profile-or-setting-what/756792

It should be investigated.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #61565 

NOTE: This now introduces a small break where the `username` is shown in the client everywhere the `usernameDisplay` used to be shown.

That is to say, instead of showing `developmentUser` on the profile page, it will show `developmentuser`.

### CODE REVIEW

File: api/src/routes/protected/user.ts [hunk 1]
```diff
@@ -682,7 +682,8 @@ export const userGetRoutes: FastifyPluginCallbackTypebox = (
               name: name ?? '',
               theme: theme ?? 'default',
               twitter: normalizeTwitter(twitter),
-              username: usernameDisplay || username,
+              username,
+              usernameDisplay,
```
Comment (ojeytonwilliams) [inline api/src/routes/protected/user.ts]:
```suggestion
              usernameDisplay: usernameDisplay || username,
```
This simplifies the types and is, I think, the default we want.

File: api/src/schemas/users/get-public-profile.ts [hunk 2]
```diff
@@ -102,6 +102,9 @@ export const getPublicProfile = {
               joinDate: Type.String(),
               savedChallenges: Type.Array(savedChallenge),
               username: Type.String(),
+              usernameDisplay: Type.Optional(
+                Type.Union([Type.String(), Type.Null()])
+              ),
```
Comment (ojeytonwilliams) [inline api/src/schemas/users/get-public-profile.ts]:
```suggestion
              usernameDisplay: Type.String(),
```

File: api/src/schemas/user/get-session-user.ts [hunk 3]
```diff
@@ -117,6 +117,7 @@ export const getSessionUser = {
           joinDate: Type.String(),
           savedChallenges: Type.Optional(Type.Array(savedChallenge)),
           username: Type.String(),
+          usernameDisplay: Type.Union([Type.String(), Type.Null()]),
```
Comment (ojeytonwilliams) [inline api/src/schemas/user/get-session-user.ts]:
```suggestion
          usernameDisplay: Type.String(),
```

File: api/src/routes/public/user.ts [hunk 4]
```diff
@@ -166,7 +165,8 @@ export const userPublicGetRoutes: FastifyPluginCallbackTypebox = (
               [user.username]: {
                 isLocked: true,
                 profileUI: normalizedProfileUI,
-                username: user.username
+                username: user.username,
+                usernameDisplay: user.usernameDisplay
```
Comment (ojeytonwilliams) [inline api/src/routes/public/user.ts]:
```suggestion
                usernameDisplay: user.usernameDisplay || user.username,
```

File: api/src/schemas/user/get-session-user.ts (hunk 3 above)
Comment (ojeytonwilliams) [reply api/src/schemas/user/get-session-user.ts]: `returneduser` needs the same treatment :(

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: api/src/routes/public/user.ts (hunk 4 above)
Comment (ShaunSHamilton) [reply api/src/routes/public/user.ts]: Seems fine. I am just a little concerned this is going to bite us in the future.

Comment (ojeytonwilliams) [reply api/src/routes/public/user.ts]: It might. However, I'm optimistic that it won't cause too much confusion give that it's barely used.

**Review by ojeytonwilliams — APPROVED** [review]
I thought we'd added it too 🤷 

LGTM 👍

**Review by ojeytonwilliams — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]
