### PR TITLE
fix(client): replace Roboto Mono with Hack-ZeroSlash

### LINKED ISSUE #46530: Consider changing monospaced font for code examples
### Describe the Issue

I've had two different forum posts today in which the user thought the lowercase L was the number 1 in the HTML code examples, and I have seen this before today as well. I can definitely understand the confusion. In the example below, the user mistook the "ul" element for "u1".

image

If I remove Roboto Mono from the font family and just rely on the default monospace font on my computer it looks much more like a lowercase L.

image

### Affected Page

Several

### Your code

N/A

### Expected behavior

Find a monospaced font with a better distinction between lowercase L and the number 1.

### Screenshots

_No response_

### System

- Device: desktop
- OS: Fedora
- Browser: Firefox
- Version: 102

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dannygr664**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46530

Replace `Roboto Mono` font with `Hack-ZeroSlash` to help distinguish between `1`, `l`, `I`, `|`, `0`, and `O`.

### CODE REVIEW

**Comment by bbsmooth** [comment]
Quick question, do we want to think about changing the font used in the monaco editor to Hacked-ZeroSlash as well? It's fairly easy to do, you can set the `fontFamily` option for the editor in editor.tsx.

**Comment by ieahleen** [comment]
> Quick question, do we want to think about changing the font used in the monaco editor to Hacked-ZeroSlash as well? It's fairly easy to do, you can set the `fontFamily` option for the editor in editor.tsx.

@bbsmooth I would say yes, it's more consistent

File: client/src/components/layouts/default.tsx [hunk 1]
```diff
@@ -8,9 +8,9 @@ import { createSelector } from 'reselect';
 import latoBoldURL from '../../../static/fonts/lato/Lato-Bold.woff';
 import latoLightURL from '../../../static/fonts/lato/Lato-Light.woff';
 import latoRegularURL from '../../../static/fonts/lato/Lato-Regular.woff';
-import robotoBoldURL from '../../../static/fonts/roboto-mono/RobotoMono-Bold.woff';
-import robotoItalicURL from '../../../static/fonts/roboto-mono/RobotoMono-Italic.woff';
-import robotoRegularURL from '../../../static/fonts/roboto-mono/RobotoMono-Regular.woff';
+import hackZeroSlashBoldURL from '../../../static/fonts/hack-zeroslash/Hack-ZeroSlash-Bold.woff';
+import hackZeroSlashItalicURL from '../../../static/fonts/hack-zeroslash/Hack-ZeroSlash-Italic.woff';
+import hackZeroSlashRegularURL from '../../../static/fonts/hack-zeroslash/Hack-ZeroSlash-Regular.woff';
```
Comment (bbsmooth) [inline client/src/components/layouts/default.tsx:13]: Do we need to include the bold-italic font file here as well?

File: client/src/components/layouts/default.tsx [hunk 2]
```diff
@@ -177,21 +177,21 @@ class DefaultLayout extends Component<DefaultLayoutProps> {
...
             type='font/woff'
           />
           <link
             as='font'
             crossOrigin='anonymous'
-            href={robotoItalicURL}
+            href={hackZeroSlashItalicURL}
             rel='preload'
             type='font/woff'
           />
```
Comment (bbsmooth) [inline client/src/components/layouts/default.tsx:197]: Do we need to include the bold-italic font here as well?

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (bbsmooth) [inline client/src/components/layouts/default.tsx:13]: Also, why are only the woff files included here and not the woff2 files?

File: client/src/components/layouts/default.tsx (hunk 2 above)
Comment (bbsmooth) [inline client/src/components/layouts/default.tsx:197]: Why only the woff files and not the woff2 files as well?

**Comment by bbsmooth** [comment]
> > Quick question, do we want to think about changing the font used in the monaco editor to Hacked-ZeroSlash as well? It's fairly easy to do, you can set the `fontFamily` option for the editor in editor.tsx.
> 
> @bbsmooth I would say yes, it's more consistent

That's one vote for changing the font in the monaco editor. @ahmadabdolsaheb What say you?

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (dannygr664) [reply client/src/components/layouts/default.tsx:14]: I am trying to include the woff2 files but am getting the error `Cannot find module '../../../static/fonts/hack-zeroslash/Hack-ZeroSlash-Regular.woff2' or its corresponding type declarations.` Would it be okay to leave them out for now, as the other fonts only have `woff`?

**Comment by naomi-lgbt** [comment]
Looks like you've got some stray commits on this branch.

**Review by moT01 — DISMISSED** [review]
LGTM @dannygr664 🎉 and everyone that helped 🎉 I like the font choice. Here's a side-by-side:

Screen Shot 2022-10-03 at 9 54 19 PM

The only thing I see - do we want to delete the roboto font files from the repo here?

**Comment by ieahleen** [comment]
If it's not used anymore anywhere I am all for removing unneeded files

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (bbsmooth) [reply client/src/components/layouts/default.tsx:14]: Correct me if I'm wrong, but the reason we are importing these font files here is so that we can preload them. Since woff2 is now preferred over woff and is supported in all browsers except IE then I think if we are going to preload these fonts it should be the woff2 files, not the woff files. By the way, it appears the main difference between woff and woff2 is that the later has a better compression algorithm, so we'll save even more bandwidth by preloading woff2 instead.

File: client/src/components/layouts/default.tsx (hunk 2 above)
Comment (bbsmooth) [reply client/src/components/layouts/default.tsx:199]: If we preload the woff2 files then the type on these needs to be changed to `font/woff2`.

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (dannygr664) [reply client/src/components/layouts/default.tsx:14]: I hear you that woff2 is more efficient. I am just having trouble including the file path. Do you know why the error above might be happening? Sorry, I'm a bit new to front-end programming.

Comment (bbsmooth) [reply client/src/components/layouts/default.tsx:14]: Hmm... when I add a `2` to the end of these file paths (and to the `type` attributes on the preload `link` tags below) I don't get any errors and I can see all four woff2 files loading in the network tab of dev tools. I'm not sure why that would work for me but error for you? Perhaps @ieahleen or @ahmadabdolsaheb might have some insight?

Comment (ahmadabdolsaheb) [reply client/src/components/layouts/default.tsx:14]: Not sure why that might be happening. We could move forward with the current spec if woff2 is giving you a hard time and we could create a separate issue for woff --> woff2 for all fonts.

Additionally, not sure if we are using hackZeroSlashBoldItalicURL or hackZeroSlashItalicURL. Feel free to drop them if they are not being used.

**Review by majestic-owl448 — DISMISSED** [review]
I am happy about this, I think it's looking nicely. Thank you!

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (dannygr664) [reply client/src/components/layouts/default.tsx:13]: Hmm maybe it has to do with my local dev environment. Would it be okay to create the separate pull request? I've added a commit to remove the BoldItalic font, as I don't think it is used.

File: client/src/templates/Challenges/classic/editor.tsx [hunk 3]
```diff
@@ -279,6 +279,7 @@ const Editor = (props: EditorProps): JSX.Element => {
 
   const options: editor.IStandaloneEditorConstructionOptions = {
     fontSize: 18,
+    fontFamily: 'Hack-ZeroSlash',
```
Comment (bbsmooth) [inline client/src/templates/Challenges/classic/editor.tsx:282]:
```suggestion
    fontFamily: 'Hack-ZeroSlash', monospace,
```

File: client/src/components/layouts/default.tsx (hunk 1 above)
Comment (bbsmooth) [reply client/src/components/layouts/default.tsx:13]: I'm fine with leaving this PR preloading the woff files and opening a separate PR to switch to woff2.

File: client/src/components/layouts/default.tsx (hunk 2 above)
Comment (bbsmooth) [reply client/src/components/layouts/default.tsx:198]: We'll switch this to woff2 in a separate PR.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **AWESOME!** :sparkles: :sparkles: 

LGTM.

Thanks for this pull request and for contributing to the codebase for the first time. We will be looking forward to more contributions in the future.

Happy contributing.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:
