### PR TITLE
fix: allow at least 100 loops before breaking out

### LINKED ISSUE #51656: React challenges throwing "Potential infinite loop detected" error
### Describe the Issue

I only checked a few but it seems like anything with a state update (inputs, buttons, etc.) throws this. You can pass the challenges with the correct code but any interaction with the page that triggers a state update seems to throw this error.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/write-a-simple-counter  https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-controlled-input  https://www.freecodecamp.org/learn/front-end-development-libraries/react/use-advanced-javascript-in-react-render-method

### Your code

```



```

### Expected behavior

Valid passing code shouldn't crash the challenge page when interacting with the rendered page.

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Just saw this as well. Forum: https://forum.freecodecamp.org/t/fcc-solutions-are-crashing-the-render-frame/640546

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This allows React renders more leeway, since they often render so slowly
that their first render can exceed the loop-protect timeout

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/51656

### CODE REVIEW

**Review by huyenltnguyen — APPROVED** [review]

File: client/src/templates/Challenges/rechallenge/transformers.js [hunk 1]
```diff
@@ -54,11 +55,11 @@ async function loadBabel() {
   /* eslint-enable no-inline-comments */
   Babel.registerPlugin(
     'loopProtection',
-    protect(protectTimeout, loopProtectCB)
+    protect(protectTimeout, loopProtectCB, loopsPerTimeoutCheck)
   );
   Babel.registerPlugin(
     'testLoopProtection',
-    protect(testProtectTimeout, testLoopProtectCB, loopsPerTimeoutCheck)
+    protect(testProtectTimeout, testLoopProtectCB, testLoopsPerTimeoutCheck)
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/rechallenge/transformers.js:62]: I am sure I have asked this before, but one more time for my sanity: What is the difference between the `loopProtection` and `testLoopProtection`?

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/rechallenge/transformers.js:62]: Just the configuration. The idea is that `testLoopProtection` is less aggressive (it times out later and checks the timeout less often) as a compromise between protection and allowing slow tests to complete. 

`loopProtection` is more aggressive because people often write infinite loops on the way to writing finite ones, so we don't want people's browsers crashing just because they haven't yet written the code that modifies the conditional, say.

**Comment by lasjorg** [comment]
I assume this is expected, but I'm still seeing the loop protection trigger after enough render updates.

Try doing the "create a controlled input" and write a bunch in the input element.

Or click the increment/decrement button about 20 times in the "write a simple counter".

---

It feels pretty wrong to be throwing loop protection for valid React code that should be working just fine.

I only tested it with Gitpod but I don't think that should matter.

**Comment by ojeytonwilliams** [comment]
@lasjorg yeah, that's always going to be an issue given loop-protect's current implementation. To be honest, I can't think of a way to allow an arbitrary number of renders while also preventing infinite renders.

What we can do is play with the number of loops before the first check, so I'll increase that to 100 and we can see how that goes.

File: client/src/templates/Challenges/rechallenge/transformers.js [hunk 2]
```diff
@@ -25,7 +25,8 @@ const { filename: sassCompile } = sassData;
 
 const protectTimeout = 100;
 const testProtectTimeout = 1500;
-const loopsPerTimeoutCheck = 2000;
+const loopsPerTimeoutCheck = 20;
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/rechallenge/transformers.js:28]:
```suggestion
const loopsPerTimeoutCheck = 100;
```

**Review by ShaunSHamilton — APPROVED** [review]
Can confirm, can now click the "Increment" button 98 times before seeing:
```console
Potential infinite loop detected on line 1. Tests may fail if this is not changed.
{ [Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Counter for the full message or use the non-minified dev environment for full errors and additional helpful warnings. ] name: 'Invariant Violation', framesToPop: 1 }
Error, open your browser console to learn more.
```

**Review by naomi-lgbt — APPROVED** [review]
> so I'll increase that to 100 and we can see how that goes.

At this rate the code's gonna get dizzy.
