### PR TITLE
Fix(lang): update challenge lang on user lang change

### LINKED ISSUE #10136: [beta] Changing language, does not render the challenge in same unless refreshed
If I change my language on the settings page, the same is updated, and the routes are changed as well, which I can see in the URL.

But the views are not updated until I refresh the page. The challenges still render in the previous language. The map also displays the challenge titles in the previous language.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #10136

### CODE REVIEW

File: common/app/routes/challenges/redux/fetch-challenges-saga.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ export default function fetchChallengesSaga(action$, getState, { services }) {
     ))
     .flatMap(({ type, payload: { dashedName, block } = {} }) => {
       const state = getState();
-      const lang = state.app.languageTag;
+      const lang = state.app.lang;
```
Comment (BerkeleyTrue) [inline common/app/routes/challenges/redux/fetch-challenges-saga.js]: This key is updated by the url change, not directly by the user. We always want the URL lang to take precedence over the user selected lang. 

On the settings page, when the user selects a lang, a redirect to the new selected lang happens which will indirectly to updating this var. After the redirect, then we refetch. This incorrect key is why it was initially broken.
