### PR TITLE
Prevent tail appending to trailing comments

### LINKED ISSUE #7799: Correct code generates an error without a blank line following it.
Challenge [Accessing Nested Arrays in JSON](https://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json#?solution=%2F%2F%20Setup%0Avar%20myPlants%20%3D%20%5B%0A%20%20%7B%20%0A%20%20%20%20type%3A%20%22flowers%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22rose%22%2C%0A%20%20%20%20%20%20%22tulip%22%2C%0A%20%20%20%20%20%20%22dandelion%22%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20type%3A%20%22trees%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22fir%22%2C%0A%20%20%20%20%20%20%22pine%22%2C%0A%20%20%20%20%20%20%22birch%22%0A%20%20%20%20%5D%0A%20%20%7D%20%20%0A%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20secondTree%20%3D%20myPlants%5B1%5D.list%5B1%5D%3B%20%2F%2F%20Change%20this%20line) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I noticed in a couple cases working on the JSON examples that if there's not a blank line after my code, I get "SyntaxError: Illegal return statement".

After I add the carriage return after the last line, it submits fine.

My code:
```javascript
// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants[1].list[1]; // Change this line
```

### PR DESCRIPTION
**Pull request by bteng22**
If the code does not have a newline at the end and ends with a comment, then the first line of the tail will be cut off and will occasionally not evaluate correctly when calling eval(code).

For example:
var secondTree = myPlants[1].list[2]; // Change this line(function(x) {
  if (typeof x != 'undefined') {
    return "secondTree = " + x;
  }
  return "secondTree is undefined";
})(secondTree);

The function declaration after '// Change this line' will be cut off and the return statements below will throw an error. A newline before the tail prevents this from occurring. 

closes #7799

### CODE REVIEW

File: client/commonFramework/execute-challenge-stream.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ window.common = (function(global) {
     const originalCode = code;
     const head = common.arrayToNewLineString(common.head);
     const tail = common.arrayToNewLineString(common.tail);
-    const combinedCode = head + code + tail;
+    const combinedCode = head + code + '\n' + tail;
```
Comment (raisedadead) [inline client/commonFramework/execute-challenge-stream.js]: I am yet to test this, but I am wondering if

`const combinedCode = head + '\n' + code + '\n' + tail;`

would be a full proof to address any code that may have comment on the top.
Not that this is necessary but wouldn't this be good?

Comment (bteng22) [inline client/commonFramework/execute-challenge-stream.js]: I was thinking the same before I pushed it up. We can definitely add it as a precaution!

I hesitated to because most of the "head" code I looked through does not end with comments (and if so, most of them put a newline after their code). But if there were ever a scenario that did, it would cut off the first line of of the "code" from the editor.

I'll go ahead and throw it in as well as a precaution.

**Comment by bteng22** [comment]
@raisedadead adjusted the PR to add a newline to the initialValue of the method common.arrayToNewLineString instead of to the combinedCode in executeChallenge$. Let me know what you think! Thanks

**Comment by raisedadead** [comment]
@bteng22 You got to rebase this against staging and squash your commits. Let us know if you need help doing that in the [HelpContributors Chat Room](https://gitter.im/FreeCodeCamp/HelpContributors)

Thanks.

**Comment by raisedadead** [comment]
@bteng22 [Here is a link](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#git-rebase-at-fcc) for your reference

**Comment by bteng22** [comment]
@raisedadead Hey Mrugresh sorry for the super late delay—I got swamped at work. I'm pretty sure I squashed the commits correctly but let me know if it's not otherwise. Thanks again for all your help!

**Comment by raisedadead** [comment]
@bteng22 Yikes! Now we have 137 commits on this PR. Please visit the [Git Chat room](https://gitter.im/FreeCodeCamp/Git) and ping us. We will guide you thru this.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

@bteng22 : Thanks Brandon, this works like a charm!
