### PR TITLE
fix(map): Expand map when challenge opened

### LINKED ISSUE #16248: Map should be expand in right places to show current challenge
Currently this is how the map looks when I navigate to a specific challenge:

learn_to_code___freecodecamp

Instead, when a challenge loads, the map should automatically expand the necessary challenge super-block and sub-block to show the current challenge, like this:

learn_to_code___freecodecamp

### LINKED ISSUE #16774: Upon completing a challenge block, subsequent challenge block should be expanded in map
When I complete the final challenge in a challenge block, and am redirected to the first challenge in the subsequent challenge block, the map should be updated to collapse the previous challenge block and expand the current one.

### PR DESCRIPTION
**Pull request by vbelolapotkov**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16248
Closes #16774

#### Description

changed fetchChallenges epic to trigger additional action
challengeUpdated on complete; changed challengeUpdated meta creator to
store map specific data; added meta reducer for map and util method
to open path in the map by node name

### CODE REVIEW

File: common/app/Map/redux/utils.js [hunk 1]
```diff
@@ -157,3 +157,75 @@ export function collapseAllPanels(tree) {
...
+//   name: String,
+//   update(MapUi|Node) => MapUi|Node
+// ) => MapUi
+export function updatePath(tree, name, pathUpdater) {
+  const path = [];
+  let pathFound = false;
+
+  const isInPath = node => !!path.find(name => name === node.name);
+
+  const traverseMap = (tree, update) => {
```
Comment (BerkeleyTrue) [inline common/app/Map/redux/utils.js]: There is already a traverse map function. What is the requirement for this new function that the other does not meet?

File: common/app/Map/redux/index.js [hunk 2]
```diff
@@ -76,38 +77,51 @@ export function makePanelOpenSelector(name) {
...
+          ...state,
+          mapUi: utils.createMapUi(entities, result)
+        };
+      }
+    }),
+    initialState
+  ),
+  function metaReducer( state = initialState, action) {
+    if (action.meta && action.meta.map) {
+      const nodeName = action.meta.map.nodeName;
```
Comment (BerkeleyTrue) [inline common/app/Map/redux/index.js]: I'd namespace further so that we can add more functions in the future. see the `files` feature for an example of how this is done.

File: common/app/redux/fetch-challenges-epic.js [hunk 3]
```diff
@@ -70,12 +75,10 @@ export function fetchChallengesEpic(
...
         }))
-        .map(({ entities, result } = {}) => {
-          return fetchChallengesCompleted(
-            entities,
-            result
-          );
-        })
+        .flatMap(({ entities, result } = {}) => Observable.of(
+          fetchChallengesCompleted(entities, result),
+          challengeUpdated(challengeSelector(getState()))
```
Comment (BerkeleyTrue) [inline common/app/redux/fetch-challenges-epic.js]: Why is this necessary?

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: @BerkeleyTrue current traverse map function doesn't allow you track parent nodes, i.e. path to the node, so we have to store nodes in path before going deeper.

File: common/app/redux/fetch-challenges-epic.js (hunk 3 above)
Comment (vbelolapotkov) [reply common/app/redux/fetch-challenges-epic.js]: @BerkeleyTrue as you suggested before I've used challengeUpdated action right after fetchComplete to trigger map expansion.
We can avoid it if map metaReducer runs after action handler and get state returned by action handler. I.e. map reducer will create map only in 'fetch challenges completed' action handler, after that meta reducer will open path.

**Comment by LorenpNYC** [comment]
Unsubscribe

File: common/app/redux/fetch-challenges-epic.js (hunk 3 above)
Comment (vbelolapotkov) [reply common/app/redux/fetch-challenges-epic.js]: @BerkeleyTrue I've checked this part again. Here are the options:
1) Use challengeUpdated event right after fetchChallengesCompleted like it is done now to update map ui.
2) Add another parameter (currentChallenge) to fetchChallengesCompleted action creator to expand meta for fetchChallengesCompleted event.

IMO option 2 looks better, however option 1 has been chosen earlier.
What do you think?

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: @BerkeleyTrue changed this and moved meta creator to map as well.

Comment (BerkeleyTrue) [reply common/app/Map/redux/utils.js]: @vbelolapotkov can you explain what the path is and why you need to track it? The traversal is a depth first search algorithm. This should be sufficient to find the current challenge and open the map to expose that challenge.

Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: @BerkeleyTrue to open map I have to set isOpen = true on nodes with children in path (superBlock > block > challenge). But I have only challenge name as a starting point and do not have any link from child to parent (challenge > block > superBlock). So if I find challenge node by name, I have no way to update it's parents (block, superBlock). That is why I'm saving parent in path any time I go deeper with traversal.

File: common/app/redux/fetch-challenges-epic.js (hunk 3 above)
Comment (BerkeleyTrue) [reply common/app/redux/fetch-challenges-epic.js]: Yes, option two is what I imaged. 

Berkeley's second rule of Redux: "Never use two actions where one will do."

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (BerkeleyTrue) [reply common/app/Map/redux/utils.js]: Why do you need the full path?

Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: With full path I can check if node is a parent of challenge node and update those nodes when going out of the recursion. 
Do you have an idea on how to do this with traverse tree?

File: common/app/redux/fetch-challenges-epic.js (hunk 3 above)
Comment (vbelolapotkov) [reply common/app/redux/fetch-challenges-epic.js]: Ok, got it. Will do updates.

Comment (vbelolapotkov) [reply common/app/redux/fetch-challenges-epic.js]: @BerkeleyTrue done

File: common/app/Map/Map.jsx [hunk 4]
```diff
@@ -6,18 +6,76 @@ import { Col, Row } from 'react-bootstrap';
...
+  }
+
+  updateMapScroll() {
+    const { initialNode } = this.props;
+    const rowNode = this._row;
+    const challengeNode = rowNode.querySelector(
+      `[data-challenge="${initialNode}"]`
+    );
+
+    if ( !challengeNode ) {
```
Comment (BerkeleyTrue) [inline common/app/Map/Map.jsx]: Why would challengeNode be undefined?

File: common/app/Map/Map.jsx [hunk 5]
```diff
@@ -32,15 +90,27 @@ export class ShowMap extends PureComponent {
...
     const { superBlocks } = this.props;
+    const style = {
+      position: 'absolute',
+      top: 0,
+      bottom: 0,
+      left: 0,
+      right: 0,
+      overflowY: 'auto',
+      overflowX: 'hidden'
+    };
```
Comment (BerkeleyTrue) [inline common/app/Map/Map.jsx]: This style block doesn't change. Why does this need to be a prop instead of css?

File: common/app/Map/Map.jsx (hunk 4 above)
Comment (vbelolapotkov) [reply common/app/Map/Map.jsx]: @BerkeleyTrue in case it's not in the DOM yet.

File: common/app/Map/Map.jsx (hunk 5 above)
Comment (vbelolapotkov) [reply common/app/Map/Map.jsx]: Agreed, will move into .less

File: common/app/Map/Map.jsx (hunk 4 above)
Comment (BerkeleyTrue) [reply common/app/Map/Map.jsx]: I see. In that case I suggest we remove the retry logic and the set timeout logic and trigger this method on CDM. This should prevent trying to update dom nodes on the server/preCDM

Comment (vbelolapotkov) [reply common/app/Map/Map.jsx]: CDM is called too long before challenges are fetched. That is why CDU is used, and update is triggered only when initialNode prop is changed (on challenge.fetch.complete).
So timeout from CDM is hard to predict. However timeout from CDU is more predictable, but is less reliable than retry IMO.

Comment (BerkeleyTrue) [reply common/app/Map/Map.jsx]: > CDM is called too long before challenges are fetched.

In my scenario we would keep both triggers. The SCU when the dom is live and the CDM to be the initial trigger. That way if SCU happens when the element isn't mounted the CDM catches it. This avoids the need for the retry logic.

> I didn't get that part as I'm not aware of the ssr part.

The way it's currently set up, you'll be setting up a timeout for every request on the server. Since the dom will never mount server side, every request will create 5 setTimeouts, potentially creating side effects after a request has been fulfilled. You usually want to avoid logic like this, and with the hooks that react provides it is usually quite trivially to do so.

Comment (vbelolapotkov) [reply common/app/Map/Map.jsx]: To be honest I'm completely confused right now. I've set loggers to CDM and CDU methods of Map. None of them is called on the server during the ssr, only render is called once.
Am I doing something wrong? When is CDM called on server?

Anyway, I'm ok to shift from retry logic to single timeout. In my first attempts 300ms on CDU was enough to properly setup scroll on Map. What do you think?

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (BerkeleyTrue) [reply common/app/Map/redux/utils.js]: I believe it may be sufficient to to check for open children in the node and open the current node if any of it's children are open.

File: common/app/Map/Map.jsx (hunk 4 above)
Comment (BerkeleyTrue) [reply common/app/Map/Map.jsx]: Your right, both of those are not called on the sever. So the server side argument is invalid.

I've pulled down your and I'm finding it hard to replicate the missing dom node logic. Here is what I'm seeing. 

* The node is updated on fetchChallengesCompleted, this only happens after the dom is  mounted.
* The cdu logic is triggered by react
* The updateMapScroll finds the node (since we are already mounted)
* The logic to updateThe map scroll does its magic.

What I'm failing to see the map scroll down to the challenge element.


I believe it is this logic here: 

```js
if (itemBottom + offset < containerHeight) {
      // no need to scroll
      return;
    }
```
rosetta_code_problems__comma_quibbling___freecodecamp

That logic always catches and ends the function call without any further logic which I don't think was the intention. It seems to be due to the map panels not updating until after this logic is triggered. Initially all the challenge nodes are hidden but within the container window, the logic never continues past this point

Comment (vbelolapotkov) [reply common/app/Map/Map.jsx]: > What I'm failing to see the map scroll down to the challenge element.

There was an error in css (forget to rename some props during copy/paste from component).
I've fixed it with new commit. So everything have to be fine now.

As for the checks, that one will prevent scrollUpdate during the first run:
`if ( containerHeight === containerScrollHeight ) {`

It happens IMO because browser needs some time to update map scrollHeigh prop when new nodes (challenges) rendered.

I used timeouted call of updateMapScroll first (without retries) and it works fine with delay of 300ms. If delay is < 300 sometimes scroll is not updated. That is why I've implemented retry logic instead of fixed tiemout.

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: This involves double check of each node. I'd prefer to avoid it.

Comment (BerkeleyTrue) [reply common/app/Map/redux/utils.js]: > This involves double check of each node.

How do you figure this?

Comment (vbelolapotkov) [reply common/app/Map/redux/utils.js]: `update` is called on each child before it's called on a parent node. When it is called on a parent node you have to look through the children again to find out if any of them is opened. 
So you have to iterate twice: first iteration during a traverse, second iteration in update.

**Comment by Bouncey** [comment]
@vbelolapotkov a lot has changed since your last update, especially in the `fetchChallenges` logic. Would you mind doing a rebase please?

**Comment by vbelolapotkov** [comment]
@Bouncey ok, will do

**Comment by vbelolapotkov** [comment]
@Bouncey made refactoring, squashed previous commits and rebased to simplify a review of the resulting changes.

File: common/app/Map/redux/utils.js (hunk 1 above)
Comment (BerkeleyTrue) [reply common/app/Map/redux/utils.js]: I see. Thanks for clarifying

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
@vbelolapotkov Merged :champagne: 

Happy Coding

**Comment by vbelolapotkov** [comment]
@BerkeleyTrue  great! Thanks!

Happy Coding ;)
