### PR TITLE
fix: unhide this string

### LINKED ISSUE #42656: i18n: one challenge title is not translatable
The challenge title of challenge Use && for a More Concise Conditional is not translatable on Crowdin

image
(the greyed out text is for not translatable strings)

An other challenge where the title is translatable
image

this is the link for crowdin file: https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/23516/en-it/132?filter=basic&value=3

markdown file for the challenge: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/03-front-end-libraries/react/use--for-a-more-concise-conditional.md

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #42656 

Okay, I'm not sure why this string is being hidden in the workflow, but since it's a one-off case I went ahead and added a step to go back and unhide it.

This will allow us to unhide other individual strings in the future, if needed.

### CODE REVIEW

File: tools/crowdin/actions/unhide-specific-string/index.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+require('dotenv').config({ path: `${__dirname}/../../.env` });
+const core = require('@actions/core');
+const { getFiles } = require('../../utils/files');
+const { getStrings, changeHiddenStatus } = require('../../utils/strings');
+// eslint-disable-next-line import/no-unresolved
```
Comment (ojeytonwilliams) [inline tools/crowdin/actions/unhide-specific-string/index.js:5]:
```suggestion
```

File: tools/crowdin/actions/unhide-specific-string/index.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+const filename = core.getInput('filename');
+const stringContent = core.getInput('string-content');
+
+const hideString = async (projectId, fileName, string) => {
+  const fileResponse = await getFiles(projectId);
+  const targetFile = fileResponse.find(el => el.path.endsWith(filename));
```
Comment (ojeytonwilliams) [inline tools/crowdin/actions/unhide-specific-string/index.js:12]:
```suggestion
  const targetFile = fileResponse.find(el => el.path.endsWith(filename));
```
How about `path.baseName(el.path) === filename`?  I doubt the above code will ever be an issue, but I think `baseName` is a bit more robust.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Just some nitpicks.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by raisedadead — APPROVED** [review]
