### PR TITLE
fix(client): update search results links to open in new tab

### LINKED ISSUE #41729: Links to news from search open in same tab
If you search news articles using the search bar on /learn and click one - it opens in the current tab. All the links to news in the footer open in a new tab. Seems like they should all open in a new tab.

### PR DESCRIPTION
**Pull request by michaelparkadze**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example only English changes, or only Chinese changes, etc.

Closes #41729

After a short discussion on the issue page, I saw the need for the change so I made the smallest change to have the results link open in a new tab. I have tested this change both on my local machine and gitpod.

### CODE REVIEW

File: client/src/components/search/searchBar/SearchSuggestion.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ const Suggestion = ({ hit, handleMouseEnter, handleMouseLeave }) => {
       href={hit.url}
       onMouseEnter={handleMouseEnter}
       onMouseLeave={handleMouseLeave}
+      target={hit.url && '_blank'}
```
Comment (nhcarrigan) [inline client/src/components/search/searchBar/SearchSuggestion.js:17]: This should just be target='_blank', I think? The url is above, in the `href` attribute.

Comment (michaelparkadze) [reply client/src/components/search/searchBar/SearchSuggestion.js:17]: it is to check if the hit.url exists, if it does not the target will be null and will not open in a different page, its like an extra step to check if we want to even have the target="_blank" on the a tag :)

Comment (huyenltnguyen) [reply client/src/components/search/searchBar/SearchSuggestion.js:17]: @michaelparkadze I don't think we need the link to conditionally open in a new tab, as we want the links to have consistent behavior. Also, I believe that each search result should already contain a valid URL. But if we do want to have a check for the truthiness of the URL, then we should consider hiding the result entirely if URL is null, rather than letting the result being unresponsive to user's click. Though this is not in the scope of the issue we are trying to address.

Comment (michaelparkadze) [reply client/src/components/search/searchBar/SearchSuggestion.js:17]: So how can we continue with this? I can check if the behavior of the search results are constant and if so just remove the condition or make the necessary changes for them to be consistent. So just let me know how to continue as I am looking to contribute ;)

Comment (huyenltnguyen) [reply client/src/components/search/searchBar/SearchSuggestion.js:17]: I think the validation on the URL or search results can be left out to keep the PR in scope. This means setting `target` to `_blank` should be enough 🙂

Comment (michaelparkadze) [reply client/src/components/search/searchBar/SearchSuggestion.js]: @huyenltnguyen I made the necessary changes ;)

**Review by raisedadead — COMMENTED** [review]
This looks good. We did get this CodeQL warning: https://github.com/freeCodeCamp/freeCodeCamp/pull/41734/checks?check_run_id=2268735197,

Modern browsers are headed towards [doing this by default](https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default), however we should still go ahead and add the same because it does not hurt.

**Comment by nhcarrigan** [comment]
Noopener/noreferrer is a concern for fully external links, right?

Our search results should point to our own news site so it is less of a concern, I think?

**Comment by raisedadead** [comment]
> Noopener/noreferrer is a concern for fully external links, right?

Yes, you are correct. However, it's a best practice to not include them because we do not need the same on news side either.

**Comment by michaelparkadze** [comment]
So how do we proceed? would you like me to add 'rel="noopener noreferrer"' or not?

**Comment by huyenltnguyen** [comment]
Hey @michaelparkadze, please help us to add `rel="noopener noreferrer"` to the link. That should be all we need to get this PR approved.

**Review by raisedadead — APPROVED** [review]

**Review by huyenltnguyen — APPROVED** [review]
LGTM!

@michaelparkadze Thank you for your contribution and congrats on the first pull request to the repo 🎉
