### PR TITLE
fix(cypress): Re-introduce Firefox in Cypress CI

### LINKED ISSUE #39679: Cypress with Firefox keeps crashing
image

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39679 

Let's re-introduce Firefox before parallelizing Cypress CI. I've increased the timeout by 5 more seconds and I think that should do it. If everything goes ok, we can start parallelizing Cypress CI.

### CODE REVIEW

File: cypress/integration/learn/challenges/output.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ describe('Classic challenge', function() {
   it('shows test output when the tests are run', () => {
     cy.visit(locations.index);
     // first wait for the editor to load
-    cy.get(selectors.editor, { timeout: 10000 });
+    cy.get(selectors.editor, { timeout: 15000 });
```
Comment (ojeytonwilliams) [inline cypress/integration/learn/challenges/output.js:43]: Is Firefox particularly slow at this?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

File: cypress/integration/learn/challenges/output.js (hunk 1 above)
Comment (Twaha-Rahman) [reply cypress/integration/learn/challenges/output.js:43]: I'm guessing so. Since this is the only test that was randomly failing in Firefox, I'd say it's a good guess.

Comment (ojeytonwilliams) [reply cypress/integration/learn/challenges/output.js:43]: Right, thanks for confirming.  I'll keep that in mind, but we don't need to worry about it right now.
