### PR TITLE
fix: initialize MathJax correctly 

### LINKED ISSUE #57289: Mathjax should not rely on element classes to prevent descriptions from not being formatted
See for example problem 187
https://www.freecodecamp.org/learn/project-euler/project-euler-problems-101-to-200/problem-187-semiprimes

Image

### PR DESCRIPTION
**Pull request by Sembauke**
- **fix: do not rely on superblock classes for MathJax**
- **fix: initilize mathjax from challenge description**
- **fix: do not export superblock array**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Apologies for the noice, I made a mistake with force pushing on my previous pr.
Closes #57289

### CODE REVIEW

File: client/src/utils/math-jax.ts [hunk 1]
```diff
@@ -1,15 +1,19 @@
...
 export const isMathJaxAllowed = (pathname: string) =>
-  [
-    '/learn/javascript-algorithms-and-data-structures-v8',
-    '/learn/project-euler/',
-    '/learn/rosetta-code',
-    '/learn/scientific-computing-with-python'
-  ].some(allowedPath => pathname.includes(allowedPath));
+  initiateMathJaxOnSuperBlock.some(superBlock => pathname.includes(superBlock));
+
+const initiateMathJaxOnSuperBlock = [
```
Comment (naomi-lgbt) [inline client/src/utils/math-jax.ts:10]:
```suggestion
  superBlocksWithMathJax.some(superBlock => pathname.includes(superBlock));

const superBlocksWithMathJax = [
```

Just a naming nit. `initiateMathJax` sounds like a function that initialises Mathjax, not an array of anything.

**Review by naomi-lgbt — APPROVED** [review]

**Review by majestic-owl448 — APPROVED** [review]
