### PR TITLE
fix: remove old views

### LINKED ISSUE #36621: Remove footer views that have been ported to ghost
the following views have been ported to news and need to be removed if they exist.

- [x] About
- [x] Support
- [x] Sponsors
- [x] Academic Honesty
- [x] Code of Conduct
- [x] Privacy Policy
- [x] Terms of Service
- [x] Audit all page views other than the above.

### PR DESCRIPTION
**Pull request by ahmaxed**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36621
Closes #36696

### CODE REVIEW

File: client/src/components/Footer/index.js [hunk 1]
```diff
@@ -62,140 +61,94 @@ function Footer() {
...
-              Academic Honesty
-            </Link>
-            <Link to='https://www.freecodecamp.org/news/code-of-conduct/'>
-              Code of Conduct
-            </Link>
-            <Link to='https://www.freecodecamp.org/news/privacy-policy/'>
-              Privacy Policy
-            </Link>
-            <Link to='https://www.freecodecamp.org/news/freecodecamps-terms-of-service/'>
+            <Link to='/news/support/'>Support</Link>
```
Comment (raisedadead) [inline client/src/components/Footer/index.js]: Should these all news links be external?

Comment (ahmadabdolsaheb) [reply client/src/components/Footer/index.js]: @raisedadead seems like Gatsby recommend using <a> tag instead of link for external links.
https://www.gatsbyjs.org/docs/gatsby-link/

in that case, should I replace any link that does not route to client with <a> tag?

Comment (raisedadead) [reply client/src/components/Footer/index.js]: You should audit all the links including the ones in the footer and elsewhere on the static pages that we do serve externally should be external. 

Before that you should also check that we are on the current/correct version of the their implementation.

You should also check that we may have overrides on their implementation.

Finally adding tests would catch these questions.

Comment (raisedadead) [reply client/src/components/Footer/index.js]: Also I found that some of the links in the footer to `/news` are not current. Can you update them to on this PR?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead I double-checked the links in the footer, checked to see if our implementation is correct and current, added tests to confirm link from helpers in producing the correct link.

File: client/src/components/Footer/index.js [hunk 2]
```diff
@@ -36,23 +37,19 @@ function Footer() {
...
+              <Link className='inline' to='/donate'>
                 make a tax-deductible donation here
               </Link>
               .
             </p>
           </div>
           <div className='footer-col-1'>
             <div className='col-header'>Our Nonprofit</div>
-            <Link to='https://www.freecodecamp.org/news/about-freecodecamp/'>
+            <Link external={true} to='/news/about-freecodecamp/'>
```
Comment (raisedadead) [inline client/src/components/Footer/index.js]: This link needs to be updated.

**Review by raisedadead — CHANGES_REQUESTED** [review]

File: client/src/components/Footer/index.js (hunk 2 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Footer/index.js]: @raisedadead, thanks for updating that.
It has been resolved now.

File: client/src/client-only-routes/ShowUnsubscribed.js [hunk 3]
```diff
@@ -38,6 +38,8 @@ function ShowUnsubscribed({ unsubscribeId }) {
               </Button>
             </FullWidthRow>
           ) : null}
+          <Spacer />
```
Comment (raisedadead) [inline client/src/client-only-routes/ShowUnsubscribed.js]: Use the `size` prop instead of multiple elements

**Review by raisedadead — CHANGES_REQUESTED** [review]

**Review by raisedadead — COMMENTED** [review]
Its weird that you are updating the lockfile without updating any dependencies? Also I think we are moving away from `Enzyme` for tests. We already have `jest` and `react-testing-library` in place. Unless I am missing something?

**Review by raisedadead — COMMENTED** [review]
Also, I was thinking if you could template the list of links in the footer. I see there is a lot of repetition in the markup.

```js
			<Link external={true} to='/news/best-git-tutorial/'>
              Git Tutorial
            </Link>
            <Link external={true} to='/news/the-best-linux-tutorials/'>
              Linux Tutorial
            </Link>
            <Link external={true} to='/news/best-javascript-tutorial/'>
              JavaScript Tutorial
            </Link>
            <Link external={true} to='/news/best-react-javascript-tutorial/'>
              React Tutorial
            </Link>
```

Can we make one component and pass it an array of links?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead here is what I did
- added snapshot test for footer
- made a separated footer column and footer links into individual files
- replaced double space components in the codebase
- removed enzyme from tests

**Comment by raisedadead** [comment]
#### Awesomeness!!! Thanks @ahmadabdolsaheb !

File: client/src/components/Footer/index.js [hunk 4]
```diff
@@ -1,7 +1,9 @@
+/* eslint-disable max-len */
```
Comment (raisedadead) [inline client/src/components/Footer/index.js]: I think we are able to get rid of this now?

File: client/src/components/Footer/Footer.test.js [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+import React from 'react';
+import renderer from 'react-test-renderer';
+import 'jest-dom/extend-expect';
+
+import Footer from './';
+
+describe('<Footer />', () => {
+  it('renders to the DOM', () => {
+    const tree = renderer.create(<Footer />).toJSON();
+    console.log(tree);
```
Comment (raisedadead) [inline client/src/components/Footer/Footer.test.js]: To be removed?

**Review by raisedadead — CHANGES_REQUESTED** [review]
Some minor nit pics and we are good to go.

File: client/src/components/Footer/index.js (hunk 4 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Footer/index.js]: took care of this and the other.

File: client/src/components/Footer/Footer.test.js (hunk 5 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Footer/Footer.test.js]: thanks, was removed.

**Review by raisedadead — APPROVED** [review]
