### PR TITLE
fix(client): add better navigation for navigating back to blocks

### LINKED ISSUE #63943: Hovering blocks should not add to browser history
### Describe the Issue

https://github.com/freeCodeCamp/freeCodeCamp/issues/60280 was fixed by

https://github.com/freeCodeCamp/freeCodeCamp/pull/62212 

but this introduced a new bug. Now every block you hover is added to your browser's history,

### Affected Page

Any superblock, e.g. https://www.freecodecamp.org/learn/responsive-web-design-v9/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/responsive-web-design-v9/
2. Scroll down to Courses
3. Inside HTML expand Basic HTML
4. Mouse over "Build a Curriculum Outline" and "Understanding HTML Attributes"
5. Open your history (e.g chrome://history/ )
6. See two entries, one for "Build a Curriculum Outline" and one for "Understanding HTML Attributes"

### Expected behavior

Only "Understanding HTML Attributes" should be in the history.

### Screenshots

_No response_

### System

- Device: Desktop
- OS:  Ubuntu 24.04.2
- Browser: Chrome 141.0.7390.107 and Firefox 145.0 (64-bit)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #63943

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
This is smart. One thing I was concerned about was navigation other than just clicking with the mouse could result in the history not getting updated, but that's not necessarily a problem: https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR35 I think the `onClick` handler is the way to go. Good call.

I don't think `handleBlockClick` should be used quite like this - it's too broad.

Ideally the history should get updated when navigating away from the page. So, a partial solution would be simply update whenever the learner clicks on a challenge link. That's probably good enough, unless there's a simple way to have it update on any link being clicked.

So, I recommend `handleBlockClick` not updating the history, but only doing what's necessary when responding to a click on a block and only updating the history if the learner clicks on a challenge link.

**Comment by Sembauke** [comment]
> but only doing what's necessary when responding to a click on a block and only updating the history if the learner clicks on a challenge link.

So you're saying only update the history when actually clicking on a challenge, not for example on the block header?

**Comment by ojeytonwilliams** [comment]
> So you're saying only update the history when actually clicking on a challenge, not for example on the block header?

Yeah. The idea being we only want to add to the history at the point you leave the page. i.e. as close as we can make it to normal browser behaviour, but with the fragment (e.g. `#block-in-question`) attached.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Tests

**Comment by Sembauke** [comment]
Yep, completely slipped my mind 😓

File: client/src/templates/Introduction/components/block-header.tsx
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/block-header.tsx]: `onLinkClick` only applies to link blocks, meaning it's tied to the `blockUrl` prop, so I think we can improve the interface here a bit.

```suggestion
interface BaseBlockHeaderProps {
```

File: client/src/templates/Introduction/components/block-header.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ interface BlockHeaderProps {
   blockIntroArr?: string[];
   accordion?: boolean;
   blockUrl?: string;
+  onLinkClick?: () => void;
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/block-header.tsx]:
```suggestion
```

File: client/src/templates/Introduction/components/block-header.tsx [hunk 2]
```diff
@@ -23,6 +23,7 @@ interface BlockHeaderProps {
...
 }
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/block-header.tsx:26]:
```suggestion

interface BlockHeaderButtonProps extends BaseBlockHeaderProps {
  blockUrl?: never;
  onLinkClick?: never;
}

interface BlockHeaderLinkProps extends BaseBlockHeaderProps {
  blockUrl: string;
  onLinkClick: () => void;
}

type BlockHeaderProps = BlockHeaderButtonProps | BlockHeaderLinkProps;
```

File: client/src/templates/Introduction/components/challenges.tsx
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx:219]:
```suggestion
          blockTitle={blockTitle}
          onChallengeClick={onChallengeClick}
```

Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]:
```suggestion
  blockTitle,
  onChallengeClick
```

Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]:
```suggestion
      <ButtonLink size='small' href={firstIncompleteChallenge.fields.slug} onClick={onChallengeClick}>
```

File: client/src/templates/Introduction/components/challenges.tsx [hunk 3]
```diff
@@ -73,16 +96,19 @@ export function ChallengesList({ challenges }: ChallengesProps): JSX.Element {
 // Step or Task challenge
 const GridChallenge = ({
   challenge,
-  isTask = false
+  isTask = false,
+  onChallengeClick
 }: {
   challenge: ChallengeInfo;
   isTask?: boolean;
+  onChallengeClick?: () => void;
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]: This should be a required prop.

```suggestion
  onChallengeClick: () => void;
```

File: client/src/templates/Introduction/components/challenges.tsx [hunk 4]
```diff
@@ -37,25 +38,44 @@ interface IsProjectBlockProps {
...
-  </Link>
-);
-
-export function ChallengesList({ challenges }: ChallengesProps): JSX.Element {
+const ListChallenge = ({
+  challenge,
+  onChallengeClick
+}: {
+  challenge: ChallengeInfo;
+  onChallengeClick?: () => void;
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]: This should be a required prop.

```suggestion
  onChallengeClick: () => void;
```

File: client/src/templates/Introduction/components/challenges.tsx [hunk 5]
```diff
@@ -37,25 +38,44 @@ interface IsProjectBlockProps {
...
+    </Link>
+  );
+};
+
+const CertChallenge = ({
+  challenge,
+  onChallengeClick
+}: {
+  challenge: ChallengeInfo;
+  onChallengeClick?: () => void;
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]: This should be a required prop.

```suggestion
  onChallengeClick: () => void;
```

File: client/src/templates/Introduction/components/challenges.tsx [hunk 6]
```diff
@@ -20,6 +20,7 @@ interface ChallengeInfo {
 
 interface ChallengesProps {
   challenges: ChallengeInfo[];
+  onChallengeClick?: () => void;
```
Comment (huyenltnguyen) [inline client/src/templates/Introduction/components/challenges.tsx]:
```suggestion
  onChallengeClick: () => void;
```

**Review by huyenltnguyen — COMMENTED** [review]
Apparently the hover behavior accidentally addressed #62555. 

Now that we've removed the hover behavior (which I agree with), we should re-open that issue. I think we might need to use react-scroll to solve that.

**Review by huyenltnguyen — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
