### PR TITLE
fix(modern-challenges): Default nav link to "Editor" if only one editor

### LINKED ISSUE #16529: Modern Challenges: when only one editor, default nav link to "Editor", else use file name
[Per @BerkeleyTrue's suggestion](https://github.com/freeCodeCamp/freeCodeCamp/pull/16459#issuecomment-358042085), modify modern challenges editor nav link to default to "Editor" instead of "index" when there is only one editor tab. Set it up so that in the future, when we have multi-tab editor, it will default to file name:

> The original intent here was to replicate an actual editor, with the name of the file you are actually editing at the top of the file but I see the issue with the name in the nav that could confuse new users. The problem with renaming it to editor is when you have more than one, you can't call them both Editor.
>
> A compromise: When there is only one editor we can default to Editor and when there is more than one we could name them by file. Thoughts?

### PR DESCRIPTION
**Pull request by werne2j**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes #16529

#### Description
For Modern Challenges when there is only one editor we want to default the nav link to display `Editor` instead of the filename. When there is more than one file then we will display the filename in the nav link

### CODE REVIEW

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 1]
```diff
@@ -24,12 +24,17 @@ const propTypes = {
...
-      return map;
-    }, {})
-  })
+  files => {
+    if (Object.keys(files).length === 1) {
+      return { nameToFileKey: { Editor: files[Object.keys(files)[0]].key }};
+    }
+    return {
+      nameToFileKey: _.reduce(files, (map, file) => {
+        map['Editor'] = file.key;
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/Modern/Show.jsx]: This makes every file `Editor`.

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/routes/Challenges/views/Modern/Show.jsx (hunk 1 above)
Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: Yes it does 🙈 Must have forgotten to change that back!

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 2]
```diff
@@ -24,12 +24,17 @@ const propTypes = {
...
   filesSelector,
-  files => ({
-    nameToFileKey: _.reduce(files, (map, file) => {
-      map[file.name] = file.key;
-      return map;
-    }, {})
-  })
+  files => {
+    if (Object.keys(files).length === 1) {
+      return { nameToFileKey: { Editor: files[Object.keys(files)[0]].key }};
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/Modern/Show.jsx]: `files[Object.keys(files)[0]].key` This logic is quite complex. We can simplify this by using lodash.get https://lodash.com/docs/4.17.4#get

Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: @BerkeleyFalse if we know what the key of the only file then yes this is a little complex. I was assuming we don't know the name of the only file. Looking at the files object, i think this can be simplified to `Object.keys(files)[0]` but i am not sure if we can guarantee that if there is only one file it is always `indexjsx`.

Comment (BerkeleyTrue) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: Ah yes, forgotten about that. It will get more complex with lodash but it will at least be declarative.

We need to get the values, then the first, then the property of key,

`_.flow(_.values, _.first, _.property('key'))({ foo: { key: 'bar' } }) // => 'bar'`

Looks like you are using this multiple times so it can be hoisted up into it's own function.

Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: Sounds good! Pushing up a change.

**Review by no-stack-dub-sack — APPROVED** [review]
thanks @werne2j, with @BerkeleyTrue's suggested changes, this LGTM, but I'll let him take a final look before merging this is.

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 3]
```diff
@@ -39,23 +47,30 @@ export const mapStateToPanes = addNS(
...
-        map[createModernEditorToggleType(file.fileKey)] = file.name;
-        return map;
-      }, {
+
+      let panesMap = {
         [types.toggleMap]: 'Map',
-        [types.toggleSidePanel]: 'Lesson'
-      });
+        [types.toggleSidePanel]: 'Lesson',
+        [`${types.toggleModernEditor}(${getFirstFileKey(files)})`]: 'Editor'
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/Modern/Show.jsx]: This should use the same `createModernEditorToggleType` as below.

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 4]
```diff
@@ -39,23 +47,30 @@ export const mapStateToPanes = addNS(
...
+        [types.toggleSidePanel]: 'Lesson',
+        [createModernEditorToggleType(getFirstFileKey(files))]: 'Editor'
+      };
+
+      // If there is more than one file show file name
+      if (Object.keys(files).length > 1) {
+        _.forEach(files, (file) => {
+          panesMap[createModernEditorToggleType(file.fileKey)] = file.name;
+        });
+      }
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/Modern/Show.jsx]: This needs to be an if/else

When there is more then one file there shouldn't be an `Editor` plan, since there will be multiple.

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 5]
```diff
@@ -39,23 +47,30 @@ export const mapStateToPanes = addNS(
...
       // must include map
       // side panel
       // editors are created based on state
       // so pane component can have multiple panes based on state
-      const panesMap = _.reduce(files, (map, file) => {
-        map[createModernEditorToggleType(file.fileKey)] = file.name;
-        return map;
-      }, {
+
+      let panesMap = {
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/Modern/Show.jsx]: This should be a const

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/routes/Challenges/views/Modern/Show.jsx [hunk 6]
```diff
@@ -18,18 +18,26 @@ import { filesSelector } from '../../../../files';
 const createModernEditorToggleType = fileKey =>
   types.toggleModernEditor + `(${fileKey})`;
 
+const getFirstFileKey = object =>
+  _.flow(_.values, _.first, _.property('key'))(object);
```
[the remark this answers is not in the document]
Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: If i don't wrap `_.flow(_.values, _.first, _.property('key'))(object);` in a function, how am i going to pass the object i want to get the first key of?

[the remark this answers is not in the document]
Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: Oh, i think i understand

[the remark this answers is not in the document]
Comment (werne2j) [reply common/app/routes/Challenges/views/Modern/Show.jsx]: I think i understand

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
💥  nice work!!


Happy Coding
