### PR TITLE
fix(settings): Make night mode settings-toggle actually work

### LINKED ISSUE #15790: Toggle night mode in settings menu doesn't work
#### Issue Description

When I go into settings and click on the night mode button, the website does not switch to night mode. It cannot switch back from night mode to default mode either. There is an error message in the console: `Cannot read property 'theme' of undefined`

I went into the code and to try to fix the issue, but I have so far come up short. The problem seems to be that `client/epics/night-mode-epic.js` is looking for the property `app.theme` in the redux store, which does not exist.

In `common/app/redux/index.js` there is an initialState object that looks like it is setting `app.theme` to `"default"`, however, clearly app.theme is never actually set to the redux store.

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.78, Firefox
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: Desktop

### PR DESCRIPTION
**Pull request by markusenglund**
Closes #15790

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15790

#### Description

Switching between night mode and the default mode now works.

The night mode epic that should have accessed app.theme from the store, would instead try to access app.theme.theme due to faulty use of the object destructuring syntax. This caused an error in the console, and prevented night mode setting from toggling.

### CODE REVIEW

**Comment by yogaboll** [comment]
I removed unnecessary comments from the pr.

File: client/epics/night-mode-epic.js [hunk 1]
```diff
@@ -35,12 +35,14 @@ export default function nightModeSaga(
       }
     })
     .filter(() => false);
+
   const toggle = actions
     .filter(({ type }) => types.toggleNightMode === type);
 
+  // Set new theme ('night' or 'default') to local storage
```
Comment (systimotic) [inline client/epics/night-mode-epic.js]: I don't think this comment is entirely accurate. From what I can tell, this is an observable that, when triggered, gets the current theme, switches it, and calls _a different function_ to store it. This function is not the function that actually sets it to local storage. I think this is better off without a comment.

**Review by systimotic — DISMISSED** [review]
Note: I haven't had the time to test whether the fix works for me yet. Hopefully I find time soon, but if somebody else has sees this before I have left another review, feel free to test this out!

File: client/epics/night-mode-epic.js (hunk 1 above)
Comment (yogaboll) [reply client/epics/night-mode-epic.js]: You're right, I'll make the change.

**Comment by yogaboll** [comment]
I made the requested change.

**Comment by QuincyLarson** [comment]
@yogaboll Well done. Works for me. Thanks for your contribution!

**Comment by systimotic** [comment]
@yogaboll Thanks for fixing this! 🎉
