### PR TITLE
fix: circular dependencies

### LINKED ISSUE #45277: Prevent circular imports via linting
### The problem

Circular dependencies can cause surprising bugs. For example, variables may not be defined before being used.

### The solution 

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md

If someone wants to use a circular dependency they can always disable the rule.

### LINKED ISSUE #45307: Circular dependency detected
In https://github.com/freeCodeCamp/freeCodeCamp/issues/45277#issuecomment-1056210055 @Jagrutiti found that there are several circular dependencies between the redux sagas and reducers.  Since these can be sources of subtle and confusing bugs, it would be good if these cycles could be broken.

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #45307 
Closes #45277

So I'm taking a stab at this.

Currently in ESLint config, I've set the `maxDepth` for the `no-cycle` rule to `2`. The command `lint:js` took 50s to run in my system and here's the current output:
<details>
<summary>Click to expand</summary>

```bash
> @freecodecamp/freecodecamp@0.0.1 lint:js
> eslint --max-warnings 0 .


/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/accept-terms-saga.js
  7:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/codeally-saga.js
  5:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/donation-saga.js
  19:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/failed-updates-epic.js
  18:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/fetch-user-saga.js
  5:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/ga-saga.js
  6:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/index.js
   8:1  error  Dependency cycle detected  import/no-cycle
  11:1  error  Dependency cycle detected  import/no-cycle
  12:1  error  Dependency cycle detected  import/no-cycle
  13:1  error  Dependency cycle detected  import/no-cycle
  14:1  error  Dependency cycle detected  import/no-cycle
  15:1  error  Dependency cycle detected  import/no-cycle
  18:1  error  Dependency cycle detected  import/no-cycle
  20:1  error  Dependency cycle detected  import/no-cycle
  22:1  error  Dependency cycle detected  import/no-cycle
  23:1  error  Dependency cycle detected  import/no-cycle
  24:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/report-user-saga.js
  7:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/save-challenge-saga.js
   3:1  error  Dependency cycle via ../../../redux:6  import/no-cycle
  16:1  error  Dependency cycle detected              import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/settings/danger-zone-saga.js
  9:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/settings/index.js
  3:1  error  Dependency cycle detected  import/no-cycle
  4:1  error  Dependency cycle detected  import/no-cycle
  5:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/settings/settings-sagas.js
  33:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/settings/update-email-saga.js
  8:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/show-cert-saga.js
  6:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/update-complete-epic.js
  5:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/redux/user-token-saga.js
  5:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/code-storage-epic.js
  13:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/completion-epic.js
  27:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/create-question-epic.js
  6:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/current-challenge-saga.js
  6:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/execute-challenge-saga.js
  38:1  error  Dependency cycle detected  import/no-cycle

/Users/niraj/Desktop/FCC/freeCodeCamp/client/src/templates/Challenges/redux/index.js
   6:1  error  Dependency cycle via ./save-challenge-saga:24  import/no-cycle
  10:1  error  Dependency cycle detected                      import/no-cycle
  11:1  error  Dependency cycle detected                      import/no-cycle
  12:1  error  Dependency cycle detected                      import/no-cycle
  13:1  error  Dependency cycle detected                      import/no-cycle
  14:1  error  Dependency cycle detected                      import/no-cycle

✖ 40 problems (40 errors, 0 warnings)
```
</details>

---

From the above output all the errors are connected through mainly 3 files:
1. /client/src/redux/index.js
2. /client/src/redux/settings/index.js
3. /client/src/templates/Challenges/redux/index.js

---

With the example of commit([843d643](https://github.com/freeCodeCamp/freeCodeCamp/commit/843d64332cea1f3b1918dbb5a38ee522e44aef66)), I'll explain why circular dependencies are happening. 

The circular loop here is that both `index.js`(same directory) and `code-lock-epic.js` are importing each other. So I moved the Redux action for `unlockCode` to `code-lock-epic.js` to get rid of the import which is causing the error. Now `index.js` is only importing the respective epic(`codeLockEpic`) and no circular loops are present. Basically the loops are happening because the epics are imported from the individual epic files to their respective `index.js` and those individual files import `index.js` again for the Redux action to be used in the same epic. 

I have a solution in mind for the remaining files, which is we move all the Redux actions to their respective epic files. Yes by doing this the Actions will be split out and stored in a lot of files instead of being stored in one single file but we get rid of the circular dependencies.

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Currently I've set the `maxDepth` value to `1` so the test passes without running out of memory.

**Comment by raisedadead** [comment]
@Sboonny,
 
Can you confirm you intended to mark this for review because the checks aren't passing yet?

**Comment by Sboonny** [comment]
I was assigned immediately after this came to my attention, when it came to my attention the test were still running so I didn't know about them failing sorry about the label.

About the review, I don't know how to test it and you seemed the best to review it and give guidance .

**Comment by Nirajn2311** [comment]
**cc** - @ojeytonwilliams

File: client/src/redux/selectors.js [hunk 1]
```diff
@@ -0,0 +1,220 @@
...
+export const showCodeAllySelector = state => {
+  return state[MainApp].showCodeAlly;
+};
+
+export const userByNameSelector = username => state => {
+  const { user } = state[MainApp];
+  // return initial state empty user empty object instead of empty
+  // object litteral to prevent components from re-rendering unnecessarily
+  // TODO: confirm if "initialState" can be moved here or action-types.js
+  return user[username] ?? initialState.user;
```
Comment (ojeytonwilliams) [inline client/src/redux/selectors.js:79]: I was overthinking it in the meeting.  Let's just use `{}` as the fallback.  If we get this migrated to TS, we can revisit it then.

Also, we already do this once in `userSelector` :man_shrugging:

File: client/src/components/formHelpers/form.tsx [hunk 2]
```diff
@@ -1,24 +1,75 @@
...
+  values: URLValues;
+  errors: ValidationError[];
+  invalidValues: (JSX.Element | null)[];
 };
 
+const normalizeOptions = {
+  stripWWW: false
+};
+
+function formatUrlValues(
```
Comment (ojeytonwilliams) [inline client/src/components/formHelpers/form.tsx:36]: Couple of things stand out.  Can this be moved into a separate file?  Maybe just called `form-helpers`.  It seems a little out of place here.

Also, how about `dynamic-form` for the directory name, rather than `formHelpers`?  The latter makes it sound like things you would need when buildling a form, rather than the form itself (which is really what's being exported here)

File: client/src/redux/types.ts [hunk 3]
```diff
@@ -1,5 +1,14 @@
-import { FlashApp, FlashMessageArg } from '../components/Flash/redux';
-import { MainApp } from '.';
+import { FlashMessages } from '../components/Flash/redux/flash-messages';
+import { ns as MainApp } from './action-types';
+
+// Shaun: Is this fine as in "rootReducer" you imported both reducer and namespace together from same file for easier updation
```
Comment (ojeytonwilliams) [inline client/src/redux/types.ts:4]: @ShaunSHamilton ?

**Review by ojeytonwilliams — DISMISSED** [review]
I had to trust in your copy-paste skills at some points, @Nirajn2311!  I couldn't see anything wrong, though. Nice job!

There was one place that things could be tweak and also a cryptic message to Shaun:

File: client/src/redux/types.ts (hunk 3 above)
Comment (ShaunSHamilton) [reply client/src/redux/types.ts:4]: Good question... give me a minute on this.

Comment (ShaunSHamilton) [reply client/src/redux/types.ts:4]: This seems fine. Nothing wrong with it.

Ideally, I imagine we would export all state apps from a single path. This file seems like it could suit.

Comment (ojeytonwilliams) [reply client/src/redux/types.ts:4]: I.e. we define both common types and namespace constants here? Sounds reasonable.

On reflection, we could do that and my suggestions separately. @Nirajn2311 is that okay?

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Thanks again, @Nirajn2311 :purple_heart:

**Review by ShaunSHamilton — APPROVED** [review]
LLTMADWWW 👍
