### PR TITLE
fix(ui-components): make Alert not dismissable

### LINKED ISSUE #45206: Add Flash component to the component library
Previously in the refactoring of the `Alert` component, we said that we would need to build a `Flash` component also, because with the current implementation of `Alert`, it is a combination of both (see https://github.com/freeCodeCamp/freeCodeCamp/pull/45015#discussion_r802387268).

I'm moving the discussion here so that we can continue to discuss.

@ahmadabdolsaheb If you're okay with my approach I can update the main issue to include `Flash` as well as making changes to the Alert component to correct its implementation 🙂

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45206

This PR is to address https://github.com/freeCodeCamp/freeCodeCamp/pull/45015#discussion_r800721802, which was moved to #45206 for further discussion.

Basically, we will eventually have `Alert` and `Flash` components. Both are identical, but one is dismissable (Flash) and one is not (Alert). The Flash component is to be built, and a low-priority one. I have added it to our component list in the main issue (#44668).

This PR is to remove props that are related to the dismisability from the Alert component.

## Screenshot

- The "Dismisable" story on the sidebar no longer exists.
- The component description is updated to mention that it is not dismissable.

Screen Shot 2022-02-28 at 22 35 16

### CODE REVIEW

File: tools/ui-components/src/alert/alert.tsx [hunk 1]
```diff
@@ -19,30 +16,26 @@ const variantClasses: Record<AlertVariant, string> = {
...
   const classes = [
-    'flex items-start p-4 mb-6 border border-transparent break-words',
+    'p-4 mb-6 border border-transparent break-words',
     variantClass,
     className
   ].join(' ');
 
   return (
     <div className={classes} role='alert'>
-      <div className='grow'>{children}</div>
```
Comment (huyenltnguyen) [inline tools/ui-components/src/alert/alert.tsx:42]: This div and the class `grow` was introduced in #45015 as part of the refactoring. It is used for the positioning of the content, but we no longer need it.

Use this diff to compare: https://github.com/freeCodeCamp/freeCodeCamp/pull/45015/files#diff-f8215b54195f23de79bf4eb3c51a39a1b558a156c486d91dac6fadea007d342e

File: tools/ui-components/src/alert/alert.tsx [hunk 2]
```diff
@@ -19,30 +16,26 @@ const variantClasses: Record<AlertVariant, string> = {
...
-  variant,
-  dismissLabel = 'Close',
-  onDismiss
+  variant
 }: AlertProps): JSX.Element {
-  const isDismissable = !!onDismiss;
   const variantClass = variantClasses[variant];
 
   const classes = [
-    'flex items-start p-4 mb-6 border border-transparent break-words',
```
Comment (huyenltnguyen) [inline tools/ui-components/src/alert/alert.tsx:35]: Same here.

Use this diff to compare: https://github.com/freeCodeCamp/freeCodeCamp/pull/45015/files#diff-f8215b54195f23de79bf4eb3c51a39a1b558a156c486d91dac6fadea007d342e

**Comment by ahmadabdolsaheb** [comment]
Thank you for taking care of this.

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
