### PR TITLE
fix(curriculum tests): test cert projects

### LINKED ISSUE #52957: [Certification projects] `pnpm test:curriculum` doesn't seem to validate solution code against hints
## Describe the bug

The `pnpm test:curriculum` command doesn't seem to validate solution code against the hints. This appears to be an issue only in certification projects.

## Steps to reproduce

- Choose a certification project file
- Change one of the hints so that the challenge doesn't pass
- Run `FCC_CHALLENGE_ID=[challenge_id] pnpm run test:curriculum`. For example: `657bdcc3a322aae1eac38392`, which is the ID of the Cash Register project
- The test passes while it should fail. (And I'm not sure what the 2 passing tests are)
  Screenshot 2024-01-05 at 00 24 30

I'm not sure if all of the certification projects have this issue. I've only tested with the Cash Register and Product Landing Page projects.

## Additional context

The issue was discovered by @ieahleen when manually testing https://github.com/freeCodeCamp/freeCodeCamp/pull/52929. The changes pass CI, but the solution code actually doesn't pass the changed test.

### PR DESCRIPTION
**Pull request by moT01**
Makes sure that all challenge types with a solution are tested. 
Adds a solution CSS file to an Odin project challenge. It could probably be deleted after https://github.com/freeCodeCamp/freeCodeCamp/pull/53058 gets in.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/52957

### CODE REVIEW

File: curriculum/test/test-challenges.js [hunk 1]
```diff
@@ -370,17 +373,8 @@ function populateTestsForLang({ lang, challenges, meta }) {
...
-            challengeType !== challengeTypes.js &&
-            challengeType !== challengeTypes.jsProject &&
-            challengeType !== challengeTypes.modern &&
-            challengeType !== challengeTypes.backend &&
-            challengeType !== challengeTypes.python
-          ) {
-            return;
-          }
+
+          if (hasNoTests) return;
```
Comment (gikf) [inline curriculum/test/test-challenges.js:377]:
```suggestion
          if (hasNoTests(challengeType)) return;
```

Comment (moT01) [reply curriculum/test/test-challenges.js:377]: umm, whoops.

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Tested locally with the fixed project test from #52929

**Review by naomi-lgbt — APPROVED** [review]
