### PR TITLE
fix(tools): allow position 0 in create-project script

### LINKED ISSUE #64234: `pnpm run create-new-project` cannot insert module at first position
### Describe the Issue

I’ve tried running `pnpm run create-new-challenge` by entering a position of zero. The script rejects the input and gives me the message: `Position must be a number greater than zero`.

When entering `1` instead the script inserts the new project below the first module.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/5c28fbffa82ad7d3b5f53c49f5608d81463d1770/tools/challenge-helper-scripts/create-project.ts#L397

### Steps to Reproduce

1. Go to the `freeCodeCamp` repo in your terminal
2. run `pnpm run create-new-project`
3. Enter some project details; for example: 
```
? Which certification does this belong to? javascript-v9
? What is the dashed name (in kebab-case) for this project? test-project-to-test-pnpm-create-new-project
? title: test-project-to-test-pnpm-create-new-project
? Choose a help category JavaScript
? Choose a block label workshop
? Choose a block layout challenge-grid
? What chapter should this project go in? javascript
? What module should this project go in? javascript-variables-and-strings
```
4. Enter `0` for the prompt `? At which position does this appear in the module?`
5. See error

### Expected behavior

The script should accept `0` as a position.

### Screenshots

`pnpm run create-new-challenge` when entering a position of zero:
Image

`pnpm run create-new-challenge` when entering a position of `1`:
Image

`superblocks/javascirpt-v9.json` after running `pnpm run create-new-challenge` with a position of `1`:
Image

### System

none

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bigfatbird**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #64234

Updated create-new-project script with additional error text. set default insert var to 0 from 1

### CODE REVIEW

File: tools/challenge-helper-scripts/create-project.ts [hunk 1]
```diff
@@ -375,11 +375,11 @@ void getAllBlocks()
       {
         name: 'position',
         message: 'At which position does this appear in the module?',
-        default: 1,
+        default: 0,
```
Comment (huyenltnguyen) [inline tools/challenge-helper-scripts/create-project.ts]: Instead of allowing 0, I think we should make the script to accept 1-based values but evaluate that as 0-based. This will maintain the consistency, as the `order` prompt right after this one expects a 1-based value.

Here is an example:

https://github.com/freeCodeCamp/freeCodeCamp/blob/745d4632530636531d8aa9793cfc55f44a391d14/tools/challenge-helper-scripts/create-language-block.ts#L121-L126

Comment (bigfatbird) [reply tools/challenge-helper-scripts/create-project.ts]: I changed the logic for this slightly :)

**Comment by bigfatbird** [comment]
Well, I see my current iteration doesn't work satisfingly enough. When entering 0 or 1 it jumps back and forth with decrementing the input even smaller. I will have to think more cleverly for this

File: tools/challenge-helper-scripts/create-project.ts
Comment (huyenltnguyen) [inline tools/challenge-helper-scripts/create-project.ts]: I think we just need to keep the code as-is and change this line to:

```suggestion
      // Convert human-friendly (1-based) position to 0-based index for insertion.
      { order: position - 1, chapter, module },
```

File: tools/challenge-helper-scripts/create-project.ts [hunk 2]
```diff
@@ -377,14 +377,14 @@ void getAllBlocks()
         message: 'At which position does this appear in the module?',
         default: 1,
         validate: (position: string) => {
-          return parseInt(position, 10) > 0
+          return parseInt(position, 10) >= 0
```
Comment (huyenltnguyen) [inline tools/challenge-helper-scripts/create-project.ts]:
```suggestion
          return parseInt(position, 10) > 0
```

File: tools/challenge-helper-scripts/create-project.ts [hunk 3]
```diff
@@ -377,14 +377,14 @@ void getAllBlocks()
...
             ? true
             : 'Position must be an number greater than zero.';
         },
         when: (answers: CreateProjectArgs) =>
           chapterBasedSuperBlocks.includes(answers.superBlock),
         filter: (position: string) => {
-          return parseInt(position, 10);
+          return parseInt(position, 10) - 1;
```
Comment (huyenltnguyen) [inline tools/challenge-helper-scripts/create-project.ts]:
```suggestion
          return parseInt(position, 10);
```

**Comment by bigfatbird** [comment]
@huyenltnguyen I updated the suggestions and it works as described. I didn't see, that the code was used on the top of the file in line 89 too. 

The input parser still messes up, if you type in -1, -2 etc... but this might be another bug?

**Comment by huyenltnguyen** [comment]
> The input parser still messes up, if you type in -1, -2 etc

I'm not sure what you mean by this. I tried entering negative numbers and got the "Position must be an number greater than zero." error, which is expected.

For these tools we don't usually handle deeper edge cases since they're intended for curriculum developers, who typically won't try to enter invalid values.

**Comment by bigfatbird** [comment]
I mean it doesn't reset the enter value to an empty input field. But it seems out of scope anyway then :)

File: tools/challenge-helper-scripts/create-project.ts [hunk 4]
```diff
@@ -86,7 +86,7 @@ async function createProject(projectArgs: CreateProjectArgs) {
     }
     void updateChapterModuleSuperblockStructure(
       projectArgs.block,
-      { order: position, chapter, module },
+      { order: position - 1, chapter, module },
```
Comment (huyenltnguyen) [inline tools/challenge-helper-scripts/create-project.ts:90]: Let's add a comment here

```suggestion
      // Convert human-friendly (1-based) position to 0-based index for insertion.
      { order: position - 1, chapter, module },
```

Comment (bigfatbird) [reply tools/challenge-helper-scripts/create-project.ts:90]: Adde the recommended comment describing the behaviour :)

**Review by huyenltnguyen — APPROVED** [review]

**Comment by huyenltnguyen** [comment]
Thanks @bigfatbird!

Regarding the input clearing issue, I noticed the behavior but I haven't looked into it. Please help create an issue so we can track it.

**Comment by bigfatbird** [comment]
Thanks for reviewing and helping out @huyenltnguyen. Sorry for the back and forth in the review process. I didn't have the right idea from the start. :)
