### PR TITLE
Fixed streak and completion dates to be showed using users timezone

### LINKED ISSUE #5799: Streak seems broken (screenshot)

### PR DESCRIPTION
**Pull request by LenaBarinova**
Getting user's timezone on the client side and passing it to the server-side with POST (on challenge complete), saving timezone to user's profile.
In a user profile page getting user's timezone and showing all date related data using user's timezone.

If a user will be browsing other's user's stats - they will be shown in signed user's timezone.

closes #5799

### CODE REVIEW

**Comment by SaintPeter** [comment]
Do we know what will happen if a user who didn't formally have a timezone suddenly gets one?  Will it break an existing streak?

Also, the server is, I believe, on New Your Time (EST).   I see that you have UTC hard coded, but I'm not sure if that was intended to stand in for server time..

File: server/boot/user.js [hunk 1]
```diff
@@ -223,9 +229,20 @@ module.exports = function(app) {
...
+              if (challenge.completedDate) {
+                challenge.completedDate = 
+                  moment.tz(challenge.completedDate, timezone).format(format);
+              }
+              if (challenge.lastUpdated) {
+                challenge.lastUpdated = 
+                  moment.tz(challenge.lastUpdated, timezone).format(format);
+              }
+              return challenge;
+          });
```
Comment (BerkeleyTrue) [inline server/boot/user.js]: It is good practice in functional programming to create a new object instead of mutating the old challenge object to prevent unwanted side-effects.

```js
             const format = 'MMM DD, YYYY';
             // use ES7 spread operator to spread the props of the challenge object
             // onto a new object
             challenge  = { ...challenge };
              if (challenge.completedDate) {
                challenge.completedDate = 
                  moment.tz(challenge.completedDate, timezone).format(format);
              }
              if (challenge.lastUpdated) {
                challenge.lastUpdated = 
                  moment.tz(challenge.lastUpdated, timezone).format(format);
              }
              return challenge;
```

File: server/boot/user.js [hunk 2]
```diff
@@ -223,9 +229,20 @@ module.exports = function(app) {
...
         }
 
-        const completedChallenges = profileUser.completedChallenges.filter(
-          ({ name }) => typeof name === 'string'
-        );
+        const completedChallenges = profileUser.completedChallenges
+          .filter(({ name }) => typeof name === 'string')
+          .map(challenge => {
+              const format = 'MMM DD, YYYY';
+              if (challenge.completedDate) {
```
Comment (BerkeleyTrue) [inline server/boot/user.js]: This constant should be hoisted to the top of the file with the rest of the constants and given a specific name. While normally not important, we serve 10's of thousands of people a day and growing. Minor memory tricks like this helps us reduce server load.

**Comment by LenaBarinova** [comment]
@SaintPeter 
1. No. The streak will not be broken. Since streak is being calculated each time it's being shown from completed challenges list from user's profile. Completed challenges haven't been changed and they will still be saved using UTC (unix epoch format) on a server side. With this change streak is being calculated using user's time zone, not servers.
2. UTC is hardcoded as a fallback in case of unsuccessful timezone detection on a client-side. It shouldn't be save to user profile. As for display I think it's equally wrong to show either UTC or server's timezone for user - we will get discrepancies as it was before.

**Comment by Em-Ant** [comment]
screenshot - 22012016 - 20 31 34

My streak seems wrong. According to the calendar it should be 21. I've noticed it a couple of days ago. I'm in Italy (UTC/GMT +1, No Daylight Saving Time )

**Comment by LenaBarinova** [comment]
It's been a while since this PR was submitted. Now I believe it will not merge nicely. Should I update it? @BerkeleyTrue do you have any more comments on code?

**Comment by BerkeleyTrue** [comment]
Nope :+1: . I thought this was already merged in. I belive @SaintPeter was waiting on me throwing it up on Beta. My bad. Let me know when you have a chance to rebase it off staging and I'll put it on Beta.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue rebased off staging. Please let me know when it's in beta, would love to test it.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue @SaintPeter, I'm ready with some "time travel" use cases to test this change, so as soon as it is in Beta, please let me know.

**Comment by BerkeleyTrue** [comment]
Live on Beta :shipit:

**Comment by LenaBarinova** [comment]
@BerkeleyTrue Thanks! 

On a client side I'm getting old CommonFramework.js file (same version as in production, without my changes), though I have cleaned my cache. Is there a way to reinforce CommonFramework.js file regeneration to include client side changes?

**Comment by BerkeleyTrue** [comment]
Sorry about that. Now it should be up

**Comment by LenaBarinova** [comment]
Beautiful! From first sight - it works. Is there by any chance a test account with rich history in Beta?

File: server/boot/user.js [hunk 3]
```diff
@@ -183,6 +185,12 @@ module.exports = function(app) {
         }
         profileUser = profileUser.toJSON();
 
+        // timezone of signed-in account
+        // to show all date related components
+        // using signed-in account's timezone
+        // not of the profile she is viewing
+        const timezone = req.user.timezone || 'UTC';
```
Comment (BerkeleyTrue) [inline server/boot/user.js]: `Cannot read property timezone of undefined`

You'll need to verify that the user exists as you don't need to be signed to hit this endpoint

**Comment by BerkeleyTrue** [comment]
I've connected to production DB to test out, put found an issue that crashes the server. I'll need to revert until that issue is fixed

**Comment by LenaBarinova** [comment]
Ups, sorry. My bad. Haven't tested it without signing in.
@BerkeleyTrue, I fixed the issue.

**Comment by LenaBarinova** [comment]
@BerkeleyTrue could you please deploy this fix on Beta when you are available?

**Comment by BerkeleyTrue** [comment]
Pushed

**Comment by LenaBarinova** [comment]
Looks good now. There still differences when the user is not signed in, but this is expected. With the signed in user all the three components (heatmap, streak, list of completed assignments) are in sync.

**Comment by BerkeleyTrue** [comment]
@SaintPeter If there are no further comments on this PR I think we can merge

**Comment by SaintPeter** [comment]
It doesn't appear to catch anything on fire.  I think we can merge it.

**Comment by BerkeleyTrue** [comment]
@LenaBarinova Woot! Thanks!

**Comment by TheBGar** [comment]
I just saw that this was "closed" however, my profile still isn't displaying the correct streak. Will it be updated or will it only be counting the new streak since this issue has been pushed?

Thanks for working on this!

**Comment by LenaBarinova** [comment]
Hi @TheBGar! It should be updated right after you complete at least one challenge. Please let me know if it worked.

**Comment by TheBGar** [comment]
Thanks for your response @LenaBarinova! Regrettably it did not. After completing one challenge it **does** update. However, it only appears to update my streak back to the date you guys fixed things (I believe) rather than through the entirety of my streak. You can see on my profile page what I mean - [](http://www.freecodecamp.com/thebgar)

Thanks for all your help!

File: client/commonFramework/show-completion.js [hunk 4]
```diff
@@ -51,7 +52,8 @@ window.common = (function(global) {
         name: common.challengeName,
         completedWith: didCompleteWith,
         challengeType: common.challengeType,
-        solution
+        solution,
+        timezone: moment.tz.guess()
       };
 
       $.post('/completed-challenge/', data, function(res) {
```
Comment (king4415) [inline client/commonFramework/show-completion.js]: Jkk

Comment (king4415) [inline client/commonFramework/show-completion.js]: Hundert

File: test/server/utils/user-stats-test.js [hunk 5]
```diff
@@ -1,132 +1,160 @@
...
+      moment.utc("9/13/2015 3:00", "M/D/YYYY H:mm").valueOf(),
+      moment.utc("9/14/2015 1:00", "M/D/YYYY H:mm").valueOf()
+    ], 'America/Los_Angeles'), 4, "should return 4 when there is the only one more-than-one-days-long streak available given 'America/Los_Angeles' timezone");
+
+  t.equal(calcLongestStreak([
+      moment.utc("9/11/2015 23:00", "M/D/YYYY H:mm").valueOf(),
+      moment.utc("9/12/2015 2:00", "M/D/YYYY H:mm").valueOf(),
+      moment.utc("9/13/2015 2:00", "M/D/YYYY H:mm").valueOf(),
+      moment.utc("9/14/2015 1:00", "M/D/YYYY H:mm").valueOf()
+    ], 'America/Los_Angeles'), 3, "should return 3 when longest streak is 3 in given 'America/Los_Angeles' timezone (but would be different in default timezone UTC)");
```
Comment (king4415) [inline test/server/utils/user-stats-test.js]: Amerika/los

**Comment by LenaBarinova** [comment]
@TheBGar, I've reproduced this issue on my machine. Working on it.
