### PR TITLE
fix(UI): Remove 'CTRL + Enter' on CTA for mobile 

### LINKED ISSUE #46178: New Editor layout Improvements ☂️
### Describe the Issue

This is an umbrella issue to discuss the improvement to the editor layout:
Here is the mockup for your reference.
https://www.figma.com/file/BINkSLYG2VzT9GGEajhoiH/Untitled?node-id=0%3A1
Screen Shot 2022-06-09 at 4 33 26 PM

### General:
- [x] Make the reset step contextual (show it along with the help button at the button of the lower jaw after a few attempts) #46272
- [x] Add `Sign up to save progress` button above all elements in the lower jaw for un-auth #46401
- [x] Add the modal progress bar to the button of the lower jaw. #50167
- [x] Add a share button below the progress bar at the project completion. (Custom twitter cards) #49395
- [x] Confetti at the end of each project.
- [x] Add a quote to the lower jaw when tests pass. #50798
- [ ] Disable button and show loading bar on challenge submission
- [ ] Debounce the challenge submission from the epic not the component

### Mobile:
- [ ] Remove editor side by side display #46276
- [ ] Remove double scroll in the editor tab 
- [x] Reduce the area to the left of the line count to save space. #46309
- [x] Remove `Ctrl + Enter ` on CTA #46239

### Project:
- [ ] Minimize tests when they are not run.

### Needs further discussion:
- Is having multiple stacking options feasible? 
- Making tests challenge completion state more visible when editable region is not visible.
- For mobile, is the lower jaw redundant or the lower buttons row.
- What is the best way to nest tabs and simplify the navigation for Mobile.

### Issues 
- Toggling the editor tab clears the lower jaw state.
- The focus should be on the editable region of the editor when starting a challenge.

ref:
#45997
#46059

### PR DESCRIPTION
**Pull request by JordanMooree**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Clears a mobile task in #46178☂️ 

- [x]  Remove `Ctrl + Enter` on CTA

Produces following result:
image

Reverts CTA on screen sizes >= 768px:
image

### CODE REVIEW

**Comment by bbsmooth** [comment]
Personally, I think we should get rid of the "Ctrl + Enter" completely instead of trying to guess if the person is using a touch/mobile device. I think having a separate page/pop-up for the keyboard shortcuts would be a much better solution. We could provide a link to it on the main menu. This would give power keyboard users a single place to find this information and everyone else could just ignore it.

As far as this PR is concerned, there are touch screens that are wider than 768px and there are keyboard users who use screens that are less than 768px. Ya, it will work as intended in most situations, but again, why try to guess and settle for good enough when we could provide this information to everyone who wants it.

**Comment by raisedadead** [comment]
> Personally, I think we should get rid of the "Ctrl + Enter" completely instead of trying to guess if the person is using a touch/mobile device. I think having a separate page/pop-up for the keyboard shortcuts would be a much better solution. We could provide a link to it on the main menu. 

I totally agree with this.

Also, I think we can do one better by using a one-time product tour (https://introjs.com) to help new users familiarize themselves with the application. That could cut down a lot of the common support requests, we get on the forum.

Regardless if we do go that route it has to go in a separate discussion and PR.

**Comment by ojeytonwilliams** [comment]
> Also, I think we can do one better by using a one-time product tour (https://introjs.com/) to help new users familiarize themselves with the application. That could cut down a lot of the common support requests, we get on the forum.

I really don't like product tours and always skip them if I can.  I strongly recommend only using them as a last resort, because they're just another thing that's stopping a user from doing what they want. That is to say, getting started.

That's just my preference/intuition, though.  If we want to find out, we could A/B test and see if it helps or drives people away.

Anyways, back to the topic. I like the idea of taking Ctrl + Enter out of the button.  How about putting it in hover text instead?

**Comment by ahmadabdolsaheb** [comment]
We could agree on a number of challenges after which we could drop a lot of these repetitive copies. 
Also a tooltip on hover is always a good idea.

**Comment by ahmadabdolsaheb** [comment]
As @bbsmooth mentioned, the feature to display a modal that includes all of the shortcuts is being developed.

I would wait for him sign off on the tooltip's accessibility.

After that, here are a few things to consider:
1 - look into best a11y practices  for tooltips.
2 - the copy has to come from the translations file similar to `{t('buttons.ask-for-help')}`. Please add the necessary keys [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/2790362df800072e6c41ff355ba5af708336b4a5/client/i18n/locales/english/translations.json#L53). 
3 - avoid using react-bootstrap as we are removing it from the repository.

**Comment by raisedadead** [comment]
I strongly suggest that we take "new changes" in new PRs to scope PRs correctly.

**Comment by raisedadead** [comment]
I am proposing the changes in this PR (as seen visually in the screenshot in the OP) are good enough to review and merge this. All the other things that we all deliberated after that can some via their own PR(s).

**Comment by JordanMooree** [comment]
@ahmadabdolsaheb I've added tests, let me know if there's anything to add or remove

File: client/src/templates/Challenges/classic/lower-jaw.tsx [hunk 1]
```diff
@@ -175,6 +176,8 @@ const LowerJaw = ({
       );
   };
 
+  const showDesktopButton = window.innerWidth > MAX_MOBILE_WIDTH;
```
Comment (raditotev) [inline client/src/templates/Challenges/classic/lower-jaw.tsx:179]: Wouldn't `window. navigator.userAgent` be better to determine type of device instead of using viewport size?

Comment (ahmadabdolsaheb) [reply client/src/templates/Challenges/classic/lower-jaw.tsx:179]: I agree, we have been traditionally altering the layout for smaller screens regardless of the device to save up space. 
That being said, we are missing out on some optimization opportunities. 

This pr could go in as is and we could discuss this in a separate issue and research best practices.

**Review by ahmaxed — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
