### PR TITLE
fix(scripts): add hasEditableBoundaries property for workshop metadata

### LINKED ISSUE #62411: Missing data when using `pnpm run create-new-project`
At the moment using `pnpm run create-new-project` to create a workshop does not add `"hasEditableBoundaries": true` to the `freeCodeCamp/curriculum/structure/blocks/workshop-dashed-name.json` file creating this weird situation where the instructions are repeated in another window:

Image

So it would be nice to add that for workshops by default.

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #62411

Is this good enough? otherwise to make it fit the current schema it would need to be changed quite a lot as the template for the metadata seems to be used for at least labs too (unless I have misread the code)

or maybe that would be a good approach, but it would require more time. We have a limited number of challenge types we use, lab, workshop, lecture, review, quiz for coding, and the language curriculum will have its own limited number of challenge types, so maybe a template for each?

### CODE REVIEW

**Review by a2937 — COMMENTED** [review]
While that is a workable fix, is it possible to add the field directly onto the FullStack Step Meta in the `get-base-meta` file in the helpers directory? 

Roughly around line 42. 

(Needs to check if it's used elsewhere)

**Review by a2937 — APPROVED** [review]
I'm approving this because it certainly is possible that the same meta will be used for labs. 

For a future PR, I like the second option. More concentrated templates for different types of challenges; all indexable by the block type sounds like a good idea.

**Comment by majestic-owl448** [comment]
> add the field directly onto the FullStack Step Meta

yeah, it seems to be used for labs too, and those don't want the property, so until there are two separate templates for the two challenge types this looked like the quickest approach

File: tools/challenge-helper-scripts/create-project.ts [hunk 1]
```diff
@@ -185,6 +185,9 @@ async function createMetaJson(
     newMeta = getBaseMeta('FullStack');
     newMeta.blockType = blockType;
     newMeta.blockLayout = blockLayout;
+    if (blockType === 'workshop') {
+      newMeta.hasEditableBoundaries = true;
+    }
```
Comment (invasorMou) [inline tools/challenge-helper-scripts/create-project.ts]:
```suggestion
    if (blockType === BlockTypes.workshop) {
      newMeta.hasEditableBoundaries = true;
    }
```

There is an enum `BlockTypes` being used in other parts of this file, like line 105, seems like this enum has all the possibles values the blockType can have including 'workshop', I think is a better idea to compare against `BlockTypes.workshop` to keep consistency across the file

**Review by ojeytonwilliams — APPROVED** [review]
I think `hasEditableBoundaries` needs removing in favour of `blockType`, but this is a nice fix for the actual issue.

LGTM :+1:
