### PR TITLE
fix(a11y): hide spacer span

### LINKED ISSUE #48700: Spacer having a screen reading text while it's a styling SVG
**Describe the issue**
In this file https://github.com/Sboonny/freeCodeCamp/blob/29f0897a8b2ca3176e7452c3d4da8fcff9c94723/client/src/assets/icons/spacer.tsx#L10-L28

You will notice that there is a screen reader text for spacer icon, which I think it's unnecessary because the icon doesn't provide additional context, but it's there for styling

I am wondering was there a reason for adding the screen reader text and not hiding it?

I found it while checking FormGroup in the setting page. If there is a reason for it, should we hide the one in "recieve Quincy's emails" toggle button in the setting page?

image

### PR DESCRIPTION
**Pull request by Endless8**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48700

removed html text and added aria-hidden attribute to span element

### CODE REVIEW

File: client/src/assets/icons/spacer.tsx [hunk 1]
```diff
@@ -10,7 +10,7 @@ function Spacer(props: SpacerPropTypes): JSX.Element {
 
   return (
     <>
-      <span className='sr-only'>{t('icons.spacer')}</span>
+      <span className='sr-only' aria-hidden='true' />
       <svg
         className='tick'
```
Comment (Sboonny) [inline client/src/assets/icons/spacer.tsx:15]: Applying the suggestion may break the format, can you clean the `<></>` because it becomes useless without multiple children in the JSX.Component


```suggestion
      <svg
        className='tick'
        aria-hidden='true' 
```

Comment (bbsmooth) [reply client/src/assets/icons/spacer.tsx:15]: Yes, this is what needs to be done. There is no reason to have that `span` there at all.

Comment (Endless8) [reply client/src/assets/icons/spacer.tsx]: I clicked on "Commit suggestion" and Lint job failed, I did something wrong?

Comment (Sboonny) [reply client/src/assets/icons/spacer.tsx]: Nope, the code wasn't formatted for prettier. If you opened your gitpod/local environment and run `git pull` to make sure that the changes are in your environment, you can go to the changed file, and format it. (press `ctrl + a`, then `alt + shift + f`. It will format it for you 👍 ).

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Endless8, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future. Sorry for being vague in our description in the issue.

 Cheers & happy contributing!

**Review by moT01 — APPROVED** [review]
LGTM @Endless8 🎉 Thanks for contributing to freeCodeCamp 🎉
