### PR TITLE
fix(client): profile image size and alignment

### LINKED ISSUE #52083: Learn: profile icon isn't centered in nav
### Describe the Issue

The profile icon in the nav isn't centered within it's border.

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/
2. Sign in if you aren't
3. Look at profile icon at the top right - see that it isn't centered

### Expected behavior

It to be centered

### Screenshots

Screen Shot 2023-10-24 at 4 34 56 PM

^ See problem - the icon has too much space at the top

I opened the devtools and played around for a quick second. Removing the line-height added by bootstrap fixed the issue:

Screen Shot 2023-10-24 at 4 35 21 PM

### System

I only gave this a quick test on firefox.

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR 
- Fixes the profile image misalignment in the navbar (the initial attempt was #52087 but it introduced another bug and was reverted in #52253)
- Closes #52083

It's not possible to write tests for these UI changes. The only option we have right now is snapshot testing, but snapshots don't give me much confidence as they don't catch the CSS differences, and we usually would just update them along with code changes so they aren't that meaningful IMHO.

I'll be looking into the [visual regression testing feature](https://playwright.dev/docs/test-snapshots) that Playwright provides next and cover this case with it. But let me know if you think snapshots are needed.

## Screenshots

|  | Desktop | Mobile |
| --- | --- | ---|
| Default image | Screenshot 2023-11-07 at 18 57 04 | Screenshot 2023-11-07 at 18 57 18 |
| Custom image (https://cdn.freecodecamp.org/platform/universal/logo-512X512.png) | Screenshot 2023-11-07 at 18 13 33 | Screenshot 2023-11-07 at 18 14 00 |

### CODE REVIEW

File: tools/ui-components/src/image/image.tsx [hunk 1]
```diff
@@ -2,16 +2,16 @@ import React from 'react';
 import { ImageProps } from './image.types';
 
 export const Image = React.forwardRef<HTMLImageElement, ImageProps>(
-  ({ alt, src, responsive, ...props }, ref): JSX.Element => {
+  ({ alt, src, responsive, className, ...props }, ref): JSX.Element => {
```
Comment (raisedadead) [inline tools/ui-components/src/image/image.tsx:5]: Do we want to set "responsive" as the default? What happens when the component does not specify the `className` or the `reponsive` prop?

**Review by raisedadead — APPROVED** [review]

**Review by moT01 — APPROVED** [review]
LGTM @huyenltnguyen 🎉
