### PR TITLE
Error messages for invalid tokens from email links

### LINKED ISSUE #9195: Email verification link doesn't work in at least some cases
#### Issue Description
We are getting an alarming number of emails from campers who can't verify their emails. They get this error:

{"error":{"name":"Error","status":400,"message":"Invalid token: ["<token>","statusCode":400,"code":"INVALID_TOKEN"}}

### PR DESCRIPTION
**Pull request by raisedadead**
This commit, adds error messages for users hitting the confirm
endpoint with invalid, or expired tokens from emailed links.

Closes #9195

### CODE REVIEW

**Comment by raisedadead** [comment]
/to @QuincyLarson and @BerkeleyTrue : You may want to verify the error messages in this commit.
I'll test this thoroughly before confirming you guys for a merge.

File: common/models/user.js [hunk 1]
```diff
@@ -90,13 +90,58 @@ module.exports = function(User) {
   });
 
   debug('setting up user hooks');
+
+  User.beforeRemote('confirm', function(ctx, _, next) {
+
+    if (!ctx.req.query) {
+      ctx.res.redirect('/');
```
Comment (BerkeleyTrue) [inline common/models/user.js]: your missing a return statement here

File: common/models/user.js [hunk 2]
```diff
@@ -90,13 +90,58 @@ module.exports = function(User) {
...
+    const token = ctx.req.query.token;
+    const redirect = ctx.req.query.redirect;
+
+    User.findById(uid, (err, user) => {
+
+        if (err || !user) {
+          ctx.req.flash('error', {
+            msg: dedent`Oops, something went wrong, please try again later`
+          });
+          ctx.res.redirect('/');
```
Comment (BerkeleyTrue) [inline common/models/user.js]: missing return statement

File: common/models/user.js [hunk 3]
```diff
@@ -90,13 +90,58 @@ module.exports = function(User) {
...
+        }
+
+        if (!user.verificationToken && user.emailVerified) {
+          ctx.req.flash('info', {
+            msg: dedent`Looks like you have already verified your email.
+             Please login to continue.`
+          });
+          ctx.res.redirect(redirect);
```
Comment (BerkeleyTrue) [inline common/models/user.js]: missing return statement

File: common/models/user.js [hunk 4]
```diff
@@ -90,13 +90,58 @@ module.exports = function(User) {
...
+        }
+
+        if (user.verificationToken && user.verificationToken !== token) {
+          ctx.req.flash('info', {
+            msg: dedent`Looks like you have clicked an invalid link.
+             Please login and request a fresh one.`
+          });
+          ctx.res.redirect(redirect);
```
Comment (BerkeleyTrue) [inline common/models/user.js]: missing return statement

File: common/models/user.js [hunk 5]
```diff
@@ -90,13 +90,58 @@ module.exports = function(User) {
...
+        }
+
+    });
+
+    next();
+  });
+
   User.afterRemote('confirm', function(ctx) {
+    if (!ctx.req.query) {
+      ctx.res.redirect('/');
```
Comment (BerkeleyTrue) [inline common/models/user.js]: missing return statement

**Comment by Bouncey** [comment]
@BerkeleyTrue is this OK to merge?

File: common/models/user.js [hunk 6]
```diff
@@ -90,13 +90,57 @@ module.exports = function(User) {
   });
 
   debug('setting up user hooks');
+
+User.beforeRemote('confirm', function(ctx, _, next) {
```
Comment (BerkeleyTrue) [inline common/models/user.js]: Indenting is off here

**Comment by BerkeleyTrue** [comment]
@Bouncey Code looks good other than my comment. Where you able to QA?

**Comment by Bouncey** [comment]
@BerkeleyTrue No I couldn't reproduce.

**Comment by raisedadead** [comment]
Fixed the indentation, please test. 

Scenario is fairly simple. 
1. When a user receives a link to verify their email address, if they clicks on the emailed link a second time (after using it once), they were thrown an error.
2. This error while valid, didn't resolve gracefully into proper error messages notifying the user of the cause.
3. This has been hence rectified, for conditions like expired tokens/non-existent tokens.

**Comment by BerkeleyTrue** [comment]
@raisedadead Looks like it does not catch `if (!user.verificationToken && ~user.emailVerified)`

**Comment by BerkeleyTrue** [comment]
@raisedadead Nice work as always! 👍
