### PR TITLE
fix(client): empty space below codePane after resizing classic layout

### LINKED ISSUE #55931: Resizing editor/console in classic challenge breaks layout in step-based challenges
### Describe the bug
Changing the size of editor/console in the classic challenge, is reflected in the step-based layout, by adding empty space below the _code_ pane. This space cannot be resized in the step-based layout.

[image](https://github.com/user-attachments/assets/70de3ea8-ccfd-4fe7-b672-ed557f8fc768)

Resizing editor/console changes the `codePane` in the `challenge-layout` local storage. That value is also used in the step-based layout, but _code_ pane in that layout is not sharing vertical space with anything else.

### To Reproduce
1. Be logged in.
2. Go to classic challenge, ie. https://www.freecodecamp.org/learn/rosetta-code/rosetta-code-challenges/align-columns
3. Resize editor/console on the right.
4. Go to step-based challenge, ie. https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-45
5. Below the _code_ pane on the left there will be empty space.

### Expected behavior
Empty space not being added in the step-based layout when editor/console is resized in classic challenge.

### Additional context
Resizing editor/console in classic challenge is also a bit spotty. When mouse button is released, after clicking and dragging the divider, it will often _jump_ a bit higher or lower than the exact point where divider was released.

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55931

- - -
- `flex` attribute/value is added to `codePane` in a limited number of cases.

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
It might be useful to add a comment on the attribute usage condition as it is a pretty niche solution.

**Comment by gikf** [comment]
> It might be useful to add a comment on the attribute usage condition as it is a pretty niche solution.

What about extracting the `!isMultifileCertProject && !projectBasedChallenge` into variable ie. `hasResizableCodePane`?

**Comment by Sembauke** [comment]
Sounds good, one suggestion would be `hasVerticalResizableCodePane`.

**Review by ojeytonwilliams — COMMENTED** [review]
I'm a bit late to this, but could it be better to set the flex-basis to 100% instead? We always want the containers to be full, after all.

cc: @huyenltnguyen

**Comment by gikf** [comment]
> I'm a bit late to this, but could it be better to set the flex-basis to 100% instead? We always want the containers to be full, after all.

Do you mean something like this?
```js
flex={hasVerticalResizableCodePane ? codePane.flex : 1.0}
```

**Comment by ojeytonwilliams** [comment]
No, I was thinking we could specify both flex-grow and flex-basis. E.g. `flex: 0.5 100%` rather than `flex: 0.5`.

I'm not sure that's the way to go, but I thought I'd raise the idea.

File: client/src/templates/Challenges/classic/desktop-layout.tsx [hunk 1]
```diff
@@ -237,8 +239,8 @@ const DesktopLayout = (props: DesktopLayoutProps): JSX.Element => {
               orientation='horizontal'
             >
               <ReflexElement
-                flex={codePane.flex}
                 name='codePane'
+                {...(hasVerticalResizableCodePane && { flex: codePane.flex })}
```
Comment (gikf) [inline client/src/templates/Challenges/classic/desktop-layout.tsx:243]: @ojeytonwilliams what do you think?
```suggestion
                {...{style: { flexGrow: codePane.flex, flexBasis: '100%'}}}
```

- - -

Btw. This doesn't work:
```js
              <ReflexElement
                name='codePane'
                flex={codePane.flex}
                {...{style: { flexBasis: '100%'}}}
                {...reflexProps}
                {...resizeProps}
              >
```

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/classic/desktop-layout.tsx:243]: I did a little digging into the Reflex source and it maps the `flex` property onto `flex-grow`. It doesn't really expect us to mess around with the details.

On balance, I think your original solution is the way to go. Sorry for the distraction!

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

File: client/src/templates/Challenges/classic/desktop-layout.tsx (hunk 1 above)
Comment (gikf) [reply client/src/templates/Challenges/classic/desktop-layout.tsx:243]: No worries!
