### PR TITLE
Fix: Lang routes persist between sessions

### LINKED ISSUE #11627: Untranslated challenge links do not respect url lang
Language specific routes not correct for new sessions after selecting a different language.

If I select a language, the routing is all correct for that session.

If I start a new session, translated challenges render correctly (they are translated), but lang routes revert to `en` after first navigation.

anim

PR #11545 relies on this issue being resolved

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11627 

#### Description

Passed `[coldStorage]initialState.app.lang` to `useLangRoutes`

### CODE REVIEW

File: client/index.js [hunk 1]
```diff
@@ -42,7 +43,7 @@ window.__fcc__ = {};
 
 const serviceOptions = { xhrPath: '/services', context: { _csrf: csrfToken } };
 
-const history = useLangRoutes(createHistory)();
+const history = useLangRoutes(createHistory, primary)();
```
Comment (BerkeleyTrue) [inline client/index.js]: This state is already in the url. 

Can we add a closure to useLangRoutes and pull this information from the url instead of relying on the initialState?

**Comment by BerkeleyTrue** [comment]
Code LGTM. Will run through it after dinner.
