### PR TITLE
Make translated challenge titles searchable

### LINKED ISSUE #11828: Searching for translated challenge names not working
After setting my language to Spanish, if I search for the challenge `Búsqueda de perfiles` The map is empty, with no hint that my search returned no results.

With my language still set to Spanish, if I search for the challenge `Profile Lookup` I see the translated name (Búsqueda de perfiles) in the map.

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11828 

#### Description

Created a new `title` field for each `challenge` leaf in the mapUi.

Adjusted `applyFilterToMap` to search `title` field instead of `name`

Amended `/common/app/routes/challenge/utils.test.js` to fit

### CODE REVIEW

File: common/app/routes/challenges/utils.js [hunk 1]
```diff
@@ -282,6 +282,16 @@ export function filterComingSoonBetaFromEntities(
...
 }
 
+export function searchableChallengeTitles({ challenge: challengeMap } = {}) {
+  return Object.keys(challengeMap)
+    .map(dashedName => challengeMap[dashedName])
+    .reduce((accu, current) => ({
+        ...accu,
+        [current.dashedName]: current.title
+      })
+    , {});
```
Comment (BerkeleyTrue) [inline common/app/routes/challenges/utils.js]: Using spread hear is quite slow and creates tons of objects needlessly.

Since the accumulator does not exist outside of the reduce function it is a ok to mutate it here and speed up this process.

```js
       .reduce((accu, current) => {
          accu[current.dashedName] = current.title;
          return accu;
       }, {})
```

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Review by BerkeleyTrue — APPROVED** [review]
