### PR TITLE
fix(client): remove JS comments from user code for tests

### LINKED ISSUE #41448: Low priority: ignore comments when checking the code in the challenges
This is low priority and I'm not sure if it has been brought up, sorry if I'm doing this wrong.  On one of the challenges I had commented out the splice call but I still got an error that I should not use it.  I assume when the checks are being performed they are not skipping commented out lines.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/remove-elements-from-an-array-using-slice-instead-of-splice

**Tell us about your browser and operating system:**
* Browser Name: Edge
* Browser Version: Version 89.0.774.45
* Operating System: Windows

### PR DESCRIPTION
**Pull request by Dzheky**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41448

I am just learning the codebase, please let me know if I did something wrong or didn't do something right, I will make changes.

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Nice work @Dzheky this is exactly what we were looking for.

Now that you've done this, we can do two things.  Firstly, we don't need to expose `__helpers.removeJSComments` any more, since it's being applied during the build.  Secondly, we can remove `__helpers.removeJSComments` from the challenges.

Would you be interested in implementing these changes?  They make sense to be part of this PR.

**Comment by Dzheky** [comment]
> Nice work @Dzheky this is exactly what we were looking for.
> 
> Now that you've done this, we can do two things. Firstly, we don't need to expose `__helpers.removeJSComments` any more, since it's being applied during the build. Secondly, we can remove `__helpers.removeJSComments` from the challenges.
> 
> Would you be interested in implementing these changes? They make sense to be part of this PR.

Thank you! Sure I can look into it, I am not 100% sure what you are asking, but I will figure it out!

**Comment by ojeytonwilliams** [comment]
> I am not 100% sure what you are asking,

Ah, sorry about that, let me try and clarify.  Since you've applied `removeJSComments` in `build.js` there should be no need to call it in challenges.  That means we can export removeJSComments separately 
```js
export const removeJSComments = codeStr => {
```
and remove it from the `__helpers` by doing this
```js
const curriculumHelpers = {
  removeHtmlComments,
  removeCssComments,
  removeWhiteSpace
};
```

File: client/src/templates/Challenges/utils/build.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ import {
 import frameRunnerData from '../../../../../config/client/frame-runner.json';
 // eslint-disable-next-line import/no-unresolved
 import testEvaluatorData from '../../../../../config/client/test-evaluator.json';
+import curriculumHelpers from '../../../utils/curriculum-helpers';
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/build.js:16]:
```suggestion
import { removeJSComments } from '../../../utils/curriculum-helpers';
```
since we're talking about removing `removeJSComments` from the default export

File: client/src/templates/Challenges/utils/build.js [hunk 2]
```diff
@@ -164,16 +165,27 @@ export function buildJSChallenge({ files }, options) {
...
-        .join('\n'),
-      sources: buildSourceMap(files)
-    }));
+        .join('\n');
+      let sources = buildSourceMap(files);
+      if (options?.removeComments !== false) {
+        build = curriculumHelpers.removeJSComments(build);
+        sources = {
+          ...sources,
+          index: curriculumHelpers.removeJSComments(sources.index)
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/build.js:180]:
```suggestion
        build = curriculumHelpers.removeJSComments(build);
        sources = {
          ...sources,
          index: removeJSComments(sources.index)
```

Comment (Dzheky) [reply client/src/templates/Challenges/utils/build.js:180]: Ah I see, ok will do! Thank you for clarifying!

**Comment by Dzheky** [comment]
@ojeytonwilliams Hello, I have finished what you have requested.

**Review by ojeytonwilliams — DISMISSED** [review]
LGTM :+1: 

Thanks for sorting this out so quickly @Dzheky

@nhcarrigan since this affects espanol and chinese, do we need to do anything special?  Or can we just wait until the upload/download cycle is complete before deploying?

**Comment by raisedadead** [comment]
> since this affects espanol and chinese, do we need to do anything special?

I am of the opinion that we add the changes to the files for CI to pass as a one-off.

**Comment by ojeytonwilliams** [comment]
@Dzheky don't worry if the bot complains about changes to the espanol and chinese. It's not our usual workflow, but it's fine in this case.

**Comment by nhcarrigan** [comment]
> I am of the opinion that we add the changes to the files for CI to pass as a one-off.

Yep, this is a weird edge case where we'd want to ignore the `no-translate` check and merge anyway. That specific CI doesn't run on `push` or on our deployment branches, so there's no issue with merging 🙂

**Comment by Dzheky** [comment]
So is there anything I need to do? 😃

**Comment by ojeytonwilliams** [comment]
> So is there anything I need to do?

Could you add the `removeComments: false` frontmatter to the espanol and chinese files?  Once that's done the bot will complain, but the Localize tests should pass.  Then we'll give it a final review before merging.

File: curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code.md [hunk 3]
```diff
@@ -2,6 +2,7 @@
 id: bd7123c9c441eddfaeb4bdef
 title: Comment Your JavaScript Code
 challengeType: 1
+removeComments: false
```
Comment (nhcarrigan) [inline curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code.md:5]: I *believe* This should be the only change that needs to be mirrored on the Espanol and Chinese versions of the file.

**Comment by Dzheky** [comment]
@ojeytonwilliams, @nhcarrigan Thank you for review, I think now all the tests pass. Well except one

**Comment by nhcarrigan** [comment]
That's the one we expected to fail, so no worries there 🙂

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by Dzheky** [comment]
So can this be merged? 😄

**Comment by raisedadead** [comment]
> So can this be merged? 

Yes - when we get more approvals. Thanks for your patience with this. Meanwhile, you are welcome to work on other things if that interests you.

**Review by moT01 — APPROVED** [review]
LGTM @Dzheky 🎉 I looked over and tested this pretty good, I don't see any issues.

@nhcarrigan had a concern there that wasn't resolved. The non-english files have the `removeJsComments` function removed their tests. Shouldn't be a problem.

For future reference, it's best to try and give your branch a more descriptive name @Dzheky - see `#3` [here](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally) - no big deal

**Comment by moT01** [comment]
I'm just gonna merge this. Thanks for contributing to freeCodeCamp @Dzheky 🎉
