### PR TITLE
fix(ui-components): disabled button behavior

### LINKED ISSUE #45712: [UI Components] Disabled button should not have active styles
## To reproduce

The Button component in the UI component library is having active styles even when it is disabled.

Refer to: https://github.com/freeCodeCamp/freeCodeCamp/pull/45665#issuecomment-1101213249

## Expected behavior

Disabled Button should not have active styles.

## Screenshots

clickable

## Useful resources

- Component library contributing guide: https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library
- Button component code: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/ui-components/src/button/button.tsx

### PR DESCRIPTION
**Pull request by saltedTofu**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45712

Changed disabled button to not have active styles

### CODE REVIEW

File: tools/ui-components/src/button/button.tsx [hunk 1]
```diff
@@ -46,7 +46,11 @@ const computeClassNames = ({
         'bg-default-background-danger',
         'text-default-foreground-danger',
         ...(disabled
-          ? []
+          ? [
+            'active:before:bg-default-background-quaternary',
+            'active:before:opacity-0',
+            'focus:ring-0'
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:52]: Instead of overridding the background of the pseudo element, we can use `hidden` instead. It will set `display: none` to the pseudo element and remove the overlay entirely.

Also, we want disabled button to be focusable, so we should keep the focus ring to help let the user know where their focus is on.

```suggestion
            'active:before:hidden',
```

File: tools/ui-components/src/button/button.tsx [hunk 2]
```diff
@@ -120,7 +132,6 @@ export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
     const handleClick = useCallback(
       (event: React.MouseEvent<HTMLButtonElement>) => {
         const ariaDisabled = event.currentTarget.getAttribute('aria-disabled');
-
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:123]: Hope you don't mind keeping this empty line. I find the code a bit easier to read with it 🙂

Comment (saltedTofu) [reply tools/ui-components/src/button/button.tsx:123]: For sure! Do I need to edit anything in my commit to keep the empty line? (new to working with open-source).

File: tools/ui-components/src/button/button.tsx [hunk 3]
```diff
@@ -59,7 +61,11 @@ const computeClassNames = ({
         'bg-default-background-info',
         'text-default-foreground-info',
         ...(disabled
-          ? []
+          ? [
+            'active:before:bg-default-background-quaternary',
+            'active:before:opacity-0',
+            'focus:ring-0'
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:67]: We should apply the same rule as https://github.com/freeCodeCamp/freeCodeCamp/pull/45739#discussion_r857155977 to this.

```suggestion
            'active:before:hidden'
```

File: tools/ui-components/src/button/button.tsx [hunk 4]
```diff
@@ -73,7 +79,11 @@ const computeClassNames = ({
         'bg-default-background-quaternary',
         'text-default-foreground-secondary',
         ...(disabled
-          ? []
+          ? [
+            'active:before:bg-default-background-quaternary',
+            'active:before:opacity-0',
+            'focus:ring-0'
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:85]: Here as well

```suggestion
            'active:before:hidden'
```

File: tools/ui-components/src/button/button.tsx (hunk 2 above)
Comment (huyenltnguyen) [reply tools/ui-components/src/button/button.tsx:123]: GitHub doesn't allow suggestions on deleted lines, so you would need to add the line back locally, then commit and push the change.

Let me know if you need help with this.

Comment (saltedTofu) [reply tools/ui-components/src/button/button.tsx]: Just commited with the line added back in, is this right?

File: tools/ui-components/src/button/button.tsx [hunk 5]
```diff
@@ -59,7 +59,11 @@ const computeClassNames = ({
         'bg-default-background-info',
         'text-default-foreground-info',
         ...(disabled
-          ? []
+          ? [
+              'active:before:bg-default-background-quaternary',
+              'active:before:opacity-0',
+              'focus:ring-0'
+            ]
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:66]:
```suggestion
          ? ['active:before:hidden']
```

File: tools/ui-components/src/button/button.tsx [hunk 6]
```diff
@@ -73,7 +77,11 @@ const computeClassNames = ({
         'bg-default-background-quaternary',
         'text-default-foreground-secondary',
         ...(disabled
-          ? []
+          ? [
+              'active:before:bg-default-background-quaternary',
+              'active:before:opacity-0',
+              'focus:ring-0'
+            ]
```
Comment (huyenltnguyen) [inline tools/ui-components/src/button/button.tsx:84]:
```suggestion
          ? ['active:before:hidden']
```

**Review by huyenltnguyen — COMMENTED** [review]
Thanks for the update! We still need to apply the `active:before:hidden` class to a couple places.

File: tools/ui-components/src/button/button.tsx (hunk 2 above)
Comment (huyenltnguyen) [reply tools/ui-components/src/button/button.tsx]: Yup! The removal is reverted 👍

**Review by huyenltnguyen — APPROVED** [review]
LGTM 👍 

@saltedTofu Thank you for the help! 🙂

**Comment by ahmadabdolsaheb** [comment]
Thanks @saltedTofu 👍
