### PR TITLE
fix(api): add toLowerCase method to email

### LINKED ISSUE #38581: Convert email to lowercase when receiving from OAuth 2 Provider
The email string is received as is before a db query. This makes it for a rare bug, when OAuth 2 providers send it in the case the users chose to store it with them.

A mismatch can happen between emails: `Someone@example.com` and `somone@example.com`, etc, leading to failed login attempts.

We should convert the email received to lowercase to be safe (because that's how we store it in db).

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38581

### CODE REVIEW

File: api-server/common/models/User-Identity.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ export default function(UserIdent) {
     // get the email from the auth0 (its expected from social providers)
     const email =
       profile && profile.emails && profile.emails[0]
-        ? profile.emails[0].value
+        ? profile.emails[0].value.toLowerCase()
```
Comment (raisedadead) [inline api-server/common/models/User-Identity.js:46]: I should have clarified, this may not be guarenteed to be a string.

Comment (Sky020) [reply api-server/common/models/User-Identity.js:46]: So, if the value is there, it still may return as `undefined` or similar?

File: api-server/common/models/User-Identity.js [hunk 2]
```diff
@@ -41,10 +41,9 @@ export default function(UserIdent) {
       include: 'user'
     };
     // get the email from the auth0 (its expected from social providers)
-    const email =
-      profile && profile.emails && profile.emails[0]
-        ? profile.emails[0].value
-        : '';
+    let val = '' + profile.emails[0].value;
```
Comment (ojeytonwilliams) [inline api-server/common/models/User-Identity.js:44]: We still need to check the chain, `profile.emails[0].value` exists, as is currently done below for `email`. what we should do is piggy-back off that.

File: api-server/common/models/User-Identity.js [hunk 3]
```diff
@@ -41,10 +41,9 @@ export default function(UserIdent) {
...
+    val.toLowerCase();
```
Comment (ojeytonwilliams) [inline api-server/common/models/User-Identity.js:45]: We need to assign the output of `toLowerCase` to something.  What I recommend is to use `email`, which already checks that the value exists and use `email = email.toLowerCase()`.

It's probably worth checking that `typeof email === 'string'`, too, just err on the side of caution (even though it's probably a string or null).

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: api-server/common/models/User-Identity.js (hunk 3 above)
Comment (raisedadead) [reply api-server/common/models/User-Identity.js:45]: Hey @Sky020 looks like you used the snippet I shared as is. It was more of a pseudo code to give you an idea. I should have been more clear. 😅 

Oliver is correct here. You would need to essentially ensure that you are working with a sting and then making it lowercase before the db query.

Comment (Sky020) [reply api-server/common/models/User-Identity.js]: Right. Sorry about that. I guess I jumped the gun, and rushed too much without reviewing.

File: api-server/common/models/User-Identity.js [hunk 4]
```diff
@@ -43,7 +43,7 @@ export default function(UserIdent) {
     // get the email from the auth0 (its expected from social providers)
     const email =
       profile && profile.emails && profile.emails[0]
-        ? profile.emails[0].value
+        ? ('' + profile.emails[0].value).toLowerCase()
```
Comment (ojeytonwilliams) [inline api-server/common/models/User-Identity.js:46]: Trouble is, if the value is `null` then `email` ends up being the string `'null'` and I think it should be `''`.

Instead, I'd check if `profile.emails[0].value` exists and is a string.  If that's the case, then return the lower case version, otherwise just return the empty string.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: api-server/common/models/User-Identity.js (hunk 4 above)
Comment (Sky020) [reply api-server/common/models/User-Identity.js]: Right. I have tried to implement something encompassing enough.

**Review by ojeytonwilliams — COMMENTED** [review]
That's an elegant solution, I like it.  We'd need to add @babel/plugin-proposal-optional-chaining to the api-server to make that work.  

@raisedadead is that something we could use?  From a quick search around, it seems it's at 'Stage 4' and so will be part of the language sooner or later.

**Comment by raisedadead** [comment]
> is that something we could use?

Yes, sure.

**Comment by raisedadead** [comment]
Hi @Sky020 can you update/configure the dependencies as requested by Oliver.

**Comment by Sky020** [comment]
@raisedadead , sure. I will take a look at it. Is there anything specific I need to know about the config?

**Comment by ojeytonwilliams** [comment]
@Sky020 nothing special, no, you've done exactly what we need.

Some unit tests would be great, if you've got a moment.  I'd be happy to help out with that.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Sorry, I've found it returning the empty string when I logged in via Auth0, let me investigate a bit.

**Review by raisedadead — APPROVED** [review]
