### PR TITLE
fix: optionally keep source if setting file contents

### LINKED ISSUE #58741: Step 38 of cat photo app pass with no code
I was working on the step for a different reason, and found this weird behaviour:

- on the seed code the tests fail correctly
- if I remove all the code, the tests pass

I don't know if this is something that can be fixed, but I think it's at least worth investigating

Link: freecodecamp.org/learn/full-stack-developer/workshop-cat-photo-app/step-38

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
It's optional because setContent is used is code-storage-epic and I did not what to change its behaviour.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/58741

### CODE REVIEW

File: shared/utils/polyvinyl.ts [hunk 1]
```diff
@@ -103,16 +103,17 @@ function checkPoly(poly: ChallengeFile) {
...
-  poly: ChallengeFile
+  poly: ChallengeFile,
+  source?: string | null
 ): ChallengeFile {
   checkPoly(poly);
   return {
     ...poly,
     contents,
-    source: null
+    source: source ?? null
```
Comment (naomi-lgbt) [inline shared/utils/polyvinyl.ts:116]:
```suggestion
    source
```

We don't need nullish coalescing for a `string | null` value if the fallback is also `null`.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]

File: shared/utils/polyvinyl.ts (hunk 1 above)
Comment (ojeytonwilliams) [reply shared/utils/polyvinyl.ts:116]: Good point. Now that you mention it, we can get rid of the `null`s entirely.

**Review by naomi-lgbt — APPROVED** [review]

**Review by Sembauke — APPROVED** [review]
