### PR TITLE
fix(editor): Clear codemirror undo on new challenge

### LINKED ISSUE #16960: [Beta: CodeMirror] User can undo past the current challenge
#### Challenge Name

Any challenge with a code editor.

#### Issue Description

Steps to reproduce:
1. Complete a challenge.
2. Enter some code in the new challenge.
3. Keep undoing typing and your current code will be reverted to that of the previous challenge.

#### Browser Information

* Browser Name, Version: Chrome 65.0.3325.181
* Operating System: macOS 10.13.3
* Mobile, Desktop, or Tablet: desktop

#### Screenshot

freecodecamp beta - undo issue

### PR DESCRIPTION
**Pull request by love1024**
clear codemirror undo stack on new challenge

Closes #16960

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16960

### CODE REVIEW

File: common/app/routes/Challenges/views/classic/Editor.jsx [hunk 1]
```diff
@@ -120,11 +124,18 @@ export class Editor extends PureComponent {
     MouseTrap.unbind('e', 'keyup');
   }
 
+  componentDidUpdate(nextProps) {
+    if (nextProps.id !== this.props.id) {
+      this.refs.editor.getCodeMirror().doc.clearHistory();
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/classic/Editor.jsx]: Is this still required? 

My understanding is that if `react` is tracking a keyed component and the key changes, it is essentially like the previous keyed component is unmounted and and the new keyed component is mounted, therefore there would be no history to clear.

**Review by Bouncey — COMMENTED** [review]
Keying the Editor is a nice solution to the issue that was reported. Just a question on the method called in CDU

File: common/app/routes/Challenges/views/classic/Editor.jsx (hunk 1 above)
Comment (love1024) [reply common/app/routes/Challenges/views/classic/Editor.jsx]: Yes nice catch because of key there is no need to clear history. thanks for input, i will updated the PR with latest.

File: common/app/routes/Challenges/views/classic/Editor.jsx [hunk 2]
```diff
@@ -136,8 +141,9 @@ export class Editor extends PureComponent {
         >
         <NoSSR onSSR={ <CodeMirrorSkeleton content={ content } /> }>
           <Codemirror
-            onChange={ change => classicEditorUpdated(fileKey, change) }
-            options={ this.createOptions({ executeChallenge, mode, cmTheme }) }
+            key={id}
+            onChange={change => classicEditorUpdated(fileKey, change)}
```
Comment (Bouncey) [inline common/app/routes/Challenges/views/classic/Editor.jsx]: Sorry for the nit, for the coding style of this code base, we space our props like so
```jsx
<Component
  prop1={ foo }
  prop2={ 'bar' }
  prop3={ 42 }
  prop4={ () => console.log('clicky') }
/>
```

**Review by Bouncey — CHANGES_REQUESTED** [review]

File: common/app/routes/Challenges/views/classic/Editor.jsx (hunk 2 above)
Comment (love1024) [reply common/app/routes/Challenges/views/classic/Editor.jsx]: sure i will update the PR.

**Review by Bouncey — APPROVED** [review]
Thanks @love1024
