### PR TITLE
fix(ui-components): button component styles

### LINKED ISSUE #52115: [UI Components] Styling issues in Button component
### Describe the Issue

I found the following issues in the `ui-components`'s Button component:

| Issue | Screenshot |
| --- | --- |
| Button has incorrect border style | Screenshot 2023-10-26 at 11 48 43 |
| Button link (a link that looks exactly like a button) doesn't have a border | Screenshot 2023-10-26 at 11 46 38 |
| Download link is not rendered correctly on Storybook | Screenshot 2023-10-26 at 11 44 53 |
| Disabled button has a focus outline on click | Screenshot 2023-10-26 at 14 33 31 |

### Affected Page

Currently only on Storybook

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR:
- Fixes styling issues in the Button component  (resolves #52115)
- ~Exports the Button component from `ui-components` for consumption~ (hold off, see https://github.com/freeCodeCamp/freeCodeCamp/pull/52116#discussion_r1374460588)

Note: It's probably easier to review the PR with Hide Whitespace Changes enabled.

## Steps to test

- Apply the change in #52094
- Run:
  ```cmd
  cd tools/ui-components
  pnpm run storybook
  ```   
- Check the Button stories

## Screenshots

| Issue | Before | After |
| --- | --- | --- |
| Button has incorrect border style | Screenshot 2023-10-26 at 11 48 43 | Screenshot 2023-10-26 at 14 41 44 |
| Button link (a link that looks exactly like a button) doesn't have a border | Screenshot 2023-10-26 at 11 46 38 | Screenshot 2023-10-26 at 14 43 44 |
| Download link is not rendered correctly on Storybook | Screenshot 2023-10-26 at 11 44 53 | Screenshot 2023-10-26 at 14 44 22 |
| Disabled button has a focus outline on click | Screenshot 2023-10-26 at 14 33 31 | Screenshot 2023-10-26 at 14 45 03 |

### CODE REVIEW

File: tools/ui-components/src/button/button.tsx [hunk 1]
```diff
@@ -123,7 +131,7 @@ const StylessButton = React.forwardRef<React.ElementRef<'button'>, ButtonProps>(
         onClick={handleClick}
         aria-disabled={disabled}
         ref={ref}
-        type={type ?? 'button'}
```
[the remark this answers is not in the document]
Comment (Sembauke) [reply tools/ui-components/src/button/button.tsx:126]: @huyenltnguyen, at the moment I think the button `type` is still overwritten by line 116 as "button" is the default value here for the parameter.

File: tools/ui-components/src/index.ts [hunk 2]
```diff
@@ -1,6 +1,6 @@
 // Use this file as the entry point for component export
-// export { Button } from './button';
 export { Alert, type AlertProps } from './alert';
+export { Button } from './button';
```
Comment (ahmaxed) [inline tools/ui-components/src/index.ts:3]:
```suggestion
// export { Button } from './button';
```
This should not matter, but we ended up with some unpredictable outcomes. I would prefer adding this during the component swap.

**Review by ahmaxed — APPROVED** [review]

File: tools/ui-components/src/index.ts (hunk 2 above)
Comment (ahmaxed) [reply tools/ui-components/src/index.ts:3]: Also, the related tests are not passing locally either. So they need to be updated accordingly.

**Review by Sembauke — APPROVED** [review]
