### PR TITLE
fix(client): Remove all trailing slashes from user submitted urls

### LINKED ISSUE #36067: APIs and Microservices Projects - Solutions links are appended with "/"
**Describe the bug**

- Submitting the solution link as "https://xyz.com/" produces an error.
- Submitting "https://xyz.com" does not.

Whenever we submit a solution link "https://xyz.com/" it is appended with "/_api/" so resultant solution gives "Not Found/Timeout error" and the same link submitted without "/" like "https://xyz.com" gives solution as accepted.

**To Reproduce**
1. Go to [Challenge Link](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/)
2. Click on 'solution input box'
3. Enter "https://freecodecamp-practices.herokuapp.com"
4. The solution gets accepted.
5. Enter "https://freecodecamp-practices.herokuapp.com/"
6. See error

**Expected behavior**
This should be tackled as Chrome appends "/" by default to any domain URL you copy, so people who would copy URL from search bars will get URLs appended with "/" hence producing wrong results.

**[Challenge Git Link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/managing-packages-with-npm/how-to-use-package.json-the-core-of-any-node.js-project-or-npm-package.english.md)** 
This file shows the testString is directly appended with "/_api" without checking if the input URL contains "/" at the end or not.

**Screenshots**
Bug

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Google Chrome
 - Version 73.0.3683.75

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

As discussed in #36067 valid solutions can be rejected because they have a trailing slash.  Almost all challenge tests that get user submitted URLs append `/some/path` to them. If the user's server doesn't know how to deal with URLs like `http://example.com//some/path` they will fail.  This just strips any trailing slashes to avoid this.

Closes #36067

### CODE REVIEW

File: client/src/templates/Challenges/utils/frame.js [hunk 1]
```diff
@@ -103,8 +103,11 @@ const initTestFrame = frameReady => ctx => {
     // default for classic challenges
     // should not be used for modern
     const code = sources && 'index' in sources ? sources['index'] : '';
-    // provide the file name and get the original source
-    const getUserInput = fileName => toString(sources[fileName]);
+    const getUserInput = fileName => {
+      return fileName === 'url'
```
Comment (ValeraS) [inline client/src/templates/Challenges/utils/frame.js]: IMO, this is not the right place for such things. It may be better to do this while storing these values ​​in the store.

**Review by ValeraS — CHANGES_REQUESTED** [review]

File: client/src/templates/Challenges/utils/frame.js (hunk 1 above)
Comment (ojeytonwilliams) [reply client/src/templates/Challenges/utils/frame.js]: In principle, yes, but isn't simple as `redux-form` updates the store as the user types.  If you remove slashes before storing a url, the user can never type something like example.com/about because they get stuck at example.com.

I can see two options.  Normalize in the selector or normalize in `handleSubmit`.

Doing it via the selector is trivial, but does mean the store will have trailing slashes.

Doing it in `handleSubmit` is a bit messy. since you'd need to do something similar to `ProjectForm`.  Add an action like `updateBackendForm` and use that to change the form's store before executing the challenge.

Do you think it's worth adding the extra complexity or would normalizing the selector be okay?

Comment (ValeraS) [reply client/src/templates/Challenges/utils/frame.js]: > Doing it in handleSubmit is a bit messy. since you'd need to do something similar to ProjectForm. Add an action like updateBackendForm and use that to change the form's store before executing the challenge.

I think this solution is ok. But without "change the form's store before executing the challenge". I propose to add to the `store` a `backendFormValues`, update them onSubmit and get these values in `backendFormValuesSelector`.

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/utils/frame.js]: That seems to be working out okay.  My latest commit reverts the original changes and does everything via `submit`.

**Review by ValeraS — APPROVED** [review]

**Review by raisedadead — APPROVED** [review]
