### PR TITLE
fix(curriculum): Reworded Challenge Editor

### LINKED ISSUE #47328: challenge-editor step tools off by one error
The tool "Insert step" says to write the nth step after which the new step will be added.
image

But if I write 16, it creates a new step 16, not 17.
If I want a new step after 16, I have to write 17.

### PR DESCRIPTION
**Pull request by hanswang123456**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47328

### CODE REVIEW

File: tools/challenge-editor/client/src/components/tools/Tools.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const Tools = () => {
       <CreateEmptySteps {...{ superblock, block }} />
       <h2>Insert Step</h2>
       <p>
-        This tool inserts a new step after the <code>nth</code> step.
+        This tool inserts a step as the <code>nth</code> step.
```
Comment (ieahleen) [inline tools/challenge-editor/client/src/components/tools/Tools.tsx:30]:
```suggestion
        This tool inserts a new step as the <code>nth</code> step.
```
I think "new" here worked, didn't it?

**Review by ojeytonwilliams — APPROVED** [review]
Thanks, @hanswang123456, these instructions are nice and clear. This LGTM :+1:

**Review by majestic-owl448 — APPROVED** [review]
image

both the editor and the docs seem approrpiately updated :+1:
