### PR TITLE
fix(i18n): add i18next keys for ShowProjectLinks

### LINKED ISSUE #41155: Add i18n keys to ShowProjectLinks component
This [ShowProjectLinks component](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/client-only-routes/ShowProjectLinks.js#L162) is mostly untranslated. Keys should be added to [the JSON files](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json) and used in the component so it can be translated. There's some [docs that may be helpful here](https://contribute.freecodecamp.org/#/how-to-translate-the-website).

Screen Shot 2021-02-17 at 11 46 47 AM

### PR DESCRIPTION
**Pull request by errmayank**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41155 

* The `translation.json` file for Chinese and Spanish uses English values for now.
* I've used the project title as a key in `translations.json`, _certification => project => title => 'Project Title'_ to translate project titles let me know if there's a better way to do this.
* In `ShowProjectLinks.js` I've used the `t` function to translate simple texts and for more complex (nested) cases I've used the `<Trans />` component.

### CODE REVIEW

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 1]
```diff
@@ -142,7 +150,12 @@ const ShowProjectLinks = props => {
       ({ link, title, id }) => (
         <li key={id}>
           <Link to={link} className='project-link'>
-            {title}
+            <Trans
+              i18nKey={`certification.project.title.${title}`}
+              defaults={title}
+            >
+              placeholder
+            </Trans>
```
Comment (errmayank) [inline client/src/client-only-routes/ShowProjectLinks.js:158]: For some reason bracket notation was not working for dynamic title in `i18nKey`, so I went with the dot notation.

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 2]
```diff
@@ -132,7 +135,12 @@ const ShowProjectLinks = props => {
               rel='noopener noreferrer'
               target='_blank'
             >
-              {cert.title}
+              <Trans
+                i18nKey={`certification.project.title.${cert.title}`}
+                defaults={cert.title}
+              >
+                placeholder
+              </Trans>
```
Comment (errmayank) [inline client/src/client-only-routes/ShowProjectLinks.js:143]: For some reason bracket notation was not working for dynamic project title keys in `i18nKey`, so I went with the dot notation.

Comment (ShaunSHamilton) [reply client/src/client-only-routes/ShowProjectLinks.js:143]: It seems most of these `Trans` components can be changed to using the `t` function?

Comment (moT01) [reply client/src/client-only-routes/ShowProjectLinks.js:143]: A quick glance looks like only the footnote would need to use `Trans` I think. It works either way - the documentation recommends to use the `t` when you can.

**Comment by moT01** [comment]
I believe these title are already translated in the challenge files - probably be pretty tough to pull them from there though.

I guess they should get translated automatically by crowdin I think, since the strings will match what has already been translated. Just thinking out loud here.

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 2 above)
Comment (errmayank) [reply client/src/client-only-routes/ShowProjectLinks.js:143]: @ShaunSHamilton @moT01 for this case in particular I went with the `Trans` component because since the project title is dynamic I thought it would be safer to have `defaults` (in case the key is not found in `translations.json`) so that we can fall back to the original/untranslated project title. With the `t` function I guess I'd have to use ternary operator to make it work like this?

It's your call I can swap `Trans` component with the `t` function if you want except in the footnote as you said.

**Comment by ojeytonwilliams** [comment]
> I believe these title are already translated in the challenge files - probably be pretty tough to pull them from there though.

That's definitely how it should be done.  Then there would be no need to use `Trans` for the titles as they'd already be translated.  That said, it's not trivial, so it may take a while to implement.

@RandellDawson how much extra work are we generating by temporarily changing `translations.json`?

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 2 above)
Comment (ojeytonwilliams) [reply client/src/client-only-routes/ShowProjectLinks.js:143]: How about ``t(`certification.project.title.${cert.title}`, cert.title)``, if the issue is defaults?

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 1 above)
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:158]:
```suggestion
            {t(`certification.project.title.${title}`,title)}
```
Same principle as above.

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 3]
```diff
@@ -158,9 +171,16 @@ const ShowProjectLinks = props => {
...
+      <Trans
+        user={name}
+        i18nKey={
+          certName === 'Legacy Full Stack'
+            ? 'certification.project.heading-legacy-full-stack'
+            : 'certification.project.heading'
+        }
+      >
+        {{ user: name }}
+      </Trans>
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:183]:
```suggestion
      {t(
        certName === 'Legacy Full Stack'
          ? 'certification.project.heading-legacy-full-stack'
          : 'certification.project.heading',
        { user: name }
      )}
```
Since it's just a string we can use `t` here, as Tom said.

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 4]
```diff
@@ -173,23 +193,22 @@ const ShowProjectLinks = props => {
...
-        report this to our team
-      </a>
-      .
+      <Trans i18nKey='certification.project.footnote'>
+        <a
+          href='https://www.freecodecamp.org/news/academic-honesty-policy/'
+          target='_blank'
+          rel='noreferrer'
+        >
+          placeholder
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:202]:
```suggestion
          academic honesty policy
```
As I understand it, this is the default value, so we should fallback to the English

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 5]
```diff
@@ -173,23 +193,22 @@ const ShowProjectLinks = props => {
...
+        </a>
+        <a
+          href={`/user/${username}/report-user`}
+          target='_blank'
+          rel='noreferrer'
+        >
+          placeholder
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:209]:
```suggestion
          report this to our team
```
Same principle as the previous placeholder.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @errmayank nice work on this PR.  I have a few suggestions on how it could be simplified slightly:

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 2 above)
Comment (errmayank) [reply client/src/client-only-routes/ShowProjectLinks.js:143]: Cool, I didn't know about this.

**Comment by errmayank** [comment]
@ojeytonwilliams Thanks for the help! I've made the necessary changes.

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 6]
```diff
@@ -173,23 +179,22 @@ const ShowProjectLinks = props => {
...
-      , please{' '}
-      <a
-        href={`/user/${username}/report-user`}
-        target='_blank'
-        rel='noreferrer'
-      >
-        report this to our team
-      </a>
-      .
+      <Trans i18nKey='certification.project.footnote'>
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:182]:
```suggestion
      <Trans i18nKey='certification.project.footnote'>
        If you suspect that any of these projects violate the{' '}
```
To provide the default.

File: client/i18n/locales/english/translations.json [hunk 7]
```diff
@@ -483,6 +483,83 @@
...
     "verify": "Verify this certification at {{certURL}}",
     "issued": "Issued",
-    "fulltext": "<0>This certifies that</0> <1>{{user}}</1> <2>has successfully completed the freeCodeCamp.org</2> <3>{{title}}</3> <4>Developer Certification, representing approximately {{time}} hours of coursework.</4>"
+    "fulltext": "<0>This certifies that</0> <1>{{user}}</1> <2>has successfully completed the freeCodeCamp.org</2> <3>{{title}}</3> <4>Developer Certification, representing approximately {{time}} hours of coursework.</4>",
+    "project": {
+      "heading-legacy-full-stack": "As part of this Legacy Full Stack certification, {{user}} completed the following certifications:",
+      "heading": "As part of this certification, {{user}} built the following projects and got all automated test suites to pass:",
+      "solution": "solution",
+      "source": "source",
+      "footnote": "If you suspect that any of these projects violate the <0>academic honesty policy</0>, please <1>report this to our team</1>.",
```
Comment (ojeytonwilliams) [inline client/i18n/locales/english/translations.json:492]:
```suggestion
      "footnote": "If you suspect that any of these projects violate the <1>academic honesty policy</1>, please <3>report this to our team.</3>",
```
The tag number generation is a bit odd, but these work for me locally.

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 8]
```diff
@@ -173,23 +179,22 @@ const ShowProjectLinks = props => {
...
+          rel='noreferrer'
+        >
+          academic honesty policy
+        </a>
+        <a
+          href={`/user/${username}/report-user`}
+          target='_blank'
+          rel='noreferrer'
+        >
+          report this to our team
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:195]:
```suggestion
          report this to our team.
```
Final nitpick

File: client/src/client-only-routes/ShowProjectLinks.js [hunk 9]
```diff
@@ -173,23 +179,22 @@ const ShowProjectLinks = props => {
...
-      .
+      <Trans i18nKey='certification.project.footnote'>
+        <a
+          href='https://www.freecodecamp.org/news/academic-honesty-policy/'
+          target='_blank'
+          rel='noreferrer'
+        >
+          academic honesty policy
+        </a>
+        <a
```
Comment (ojeytonwilliams) [inline client/src/client-only-routes/ShowProjectLinks.js:190]:
```suggestion
        </a>
        , please{' '}
        <a
```
Default again.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey @errmayank thanks again for your hard work on this. 

As well as the suggestions below, could you revert the changes to `/chinese/translations.json` and `/espanol/translations.json`? We just changed our approach so we default to English https://github.com/freeCodeCamp/freeCodeCamp/pull/41246 which means we're better off leaving those files alone and relying on the defaults.

**Comment by errmayank** [comment]
@ojeytonwilliams cool! just to make sure, I should keep `/english/translations.json` as it is right now with project titles right?

File: client/i18n/locales/english/translations.json (hunk 7 above)
Comment (errmayank) [reply client/i18n/locales/english/translations.json:492]: These were working for me before as well when I tested it locally but sure I'll make this change :)

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 8 above)
Comment (errmayank) [reply client/src/client-only-routes/ShowProjectLinks.js:195]: I've added the period after the closing `a` tag if that's okay because that's how it was before and in the `translations.json` 😛
```json
"footnote": "If you suspect that any of these projects violate the <0>academic honesty policy</0>, please <1>report this to our team</1>."
```

```js
    rel='noreferrer'
  >
    report this to our team
  </a>
  .
</Trans>
```

File: client/i18n/locales/english/translations.json (hunk 7 above)
Comment (errmayank) [reply client/i18n/locales/english/translations.json:492]: @ojeytonwilliams These were working for me before as well when I tested it locally, should I make this change?

File: client/src/client-only-routes/ShowProjectLinks.js (hunk 6 above)
Comment (errmayank) [reply client/src/client-only-routes/ShowProjectLinks.js:182]: Weird but after adding this to provide default value react-i18next does not pick up the nested values and renders nothing in place of the `a` tags

Screenshot from 2021-02-26 01-11-04

Screenshot from 2021-02-26 01-10-42

Comment (errmayank) [reply client/src/client-only-routes/ShowProjectLinks.js:182]: Weird but after adding this to provide default value react-i18next renders nothing in place of the `a` tags

Screenshot from 2021-02-26 01-11-04

Screenshot from 2021-02-26 01-10-42

**Comment by errmayank** [comment]
@ojeytonwilliams Weird but after adding default values to the `Trans` component react-i18next renders nothing in place of the `a` tags

Screenshot from 2021-02-26 01-11-04

Screenshot from 2021-02-26 01-10-42

**Comment by errmayank** [comment]
@ojeytonwilliams Weird but after adding default values to the `Trans` component as you suggested react-i18next renders duplicate values in place of the `a` tags like this

Screenshot from 2021-02-26 01-11-04

Screenshot from 2021-02-26 01-10-42

**Comment by errmayank** [comment]
@ojeytonwilliams weird but after changing to footnote to what you suggested and adding those default values, the text does not render properly

Screenshot from 2021-02-26 01-55-12

**Comment by errmayank** [comment]
Here's how I was able to make this work by using fragments

```json
"footnote": "If you suspect that any of these projects violate the <1>academic honesty policy</1>, please <3>report this to our team</3>."
```

```js
<Trans i18nKey='certification.project.footnote'>
  <>If you suspect that any of these projects violate the </>
  <a
    href='https://www.freecodecamp.org/news/academic-honesty-policy/'
    target='_blank'
    rel='noreferrer'
  >
    academic honesty policy
  </a>
  <>, please </>
  <a
    href={`/user/${username}/report-user`}
    target='_blank'
    rel='noreferrer'
  >
    report this to our team
  </a>
  <>.</>
</Trans>
```

**Comment by ojeytonwilliams** [comment]
> cool! just to make sure, I should keep `/english/translations.json` as it is right now with project titles right?

Yes, that's exactly right, thanks.

> Here's how I was able to make this work by using fragments

Nice job getting that to work, but we can get away without using fragments here.  The trick is to find the correct numbers for the translation string and that's explained [here](https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string).  Long story short: we have to look at the `children` of the `<Trans>` component to find those numbers.

**Comment by ojeytonwilliams** [comment]
I've updated my suggestion - if that doesn't work for you, just let me know and I'll make 100% it works locally and push a commit!

**Comment by moT01** [comment]
Random component from the landing page:

Screen Shot 2021-02-25 at 6 28 27 PM

You can use the react dev tools to see the children - as it states in the linked docs. Nice to get a visualization some times.

**Review by CyberFlameGO — APPROVED** [review]

**Review by CyberFlameGO — APPROVED** [review]

**Review by CyberFlameGO — DISMISSED** [review]

**Comment by errmayank** [comment]
@ojeytonwilliams great! the updated replacement tags that you suggested is working, I've pushed my changes.

**Comment by errmayank** [comment]
The Lint Source Files test failed due to missing keys in chinese and espanol `translations.json`

**Comment by RandellDawson** [comment]
@ojeytonwilliams I thought we had changed it so we no longer have to add the non-English keys.  Instead, the fallback was English and then when the English source file gets uploaded to Crowdin gets uploaded, the file would get the English version at first until translated/approved.

**Review by ojeytonwilliams — DISMISSED** [review]
@RandellDawson so did I, but it looks like we just agreed that that was the plan.

@errmayank thanks again for bearing with us on this.  As far as I'm concerned this PR is done, so I'll take care of the validation problem myself and rebase this PR once that's complete.

**Comment by RandellDawson** [comment]
@raisedadead Can you confirm that we still want to have to add changes to the non-English files for `translations.json`?  I thought we were going to stick with using English as the fallback for any missing keys, then once Crowdin downloads the translations, the translations for the key values would be used.

**Comment by nhcarrigan** [comment]
English is currently set to be the fallback value - if we choose to go this direction, I can disable the linting specifically for the `intro.json` and `translation.json` files.

**Comment by raisedadead** [comment]
Yes - @nhcarrigan you can go ahead and remove the linting. Maybe we can downgrade that to a warning or something just as an FYI, but it should not throw.

**Comment by errmayank** [comment]
I guess instead of `throw new Error()` in [schema-validation.js#L135](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/schema-validation.js#L135) we could just do a `console.warn()`?

**Comment by ojeytonwilliams** [comment]
GitHub actions are currently down, so we may need to restart them once that is resolved.

**Comment by nhcarrigan** [comment]
Looks to be resolved now, according to their status page.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@errmayank  Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝
