### PR TITLE
fix(auth): Add verification route for email

### LINKED ISSUE #17120: Social auth should lead to email update, and exit.
Make sure the social authentication leads to an email confirmation page and there's no way to get past that without first verifying their email address.

### LINKED ISSUE #17213: req.clearCookie on signout

### PR DESCRIPTION
**Pull request by raisedadead**
Closes  #17213
Closes #17120

### CODE REVIEW

File: server/boot/authentication.js [hunk 1]
```diff
@@ -38,9 +38,33 @@ module.exports = function enableAuthentication(app) {
...
+        throw wrapHandledError(
+          new Error('could not destroy session'),
+          {
+            type: 'info',
+            message: 'Oops, something is not right.',
+            redirectTo: '/'
+          }
+        );
+      }
+      res.clearCookie('jwt_access_token');
```
Comment (Bouncey) [inline server/boot/authentication.js]: > Web browsers and other compliant clients will only clear the cookie if the given options is identical to those given to res.cookie(), excluding expires and maxAge.

[Express docs](http://expressjs.com/en/4x/api.html#res.clearCookie)

File: server/boot/authentication.js [hunk 2]
```diff
@@ -38,9 +38,33 @@ module.exports = function enableAuthentication(app) {
...
+    ifNoUserRedirectHome,
+    (req, res) => res.render('account/update-email', {
+      title: 'Update your email'
+    })
+  );
+
   router.get('/signout', (req, res) => {
     req.logout();
-    res.redirect('/');
+    req.session.destroy( (err) => {
```
Comment (Bouncey) [inline server/boot/authentication.js]: I think we should be removing all `AccessToken` documents related to the users id also

File: server/boot/user.js [hunk 3]
```diff
@@ -119,6 +119,10 @@ module.exports = function(app) {
       if (err) { return next(err); }
       req.logout();
       req.flash('success', 'You have successfully deleted your account.');
+      res.clearCookie('jwt_access_token');
```
Comment (Bouncey) [inline server/boot/user.js]: As note above

File: server/views/account/update-email.jade [hunk 4]
```diff
@@ -0,0 +1,57 @@
+extends ../layout
```
Comment (Bouncey) [inline server/views/account/update-email.jade]: We already have an `update-email` page [on beta](https://beta.freecodecamp.org/settings/update-email), Could this be used?

Comment (raisedadead) [reply server/views/account/update-email.jade]: That's what I tried first. If you try to hit `/settings` or `/settings/` pages from express redirect, the errors notifications are messed up. Instead of the flash, I get react notifications. And those are made generic 'Oops....' messages.

Also, I believe there are more than one for that matter.

I'll push a commit just to show what I mean.

Comment (Bouncey) [reply server/views/account/update-email.jade]: Are you getting any errors back?

Comment (raisedadead) [reply server/views/account/update-email.jade]: On the jade page, nope. I think the API endpoint was too customised for the react page. I have no clue what was the thought then. Anyways.. am okay with using the react page as long as we can figure out.. the reason.

Let me know what you think.. I am running out of ideas. I am around to pair.

File: server/boot/authentication.js (hunk 2 above)
Comment (raisedadead) [reply server/boot/authentication.js]: I would prefer that to be done on the mongodb side, using indexes.

Comment (raisedadead) [reply server/boot/authentication.js]: That's because a search call can be expensive. And we want to avoid that. A user can be logged in from multiple devices and multiple browsers. Looking for which session to invalidate, express side it yet another call to the DB that I think we should avoid.

The bad thing is the DB bloats up. But even that is manageable now, and with indexes they should be optimised?

What do you think?

File: server/middlewares/email-not-verified-notice.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
+import dedent from 'dedent';
+
+const ALLOWED_METHODS = ['GET'];
+const EXCLUDED_PATHS = [
+  '/api/flyers/findOne',
+  '/signout',
+  '/update-email',
+  '/passwordless-change'
```
Comment (Bouncey) [inline server/middlewares/email-not-verified-notice.js]: Please add `/external/services/user` to the excluded paths, else Learn cannot redirect unverified users correctly

**Review by Bouncey — CHANGES_REQUESTED** [review]

**Comment by raisedadead** [comment]
I am finding it weird that in the success case, the message is an empty object.

**Comment by raisedadead** [comment]
Just one more thing to check here would be the doesExist to avoid the conflict with preexisting emails.

**Comment by raisedadead** [comment]
Okay.. can you give this one more go? I think I have handled the cases. I can merge in my other PR here as well if you prefer?

File: common/models/user.js [hunk 6]
```diff
@@ -652,17 +657,18 @@ module.exports = function(User) {
...
-            emailVerifyTTL: new Date()
-          };
-        return this.update$(update)
-          .do(() => Object.assign(this, update))
-          .flatMap(() => this.requestAuthEmail(false, newEmail));
+      .flatMap(()=>{
+        return Observable.forkJoin(
+          this.update$(updateConfig),
+          this.requestAuthEmail(false, newEmail),
+          (user, message) => ({ user, message })
```
Comment (Bouncey) [inline common/models/user.js]: Seeing as we are not using the `user`, we can just skip over it, Then we are just returning the message string. so we can refactor this to not even need the `map`. We also need to update `this` at the same time, I 'think' this is some weird loopback 'in-memory' thing where we can update the db, but if we want to use the updates any time soon, we need to update `this` also.

```js
return Observable.forkJoin(
  this.update$(updateConfig),
  this.requestAuthEmail(false, newEmail),
  (_, message) => message
)
.do(() => {
  Object.assign(this, updateConfig);
});
```

File: server/boot/settings.js [hunk 7]
```diff
@@ -41,7 +41,7 @@ export default function settingsController(app) {
     const { user, body: { email } } = req;
     return user.requestUpdateEmail(email)
       .subscribe(
-        message => res.json({ message }),
+        (message) => res.json({ message: message }),
```
Comment (Bouncey) [inline server/boot/settings.js]: This change is not required

**Review by Bouncey — CHANGES_REQUESTED** [review]
The sign in link from the email redirects to a challenge on successful sign in. Can this be changed to `/` please. Many thanks

**Comment by raisedadead** [comment]
Okay, this is ready for a review. I could not reproduce the redirect issue that you pointed earlier. Lets check it in QA.

**Comment by Bouncey** [comment]
`/boot/authentication.js -> getPasswordlessAuth`

```js
// at this point token has been validated and destroyed
// update user and log them in
.map(user => user.loginByRequest(req, res))
.do(() => {
  let redirectTo = '/';

  if (
    req.session &&
    req.session.returnTo
  ) {
    redirectTo = req.session.returnTo;
  }

  req.flash(
    'success',
    'Success! You have signed in to your account. Happy Coding!'
  );

  return res.redirect(redirectTo);
})
```

I think the idea is to always send them to `www`. At the minute I get redirected to learn, when a come back manually to `www`, I get the success flash. This doesn't make sense any more, it could be days after signing in that I see the flash.

**Review by Bouncey — APPROVED** [review]
