### PR TITLE
Fix: replace all GoMix with Glitch

### LINKED ISSUE #14015: [beta] Replace GoMix with Glitch
Recently, GoMix was renamed to Glitch. The "old" URLs are not working anymore, and this breaks some challenges, like [this one](https://medium.com/glitch/welcome-to-glitch-fe161d0fc39b#.suxl68eol). We should change all the appearances of "Gomix" to "Glitch" and fix all the broken links. It looks like in most cases the users are redirected to the right URL (glitch.com), but not always (e.g. the first link in the NPM introduction).

---

You can find more information about this name change [in this article](https://medium.com/glitch/welcome-to-glitch-fe161d0fc39b#.suxl68eol).

I'm aware of #13095 but I think this is a different problem.

### PR DESCRIPTION
**Pull request by zixu-zhao**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Replace all GoMix with Glitch as required.

Closes #14015

### CODE REVIEW

File: client/rechallenge/throwers.js [hunk 1]
```diff
@@ -49,13 +49,13 @@ const throwForJsHtml = {
         }
       }
     }, {
-      name: 'gomix in code',
-      description: 'Code with the URL gomix.me ' +
+      name: 'glitch in code',
+      description: 'Code with the URL glitch.me ' +
```
Comment (dhcodes) [inline client/rechallenge/throwers.js]: @ZZhaoTireless Could you change these to check for either `glitch.com` or `glitch.me`? I think the former is much more likely but the latter still redirects so it might as well be both.

File: client/rechallenge/throwers.js [hunk 2]
```diff
@@ -49,13 +49,13 @@ const throwForJsHtml = {
...
         'should not be allowed to run',
-      detectGomixInCode: /gomix\.me/gi,
-      thrower: function checkForGomix({ contents }) {
-        if (contents.match(this.detectGomixInCode)) {
-          throw new Error('Gomix.me should not be in the code');
+      detectGlitchInCode: /glitch\.me/gi,
```
Comment (dhcodes) [inline client/rechallenge/throwers.js]: Same here.

File: client/rechallenge/throwers.js (hunk 1 above)
Comment (ZZhaoTireless) [inline client/rechallenge/throwers.js]: Sure, will do that.

**Comment by ZZhaoTireless** [comment]
@dhcodes Hi, I updated my code to support check for either `glitch.com` or `glitch.me`.

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @ZZhaoTireless !

**Comment by raisedadead** [comment]
@dhcodes thanks for the review, please merge if you are OK with the changes.

**Comment by dhcodes** [comment]
@raisedadead testing as you spoke. don't rush me ;)

**Comment by dhcodes** [comment]
@ZZhaoTireless looks good to me. Thanks for making these changes. 🌮 🎉 💯

**Comment by ZZhaoTireless** [comment]
Thanks for reviewing my code!

**Comment by QuincyLarson** [comment]
@ZZhaoTireless Awesome - thanks for fixing this! @dhcodes and @raisedadead thanks for QA'ing!
