### PR TITLE
Fix closing backticks indentation on bug report

### LINKED ISSUE #12838: [beta] Bug reporting issue
When you use the "Bug" button on a challenge, in a lot of cases, the closing backticks are indented, which causes them to be displayed as code. This is particularly annoying when there is content (especially images) beneath the code in the bug report, as it then also displays as code.

This does not seem to happen consistently for all challenges, but it seems to be happening for a large amount of them. Out of 5 randomly picked challenges, only one did not have this problem.

### PR DESCRIPTION
**Pull request by systimotic**
#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12838

#### Description
As described in the issue, the closing backticks for a codeblock are indented, which makes them display as code.
It appears that there's an issue with dedent. I tried adding newlines before it both as lines that were empty in the editor and as `\n`, but it did not help.
I switched the code from dedent to good old string concatenation, which works fine.

### CODE REVIEW

**Comment by raisedadead** [comment]
@systimotic you just beat me into this... damn you are fast!

**Comment by Greenheart** [comment]
@systimotic Nice work! :blush:

Template strings and `dedent` are a clean solution, but since this works - why not stick to this method? :ok_hand:

**Comment by systimotic** [comment]
@raisedadead I kind of already knew the solution when I reported it five hours ago, and had planned to do it now 😛 It was very fast, yeah, but that's not always the case for me 🙂

@Greenheart Thanks! Yeah, that was my thinking as well 👍

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @systimotic

File: common/app/routes/challenges/redux/bug-saga.js [hunk 1]
```diff
@@ -12,13 +10,11 @@ function filesToMarkdown(files = {}) {
...
     const fileType = file.ext;
-    return fileString + dedent`
-      \`\`\`${fileType}
-      ${fileName}
-      ${file.contents}
-      \`\`\`
-      \n
-    `;
+    return fileString +
+      '\`\`\`' + fileType + '\n' +
```
Comment (BerkeleyTrue) [inline common/app/routes/challenges/redux/bug-saga.js]: Operators should end the line and the next addition should come on a new line

```js
return foo +
  'bar' +
  baz;
```

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/routes/challenges/redux/bug-saga.js (hunk 1 above)
Comment (systimotic) [inline common/app/routes/challenges/redux/bug-saga.js]: @BerkeleyTrue 👍 I was trying to make it look like it did with dedent, but I'm OK with that as well. I updated the PR.

**Comment by raisedadead** [comment]
:shipit:

**Review by Greenheart — APPROVED** [review]
Let's launch it! :rocket:
