### PR TITLE
fix(client): allow ipv6 urls for localhost

### LINKED ISSUE #54037: URL validator should account for ipv6
https://github.com/freeCodeCamp/freeCodeCamp/blob/fcf6bfae6aab263dfe5c1b0a7b40c7580c97c51e/client/src/components/formHelpers/form-validators.tsx#L11

URL validator does not allow `http://[::1]:3000` to be submitted, despite passing the tests. This *is* a valid local URL. We may want to account for this, as well as options like `127.0.0.1:3000`

### PR DESCRIPTION
**Pull request by shootermv**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54037

### CODE REVIEW

File: client/src/components/formHelpers/form-validators.tsx [hunk 1]
```diff
@@ -8,8 +8,8 @@ const editorRegex =
   /repl\.?it(\.com)?\/(@|join\/)|glitch\.com\/edit\/#!|codesandbox\.io\/s\/|github\.com/;
 const fCCRegex =
   /codepen\.io\/freecodecamp|freecodecamp\.rocks|github\.com\/freecodecamp|\.freecodecamp\.org/i;
-const localhostRegex = /localhost:/;
-const httpRegex = /http(?!s|([^s]+?localhost))/;
+const localhostRegex = /localhost:|[::1]:/;
+const httpRegex = /http(?!s|([^s]+?(localhost|[::1])))/;
```
Comment (ShaunSHamilton) [inline client/src/components/formHelpers/form-validators.tsx:12]: This does not work for `http://127.0.0.1:3000`. We should use a library for this instead of coming up with the regex ourselves - there are too many valid formats.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]

File: client/src/components/formHelpers/form-validators.tsx (hunk 1 above)
Comment (ShaunSHamilton) [reply client/src/components/formHelpers/form-validators.tsx]: The only change that needs to be made is instead of a custom regex for `localhostRegex`, we should use a library to get match against `ipv4` and `ipv6`.

The `http` logic needs to remain. In your image, you misspelt `localhost`. So, the address is treated as a public address. We cannot accept `http` addresses (unless they are for the tests, and are local), because they will be displayed on certifications/profiles, and redirect to insecure websites.

**Comment by ShaunSHamilton** [comment]
Thanks for your work on this @shootermv . I have just pushed the necessary changes to close the issue.

**Review by raisedadead — CHANGES_REQUESTED** [review]
nit: rename the `ip.ts` to something like `form-ip-utils.ts`

File: client/src/components/formHelpers/form-validators.test.ts [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+  const nonEditorAddresses = [
+    'example.com',
+    'http://example.com',
+    'https://example.com',
+    'http://repl.it',
+    'http://glitch.com',
+    'https://repl.it/home'
+  ];
+
+  editorAddresses.forEach(address => {
```
Comment (shootermv) [inline client/src/components/formHelpers/form-validators.test.ts:31]: this is exactly period im learning to do unit tests,
very good to see it in action!
may i ask: what to use `toBeNull` better than`toBeTruthy`?
Thanks in advance

Comment (ShaunSHamilton) [reply client/src/components/formHelpers/form-validators.test.ts:31]: > may i ask: what to use toBeNull better thantoBeTruthy?

1) The error (assertion) messages are better - the error explicitly mentions the expectation for the value to be `null`
2) The API does explicitly return `null`
3) Any change to the API where it accidentally returns `undefined` or `false` is now caught by the tests

**Review by raisedadead — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
