### PR TITLE
Fix Half Way Club Gitter Link

### LINKED ISSUE #3934: broken link
when I finish all challenges, the flash info is `Once you have completed all of our challenges, you should join our<a target="\"_blank\"" href="\"//gitter.im/freecodecamp/HalfWayClub\"">Half Way Club</a>
and start getting ready for our nonprofit projects.`. click the `a` element will not open HalfWayClub of gitter
I'm using firefox 41.0.1 on windows, I think there is something wrong with https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/server/boot/challenge.js#L234-L235

### PR DESCRIPTION
**Pull request by arialaurel**
Closes #3934

### CODE REVIEW

File: server/boot/challenge.js [hunk 1]
```diff
@@ -233,7 +233,7 @@ module.exports = function(app) {
             req.flash('info', {
               msg: dedent`
                 Once you have completed all of our challenges, you should
-                join our <a href=\"//gitter.im/freecodecamp/HalfWayClub\"
+                join our <a href=\"https://gitter.im/freecodecamp/HalfWayClub\"
                 target=\"_blank\">Half Way Club</a> and start getting
```
Comment (BerkeleyTrue) [inline server/boot/challenge.js]: @ltegman The actually issue with this is the escaping of double quotes. Since this is the new template string syntax, the double quotes end up having two brackets, which destroys the link. The https can stay but the escapes need to be removed

**Comment by ltegman** [comment]
Good to know about template strings! I clearly haven't played around with that part of ES6 enough. Should be fixed now.

**Comment by BerkeleyTrue** [comment]
:+1:
