### PR TITLE
fix(learn): Standardazie frontend, backend, full-stack

### LINKED ISSUE #62247: Standardize use of "Front End" VS "Frontend" in /learn and cert names
### Describe the Issue

Currently one cert is called "Front End Libraries" and another "Backend JavaScript".

Note that "Backend" has always been more popular, and "Front End" has been more popular but that this has changed in the past year or so to "Frontend" being more popular.

This said, I think "Front End" and "Back End" are much easier to read. And we don't want to have to change the URLs and references to Front End in our URLs. So I propose we just go with Back End and Front End for these cert names and for our /learn UI.

### Affected Page

https://www.freecodecamp.org/learn/full-stack-developer

### Steps to Reproduce

Visit the page and scroll down. You'll see that "front end" and "backend" don't jive with one another.

### Expected behavior

We should update the cert names in /learn's UI and on certs to use this pattern. This can be a one-time change. Note that 

### Screenshots

Image

Image

### System

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by majestic-owl448**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/62247

### CODE REVIEW

File: packages/shared/src/config/certification-settings.ts
Comment (ojeytonwilliams) [inline packages/shared/src/config/certification-settings.ts]:
```suggestion
  [Certification.LegacyFullStack]: 'Legacy Full-Stack',
```

File: packages/shared/src/config/certification-settings.ts [hunk 1]
```diff
@@ -291,10 +291,10 @@ export const certToTitleMap: Record<Certification, string> = {
   // Upcoming certifications
   [Certification.RespWebDesignV9]: 'Responsive Web Design',
   [Certification.JsV9]: 'JavaScript',
-  [Certification.FrontEndDevLibsV9]: 'Front End Development Libraries',
+  [Certification.FrontEndDevLibsV9]: 'Frontend Development Libraries',
   [Certification.PythonV9]: 'Python',
   [Certification.RelationalDbV9]: 'Relational Database',
-  [Certification.BackEndDevApisV9]: 'Back End Development and APIs',
+  [Certification.BackEndDevApisV9]: 'Backend Development and APIs',
   [Certification.FullStackDeveloperV9]: 'Full Stack Developer',
```
Comment (ojeytonwilliams) [inline packages/shared/src/config/certification-settings.ts]:
```suggestion
  [Certification.FullStackDeveloperV9]: 'Full-Stack Developer',
```

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Here's a couple more.

**Review by ojeytonwilliams — APPROVED** [review]
I know it's still draft, but it's already looking good 👍
