### PR TITLE
fix(client): unify client donations methods

### LINKED ISSUE #38052: Lag on donate page may cause a 2nd duplicate donation
A small percentage of donors accidentally create a second duplicate donation (when they intend to only create one monthly-recurring donation).

I suspect this may be due to some sort of input lag when they are on a less reliable connection. We should create some sort of debounce to ensure people don't accidentally create two donations instead of one.

### LINKED ISSUE #39507: Donation prompt modal recurs during same session after donating
Steps to reproduce:

1. Create a new account on /learn
2. Complete a section. The Trophy modal will show up. 

Python_for_Everybody___freeCodeCamp_org

3. Enter credit card information into the modal and successfully become a donor.
4. During the same session, continue completing challenges. The donation prompt will still show up even though isDonor is now true.

Front_End_Libraries_Projects_-_Build_a_JavaScript_Calculator___Learn___freeCodeCamp_org

This would be a frustrating experience for someone who had just donated, and may cause them to cancel their donation afterward. So we should fix this ASAP.

Note that I noticed I had an ad blocker active when this happened. I also did not refresh my browser. I do not know whether either of these played a part in this.

### PR DESCRIPTION
**Pull request by ahmaxed**
This Pr does the followings:

-  merges MinimalDonateForm into DonateForm
- unifies donation state and move it redux
- debounces stripe calls
- make the IsDonating consistant between db and redux store.
- moves ajax logic to sagas
- resolves issues with GA actions

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38052
Closes #39507

ref #38373

### CODE REVIEW

File: client/src/components/Donation/DonateForm.js [hunk 1]
```diff
@@ -335,9 +428,45 @@ class DonateForm extends Component {
       </Row>
     );
   }
+
+  render() {
+    const {
+      donationFormState: { processing, success, error },
+      isMinimalForm
+    } = this.props;
+    if (success || error) {
```
Comment (ojeytonwilliams) [inline client/src/components/Donation/DonateForm.js:437]:
```suggestion
    if (success || error || processing) {
```
Can't we simplify things by including processing here?

File: client/src/redux/donation-saga.js [hunk 2]
```diff
@@ -22,6 +37,40 @@ function* showDonateModalSaga() {
...
+    yield call(postChargeStripe, payload);
+    yield put(postChargeStripeComplete());
+  } catch (error) {
+    const data =
+      error.response && error.response.data
+        ? error.response.data
+        : {
+            error: defaultDonationError
+          };
+    yield put(postChargeStripeError(data.error));
```
Comment (ojeytonwilliams) [inline client/src/redux/donation-saga.js:66]:
```suggestion
    const err =
      error.response && error.response.data
        ? error.response.data.error
        : defaultDonationError
    yield put(postChargeStripeError(err));
```
I think this is a little cleaner.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
One thing that confused me was why `addDonation` appeared on the PayPal button, but not elsewhere.  Could we change that to `addPayPalDonation` instead?

Aside from that quibble, this looks solid.  The only other thing we need are tests, but it'll probably take some doing before we can get them working properly in Cypress.  With that in mind, I'm fine with this going in without them, but we shouldn't delay indefinitely.

File: client/src/components/Donation/DonateForm.js (hunk 1 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Donation/DonateForm.js:437]: That would remove the payment provider element from the DOM and payment will be interrupted. 
Therefore I still keep the elements in the DOM but hide them and show the processing message.

**Comment by ahmadabdolsaheb** [comment]
> One thing that confused me was why addDonation appeared on the PayPal button, but not elsewhere. Could we change that to addPayPalDonation instead?

we could change it to that. it is just the name of the endpoint that it hits.

File: client/src/components/Donation/DonateForm.js (hunk 1 above)
Comment (ojeytonwilliams) [reply client/src/components/Donation/DonateForm.js:437]: Understood, thanks for explaining.

File: client/src/components/Donation/DonateForm.js [hunk 3]
```diff
@@ -140,10 +189,16 @@ class DonateForm extends Component {
     this.setState({ donationAmount });
   }
 
-  async handleStripeCheckoutRedirect(e) {
-    const { stripe } = this.props;
+  async handleStripeCheckoutRedirect(e, paymentMethod) {
+    const { stripe } = this.state;
```
Comment (ojeytonwilliams) [inline client/src/components/Donation/DonateForm.js:193]: What happens if stripe has not loaded?  Can we disable the buttons until that has happened?

File: client/src/components/Donation/DonateForm.js [hunk 4]
```diff
@@ -305,25 +361,62 @@ class DonateForm extends Component {
...
+          <Spacer />
+          <StripeProvider stripe={stripe}>
+            <Elements>
+              <DonateFormChildViewForHOC
+                defaultTheme={defaultTheme}
+                donationAmount={donationAmount}
+                donationDuration={donationDuration}
+                getDonationButtonLabel={() =>
+                  `Confirm your donation of ${donationPlan}`
+                }
```
Comment (ojeytonwilliams) [inline client/src/components/Donation/DonateForm.js:407]:
```suggestion
                donationButtonLabel={`Confirm your donation of ${donationPlan}`}
```
Can we make this change and remove the other `getDonationButtonLabel` function?  I think `donationPlan` covers everything now.

**Comment by ojeytonwilliams** [comment]
> we could change it to that. it is just the name of the endpoint that it hits.

No, it's fine. On reflection I like your way better.  It'll become more obvious once there are more donation methods.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hey Ahmad, I've pushed a nitpicky rename (if you think it's less clear, let me know) and had a few, very minor, observations:

File: client/src/components/Donation/DonateForm.js (hunk 3 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Donation/DonateForm.js:193]: We handle that logic in componentDidMount. We could ultimately display a loader similar to paypal until stripe loads.

Comment (ahmadabdolsaheb) [reply client/src/components/Donation/DonateForm.js:192]: There is another pr coming up that combines all of those stripe buttons into one. We can address this issue there.

File: client/src/components/Donation/DonateForm.js (hunk 4 above)
Comment (ahmadabdolsaheb) [reply client/src/components/Donation/DonateForm.js]: Thanks for bringing that into my attention. I would rather keep it around since we will be doing some A/B testing in near future: however, I removed the  donationPlan and replaced it with getDonation label to make it more concise.

File: client/src/components/Donation/DonateForm.js (hunk 3 above)
Comment (ojeytonwilliams) [reply client/src/components/Donation/DonateForm.js:192]: Okay, makes sense.  If the button isn't around to be clicked before Stripe has loaded, this seems fine.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Thanks for your patience during the reviewing.

@raisedadead do you want to sanity check this before it goes in?

**Review by raisedadead — APPROVED** [review]
