### PR TITLE
fix(client): adjust cert heading

### LINKED ISSUE #65368: Certificate Page - no project links
### Describe the Issue

After receiving a certificate for one of the new courses in beta, below the certificate it says:
"As part of this certification, ___ built the following projects and got all automated test suites to pass:"
However, instead of listing the projects with links to them, it only has a row for the "Python Certification Exam", and the link column for it says "No solution to display". 

Image

Image

### Affected Page

https://www.freecodecamp.org/certification/i-m-day/python-v9

### Steps to Reproduce

1. Go to show certificate page for one of the new (v9) courses

### Expected behavior

the certificates for the legacy courses show the correct result

Image

### Screenshots

_No response_

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Firefox]
- Version: [don't know]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by garyeung**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #65368

### CODE REVIEW

File: client/src/client-only-routes/show-project-links.tsx [hunk 1]
```diff
@@ -161,7 +164,10 @@ const ShowProjectLinks = (props: ShowProjectLinksProps): JSX.Element => {
   const getCertHeading = (cert: Certification) => {
     if (cert === Certification.LegacyFullStack) {
       return 'certification.project.heading-legacy-full-stack';
-    } else if (cert === Certification.FoundationalCSharp) {
+    } else if (
+      cert === Certification.FoundationalCSharp ||
```
Comment (huyenltnguyen) [inline client/src/client-only-routes/show-project-links.tsx]: `currentCertifications` already contains `FoundationalCSharp` so this condition is not needed.

**Comment by aydenhailey78-hub** [comment]
Thanks

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for taking the time to contribute.

This LGTM 👍 

---

One improvement I would make in a future PR is refactoring the test. As it stands, the e2e test is acting as a snapshot, but with worse behaviour. Either, this should be replaced with a snapshot test. Or, the certifications should be imported from `certification-settings` instead of hard-coded.
