### PR TITLE
fix(api): update backend project validation

### LINKED ISSUE #53690: [api]: adjust challenge validation to require source code link
Add changes done here to new API: https://github.com/freeCodeCamp/freeCodeCamp/pull/53512/files

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/53690

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by Sembauke — APPROVED** [review]

File: api/src/schemas.ts [hunk 1]
```diff
@@ -526,8 +526,8 @@ export const schemas = {
     body: Type.Object({
       id: Type.String({ format: 'objectid', maxLength: 24, minLength: 24 }),
       challengeType: Type.Optional(Type.Number()),
-      solution: Type.String({ format: 'url', maxLength: 1024 }),
-      // TODO(Post-MVP): require format: 'url' for githubLink
+      // Solution does not need to be a valid URL unless it is NOT `backEndProject`
```
Comment (Sembauke) [inline api/src/schemas.ts:529]:
```suggestion
      // The solution must be a valid URL, unless it is a `backEndProject`.
```

Comment (Sembauke) [reply api/src/schemas.ts:529]: This comment confused me a lot.
