### PR TITLE
fix: separate certs from interview prep on landing page

### LINKED ISSUE #37340: Landing page shows interview prep as a cert
On the home page, it lists the `coding interview prep` section as a certification....

Screen Shot 2019-10-16 at 9 06 48 AM

Maybe remove that since there's no cert for it?

### PR DESCRIPTION
**Pull request by moT01**
This is what I came up with, let me know if we want some different....

Screen Shot 2019-10-22 at 12 42 31 PM

Closes #37340

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

File: client/src/components/landing/index.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ const BigCallToAction = () => (
 
 export const Landing = ({ edges }) => {
   const superBlocks = uniq(edges.map(element => element.node.superBlock));
+  const interviewPrep = superBlocks.splice(6, 1);
```
Comment (raisedadead) [inline client/src/components/landing/index.js]: We should probably check that this one is going to come out to be Interview Prep. I think if we added a certification in future, this will differ?

A simple way to know would be adding a simple test and checking the DOM renders the Interview prep. superblock title.

In future any change would break the test drawing attention to the necessary change here.

**Review by raisedadead — CHANGES_REQUESTED** [review]

**Comment by raisedadead** [comment]
Nevermind, I think I am not going to be nit picky on this for now.

File: client/src/components/landing/index.js (hunk 1 above)
Comment (moT01) [reply client/src/components/landing/index.js]: Yea, there should probably be something more there. Even if it's just a check in the code.

Comment (raisedadead) [reply client/src/components/landing/index.js]: I think adding some tests should be fine, so that this is not missed in future.
