### PR TITLE
fix(api): handle invalid picture URLs for '/update-my-about'

### LINKED ISSUE #50399: Add validation to /update-my-about

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #50399

### CODE REVIEW

**Comment by Sembauke** [comment]
Don't exactly know how much validation we want as we already check a ton on the client side. This might be a bit redundant.

**Comment by raisedadead** [comment]
> Don't exactly know how much validation we want as we already check a ton on the client side.

We can not ever trust any client side code. All schema validations should also be enforced on the API.

File: api/src/routes/protected/settings.ts [hunk 1]
```diff
@@ -485,14 +485,20 @@ ${isLinkSentWithinLimitTTL}`
       const logger = fastify.log.child({ req, res: reply });
       const hasProtocol = isPictureWithProtocol(req.body.picture);
 
+      if (!hasProtocol && req.body.picture) {
+        logger.warn(`Invalid picture URL: ${req.body.picture}`);
+        void reply.code(400);
+        return { message: 'flash.wrong-updating', type: 'danger' } as const;
+      }
```
Comment (raisedadead) [inline api/src/routes/protected/settings.ts]: Can we expand this to more robust URL checking? Do we use `zod` or similar these days?

**Review by raisedadead — COMMENTED** [review]
.

File: api/src/routes/protected/settings.ts (hunk 1 above)
Comment (Sembauke) [reply api/src/routes/protected/settings.ts]: Sure I can expand on this more, we use Typebox for this. Do we want to send a request to the given URL as well? We do this on the client-side, but as you said, that can't be relied upon.

Comment (raisedadead) [reply api/src/routes/protected/settings.ts]: Sending an outgoing request is not needed. I think a basic check like the shape of the URL including if it has an extension, protocol etc should be enough. We do not care if the URL is a 404.

**Comment by Sembauke** [comment]
@ojeytonwilliams Any idea why this is happening? Can we not test extensions with TypeBox?
 ```bash
 FAIL  src/schema.test.ts > Schemas do not use obviously dangerous validation > schema updateMyAbout > body is secure
AssertionError: expected false to be truthy
```

File: api/src/routes/protected/settings.ts (hunk 1 above)
Comment (Sembauke) [reply api/src/routes/protected/settings.ts]: We already test for protocol, see `isPictureWithProtocol`. I'll see what I can do with adding a check for extensions.

**Comment by Sembauke** [comment]
@raisedadead Let me know if this is what you had in mind.

**Comment by raisedadead** [comment]
Looks good, the only additional thing that I would do id take the helpers and then make a singular (a function that wraps over all) check instead of all these conditionals. Its easier to read and follow that way.

**Comment by Sembauke** [comment]
Okay, I think I know what you mean. Care to take another look at it?

**Review by raisedadead — APPROVED** [review]
Code LGTM. Should expand the tests and we can merge.

**Comment by Sembauke** [comment]
Alright, I have added some extra tests to confirm everything works correctly.
