### PR TITLE
fix: remove flash saying JS is disabled

### LINKED ISSUE #16867: Beta: preview panel covered by flash message
When going through the challenges, the `JavaScript is disabled. Execute code to enable` flash message constantly shows up in the preview panel covering the preview itself. There's no way to close it - it doesn't fade out. It's really annoying, and it's pretty much on every challenge that shows the preview.
<hr>

screenshot from 2018-03-10 09-45-07
<hr>

#### Potential solutions:
Add the ability to close the message.
Fade it out after a second or so.
Push the preview content down.

<hr>
It looks like something related to this was recently worked on #16804

### PR DESCRIPTION
**Pull request by tchaffee**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes #16867

#### Description
Removed the 'JavaScript is disabled....' flash message from the preview pane. See the issue for more details.

### CODE REVIEW

File: common/app/routes/Challenges/Preview.jsx [hunk 1]
```diff
@@ -1,41 +1,17 @@
...
-import { isJSEnabledSelector } from './redux';
-import {Alert} from 'react-bootstrap';
-
 
 const mainId = 'fcc-main-frame';
 
-const mapStateToProps = state => ({
-  isJSEnabled: isJSEnabledSelector(state)
-});
+const mapStateToProps = null;
```
Comment (Bouncey) [inline common/app/routes/Challenges/Preview.jsx]: If we are not using state or actions in this component, we can make it stateless and not have it connect to redux. We could go even further and it a stateless function too.

**Review by Bouncey — CHANGES_REQUESTED** [review]
There is some css that can be removed also. The class `js-alert-wrapper` is only used here.

**Comment by tchaffee** [comment]
@Bouncey Thanks for the review and I made the changes you suggested. If there's anything else, let me know and I should be able to get to this today.

**Review by Bouncey — APPROVED** [review]
