### PR TITLE
Fix/danger zone warning

### LINKED ISSUE #16755: [beta] make warning in delete progress / account more common to non-native speakers
image

> Tread carefully, changes made in this area are permanent. They cannot be undone.

This message needs to be more common to non-native speakers. Something on lines of 

> Please be careful. Changes made in the section cannot be reversed.

### PR DESCRIPTION
**Pull request by Brybro**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16755

#### Description
Improved the danger zone warning so it is better understood by all users.

### CODE REVIEW

File: common/app/routes/Settings/components/DangerZone.jsx [hunk 1]
```diff
@@ -47,6 +47,11 @@ class DangerZone extends PureComponent {
   }
 
   render() {
+    const centerText = {
```
Comment (raisedadead) [inline common/app/routes/Settings/components/DangerZone.jsx]: Remove this styling, this should be rather handled in a dedicated styles file, for the component group. On that note, for this particular message this is an unneeded change.

File: common/app/routes/Settings/components/DangerZone.jsx [hunk 2]
```diff
@@ -58,10 +63,10 @@ class DangerZone extends PureComponent {
             >
             <Alert
               bsStyle='danger'
+              style={centerText}
```
Comment (raisedadead) [inline common/app/routes/Settings/components/DangerZone.jsx]: Remove this styling, this should be rather handled in a dedicated styles file, for the component group. On that note, for this particular message this is an unneeded change.

**Review by raisedadead — CHANGES_REQUESTED** [review]

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @Brybro , for this pull request and contributing to the code-base for the first time.
We will be looking forward for more contributions in future.

Cheers and happy contributing!
