### PR TITLE
fix(client): debounce challenge submissions

### LINKED ISSUE #66964: Duplicated entry in the timeline
### Describe the Issue

When you double-click (or click very fast repeatedly) accidentally on the “Check my code / Submit and continue” button the challenge is saved twice in the timeline. Is there a way to delete the duplicate entry?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-3

### Steps to Reproduce

1. Go to any workshop page 
2. Click on 'Check your code' and double click on "Submit and continue"

### Expected behavior

The challenge must be saved only once in the timeline.

### Screenshots

Image

Image

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AyushK5ingh**
## Description

Fixes duplicate timeline entries caused by rapid or accidental double-clicks on "Submit and continue" by adding a module-level submit lock to the `useSubmit` hook.

**Before & After:** 

https://github.com/user-attachments/assets/1b782378-c095-4c83-bdb9-734b305bcd68

## What Changed

**`client/src/templates/Challenges/utils/fetch-all-curriculum-data.tsx`**
- Added a module-level `isSubmitLocked` flag with a 1000ms reset window.
- First click dispatches immediately; any subsequent calls within 1000ms are ignored.
- Lock is shared across all `useSubmit` hook instances, preventing parallel tab races.

**`client/src/templates/Challenges/classic/editor.tsx`**
- Removed the now-redundant per-instance `debounce` wrapper around `submitChallenge`.
- `tryToSubmitChallenge` now calls `useSubmit` directly since the lock is handled inside the hook.

**`client/src/templates/Challenges/utils/fetch-all-curriculum-data.test.tsx`**
- Added tests verifying rapid calls only dispatch once within the lock window.
- Added tests verifying the lock is shared across multiple hook instances.
- Added tests verifying submit works again after the lock window elapses.

## Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #66964

### CODE REVIEW

**Comment by AyushK5ingh** [comment]
@ojeytonwilliams can help me out, the tests are failing after merge from the main, and i tried the get rid of out commits then  github action locked the last pr closed

**Comment by AyushK5ingh** [comment]
commit [fd8d411] passes but after which it is merged from main then it fails

**Comment by raisedadead** [comment]
Utilize the links provided in the contributing guide to seek assistance. Refrain from @mentioning individuals, as it may be perceived as rude and they might be occupied. 

We ask you to dedicate 10 minutes to reading the contributing guidelines, followed by using AI for code modifications. It saves YOU time.

There is no necessity to continuously merge the main branch onto your branch, as this results in unnecessary CI runs. Please ensure all your existing commits are squashed.

**Comment by AyushK5ingh** [comment]
I squashed all the commit and merged into one. and i have gone through contributing guide. I pinged OJ bcz int he prior PR he was reviewing my code. and i made a mistake and accidentally closed the PR, So i pinged OJ to let him know my error and new PR, bcz there is no other to way to communicate with contributors.

File: client/src/templates/Challenges/utils/fetch-all-curriculum-data.tsx [hunk 1]
```diff
@@ -8,7 +9,10 @@ import type {
   ChallengeNode,
   SuperBlockStructure
 } from '../../../redux/prop-types';
-import { useEffect } from 'react';
+
+const SUBMIT_DEBOUNCE_MS = 1000;
+
+let isSubmitLocked = false;
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/fetch-all-curriculum-data.tsx]: Apologies if I pointed you the wrong way, but it's fine to use a ref for this.

The tests are failing because they try to submit different challenges rapidly. So, if you use a ref then the debouncing will prevent duplicate submissions coming from a single page, but still allow playwright to quickly submit.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
It's not necessary to @ mention the team since we get notifications on new PRs already. That's part of why we recommend avoiding @ mentions most of the time.

**Comment by raisedadead** [comment]
> there is no other to way to communicate with contributors.

Did you bother reading the contributing guidelines? Instead of doubling-down you could have, read the guide and "known" the way to reach us.

We welcome your contribution but please do not embarrass yourself when you are working in public. Years from now you will find this childish.

**Comment by AyushK5ingh** [comment]
I think I misrepresented myself and I apologize for that

I did read the contributing guidelines, however the only contact options listed are Discord, GitHub Discussions, and the freeCodeCamp Forum all public spaces I couldn't find a way to privately reach OJ. My only prior contribution experience is with Meshery, which uses Slack where direct messaging is straightforward. I am not familiar with Discord, so I wasn't aware I could DM someone there privately

That is the only reason I resorted to @mentioning him and I tagged only OJ specifically because he was already reviewing my previous PR which I had accidentally closed. It was not out of ignorance of the guidelines. I now understand that the team is automatically notified on new PRs and I will avoid @mentions going forward. Sorry for the unnecessary noise.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for your patience, @AyushK5ingh, this LGTM 👍 

The fact you took the time to create some solid tests is a real help. Thanks again.
