### PR TITLE
fix(client): handle final project submission

### LINKED ISSUE #50812: Go to next challenge is throwing an error for certificate challenge
### Describe the Issue

When completing the RWD portfolio certificate challenge and clicking "Go to next challenge" (or using Ctrl + Enter) an error is thrown in the browser console and it does not advance to the next challenge. I have _not_ tested this as signed-in or with other certificate challenges.

> Uncaught TypeError: Cannot read properties of null (reading 'includes')

Code that throws

https://github.com/freeCodeCamp/freeCodeCamp/blob/prod-current/client/src/templates/Challenges/redux/completion-epic.js#L209
```
const isNextChallengeInSameSuperBlock = nextChallengePath.includes(superBlock);
```

PR that introduced the code
https://github.com/freeCodeCamp/freeCodeCamp/pull/50033

It was changed again here (not in prod)
https://github.com/freeCodeCamp/freeCodeCamp/pull/50011

Didn't look into it more.

### Affected Page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

### Your code

```



```

### Expected behavior

To work?

### Screenshots

_No response_

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum thread: https://forum.freecodecamp.org/t/responsive-web-design-projects-build-a-personal-portfolio-webpage-is-complete-but-doesnt-submit/618254

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/50812

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Mind if I push a regression test?

**Comment by ojeytonwilliams** [comment]
> Mind if I push a regression test?

Not at all, please do!

**Comment by ojeytonwilliams** [comment]
Thanks for taking care of that, @naomi-lgbt.

**Comment by naomi-lgbt** [comment]
I do love me some regression tests.

File: cypress/e2e/default/learn/challenges/navigation.ts [hunk 1]
```diff
@@ -12,6 +12,36 @@ const challenge2 = {
     '/learn/college-algebra-with-python/#build-a-data-graph-explorer-project'
 };
 
+const rwdChallenge = {
+  url: '/learn/2022/responsive-web-design/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage',
+  nextUrl:
+    'http://localhost:8000/learn/2022/responsive-web-design/#build-a-personal-portfolio-webpage-project'
```
Comment (lasjorg) [inline cypress/e2e/default/learn/challenges/navigation.ts:18]: Is this supposed to have `http://localhost:8000` in the path?

**Review by lasjorg — APPROVED** [review]
LGTM.

I tested the submission and it moves on to the next challenge as expected. But I don't have much insight into the code or the changes.

Seeing as this bug is preventing campers from completing the RWD part of the curriculum the PR should have a bit of urgency I would think.

File: cypress/e2e/default/learn/challenges/navigation.ts (hunk 1 above)
Comment (ShaunSHamilton) [reply cypress/e2e/default/learn/challenges/navigation.ts:18]: It can, but I would prefer it to work on Gitpod using the `CYPRESS_BASE_URL` env. To move this forward though, we can leave for now.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍
