### PR TITLE
fix(UI): keep portal preview open

### LINKED ISSUE #48326: Preview external window disappears when moving to the next challenge
### Describe the Issue

I have two screens: I use one to keep the editor open and one to keep the preview window.

When I click on the "Submit and go to the next challenge" button, the preview window disappears: I have to re-open it in a separate window, and re-move it to the second screen.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-29

### Steps to Reproduce

1. Open a step of the "(New) Responsive Web Design" curriculum
2. Click on the button to open the preview in a second window (top-right, next to the "Preview" button)
3. Complete the step, click on "Check Your code" and then on "Submit and go to the next challenge"
4. The preview window closes

### Expected behavior

The preview window should stay open, containing the preview of the next step

### Screenshots

_No response_

### System

- Device: Laptop
- OS: Ubuntu 22.04
- Browser: Chrome
- Version: 106

### Additional context

This may be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/47608

### PR DESCRIPTION
**Pull request by KravMaguy**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48326

Keeps the same behavior except portal preview can remain open while moving through the curriculum. Tested locally starting at step-1 and advancing through some of the challenges. Also made sure that the open panel buttons and portal preview buttons did not create any additional windows and retained the same behavior as was originally implemented.

### CODE REVIEW

File: client/src/templates/Challenges/components/preview-portal.tsx [hunk 1]
```diff
@@ -72,16 +86,14 @@ class PreviewPortal extends Component<PreviewPortalProps> {
...
-    this.mainWindow?.addEventListener('beforeunload', () => {
-      this.externalWindow?.close();
-    });
+    this.props.storePortalWindow(this.externalWindow);
   }
 
   componentWillUnmount() {
-    this.externalWindow?.close();
-    this.props.removePortalDocument();
+    if (this.mainWindow.location.href.split('/')[3] !== 'learn') {
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/components/preview-portal.tsx:93]:
```suggestion
    if (this.mainWindow.location.href.split('/')[3] !== 'learn') {
```
This is a little too broad. It only closes the window if we navigate away from `/learn` entirely. For example, it works if we go to `/settings`, but not to `/learn/responsive-web-design`.

File: client/src/templates/Challenges/classic/desktop-layout.tsx [hunk 2]
```diff
@@ -52,10 +92,12 @@ const DesktopLayout = (props: DesktopLayoutProps): JSX.Element => {
       case 'showPreviewPane':
         if (!showPreviewPane && showPreviewPortal) setShowPreviewPortal(false);
         setShowPreviewPane(!showPreviewPane);
+        portalWindow?.close();
         break;
       case 'showPreviewPortal':
         if (!showPreviewPortal && showPreviewPane) setShowPreviewPane(false);
         setShowPreviewPortal(!showPreviewPortal);
+        portalWindow?.close();
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/classic/desktop-layout.tsx:100]:
```suggestion
        if(showPreviewPortal) portalWindow?.close();
```
It's a bit odd to be trying to close the window during an operation that opens it.

File: client/src/templates/Challenges/redux/selectors.js [hunk 3]
```diff
@@ -31,7 +31,8 @@ export const successMessageSelector = state => state[ns].successMessage;
 export const projectFormValuesSelector = state =>
   state[ns].projectFormValues || {};
 
-export const portalDocumentSelector = state => state[ns].portalDocument;
+export const portalDocumentSelector = state => state[ns].portalWindow?.document;
+export const getPortalWindow = state => state[ns].portalWindow;
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/redux/selectors.js:35]:
```suggestion
export const portalWindowSelector = state => state[ns].portalWindow;
```
To keep to the convention.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Thanks for taking this on @KravMaguy.  I've added a few observations below:

File: client/src/templates/Challenges/components/preview-portal.tsx (hunk 1 above)
Comment (KravMaguy) [reply client/src/templates/Challenges/components/preview-portal.tsx]: ive made it more specific

**Comment by KravMaguy** [comment]
@ojeytonwilliams Im unable to resolve two of your requests as it does not keep the desired behavior that I had previously implemented.

[place back in local state. place remove portalWindow inside the conditional.](https://github.com/freeCodeCamp/freeCodeCamp/commit/37363d40eede530fd5ca9a0c3dc1097d52f89fa3)

1. Preview pane does not render content 
2. portal button does not open 
3. portal window blank and does not render new content on advancing

Please advise.

**Comment by ojeytonwilliams** [comment]
Sorry, @KravMaguy I had not realised that `showPreviewPane` and `showPreviewPortal` need to be in redux so they persist through the Show component getting unmounted.  Redux does look to be the best place for them.

File: client/src/templates/Challenges/components/preview-portal.tsx [hunk 4]
```diff
@@ -72,16 +86,17 @@ class PreviewPortal extends Component<PreviewPortalProps> {
...
+    this.props.storePortalWindow(this.externalWindow);
   }
 
   componentWillUnmount() {
-    this.externalWindow?.close();
-    this.props.removePortalDocument();
+    if (
+      this.mainWindow.location.href.split('/').length !== 8 ||
+      this.mainWindow.location.href.split('/')[5] !== 'responsive-web-design'
+    ) {
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/components/preview-portal.tsx:96]: The problem with this approach is that it relies on the precise href and that's very likely to change over time.

Since the original issue about the window closing after submission, we can make use of that fact to keep the window open if and only if the user has just submitted a challenge.

This will require a bit more redux shenanigans, we can make use of the completion-epic to solve this. It knows both when the user is submitting and when that submission will move them to a new challenge.  If that dispatches a new action *before* navigating, then we can see if the user `isNavigatingToChallenge` and check that here (instead of looking at the href).

We can also set that property to false here and then all navigation that's *not* triggered by submission will close the window.

**Review by ojeytonwilliams — DISMISSED** [review]

File: client/src/templates/Challenges/components/preview-portal.tsx (hunk 4 above)
Comment (KravMaguy) [reply client/src/templates/Challenges/components/preview-portal.tsx:96]: I can do that for you, (I should point out that we might loose some desired functionality, perhaps it is better user experience for the window to stay open while navigating forward and backwards freely, not just navigation thats triggered by submission.)

regretfully, currently im unable to get the application up and running on my manchine so im unable to implement your request atm

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/components/preview-portal.tsx:96]: It's possible there's a better approach that allows that, but doesn't rely on the path, I don't know.

> im unable to implement your request atm

Don't worry, it's not urgent.

Comment (KravMaguy) [reply client/src/templates/Challenges/components/preview-portal.tsx:96]: > doesn't rely on the path,

I dont see whats wrong with using a path, even the epic is relying on a path, instead of using a hardcoded string value I can just import constant from the superblock, than at least we will still get the keep the functionality of keeping the window open as the user freely navigates and not only based upon submission of a challenge, that wont be good enough to close out the issue? 
 
image

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/components/preview-portal.tsx:96]: It's true that this does rely on the superblock being part of the path, but that's not a great approach.  We have the page context available to determine if a given page is a challenge or not. It's also possible to tell if the next page is a challenge without inspecting the path.

I don't see a good way of allowing the user to navigate anywhere without relying on the details of the path.  We can't constrain ourselves to a precise path structure long term, so we shouldn't rely on that here.

Comment (KravMaguy) [reply client/src/templates/Challenges/components/preview-portal.tsx]: it is behvaving as expected and not relying on the path. I also checked the edgecase of the last step before it moves on to the javascript projects, and it closes as expected. Is there any more work to do here?

**Review by moT01 — DISMISSED** [review]
This is looking real good @KravMaguy 🎉 I'm seeing a few potential issues still...

After I complete the last step of a project with the portal open, I go to the first step of the next project and it's a little weird:
<details><summary>Image</summary>
</details>

And the preview of first step for every project is blank. It just feels like we are giving campers too much and there isn't a focus. I'm wondering if we should close the portal (revert to internal preview) on the first step of a project. I think we want them to focus on that other modal that pops up. We could probably leave this behavior if we want - it isn't too bad, but I think that would probably be better. It doesn't seem like a big deal to have to reopen that portal on the first step for each project.

<hr>

The second thing I saw, we should probably do something about. If I have the portal open, leave the challenge (e.g. go back to the map), the portal closes itself, then go to another challenge, the preview isn't shown anywhere (internal or portal). I think we should revert back to the default (internal) preview anytime a camper goes to a challenge (component is mounted).


The way this PR sits is better than what is live, so I suppose we don't necessarily need to fix either of those, but I think we should if possible. Or, feel free to let me know what you think.

**Comment by raisedadead** [comment]
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

**Comment by Nirajn2311** [comment]
I can't seem to keep the preview window open when I go to the next challenge. Also in Safari the browser freezes due to a `RangeError: Maximum call stack size exceeded.` which is thrown repeatedly almost like an infinite loop.

Screenshot 2023-01-20 at 11 00 16

**Comment by ojeytonwilliams** [comment]
@moT01 we need some way of telling the preview window to stay open when navigating between challenges. I couldn't come up with a smarter way than checking if the user has just completed a challenge and, if so, keep it open when `PreviewPortal` is unmounted.

Which is to say, I think we need `isAdvancing`.

@Nirajn2311 what triggers the infinite loop?

**Comment by Nirajn2311** [comment]
> @Nirajn2311 what triggers the infinite loop?

Open the preview window, solve the challenge, click on the submit button to go to the next challenge and it freezes

**Comment by ojeytonwilliams** [comment]
Thanks @Nirajn2311 that stack trace helps. It seems like it's calling `togglePane('showPreviewPortal')` repeatedly and not updating `showPreviewPortal` (which should be set to false after the first `togglePane` call). However, that seems to be a safari specific issue and I can't replicate it.

One thing that might help is to `removePortalWindow` whenever we close it.  Also, we should probably remove the listeners on cleanup.

**Comment by moT01** [comment]
Hey @Nirajn2311, do you mind giving this another quick test when you get a chance to see if you are still having issues with safari?

I had a hard time testing that cause I have an older version, but I am hopeful they are resolved.

**Review by Nirajn2311 — APPROVED** [review]
LGTM and the Safari bug is resolved

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
LGTM works good 
Thanks @KravMaguy and @moT01 for implementing this :)
