### PR TITLE
fix: stop user code after 100ms of execution

### LINKED ISSUE #37837: Need to a way to prevent infinite loops in users' challenge code from crashing Chrome browsers
**Issue:** We need a way to stop code which creates an infinite loop from running long enough to crash a browser. Since master was deployed to production a few weeks back, we have seen an uptick in the number of forum questions for certain challenges (like the while loop and for loop challenges) where they inadvertently create an infinite loop with their code and it crashes the browser. I know there was something in place that used to prevent a single test from running more than 100ms, but obviously that feature was removed at some point.

If a single test takes longer than say 500ms, then the test runner should stop and a message like the following should appear in the FCC console.

> The code you have written is taking longer than the 500ms our test runner allows. You may have created an infinite loop or need to refactor an inefficient algorithm.

How to reproduce:  Using Chrome (on Windows 10), if I enter the following code for the [Iterate with JavaScript While Loops](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops) challenge:
```js
// Setup
var myArray = [];

var i = 0;
while(i < 5) {
  myArray.push(i);
  i--;
}
```

the following occurs:

Video

We have seen a significant increase in the number of forum topics/post where users are experiencing this issue.

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Code like `var xs = []; while(true){ xs.push(1) }` can quickly run the browser out of memory causing it to crash.  These changes use [@freecodecamp/loop-protect](https://www.npmjs.com/package/@freecodecamp/loop-protect) to break out of loops early (after a loop runs for more than 100ms) and warn the user that their code may contain an infinite loop.

`loop-protect` was also added back to the test runner as well, so that the user is protected when their code contains loops that are not evaluated until testing.  In testing the protection is weaker, waiting 2500ms before breaking out of a loop.

If this timeout proves to be too long, it can be lowered, potentially down to ~500ms.  In practice it's always going to be a compromise between good protection and allowing long running tests to complete.

Closes #37837

### CODE REVIEW

**Comment by RandellDawson** [comment]
I just tested the PR. However, even though I get see the error message in the console, about 750ms later, the browser still crashes.

image

**Comment by ojeytonwilliams** [comment]
@freeCodeCamp/moderators if anyone could try this out and see if it stops their browser crashing, that would be a huge help.  It works for me, but not for Randell so I'd like to see if it's any use in practice.

Once you've got the PR running locally, just go to localhost:8000/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops (using Chrome) and enter

```js
var myArray = [];

var i = 0;
while(i < 5) {
  myArray.push(i);
  i--;
}
```

It should output to the fcc console and *not* crash, but that's not guaranteed!

File: client/src/templates/Challenges/redux/execute-challenge-saga.js [hunk 1]
```diff
@@ -163,10 +167,14 @@ function* previewChallengeSaga() {
...
         const runUserCode = getTestRunner(buildData, { proxyLogger });
         // without a testString the testRunner just evaluates the user's code
-        yield call(runUserCode, null, 5000);
+        yield call(runUserCode, null, previewTimeout);
       }
     }
   } catch (err) {
+    if (err === 'timeout') {
+      // eslint-disable-next-line no-ex-assign
+      err = `The code you have written is taking longer than the ${previewTimeout}ms our challenges allow. You may have created an infinite loop or need to rewrite an inefficient algorithm`;
```
Comment (raisedadead) [inline client/src/templates/Challenges/redux/execute-challenge-saga.js]:
```suggestion
      err = `The code you have written is taking longer than the ${previewTimeout}ms our challenges allow. You may have created an infinite loop or need to write an efficient algorithm`;
```

Let's change the double negative verbiage.

**Comment by moT01** [comment]
I mentioned in the issue that I think chrome throws the error or whatever after 3600ms - 100ms seems a little short to me. I would rather give it like 2500ms.

**Comment by ojeytonwilliams** [comment]
@moT01 I'd like to have it be longer, but it already crashes my machine intermittently at 500ms and Randell's still crashes at 100ms.

**Comment by ojeytonwilliams** [comment]
This could have been a bit simpler, but I wanted to allow JS tests to run for a long time (that was the original motivation for the workers, after all) while using loop-protect to keep the previews from crashing.

@moT01 once I used loop-protect, I was able to raise the preview timer to 2500ms without any obvious issues.

File: client/src/templates/Challenges/rechallenge/transformers.js [hunk 2]
```diff
@@ -23,7 +23,14 @@ import createWorker from '../utils/worker-executor';
 import { filename as sassCompile } from '../../../../config/sass-compile';
 
 const protectTimeout = 100;
-Babel.registerPlugin('loopProtection', protect(protectTimeout));
+
+function loopProtectCB(line) {
+  console.log(
+    `Potentially infinite loop detected on line ${line}. Tests may fail if this is not changed`
```
Comment (RandellDawson) [inline client/src/templates/Challenges/rechallenge/transformers.js]:
```suggestion
    `Potentially infinite loop detected on line ${line}. Tests may fail if this is not changed.`
```

**Comment by raisedadead** [comment]
LGTM, I am not a fan of depending on GitHub for the package. Can we fork and publish the version we need @ojeytonwilliams ? If yes, I can take care of it.

**Comment by ojeytonwilliams** [comment]
@raisedadead do you mean a scoped version like `@freecodecamp/loop-protect`?  I assume so, it uses the MIT license.

After discussing with @RandellDawson I added loop-protect back into the js tests, but with a long timeout to avoid the problems mentioned in https://github.com/freeCodeCamp/freeCodeCamp/pull/34524.  This should make it less likely that the tests crash the browser, though we might need to tune the precise timeout later.

**Comment by ojeytonwilliams** [comment]
I've created a [fork](https://github.com/ojeytonwilliams/loop-protect) of `loop-protect` and created the necessary changes on that.  We'll need to tune the numbers so that it's as restrictive as possible while still allowing the slow challenges to complete.

**Comment by ojeytonwilliams** [comment]
The latest commit is set so that, on my machine, it doesn't crash (barely) if you try to use

```js
var xs = [];
while(true) {
  xs.push(i++);
}
```
While still passing `npm run test:curriculum`.  There is not much leeway.  Increasing the timeout much more than 4000ms crashes my browser and anything below 2500ms does not reliably pass the tests.

Assuming this approach is okay, I think we should try lowering the timeout and relax any tests that fail, if possible and if the solution is a reasonable algorithm.

**Comment by raisedadead** [comment]
I was wondering if we could hook into some other API for the render. For instance [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) could be used to check if the test runner (worker) crashed and display a message, if not proceed to render.

**Comment by ojeytonwilliams** [comment]
I'm not sure that will help.  The code is already evaluated inside a try block

```js
    try {
      testResult = eval(`
        ${e.data.build}
        __userCodeWasExecuted = true;
        ${e.data.testString}
      `);
    } catch (err) {
```

and any actual errors are handled nicely.  In these cases I think the JS engine is going OOM and the entire browser has to shut down as a result, so the only thing we can do is try to avoid them.

I mean, if you think it's worth a try, I can see if it works.  I'm not optimistic, though.

**Comment by raisedadead** [comment]
Hmm, I see. My intent is to be able to separate the render loop from the execution loop. (The workers were intended to do this)

**Comment by ojeytonwilliams** [comment]
I've published the fork and updated the reference.  When I checked it locally it still crashed at 3000ms, so I lowered it slightly.  This may result in the tests occasionally failing, so, when I can, I'll modify those challenges.

**Comment by ojeytonwilliams** [comment]
Blocked until the tests pass reliably.

**Comment by ojeytonwilliams** [comment]
I think, pending QA, this is in good shape.  The lowest I went in testing was 250ms, which resulted in at least one project Euler challenge failing.  At 500ms everything worked just fine.

**Comment by raisedadead** [comment]
@moT01 @RandellDawson do you mind taking a look?

File: client/src/templates/Challenges/rechallenge/transformers.js [hunk 3]
```diff
@@ -23,17 +23,42 @@ import createWorker from '../utils/worker-executor';
 import { filename as sassCompile } from '../../../../config/sass-compile';
 
 const protectTimeout = 100;
-Babel.registerPlugin('loopProtection', protect(protectTimeout));
+const testProtectTimeout = 2500;
+const loopsPerTimeoutCheck = 2000;
+
+function loopProtectCB(line) {
+  console.log(
+    `Potentially infinite loop detected on line ${line}. Tests may fail if this is not changed.`
```
Comment (moT01) [inline client/src/templates/Challenges/rechallenge/transformers.js]:
```suggestion
    `Potential infinite loop detected on line ${line}. Tests may fail if this is not changed.`
```

File: client/src/templates/Challenges/rechallenge/transformers.js [hunk 4]
```diff
@@ -23,17 +23,42 @@ import createWorker from '../utils/worker-executor';
...
+  );
+}
+
+function testLoopProtectCB(line) {
+  console.log(
+    `Potentially infinite loop detected on line ${line}. Tests may be failing because of this.`
```
Comment (moT01) [inline client/src/templates/Challenges/rechallenge/transformers.js]:
```suggestion
    `Potential infinite loop detected on line ${line}. Tests may be failing because of this.`
```

File: client/src/templates/Challenges/redux/execute-challenge-saga.js [hunk 5]
```diff
@@ -155,18 +158,22 @@ function* previewChallengeSaga() {
...
         const runUserCode = getTestRunner(buildData, { proxyLogger });
         // without a testString the testRunner just evaluates the user's code
-        yield call(runUserCode, null, 5000);
+        yield call(runUserCode, null, previewTimeout);
       }
     }
   } catch (err) {
+    if (err === 'timeout') {
+      // eslint-disable-next-line no-ex-assign
+      err = `The code you have written is taking longer than the ${previewTimeout}ms our challenges allow. You may have created an infinite loop or need to write an efficient algorithm`;
```
Comment (moT01) [inline client/src/templates/Challenges/redux/execute-challenge-saga.js]:
```suggestion
      err = `The code you have written is taking longer than the ${previewTimeout}ms our challenges allow. You may have created an infinite loop or need to write a more efficient algorithm`;
```

Comment (moT01) [reply client/src/templates/Challenges/redux/execute-challenge-saga.js]: Minor suggested change here, I think this sounds a little friendlier.

File: client/src/templates/Challenges/rechallenge/transformers.js (hunk 3 above)
Comment (moT01) [reply client/src/templates/Challenges/rechallenge/transformers.js]: The grammar here doesn't sound right to me - not quite sure if it is or not. I'll let you decide.

**Review by moT01 — COMMENTED** [review]
A few minor grammar suggestions for now.

Other than that, I could not get my chrome to throw that error.

I did not dive into the code here yet - I think @RandellDawson should see if his browser is having any issues since he was when you (@ojeytonwilliams ) were not, and if it seems to be working for him, I can try and give the code a better review.

File: client/src/templates/Challenges/rechallenge/transformers.js (hunk 3 above)
Comment (ojeytonwilliams) [reply client/src/templates/Challenges/rechallenge/transformers.js]: I *slightly* prefer potentially, but I could be swayed.  @RandellDawson do you have a preference?

**Comment by ojeytonwilliams** [comment]
> Other than that, I could not get my chrome to throw that error.

Does it throw on live?

**Comment by moT01** [comment]
Yes, Chrome throws the error on production for me - The "Aw, Snap!" screen shows up.

File: client/src/templates/Challenges/rechallenge/transformers.js (hunk 3 above)
Comment (raisedadead) [reply client/src/templates/Challenges/rechallenge/transformers.js]: I am inclined on Tom's suggestion i.e potential

Comment (thecodingaviator) [reply client/src/templates/Challenges/rechallenge/transformers.js]: `Potential` sounds better to me

**Comment by raisedadead** [comment]
I pulled this down and tested, and seems to be working fine for the challenge in the linked issue. Should we merge this and wait for more feedback?

**Comment by ojeytonwilliams** [comment]
I'd like to wait until @RandellDawson has had a chance to test it, since his machine seemed to crash the most readily.

**Comment by raisedadead** [comment]
Sure thing.

**Comment by RandellDawson** [comment]
Sorry I have been attending to other stuff.  I will look at this today.

**Comment by iansibindi** [comment]
Hy

**Comment by RandellDawson** [comment]
@raisedadead This PR was not ready for merging.  I have been working with @ojeytonwilliams to test it and things were still not working properly on my machine.

**Comment by raisedadead** [comment]
I wanted to test this out on the .dev, from what I know its not going to make the experience worser? From what I understand it will still be resulting in what we have on production for some machines (like yours)?

**Comment by raisedadead** [comment]
Feel free to report fresh issues as you find them.

**Comment by RandellDawson** [comment]
> From what I understand it will still be resulting in what we have on production for some machines (like yours)?

It does not report to the user an infinite loop in the FCC console like it is supposed to.  It just says tests timed out.

**Comment by ojeytonwilliams** [comment]
Js challenges on .dev are completely broken right now:
image

almost certainly due to my PR.  I'm not, yet, sure why since it works perfectly on my machine
