### PR TITLE
fix(i18n): translate block names in completion modal

### LINKED ISSUE #41511: [i18n] Completion modal block names aren't being translated
In the completion modal after passing a challenge, the block names are showing up in English:
Screen Shot 2021-03-16 at 3 32 02 PM

But the breadcrumbs:
Screen Shot 2021-03-16 at 3 32 15 PM

And superblock pages:
Screen Shot 2021-03-16 at 3 32 28 PM

it has the translated block names. I wouldn't think it would be too hard to use the existing translations in the completion modal.

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41511

### CODE REVIEW

File: client/src/templates/Challenges/components/CompletionModalBody.js [hunk 1]
```diff
@@ -58,7 +61,11 @@ export class CompletionModalBody extends PureComponent {
   }
 
   render() {
-    const { blockName, completedPercent, t } = this.props;
+    const { blockName, completedPercent, superBlock, t } = this.props;
+
+    const blockTitle = t(
+      `intro:${superBlock}.blocks.${dasherize(blockName)}.title`
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/components/CompletionModalBody.js:67]: Rather than dasherizing (which I'm trying to remove entirely from the client), can we just pass `block` here?

File: client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap [hunk 2]
```diff
@@ -64,7 +64,7 @@ exports[`<CompletionModalBody /> matches snapshot 1`] = `
     <div
       class="completion-block-name"
     >
-      Basic HTML and HTML5
+      intro:responsive-web-design.blocks.basic-html-and-html5.title
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap:67]: I don't think the key should ever appear in a component.  Shouldn't it fall back to the English?

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap (hunk 2 above)
Comment (nhcarrigan) [reply client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap:67]: That's how it is configured, yes - but I'm not sure if the snapshots call the i18n function.

Comment (moT01) [reply client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap:67]: Not sure if I implemented this part the best. The translations aren't actually loaded for [the tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/configForTests.js). There's some [more info here](https://react.i18next.com/misc/testing). We could try and see if they can be loaded - I would have to play around with it. [Another relevant file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/__mocks__/react-i18nextMock.js)

Comment (ojeytonwilliams) [reply client/src/templates/Challenges/components/__snapshots__/CompletionModalBody.test.js.snap:67]: Okay, thanks for the context.  Don't worry about that for this PR, it's clearly out of scope.

File: client/src/templates/Challenges/components/CompletionModalBody.js (hunk 1 above)
Comment (moT01) [reply client/src/templates/Challenges/components/CompletionModalBody.js]: Should be fixed

File: client/src/templates/Challenges/projects/frontend/Show.js [hunk 3]
```diff
@@ -176,7 +176,7 @@ export class Project extends Component {
                 <br />
                 <Spacer />
               </Col>
-              <CompletionModal blockName={blockName} />
+              <CompletionModal block={block} superBlock={superBlock} />
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/projects/frontend/Show.js:179]:
```suggestion
              <CompletionModal
                block={block}
                blockName={blockName}
                superBlock={superBlock}
              />
```
Currently `CompletionModal` still needs `blockName`.  I think it's worth refactoring it so it doesn't, but I can handle that in another PR.

File: client/src/templates/Challenges/video/Show.js [hunk 4]
```diff
@@ -298,7 +298,7 @@ export class Project extends Component {
                 </Button>
                 <Spacer size={2} />
               </Col>
-              <CompletionModal blockName={blockName} />
+              <CompletionModal block={block} superBlock={superBlock} />
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/video/Show.js:301]:
```suggestion
              <CompletionModal
                block={block}
                blockName={blockName}
                superBlock={superBlock}
              />
```

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
I went ahead and updated the 4th Show.js, so they all get the required props now.  

LGTM :+1:

**Review by ahmaxed — APPROVED** [review]
