### PR TITLE
fix(client): update text container for fsd lessons

### LINKED ISSUE #63699: Update text container width for fsd lessons
Since we have added the interactive examples the container for the text now spreads most of the page.

Image

While that works for some, others like Quincy have brought up that it would be nice if the width for the text container was smaller so it is easier to read. This is mainly for those who use larger monitors.

### PR DESCRIPTION
**Pull request by AdityaSingh-18**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitHub Codespaces.

Closes #63699

This PR is to update the text container for fsd lessons to make the lesson content width consistent and less wide, while keeping the interactive editor width unchanged.

Changes Made:

- Made the width of the text container the same as in non-interactive editor lessons
- The code blocks inside the interactive editor boundary have the same width when the interactive editor is disabled to maintain consistency
- When the interactive editor is enabled, it is displayed with a wider width compared to text content
- Shrunk the editor a little and added margin between text and editor

### CODE REVIEW

File: client/src/templates/Challenges/generic/show.tsx [hunk 1]
```diff
@@ -276,10 +276,22 @@ const ShowGeneric = ({
               )}
 
               {nodules?.map((nodule, i) => {
+                // when the editor is enabled
+                if (
+                  nodule.type === 'interactiveEditor' &&
+                  showInteractiveEditor
+                ) {
```
Comment (moT01) [inline client/src/templates/Challenges/generic/show.tsx]: Feels like there's some extra logic happening here. We have pretty much the same check in the `renderNodule` function.

**Review by moT01 — COMMENTED** [review]
Left one comment about the code - maybe fine to just leave it. Regarding the UI - it's not bad...

<details><summary>image</summary>

Image

</details>

The text is more readable, but the editor feels a little wide. I shrunk the editor and added some margin above and below to check it out (text is the same width):

<details><summary>image</summary>

Image

</details>

Looks a bit better in my opinion. For the most part, I think that's enough room in the editor to show the code and preview. There may be a few spots where it feels a bit crowded in the editor - couldn't actually find any. I think I would do something like that, what do you think @AdityaSingh-18?

File: client/src/templates/Challenges/generic/show.tsx (hunk 1 above)
Comment (AdityaSingh-18) [reply client/src/templates/Challenges/generic/show.tsx]: Correct me if I’m mistaken, but although the checks look similar, they serve different purposes. The `renderNodule` function is used for rendering the data, while the `map()` function is for layout wrapper.

So currently, when `nodule.type` is `interactiveEditor` and the editor is `ON`, it is rendered directly at full width. For all other nodules or when the editor is `OFF`, the `<Col />` wrapper is applied to display data like in non-interactiveEditor lectures.

**Comment by AdityaSingh-18** [comment]
Yes, I agree with slightly shrinking the editor. After adjusting the text width, the editor does feel a bit too wide in comparison.

Also I saw a PR on adding the navbar on the review pages. I currently don't have much idea about how it will works, but I think it would be helpful otherwise the navbar might overlap or cut the editor content.

**Comment by AdityaSingh-18** [comment]
@moT01 I have shrunk the editor and added margin. Please let me know if any changes are needed.

<details>
<summary>Image</summary>

image

</details>

(Also should I remove those comments in code?)

File: client/src/templates/Challenges/generic/show.tsx (hunk 1 above)
Comment (ShaunSHamilton) [reply client/src/templates/Challenges/generic/show.tsx]: I am with @moT01  on this.

Please change the layout within the `renderNodule` function - not before.

Also, the comments are unnecessary.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 
Thank you for taking the time to contribute.

---

Personally, I would not have the extra space at the bottom, but that is mostly because the interactive editor probably should not have any bottom margin.
