### PR TITLE
Fix catch timezone bug

### LINKED ISSUE #6633: Timezone breaks submission: "cannot read `join` of null.
I cann't press the button "Submit and go to my next challenge (ctrl + enter)". But if I clicked I only see the infinite loading. How to solve this problem?
default

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
see https://github.com/moment/moment-timezone/issues/294

Up on beta.

closes #6633

### CODE REVIEW

File: client/commonFramework/show-completion.js [hunk 1]
```diff
@@ -47,13 +47,23 @@ window.common = (function(global) {
...
+        console.error(err);
+      }
       const data = {
         id: common.challengeId,
         name: common.challengeName,
         completedWith: didCompleteWith,
         challengeType: common.challengeType,
         solution,
-        timezone: moment.tz.guess()
+        timezone
```
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: Shouldn't this be `timezone: timezone` to assign it to the local variable?

File: client/commonFramework/show-completion.js [hunk 2]
```diff
@@ -47,13 +47,23 @@ window.common = (function(global) {
           next();
         });
 
+      let timezone = 'UTC';
```
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: Is `let` widely supported client side?

**Comment by brutalcrozt** [comment]
hello, how you figure it was moment which create trouble?

File: client/commonFramework/show-completion.js (hunk 2 above)
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: I suggest `var`, since: http://caniuse.com/#feat=let === ~50%

File: client/commonFramework/show-completion.js [hunk 3]
```diff
@@ -47,13 +47,23 @@ window.common = (function(global) {
...
+      try {
+        timezone = moment.tz.guess();
```
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: Will this overwrite timezone if there is an error, or will the error happen before the assignment?

File: client/commonFramework/show-completion.js (hunk 1 above)
Comment (BerkeleyTrue) [inline client/commonFramework/show-completion.js]: This is ES2015 enhanced object literal syntax.

File: client/commonFramework/show-completion.js (hunk 2 above)
Comment (BerkeleyTrue) [inline client/commonFramework/show-completion.js]: We transpile using babel before it reaches the client.

File: client/commonFramework/show-completion.js (hunk 1 above)
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: Yes, this is client side. We can't be sure it will be supported, right?

File: client/commonFramework/show-completion.js (hunk 2 above)
Comment (SaintPeter) [inline client/commonFramework/show-completion.js]: Oh.  Ok, sorry.

File: client/commonFramework/show-completion.js (hunk 3 above)
Comment (BerkeleyTrue) [inline client/commonFramework/show-completion.js]: No, the error happens within timezone. The assignment will not take affect until guess() resolves but since it throws it never resolves. It is caught by the catch below.

**Comment by SaintPeter** [comment]
:+1:
