### PR TITLE
fix(client-UI): view button takes full width

### LINKED ISSUE #45947: View button for viewing new multifile solutions is not full width
### Describe the Issue

When looking at your settings page or timeline, the view button to see a code solution and preview for the new multifile solutions is not full width. All the other buttons on those pages are full width.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/fccb1
2. See button, not full width - other buttons are

### Expected behavior

To be full width

### Screenshots

Screen Shot 2022-05-13 at 9 01 39 AM

^ Timeline - same on settings page

### PR DESCRIPTION
**Pull request by Sboonny**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

> note I didn't know how to open freecodecamp.dev in my environment to test my change, but I have used devtools to check if my idea will affect it. so please check it yourself. 

Closes #45947

Kudos to nhcarrigan, Nirajn2311, Sembauke, and Tom for their help and insights

### CODE REVIEW

File: client/src/components/profile/components/time-line.tsx [hunk 1]
```diff
@@ -122,7 +122,7 @@ function TimelineInner({
     const { challengeTitle, challengePath, certPath } = idToNameMap.get(id);
     return (
       <tr className='timeline-row' key={id}>
-        <td>
+        <td className='solutions-dropdown'>
```
Comment (Nirajn2311) [inline client/src/components/profile/components/time-line.tsx:125]: This data cell is for displaying the challenge name, not for the view button/dropdown. The view button/dropdown is the next `td` tag below but instead of adding the class to the `td` tag it's more consistent to update the code that renders the dropdown button as already one [function](https://github.com/freeCodeCamp/freeCodeCamp/blob/f98db0e1ac8c51365d2556ef53b7c0f2740405c9/client/src/components/solution-display-widget/index.tsx#L97-L122) does it. Similarly `ShowMultifileProjectSolution` function should also be updated.

**Review by Nirajn2311 — CHANGES_REQUESTED** [review]

File: client/src/components/profile/components/time-line.tsx (hunk 1 above)
Comment (Sboonny) [reply client/src/components/profile/components/time-line.tsx:125]: That's make sense, I will start working on it

Comment (Sboonny) [reply client/src/components/profile/components/time-line.tsx]: I have nested `td` in `.solutions-dropdown` 

```html
<div className='solutions-dropdown'>
  <td>
   ....
  </td>
</div>
```

and the same to `ShowMultifileProjectSolution`

```html
<div className='solutions-dropdown'>
      <DropdownButton
        block={true}
        bsStyle='primary'
        className='btn-invert'
        id={`dropdown-for-${id}`}
        title={t('buttons.view')}
      >
        <MenuItem bsStyle='primary' onClick={showUserCode}>
          {t('buttons.show-code')}
        </MenuItem>
        <MenuItem bsStyle='primary' onClick={showProjectPreview}>
          {t('buttons.show-project')}
        </MenuItem>
      </DropdownButton>
    </div>
```

File: client/src/components/profile/components/time-line.tsx [hunk 2]
```diff
@@ -122,29 +122,31 @@ function TimelineInner({
...
+          <td className='text-center'>
+            <time dateTime={completedDate.toISOString()}>
+              {completedDate.toLocaleString([localeCode, 'en-US'], {
+                year: 'numeric',
+                month: 'short',
+                day: 'numeric'
+              })}
+            </time>
+          </td>
+        </div>
```
Comment (Nirajn2311) [inline client/src/components/profile/components/time-line.tsx:149]: The changes to this file can be reverted as the changes in the other file fixes the issue.

**Review by Nirajn2311 — CHANGES_REQUESTED** [review]

**Comment by Nirajn2311** [comment]
> note I didn't know how to open freecodecamp.dev in my environment to test my change, but I have used devtools to check if my idea will affect it. so please check it yourself.

You can run the app locally or use the "Open in Gitpod" button above to test out the app

**Comment by Sboonny** [comment]
> You can run the app locally(https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) or use the "Open in Gitpod" button above to test out the app

ahh, well you know... because it was `.dev`, I thought there was a hidden way to access it. looking back, I was just intoxicated by a fantasy, that made me overthink this a little 😅😅

**Review by Nirajn2311 — DISMISSED** [review]

**Comment by Sembauke** [comment]
It might be worth giving the first row (challenge) a fixed width so that the buttons will be the same width on every page.

**Comment by Sboonny** [comment]
> It might be worth giving the first row (challenge) a fixed width so that the buttons will be the same width on every page.

I can do it, but I think adding `aspect-ratio` is more responsive. I will test both and share the result when I get back.

**Comment by Sembauke** [comment]
I think this looks better do you mind pushing a commit so we can check it out?

**Review by moT01 — COMMENTED** [review]
This is looking good @Sboonny 🎉 I was able to find a small issue on the settings page when making my window smaller:
Screen Shot 2022-05-18 at 7 26 04 AM
I deleted a few nodes so the two certs with dropdown buttons were right next to each other. Looking into it, they both have the same classes and styles applied - the problem was the width of the button content. 'view' is short, 'show solution' is long enough to make the button full width.

I would be fine merging this as-is, it's a good improvement - but if you want to take a quick look at that to see if you can come up with something - or, if you don't want to, I can take a quick look - or maybe we just merge it.

**Comment by Sboonny** [comment]
this change is based on my `viewport`, so if you find issue. I am happy to look into it.

> It might be worth giving the first row (challenge) a fixed width so that the buttons will be the same width on every page

Sembauke suggestion would have solved this issue as well, if I implemented it. but I hated how the project name looked in small screen. with this experience I think I should have kept an open mind 😂

**Comment by Sboonny** [comment]
because of the limitation of my hardware. I can't replicate it, but I am still happy to work on it.

---

 just wondering this is the right file? it looks like it has the right structure

[certification.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/certification.js)

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by Sembauke — APPROVED** [review]
