### PR TITLE
fix: submit backend projects

### LINKED ISSUE #37381: Backend project submission fails quietly
**Describe the bug**
When a backend project is submitted it does not send the solution or Github urls and is rejected, silently, by the server.

**To Reproduce**
1. Go to localhost:8000/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker
2. Enter valid urls into Solution and Github Link
3. Click "I've completed this challenge"
4. Click "Submit..."
5. Arrive at the next challenge
6. Go to your public profile (with timeline public)
7. Reload
8. See that the project does not appear.

**Expected behavior**
Either the submission should succeed or the user should be informed that it has failed.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Removed calls to updateProjectForm that clear the GitHub and Solution links before the backend project form can be processed

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/37381

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
LGMT

File: client/src/templates/Challenges/projects/ProjectForm.js [hunk 1]
```diff
@@ -26,15 +26,6 @@ export class ProjectForm extends Component {
     super(props);
     this.handleSubmit = this.handleSubmit.bind(this);
   }
-  componentDidMount() {
```
Comment (ahmadabdolsaheb) [inline client/src/templates/Challenges/projects/ProjectForm.js]: maybe we leave this one just in case?

**Review by ahmaxed — APPROVED** [review]

File: client/src/templates/Challenges/projects/ProjectForm.js (hunk 1 above)
Comment (scissorsneedfoodtoo) [reply client/src/templates/Challenges/projects/ProjectForm.js]: Yes, I agree. Better to leave it just in case.

**Review by raisedadead — APPROVED** [review]
LGTM
