### PR TITLE
fix (client): show correct donate duration in text

### LINKED ISSUE #38440: Donation page text showing wrong donation frequency
When navigating to https://www.freecodecamp.org/donate/ and selecting a monthly donation, the text below says "Confirm your donation of $X / year with PayPal" when I would expect it to say "Confirm your donation of $X / month with PayPal"

This text is coming from: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/8866ed74c201be69ace03101fca942ce06f74ee7/client/src/components/Donation/DonateForm.js#L258

There is logic elsewhere in this file that handles the different frequencies, it seems like this logic is needed here as well. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/8866ed74c201be69ace03101fca942ce06f74ee7/client/src/components/Donation/DonateForm.js#L123-L125

### PR DESCRIPTION
**Pull request by hassaanp**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38440

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @hassaanp, thanks for jumping on this so quickly. Just noticed one thing that I left as a review comment.

File: client/src/components/Donation/DonateForm.js [hunk 1]
```diff
@@ -255,8 +255,8 @@ class DonateForm extends Component {
           {subscriptionPayment ? (
             <Fragment>
               <b>
-                Confirm your donation of ${donationAmount / 100} / year with
-                PayPal:
+                Confirm your donation of ${donationAmount / 100} /{' '}
```
Comment (scissorsneedfoodtoo) [inline client/src/components/Donation/DonateForm.js]: I believe these lines can be simplified to the following:

```js
Confirm your donation of ${donationAmount / 100} / {donationDuration} with
PayPal:
```

Comment (ahmadabdolsaheb) [reply client/src/components/Donation/DonateForm.js]: I just checked, it seems like linter does that on save.
