### PR TITLE
fix(i18n): Expand/Collapse Courses Button text

### LINKED ISSUE #44476: "Expand courses" and "Collapse courses" cannot be displayed correctly in Japanese
In the screenshot below, "Expand courses" and "Collapse courses" are displayed by combining 3 strings `Expand` `Collapse` and `Courses` taken from `/client/i18n/locales/english/intro.json`

Can we change the translatable strings to `Expand courses` and `Collapse courses` ?
Not `Expand` + `Courses` and `Collapse` + `Courses` .

It is difficult to translate them correctly into a language with different grammar rules, such as Japanese. Refer to "Additional context" below for detailed explanation.

image

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/ (and all other certifications)

## To reproduce

1. Visit the above URL

## Expected behavior

"Expand courses" and "Collapse courses" can be displayed correctly in languages with different grammar rules.

## Screenshots

See above

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.93

## Additional context

The problem is caused by grammatical differences between English and Japanese (and possibly other languages).

In Japanese, the words correspond as follows:
"Expand" -> "展開"
"Collapse" -> "閉じる"
"Courses" -> "コース"

But when saying "Expand courses" or "Collapse courses", they should be like:
"Expand courses" -> "コースを展開"
"Collapse courses" -> "コースを閉じる"

Notice that:
- The order of words is different. The word for "Courses" comes first.
- We need a connecting word "を"

They are displayed incorrectly like this with current implementation. (tested in my local)
image

### PR DESCRIPTION
**Pull request by PrashantSakre**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44476

### CODE REVIEW

File: client/src/templates/Introduction/components/block.tsx [hunk 1]
```diff
@@ -203,9 +201,7 @@ export class Block extends Component<BlockProps> {
           >
             <Caret />
             <h4 className='course-title'>
-              {`${
-                isExpanded ? collapseText : expandText
-              } ${coursesText.toLowerCase()}`}
```
Comment (ieahleen) [inline client/src/templates/Introduction/components/block.tsx:208]: Considering this, please make the word courses lowercase to avoid changing the existing UI for English

File: client/i18n/locales/english/intro.json [hunk 2]
```diff
@@ -560,7 +560,7 @@
     "browse-other": "Browse our other free certifications\n(we recommend doing these in order)",
     "courses": "Courses",
     "steps": "Steps",
-    "expand": "Expand",
-    "collapse": "Collapse"
+    "expand": "Expand Courses",
```
Comment (ieahleen) [inline client/i18n/locales/english/intro.json:563]:
```suggestion
    "expand": "Expand courses",
```

File: client/i18n/locales/english/intro.json [hunk 3]
```diff
@@ -560,7 +560,7 @@
...
+    "collapse": "Collapse Courses"
```
Comment (ieahleen) [inline client/i18n/locales/english/intro.json:564]:
```suggestion
    "collapse": "Collapse courses"
```

File: client/src/templates/Introduction/components/block.tsx (hunk 1 above)
Comment (PrashantSakre) [reply client/src/templates/Introduction/components/block.tsx:208]: Hi, I made changes as requested.

**Review by gikf — APPROVED** [review]
Seems to be okay :+1:

**Review by majestic-owl448 — APPROVED** [review]
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉
