### PR TITLE
fix(a11y): settings toggles

### LINKED ISSUE #49214: Toggle buttons on Settings page are not accessible
### Describe the Issue

I've been wanting to fix the toggle buttons on the Settings page for quite a while now. PR #48567 has already been started to implement a new ToggleButton component. I wanted to create this issue to make sure that any new components address all of the current accessibility issues. The current toggles have several issues:

- Their labels are not associated with their input
- They are not always keyboard accessible
- Some of them do not use the correct inputs for their functionality

There are two types of toggles on the Settings page:

- Toggles that invoke change immediately when the toggle value is changed (e.g. Night Mode, Campfire Mode).
- Toggles that only take effect when the corresponding Save button is clicked (e.g. the Privacy Settings).

These two toggles need to be created a little differently.

One option for the immediately invoked toggles is to use a group of two `button` elements, using the `aria-pressed` attribute to signal to screen readers which one is currently set. I have put together a codepen to demonstrate how this should be marked up and function.

[Accessible Toggle Group Using Buttons](https://codepen.io/bbsmooth/pen/PoBGVOZ)

Some of these types of toggles are of the On/Off variety and thus we could use an aria switch input for them if we wanted to introduce a third type of toggle. But I don't think this is a necessity, especially because one of these toggles is not On/Off. I think it would be better to be consistent across all of these toggles. So either use `button`s for them all or make them all On/Off toggles and use a switch.

The "delayed" toggles that can only be triggered with the Save button should be composed of a group of radio buttons. No special aria attributes need to be used here.

[Accessible Toggle Group Using Radio Button Inputs](https://codepen.io/bbsmooth/pen/KKBNmym)

A few questions:

- Do we want to create separate components for each type of toggle?
- The toggles should be wrapped in `fieldset`/`legend`s. Do we want to include that in these toggles?

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

N/A

### Expected behavior

See above write-up.

### Screenshots

_No response_

### System

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bbsmooth**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49214 

Sorry @Sboonny, I didn't realize you were working on this as well.

I just went with the browser's default radio buttons. Not sure if we want to use customized buttons?

### CODE REVIEW

**Comment by Sboonny** [comment]
> Sorry @Sboonny, I didn't realize you were working on this as well.

Didn't do much, to be honest, and I am always happy with the help, ping me if you want me to pick up a task.

**Comment by bbsmooth** [comment]
@Sboonny What I really need to know is how we want to style the radio buttons. That's the main blocker.

**Comment by Sboonny** [comment]
I don't mind the current look, but I will bring this to the Wednesday meeting, if needed 👍

**Comment by ahmadabdolsaheb** [comment]
We could go with something like this for the styles:
Screenshot 2023-03-15 at 12 23 34 PM

Also the tick for the toggle could come back if it does not have any accessibility issues.

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb I would be hesitant to use square boxes here since they are usually associated with check boxes, not radio buttons.

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+  action,
+  explain,
+  flag,
+  flagName,
+  toggleFlag,
+  ...restProps
+}: ToggleRadioSettingProps): JSX.Element {
+  const randomId = Math.floor(Math.random() * 1_000_000);
+  const firstRadioId = `radioA${randomId}`;
+  const secondRadioId = `radioB${randomId}`;
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:25]: Same as toggle button
```suggestion
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+  return (
+    <div className='toggle-setting-container'>
+      <fieldset
+        {...(explain && {
+          'aria-labelledby': `legend${randomId} desc${randomId}`
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:31]:
```suggestion
          'aria-labelledby': `legend${flagName} desc${flagName}`
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+        })}
+      >
+        <legend
+          className='sr-only'
+          {...(explain && { id: `legend${randomId}` })}
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:36]:
```suggestion
          {...(explain && { id: `legend${flagName}` })}
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+        >
+          {action}
+        </legend>
+        <div className='toggle-description'>
+          <p aria-hidden={true}>{action}</p>
+          {explain ? <p id={`desc${randomId}`}>{explain}</p> : null}
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:42]:
```suggestion
          {explain ? <p id={`desc${flagName}`}>{explain}</p> : null}
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+        </div>
+        <div className='toggle-radio-group'>
+          <label htmlFor={firstRadioId} data-checked={flag}>
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:45]:
```suggestion
          <label htmlFor={flagName} data-checked={flag}>
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+            <input
+              id={firstRadioId}
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:47]:
```suggestion
              id={flagName}
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+              {...(flag && { defaultChecked: true })}
+              {...(!flag && { onChange: toggleFlag })}
+              name={flagName}
+              value={1}
+            />
+            <span>{restProps.onLabel}</span>
+          </label>
+          <label htmlFor={secondRadioId} data-checked={!flag}>
+            <input
+              id={secondRadioId}
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:58]:
```suggestion
              id={flagName}
```

File: client/src/components/settings/toggle-radio-setting.tsx [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+              id={firstRadioId}
+              type='radio'
+              {...(flag && { defaultChecked: true })}
+              {...(!flag && { onChange: toggleFlag })}
+              name={flagName}
+              value={1}
+            />
+            <span>{restProps.onLabel}</span>
+          </label>
+          <label htmlFor={secondRadioId} data-checked={!flag}>
```
Comment (Sboonny) [inline client/src/components/settings/toggle-radio-setting.tsx:56]:
```suggestion
          <label htmlFor={flagName} data-checked={!flag}>
```

**Comment by Sboonny** [comment]
Just wondering, do we need aria-labelledby? I though legend with screen-only class is good enough to act as aria-labelledby.

What am I missing? https://www.w3.org/WAI/tutorials/forms/labels/#using-aria-labelledby

File: client/src/components/settings/toggle-button-setting.tsx [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+};
+
+export default function ToggleButtonSetting({
+  action,
+  explain,
+  flag,
+  toggleFlag,
+  ...restProps
+}: ToggleButtonSettingProps): JSX.Element {
+  const randomId = Math.floor(Math.random() * 1_000_000);
```
[the remark this answers is not in the document]
Comment (bbsmooth) [reply client/src/components/settings/toggle-button-setting.tsx:22]: Ahh, thanks for pointing this out. I think the reason I didn't use `flagName` in the first place is because originally they were not unique. If you look at the donation toggle you'll see that it was originally using `showPortfolio` for the `flagName` by mistake, thus there were duplicate `flagName` values. Even though I fixed that and they are all unique now, I must have forgot about it and decided to create a random ID instead to guarantee uniqueness.

**Comment by bbsmooth** [comment]
> do we need aria-labelledby?

You'll notice that `aria-labelledby` is only used when the toggle has extra description text. In that case, we use `aria-labelledby` to change the accessible name to include both the toggle name and the description text so that screen readers will announce both when the user is interacting with the toggle. This is a standard best practice pattern.

**Comment by ahmadabdolsaheb** [comment]
> @ahmadabdolsaheb I would be hesitant to use square boxes here since they are usually associated with check boxes, not radio buttons.
Sure, we could go with round ones.

File: client/src/components/settings/toggle-button-setting.tsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (Sboonny) [reply client/src/components/settings/toggle-button-setting.tsx:22]: Didn't notice the comment until ahmad pushed it to the notification, sorry for late reply.

I think this is the wrong mindset to have, there is 1/100000 chance that the random function id will provide the same id, so instead of relaying on chance to provide unique description, we can make it more obvious that `flagName` should be unique:

- adding comments.
- changing the variable to `screenReaderContext`.
- providing `@example` and `@params` in TypeScript, to show as hints in the editor.

it isn't enforcing the unique `flagName`, but people will be going out of their way to ignore all of these hints, and if contributor do, members shouldn't.

---

I know that we are people that do make mistakes, I can say that because I am the most person to make mistakes, but the solution shouldn't be making an abstract solution that can be forgotten, then removed because someone didn't remember the importance of the uniqueness.

but we have to get better and do better, and provide better info through the code that this is something that should be respected for these reasons.

[the remark this answers is not in the document]
Comment (bbsmooth) [reply client/src/components/settings/toggle-button-setting.tsx:22]: @Sboonny 
> there is 1/100000 chance that the random function id will provide the same id

I don't think this is an issue. React 18 now provides a `useId` hook which guarantees a unique id, so we can ultimately use that. In the meantime, there are modules we could use instead to get the same thing, such as react-id-generator. Or we could do our own checks to make sure the id generated by `random()` doesn't exist and just try again if it does. We could also use `Cryto.getRandomValues()` instead to get even better random numbers to decrease the chances of duplicates.

My point is that these ids are being used behind the scenes merely for accessibility reasons and thus they do not need to be known by the programmer, and should not depend on the programmer to give them a value since there is a chance of programmer error. I don't think this is an abstract solution. This is a perfectly reasonable solution to ensure that accessibility is met, and in my opinion, a much cleaner solution than all of the bullets points we'd have to implement above. And the reason for generating the id would not be forgotten as we can add a comment at the source explaining why we are generating a unique id.

But in reality, the chances of a developer using the same flagName is probably close to nil and so this is not a battle worth continuing :slightly_smiling_face: Because the accessibility of these controls needs urgent fixing and I would like to see it happen ASAP, I will acquiesce and make the suggested changes so we can get this merged.

File: client/src/components/settings/toggle-radio-setting.tsx (hunk 1 above)
Comment (bbsmooth) [reply client/src/components/settings/toggle-radio-setting.tsx:25]: I think it is best if we leave the `firstRadioId` and `secondRadioId` declarations here (and just use `flagName` instead of `randomId`) since these values are each used in two places below and thus if changed them for some reason we would only need to change them once here.

File: client/src/components/settings/toggle-radio-setting.tsx (hunk 5 above)
Comment (bbsmooth) [reply client/src/components/settings/toggle-radio-setting.tsx:44]: Leaving this as `firstRadioId` since it is used in more than one place.

File: client/src/components/settings/toggle-radio-setting.tsx (hunk 6 above)
Comment (bbsmooth) [reply client/src/components/settings/toggle-radio-setting.tsx:46]: Leaving this as `firstRadioId` since it is used in more than one place.

File: client/src/components/settings/toggle-radio-setting.tsx (hunk 8 above)
Comment (bbsmooth) [reply client/src/components/settings/toggle-radio-setting.tsx:55]: Leaving this as `secondRadioId` since it is used in more than one place.

File: client/src/components/settings/toggle-radio-setting.tsx (hunk 7 above)
Comment (bbsmooth) [reply client/src/components/settings/toggle-radio-setting.tsx:57]: Leaving this as `secondRadioId` since it is used in more than one place.

File: client/src/components/settings/toggle-button-setting.tsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (Sboonny) [reply client/src/components/settings/toggle-button-setting.tsx]: No need, if there's a better solution that provide a granted unique I'd, we can move to them later.

I was not aware of these other options q👍

**Review by Sboonny — APPROVED** [review]
Btw, you are right in this https://github.com/freeCodeCamp/freeCodeCamp/pull/49664#discussion_r1145562584, if you want to revert the lastest commit, please do so.

---

My suggestion was based on lack of knowledge, which you have provided. this is good to go after fixing the conflicts 👍.

**Comment by Sboonny** [comment]
@bbsmooth, Is it okay if I push a commit that sort RTL, and fix the conflict?

**Comment by bbsmooth** [comment]
@Sboonny Yes, go ahead.

**Comment by bbsmooth** [comment]
@Sboonny, are you done with your RTL updates? Everything looks pretty good, there are just a few minor things I'd like to adjust, but I want to wait until you are done.

**Comment by Sboonny** [comment]
Yeab, please go ahead. 👍

**Comment by bbsmooth** [comment]
@Sboonny I updated the styling on the buttons so that the text is always centered and the check mark will be positioned just to the outside of the text. I also added a slight gap between the buttons so that the outline focus indicator would show on all four sides of both buttons. But if you would rather not have that `3px` gap then we can add a background color to the `.toggle-button-group` wrapper `div` to fill that space.

The radio buttons still look the same but I switched their various margins to logical properties so they would look the same in rtl languages.

**Comment by Sboonny** [comment]
> But if you would rather not have that `3px` gap then we can add a background color to the `.toggle-button-group` wrapper `div` to fill that space. Or, we could remove the `3px` gap and then use relative positioning and `z-index` on the button when focused to make sure that it stacks above the other button so that all four sides of the outline show. 


No need, Idk what the others think, but I am happy with the current looks 👍.

File: client/src/components/settings/toggle-button-setting.tsx [hunk 10]
```diff
@@ -0,0 +1,88 @@
...
+
+type ToggleButtonSettingProps = {
+  action: string;
+  explain?: string;
+  flag: boolean;
+  toggleFlag: () => void;
+  offLabel: string;
+  onLabel: string;
+};
+
```
[the remark this answers is not in the document]
Comment (ahmadabdolsaheb) [reply client/src/components/settings/toggle-button-setting.tsx:11]: The styles could be moved the a css file.

**Comment by ahmadabdolsaheb** [comment]
Thank you for the hard work here.
 The difference between the inputs are harder to distinguish in dark mode than it is in Light mode.

Screenshot 2023-04-04 at 2 22 13 PM

Would it be possible to set the border of the unselected input to the secondary-color and the background to transparent or the secondary-background?

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb I agree, in dark mode it is hard to tell the difference between the selected and non-selected radio button. Browsers don't provide a lot of options for styling native radio buttons. I will see if I can somehow make the difference between the two states larger using only CSS but I fear I we may need to switch to some sort of custom solution.

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb Custom radio button styling added. Should be very clear now both in light and dark mode.

**Review by ahmaxed — APPROVED** [review]
Thanks for the hard here. I want to get this in asap, but there are a few changes that improve the toggle buttons in another pr:
- toggle-button.tsx in the helper folder could be removed since it is not used anywhere.
- checkIconStyle should be moved to a CSS file.
- we have toggle buttons in video courses (scientific-computing-with-python, etc.), the newly added toggles should replicate the style of the pre-exiting toggles for consistency.
