### PR TITLE
fix(client): scicompy links to new projects

### LINKED ISSUE #55091: SciComPy - Certification project links are broken
**Describe the bug**
Clicking on the certification project name results in `404 Page Not Found` both in settings and from the view certification page.
image

**To Reproduce**
1. Go to either [freecodecamp.org/settings#cert-scientific-computing-with-python-v7](https://www.freecodecamp.org/settings#cert-scientific-computing-with-python-v7) 
    or freecodecamp.org/certification/username/scientific-computing-with-python-v7 (note that you must replace `username` in the link)
3. Click on a certification project name
4. See 404 Page Not Found

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55091

Not sure how these slipped through for so long.

### CODE REVIEW

**Review by majestic-owl448 — CHANGES_REQUESTED** [review]
In the settings now the link is `http://localhost:8000/learn/scientific-computing-with-python//build-an-arithmetic-formatter-project/build-an-arithmetic-formatter-project`, those double slashes don't look good

File: client/config/cert-and-project-map.ts [hunk 1]
```diff
@@ -23,9 +23,7 @@ const apiMicroBase =
   '/learn/back-end-development-and-apis/back-end-development-and-apis-projects';
 const qaBase = '/learn/quality-assurance/quality-assurance-projects';
 const infoSecBase = '/learn/information-security/information-security-projects';
-const sciCompPyBase =
-  '/learn/scientific-computing-with-python/' +
-  'scientific-computing-with-python-projects';
+const sciCompPyBase = '/learn/scientific-computing-with-python/';
```
Comment (ilenia-magoni) [inline client/config/cert-and-project-map.ts:26]:
```suggestion
const sciCompPyBase = '/learn/scientific-computing-with-python';
```
I think this should be enough

**Review by majestic-owl448 — APPROVED** [review]

**Review by Dario-DC — APPROVED** [review]
