### PR TITLE
fix: improve universal navbar UI

### LINKED ISSUE #50610: Improve the navbar UI
### Describe the Issue

Navbar and its contents seem simple, redesigning the items and menu may improve the UI 

### Affected Page

https://www.freecodecamp.org

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org'
2. Play around with the navbar
3. Improve the menu
4. Good looking sign in/signup actions

### Expected behavior

enhance the design for a better look and feel 

### Screenshots

_No response_

### System

- Device: any
- OS: all
- Browser: all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by victor-duarte**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50610

- Increase site navigation height
- Updated CTA's size and spacing in site navigation for consistency
- Updates Microsoft logo `viewBox` values so that the SVG boundary is around the logo
   - Checked on exam navigation and certification page 
- Update CSS related to Microsoft logo usage
- Removed unused CSS and unneeded extra markup
- Update implementation to mobile-first
- Move and create variables to manage menu and elements heights
- Reduced number of breakpoints used
- Add scrolling to language menu

Notes:

- Checked that menu kept working across viewports
- There are still refactors that could be done to keep cleaning and improving code but it seems for the time being this should be enough
- The following were screenshots reviewed, if there are other pages or special conditions not reflected here it means it was not verified

**Exam navigation**
image

image

**Global navigation**

image

image

image

image

image=

**Certificate**

image

### CODE REVIEW

**Comment by bbsmooth** [comment]
Current production pic:
pic2

This PR pic:
pic1

This pics were taken with a 1280x1024 viewport zoomed into 400%. On the production pic you can see that all three buttons in the top right are visible while in the pic for this PR the rightmost button is cutoff. And if you have it on normal 100% zoom and narrow the viewport to 320px then almost the entire button is cutoff. On production, the fCC logo shrinks in order to accommodate the buttons.

Also, notice that the height of the navbar in this PR is about twice as tall as the one on production, which shrinks the viewable editor space down from three lines to two lines. Not saying we need to solve this issue in this PR. Just putting in a plug for my issue [#49054](https://github.com/freeCodeCamp/freeCodeCamp/issues/49054).

**Comment by victor-duarte** [comment]
@bbsmooth, an update has been pushed to handle https://github.com/freeCodeCamp/freeCodeCamp/pull/51108#issuecomment-1662848740:

_"This pics were taken with a 1280x1024 viewport zoomed into 400%. On the production pic you can see that all three buttons in the top right are visible while in the pic for this PR the rightmost button is cutoff. And if you have it on normal 100% zoom and narrow the viewport to 320px then almost the entire button is cutoff. On production, the fCC logo shrinks in order to accommodate the buttons."_

**320px**
image

**1280px zoomed 400%**
image

Regarding the second comment,

_"Also, notice that the height of the navbar in this PR is about twice as tall as the one on production, which shrinks the viewable editor space down from three lines to two lines. Not saying we need to solve this issue in this PR."_

Correct, the height was increased. If needed to be changed please advise since the ticket only said to increase the height as a whole and not specific to a screen viewport.

Thank you, for looking.

**Comment by ahmaxed** [comment]
Thank you for working on this PR. It looks pretty good.
Although the height of the universal navigation need changing, the size of the buttons should stay the same. That allows for sufficient space between active elements during scrolling. 

Could you please make sure the size of the buttons stay the same?

**Comment by Sboonny** [comment]
> New issue. Zoom in to 400%. Expand either the language or main menu. Notice that you can't scroll either menu.
> 
> P.S. I just noticed that on production you can scroll the main menu at 400% zoom but you can't scroll the language menu. So it looks like we missed that when initially adding the language menu.

Bruce, have you started working on this? is it okay if I pick it up?

**Comment by bbsmooth** [comment]
> Bruce, have you started working on this?

No. I figured @victor-duarte would fix it in this PR.

**Comment by Sboonny** [comment]
Make senses 👍, Victor if you need help, say so in the forum or our discord, we are happy to help.

**Comment by victor-duarte** [comment]
Changes made:
- Update CTA heights to match production and be consistent between these so the outcome is that only the height of the navigation bar changed and some items height changed, e.g: signup button height matches the sibling buttons.
- Update language menu to be scrollable
- Update main menu to be scrollable
- Update PR description and images

@Sboonny, @bbsmooth, @ahmaxed

**Comment by ahmaxed** [comment]
Thank you for iterating on your solution. The label change was a mistake. I will take a look at your PR in detail first thing tomorrow.

**Comment by ahmaxed** [comment]
I looked into the pr and notice the following two changes:
- The border around the avatar is not showing up. ( pnpm run seed:certified-user  for more visibility)
- On the Microsoft certification, the Microsoft logo be smaller to achieve an asymmetrical balance with the freeCodeCamp logo.

**Comment by victor-duarte** [comment]
Updates done following up on https://github.com/freeCodeCamp/freeCodeCamp/pull/51108#issuecomment-1682010765 comments.

- Display border around avatar:
image

- Adjust Microsoft logo height (eyeballed) in Certification screen so logos have a similar height
image

cc: @ahmaxed

**Comment by victor-duarte** [comment]
@ahmaxed, @raisedadead, by mistake I hit the close with comment cta 😢 

Can you re-open the PR or should I create a new one?

**Review by ahmaxed — APPROVED** [review]

File: client/src/components/Header/components/language-list.tsx [hunk 1]
```diff
@@ -52,11 +52,9 @@ const LanguageList = ({ t, navigate }: LanguageListProps): JSX.Element => {
   // the accessibility tree just needs a little more time to pick up the change.
   // This function allows us to set aria-expanded to false and then delay just a bit before setting focus on the button
   const closeAndFocus = () => {
-    listButtonRef.current?.classList.add('force-show');
     setShowList(false);
     setTimeout(() => {
       listButtonRef.current?.focus();
-      listButtonRef.current?.classList.remove('force-show');
     }, 100);
```
Comment (Sboonny) [inline client/src/components/Header/components/language-list.tsx:58]: >  We need the force-show class to keep the menu open when aria-expanded is set to false otherwise the menu will be display: none and we'll lose keyboard focus before we set it on the button

More context in Bruce's comment https://github.com/freeCodeCamp/freeCodeCamp/pull/50084#discussion_r1175996808

How did you provide the necessary time for the accessibility tree to pick up the change, without the classes?

Comment (victor-duarte) [reply client/src/components/Header/components/language-list.tsx]: I did not experience any a11y issues using (voiceover) nevertheless the changes have been reverted to avoid any undesired behaviors, these have been added back as the associated css.

Comment (bbsmooth) [reply client/src/components/Header/components/language-list.tsx]: Not every screen reader may need this fix, and sometimes only one does. It could very well be that NVDA is the only one that needs it.

**Comment by bbsmooth** [comment]
This is the language menu expanded when the browser height is less than the height of the menu:

language-menu

Notice the menu extends all the way down to the bottom of the view port.

This is the main menu expanded when the browser height is less than the height of the menu:

main-menu

Notice that the menu does not extend all the way down to the bottom of the view port.

Not sure if this difference in behavior needs to be addressed?

**Comment by victor-duarte** [comment]
And update for https://github.com/freeCodeCamp/freeCodeCamp/pull/51108#issuecomment-1712655385 has been pushed.

-  Gap removed
- Both menus should have similar behaviors

**Review by bbsmooth — APPROVED** [review]
I'm not seeing any accessibility issues introduced by this PR and everything seems to be working fine.

I will note that I wasn't able to test the microsoft logo since I'm not smart enough to figure out how to get into the exam.

Approved.
