### PR TITLE
fix(client): preserve scroll position of preview iframe

### LINKED ISSUE #46061: Iframe bounces back to top when running tests
### Describe the Issue

There seems to be an issue with the Iframe (this happens when having an Iframe with a scrollbar)

So to reproduce:
1.  scroll down in the Iframe
2. run the tests
3. Iframe pops back to the top

This might be annoying when trying to see the changes you made.

### Affected Page

https://freecodecamp.org/learn/2022/responsive-web-design/

### Your code

```

```

### Expected behavior

When running the test the Iframe should stay in place.

### Screenshots

_No response_

### System

- Device:  Desktop
- OS: Windows 11
- Browser:  Brave
- Version: V1.38.119

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saw-jan**
Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Possibly Closes #46061

**Difficulties**:
I tried using hooks and refs in order to achieve this but there were some unexpected behavior and difficulties. Using hooks didn't work for the initial render (mount) but only worked for the later re-renders (after some change in the content) - this could be due to the fact that the document contents are loaded later in the iframe.

The implementation in this PR was only the way (hack) with which I was able to achieve the expected behavior.

**Improvements**:
I believe this is not the best way to implement it but I couldn't find any. Hooks could be the best option but that didn't work.
Also, the scroll position could be stored in the store as state but I didn't dive deep into the store part.

**Result**:

[Screencast from 10-06-2022 06:46:41 PM.webm](https://user-images.githubusercontent.com/52366632/194320301-0fd40321-ef47-481c-8685-b93b8a48ea52.webm)

CC @moT01 @Sembauke @DerrykBoyd

### CODE REVIEW

File: client/src/templates/Challenges/components/preview.tsx [hunk 1]
```diff
@@ -29,6 +29,13 @@ function Preview({
     setIframeStatus(disableIframe);
   }, [disableIframe]);
 
+  useEffect(() => {
+    // reset scroll position on unmount
```
Comment (Sboonny) [inline client/src/templates/Challenges/components/preview.tsx:33]:
```suggestion
```

File: client/src/templates/Challenges/utils/frame.ts [hunk 2]
```diff
@@ -264,9 +264,39 @@ const writeContentToFrame = (frameContext: Context) => {
     createHeader(frameContext.element.id) + frameContext.build,
     frameContext.document
   );
+
+  const iframe = document.getElementById(
+    frameContext.element.id
+  ) as HTMLIFrameElement;
+  // register scroll event listner
```
Comment (Sboonny) [inline client/src/templates/Challenges/utils/frame.ts:271]:
```suggestion
```

File: client/src/templates/Challenges/utils/frame.ts [hunk 3]
```diff
@@ -264,9 +264,39 @@ const writeContentToFrame = (frameContext: Context) => {
...
+  registerScrollEventListner(iframe);
+  // restore scroll position
```
Comment (Sboonny) [inline client/src/templates/Challenges/utils/frame.ts:273]:
```suggestion
```

**Review by Sboonny — DISMISSED** [review]
There is no need to add comments, about what the functions and effect do.

If you think there is a need for a comment, you can add context of the issue. Something in the vibes of this 

> The iframe unmount and scrolls back to the top whenever camper edit their code in the editor,
> this effect aims to stop the scrolling behaviour when the iframe is unmounted

**Comment by saw-jan** [comment]
Re-requesting review from one automatically removes other reviewers :smiling_face_with_tear:

**Review by Sembauke — DISMISSED** [review]

**Review by moT01 — COMMENTED** [review]
This works real good @saw-jan 🎉 

Do you think we could add it to the preview-portal component? It's the preview that opens in a separate window when you click the icon button above the preview here:
Screen Shot 2022-10-11 at 4 44 25 PM

It doesn't work there.

File: client/src/templates/Challenges/utils/frame.ts [hunk 4]
```diff
@@ -264,9 +264,39 @@ const writeContentToFrame = (frameContext: Context) => {
...
 
+let previewScrollPosition = 0;
+export const getPreviewScrollPosition = () => previewScrollPosition;
+export const setPreviewScrollPosition = (position: number) =>
+  (previewScrollPosition = position);
+
+const registerScrollEventListner = (iframe: HTMLIFrameElement) => {
+  iframe?.contentDocument?.addEventListener('scroll', event => {
+    const target = event.target as Document;
+    setPreviewScrollPosition(target.body.scrollTop);
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/utils/frame.ts:288]: Two things here:
1) This type assertions suggests something fishy is going on - we should try not to assert this type (use a type guard, at the very least)
2) The `scroll` event should be rate limited: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event#scroll_event_throttling

File: client/src/templates/Challenges/utils/frame.ts [hunk 5]
```diff
@@ -264,9 +264,39 @@ const writeContentToFrame = (frameContext: Context) => {
...
+  });
+};
+
+const restorePreviewScrollPosition = (
+  iframe: HTMLIFrameElement,
+  position: number
+) => {
+  if (iframe.contentDocument?.body)
+    iframe.contentDocument.body.scrollTop = position;
```
Comment (ShaunSHamilton) [inline client/src/templates/Challenges/utils/frame.ts:297]:
```suggestion
  if (iframe.contentDocument?.body) {
    iframe.contentDocument.body.scrollTop = position;
  }
```

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]

**Comment by saw-jan** [comment]
> This works real good @saw-jan tada
> 
> Do you think we could add it to the preview-portal component? It's the preview that opens in a separate window when you click the icon button above the preview here: Screen Shot 2022-10-11 at 4 44 25 PM
> 
> It doesn't work there.

I will give it a try.

File: client/src/templates/Challenges/utils/frame.ts (hunk 4 above)
Comment (saw-jan) [reply client/src/templates/Challenges/utils/frame.ts]: @ShaunSHamilton,

`(1)` - I have removed the use of type guard.
`(2)` - Upon scroll, only the variable `previewScrollPosition` will get updated, not much of heavy operation. So, is it necessary to rate limit here?

File: client/src/templates/Challenges/utils/frame.ts [hunk 6]
```diff
@@ -264,9 +264,39 @@ const writeContentToFrame = (frameContext: Context) => {
...
+export const getPreviewScrollPosition = () => previewScrollPosition;
+export const setPreviewScrollPosition = (position: number) =>
+  (previewScrollPosition = position);
+
+const registerScrollEventListner = (iframe: HTMLIFrameElement) => {
+  iframe?.contentDocument?.addEventListener('scroll', event => {
+    const target = event.target as Document;
+    setPreviewScrollPosition(target.body.scrollTop);
+  });
+};
```
[the remark this answers is not in the document]
Comment (saw-jan) [reply client/src/templates/Challenges/utils/frame.ts]: Yeah, I also didn't find other way to implement this.

Things I have tried:
- use component `hooks` to restore scroll position (didn't work)
- use `redux store` (didn't work) - could have worked but the store is not exported and also, the store is created in `client/gatsby-browser.js`

**Comment by saw-jan** [comment]
> > This works real good @saw-jan tada
> > Do you think we could add it to the preview-portal component? It's the preview that opens in a separate window when you click the icon button above the preview here: Screen Shot 2022-10-11 at 4 44 25 PM
> > It doesn't work there.
> 
> I will give it a try.

This is also working while editing the content. Only at the time of detaching, the scroll will get reset (may be the global variable will get reset while creating iframe)

File: client/src/templates/Challenges/utils/frame.ts (hunk 4 above)
Comment (ShaunSHamilton) [reply client/src/templates/Challenges/utils/frame.ts]: > not much of heavy operation. So, is it necessary to rate limit here?

You are quite right. There would probably be no benefit (_might even make it worse_ 😨 )

File: client/src/templates/Challenges/utils/frame.ts [hunk 7]
```diff
@@ -267,9 +271,44 @@ const writeContentToFrame = (frameContext: Context) => {
...
 
+let previewScrollPosition = 0;
+export const getPreviewScrollPosition = () => previewScrollPosition;
+export const setPreviewScrollPosition = (position: number) =>
+  (previewScrollPosition = position);
+
+const registerScrollEventListner = (iframe: HTMLIFrameElement) => {
+  iframe.contentDocument?.addEventListener(
+    'scroll',
+    (event: IframeEvent<Document>) => {
```
Comment (saw-jan) [inline client/src/templates/Challenges/utils/frame.ts:294]: It looks like I can't even use the custom type in the listener function. Now, I can only think of using type guard.
CC @ShaunSHamilton

Comment (ShaunSHamilton) [reply client/src/templates/Challenges/utils/frame.ts:294]: I will push up the necessary changes.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @saw-jan thanks for your hard work on this.  While this PR does address the immediate problem (scroll position being reset), the root cause is that the preview is being recreated each time tests are run.  I'm not sure why we've been doing this, but it's not necessary. The tests run in their own frame and do not depend on the state of the preview.

This can be solved by reworking client/src/templates/Challenges/redux/execute-challenge-saga.js. Everything that uses `previewTask` can be removed and `executeCancellablePreviewSaga` can be replaced with `previewChallengeSaga`

**Comment by saw-jan** [comment]
> Hi @saw-jan thanks for your hard work on this. While this PR does address the immediate problem (scroll position being reset), the root cause is that the preview is being recreated each time tests are run. I'm not sure why we've been doing this, but it's not necessary. The tests run in their own frame and do not depend on the state of the preview.
> 
> This can be solved by reworking client/src/templates/Challenges/redux/execute-challenge-saga.js. Everything that uses `previewTask` can be removed and `executeCancellablePreviewSaga` can be replaced with `previewChallengeSaga`

So, does it also work when editing the content? Will it preserve the scroll position in the preview panel?

**Comment by saw-jan** [comment]
> No, but that's fine. The preview does get reset each time the content changes (it has to), so I'm not convinced there's anything that needs fixing. The preview is accurately reflecting the fact that it's changed, after all.

Yeah, regarding the rendering of the preview panel when running tests, I agree that the test run should not have affected the preview panel and should not cause the re-render of the preview.

Another thing this PR aims to solve is also to prevent the scrolling of the preview panel to the top so that the user can see the changes they made without having to scroll up or down.
> This might be annoying when trying to see the changes you made. [ From #46061 ]

**Comment by ojeytonwilliams** [comment]
> Another thing this PR aims to solve is also to prevent the scrolling of the preview panel to the top so that the user can see the changes they made without having to scroll up or down.

Yep, understood.  I get the motivation to prevent this, as it could be annoying, but I don't consider it to be a bug. It is, essentially, a visual hint that the preview has been recreated.  Obviously that's a side-effect of how we create the preview, but it serves a purpose.

Finally, storing the scroll position creates some strange behaviour that I do consider to be bugs.  If, for example, you delete the entirety of the user's code and then paste it back in, it remembers the original position and scrolls you automatically.

**Comment by ojeytonwilliams** [comment]
I just wanted to reiterate, the problem was a lack of discussion in the first place.  This PR did, after all, solve the issue as originally stated.

**Comment by moT01** [comment]
That's my fault, I said to just go for it. I suppose it's a matter of preference. Some people may prefer that it scrolls to the top as that indicator of a refresh - some may prefer it stay where it is so they can see the changes without having to scroll. Each method probably has some pro's and con's - I'm imagining working on a cert project that is very tall, like maybe the technical documentation project. Each time you type something, it "scrolls" to the top, so you scroll down to see your changes, then add some more changes, and repeat. It's not much of a hassle, but it is something. It's a more realistic experience, I suppose, cause the browser wouldn't ever actually do this on its own - although, I do like the seeing my changes immediately - so, I'm on the fence.

> If, for example, you delete the entirety of the user's code and then paste it back in, it remembers the original position and scrolls you automatically.

That does seem like a bit of a negative side effect - it would bet that it's uncommon and it seems pretty minor. There may be others though.

So what I'm hearing from you @ojeytonwilliams, is that you don't think we should preserve the scroll position - or are you just pointing out some concerns?

**Comment by ojeytonwilliams** [comment]
> So what I'm hearing from you @ojeytonwilliams, is that you don't think we should preserve the scroll position

On balance, I don't think we should.  If we get a lot of feedback that the scrolling is frustrating, we can definitely revisit this, but it seems premature to fix it before then.

The fact that the tests reset the preview is definitely a bug, though, so it would be good to fix that.

**Comment by ojeytonwilliams** [comment]
I like that idea @sidemt. If we have a setting that can disables auto-refresh and shows an 'Update Preview' button, that could work well for everyone.  My reservations about the scroll position getting stuck wouldn't apply in this case.

**Comment by moT01** [comment]
> I think we should add a loading icon separately.

I like the idea of a loader here - it might not be necessary because the preview loads so fast that you probably won't even see it. But, there could be some slow loading pages I guess, depending on what you have - so it's probably only an improvement. I would be on board.

> ...add an option to turn off the auto-refresh...

I like this idea, too. I always turn it off on codepen, as well. But, perhaps we don't want give campers that option on challenges, maybe only the cert projects - and, we would need to make sure to automatically do the initial load? maybe. Probably need an issue to discuss and work out some details.

Those are probably for another PR. As far as this PR goes, it sounds like we are leaning towards adding this behavior of saving the scroll location. Yoko is in favor, I'm leaning towards adding it, Oliver doesn't really think we should add it. I think we should get another opinion or two. If you haven't tested it out @ojeytonwilliams, I might recommend pulling the PR down and seeing it in action - it's pretty slick.

**Comment by ojeytonwilliams** [comment]
I've given it a try locally and, yeah, it's slick. @saw-jan did a great job.  To be 100% clear, I think it's implemented well, I just prefer the other options (particularly Yoko's suggestion).

>  I think we should get another opinion or two. 

Agreed.

**Comment by moT01** [comment]
Yes, these are separate issues.

> Do we need configuration options for both?

For this issue of preserving the scroll position, I would vote not to add an option to turn it on and off. It feels like too small of a feature to need an option for that. I would rather either add it or not, and don't give campers an option. The other issue, yes - make that configurable.

**Review by sidemt — DISMISSED** [review]
So can I give LGTM to this PR? For other improvements discussed above, we should create separate issues.

**Comment by ojeytonwilliams** [comment]
@sidemt I haven't a had chance to go through the code properly, but I will do that now.

File: tsconfig-base.json [hunk 8]
```diff
@@ -1,6 +1,6 @@
 {
   "compilerOptions": {
-    "lib": ["WebWorker", "DOM", "DOM.Iterable"],
+    "lib": ["WebWorker", "DOM", "DOM.Iterable", "ES2022"],
```
Comment (ojeytonwilliams) [inline tsconfig-base.json:3]:
```suggestion
    "lib": ["WebWorker", "DOM", "DOM.Iterable"],
```
What was this intended to do?  @ShaunSHamilton

File: client/src/templates/Challenges/utils/frame.ts [hunk 9]
```diff
@@ -267,9 +267,44 @@ const writeContentToFrame = (frameContext: Context) => {
...
+
+const restorePreviewScrollPosition = (
+  iframe: HTMLIFrameElement,
+  position: number
+) => {
+  if (iframe.contentDocument?.body) {
+    iframe.contentDocument.body.scrollTop = position;
+  }
+};
+
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/frame.ts:307]: Rather than have these be globals, I think this is a good time to use a class.  That class, maybe `ScrollManager`, can hold `previewScrollPosition` and have `registerScrollEventListner` and `restorePreviewScrollPosition` as methods.

We'd still be polluting the global scope, but less so. Also, it's very clear that what all these various functions and variables are for.

File: client/src/templates/Challenges/utils/frame.ts [hunk 10]
```diff
@@ -267,9 +267,44 @@ const writeContentToFrame = (frameContext: Context) => {
...
+  }
   return frameContext;
 };
 
+let previewScrollPosition = 0;
+export const getPreviewScrollPosition = () => previewScrollPosition;
+export const setPreviewScrollPosition = (position: number) =>
+  (previewScrollPosition = position);
+
+const registerScrollEventListner = (iframe: HTMLIFrameElement) => {
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/frame.ts:287]:
```suggestion
const registerScrollEventListener = (iframe: HTMLIFrameElement) => {
```
Typo.

File: client/src/templates/Challenges/utils/frame.ts [hunk 11]
```diff
@@ -267,9 +267,44 @@ const writeContentToFrame = (frameContext: Context) => {
...
+  iframe.contentDocument?.addEventListener(
+    'scroll',
+    (event: IframeEvent<Document>) => {
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/frame.ts:290]:
```suggestion
    (event) => {
```
This type doesn't exist, but `Event` is fine.

File: client/src/templates/Challenges/utils/frame.ts [hunk 12]
```diff
@@ -267,9 +267,44 @@ const writeContentToFrame = (frameContext: Context) => {
...
+      const { target } = event;
+      if (target.body.scrollTop) {
+        setPreviewScrollPosition(target.body.scrollTop);
```
Comment (ojeytonwilliams) [inline client/src/templates/Challenges/utils/frame.ts:293]:
```suggestion
      const currentTarget = event.currentTarget as Document | null;
      if (currentTarget?.body.scrollTop) {
        setPreviewScrollPosition(currentTarget?.body.scrollTop);
      }
```
`currentTarget` is safer because we know that it's `iframe.contentDocument` because that's what the listener was attached to.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

**Comment by ojeytonwilliams** [comment]
Sorry for the delay getting around to looking at the code, @saw-jan. Also, thanks for your patience through the deliberations.

File: tsconfig-base.json (hunk 8 above)
Comment (ShaunSHamilton) [reply tsconfig-base.json:3]: I cannot remember. Potentially, it was needed for one of the newer Object/Array methods - normally why I add it to configs.

That is to say, it may have been necessary for a change that is **no longer** here.

Comment (ojeytonwilliams) [reply tsconfig-base.json:3]: No worries.  Let's try without and see if any type errors appear.

File: client/src/templates/Challenges/utils/frame.ts (hunk 9 above)
Comment (saw-jan) [reply client/src/templates/Challenges/utils/frame.ts:307]: @ojeytonwilliams Where should I keep that class? In this file or make a separate one?

Comment (saw-jan) [reply client/src/templates/Challenges/utils/frame.ts]: I added the class in the same file for now.

**Review by ojeytonwilliams — APPROVED** [review]
This looks very clean and is working flawlessly.  Thanks @saw-jan!

File: client/src/templates/Challenges/utils/frame.ts (hunk 9 above)
Comment (ojeytonwilliams) [reply client/src/templates/Challenges/utils/frame.ts]: It's only used here, so that works.

**Review by raisedadead — APPROVED** [review]
