### PR TITLE
fix: separate footer from hits

### LINKED ISSUE #57100: Separation of concerns in search bar
We should not be adding a fake "footer" hit to the array of hits coming back from Algolia. It's not a hit and treating it as such is confusing and messy.

We don't need to use instantsearch's `Highlight`, since the component is very simple. Instead we should make our own. 

_Originally posted by @ojeytonwilliams in https://github.com/freeCodeCamp/freeCodeCamp/issues/57020#issuecomment-2464652794_ and edited a little for clarity.
            

The relevant code starts here: https://github.com/freeCodeCamp/freeCodeCamp/blob/6c34c2b341f9ada6f22880c018eae32541779f93/client/src/components/search/searchBar/search-hits.tsx#L39

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57100

### CODE REVIEW

File: client/src/components/search/searchBar/search-bar-footer.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+const SearchBarFooter = ({
+  hasHits,
+  query,
+  handleMouseEnter,
+  handleMouseLeave
+}: SearchBarFooterProps) => {
+  const { t } = useTranslation();
+  const title = t('search.no-tutorials');
+
+  const searchUrl = searchPageUrl;
```
Comment (ojeytonwilliams) [inline client/src/components/search/searchBar/search-bar-footer.tsx:22]:
```suggestion
```
Using `searchPageUrl` directly seems fine, tbh.

File: client/src/components/search/searchBar/search-bar-footer.tsx [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+  if (hasHits && query) {
```
Comment (ojeytonwilliams) [inline client/src/components/search/searchBar/search-bar-footer.tsx:24]: Since `!query` means we return `null`, you can just do that first and simplify the logic to `if (hasHits)`. That or `return hasHits ? ... : ...`

File: client/src/components/search/searchBar/search-bar-footer.tsx [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+          href={searchUrl + '?query=' + encodeURIComponent(query ?? '')}
+          rel='noopener noreferrer'
+          target='_blank'
+        >
+          <span className='hit-name'>
+            {t('search.see-results', { searchQuery: query })}
+          </span>
+        </a>
+      </li>
+    );
```
Comment (ojeytonwilliams) [inline client/src/components/search/searchBar/search-bar-footer.tsx:38]: I think this also needs to react to mouse enters and leaves. `onMouseEnter` and `onMouseLeave` should do the trick.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

**Review by moT01 — APPROVED** [review]

**Comment by Sembauke** [comment]
@ojeytonwilliams Could you give this another look?

**Review by ojeytonwilliams — APPROVED** [review]
Sorry for the delay, Sem. LGTM :+1:
