### PR TITLE
Fix steak calculation to not break when challenges are completed everyday

### LINKED ISSUE #6721: Steak is broken though challenges were completed everyday
This issue was originally reported by @thebgar.

The problem happens when the difference between two dates is bigger than 36 hours, but these dates still fall into two consecutive days.
screen shot 2016-02-03 at 2 56 42 pm

The dates are such:
1. 2016-02-02T04:12:43
2. 2016-02-01T05:32:25
3. 2016-01-31T18:34:15
4. 2016-01-30T17:27:53
5. 2016-01-29T04:15:04
6. 2016-01-28T05:42:50
...

It's obvious, that student has worked everyday (starting from Jan 15 till Feb 2), but when streak is calculated it considers a break between dates 4 and 5. Because in this case the difference between two dates is 1.55 days, which is more than declared constant 1.5.

I want to create this issue as a separate one, since it's not timezone related issue.
Right now I'm fixing this issue and also adding new tests to cover this particular use case.

### PR DESCRIPTION
**Pull request by LenaBarinova**
New function to prepare timestamps for streak calculation was added: it converts all timestamps to start of the day (in given timezone) and filters to distinct days. Tests added for this new function.
Unique days are being sorted only once (instead of twice): current streak calculation is done from right to left, longest streak - from left to right.
Current streak calculation changed to return after current streak is found. 
In unit tests date faking added for `new Date()` or `moment()` to return fixed date all the time. Tests become none time specific.

closes #6721

### CODE REVIEW

**Comment by SaintPeter** [comment]
I've examined the code and done some local testing and this appears to work properly and, at least, not obviously break anything.

@BerkeleyTrue Do you want to take a quick look before we merge?

File: server/utils/user-stats.js [hunk 1]
```diff
@@ -1,46 +1,55 @@
...
+    .forEachRight(cur => {
+    if (moment(prev).diff(cur, 'days') < daysBetween) {
+      prev = cur;
+      currentStreak++;
+    } else {
+      // current streak found
+      streakContinues = false;
+    }
+    return streakContinues;
+  });
```
Comment (BerkeleyTrue) [inline server/utils/user-stats.js]: Line 26-34 should be indented to indicate they are part of the `.forEachRight` function

**Comment by LenaBarinova** [comment]
@BerkeleyTrue thanks for noticing indentation, it left broken after some refactoring. 
Fixed it and pushed.

**Comment by SaintPeter** [comment]
Thanks @LenaBarinova!  :+1:

**Comment by TheBGar** [comment]
@LenaBarinova Greatly appreciate all your hard work on this. Well done and thank you!
