### PR TITLE
 fix(challenge): Handle slow network connections gracefully 

### LINKED ISSUE #16803: [beta] Unable to get any challenges from a superblock that I did not start with in the first place.
Unable to get any challenges from a superblock that I did not start with in the first place.

1. Started with ES6, and then signed in on fresh instance of the browser.
2. Went to the HTML super block.
3. Clicked through a few challenges.
4. I am getting the empty state.

image

### PR DESCRIPTION
**Pull request by Bouncey**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16803

#### Description

Provide feedback to the user that the app is 'doing stuff' whilst we wait for a response from the server for the requested block.

This PR adds an overlay loader which is triggered when we do not have the current challenge description.

This PR also addresses my mistake in thinking that `lodash.merge()` wasn't mutating state.

### CODE REVIEW

File: common/app/routes/Challenges/Side-Panel.jsx [hunk 1]
```diff
@@ -95,7 +97,8 @@ export class SidePanel extends PureComponent {
     this.descriptionTop = node;
   }
 
-  renderDescription(description = [ 'Happy Coding!' ]) {
+  renderDescription() {
+    const { description = [ 'Happy Coding!' ] } = this.props;
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/Side-Panel.jsx]: I've seen you introducing these changes in other places (moving passed in args to props destructuring). They don't seem to be related to the PR they are in. Is there something I'm missing?

This is a pattern I intentionally use where possible so that you only need to look at the render method to see where props are being used.

File: common/app/routes/Challenges/views/step/Show.jsx [hunk 2]
```diff
@@ -27,9 +31,12 @@ const renderPane = name => {
   return Comp ? <Comp /> : <span>Pane { name } not found</span>;
 };
 
-export default function ShowStep() {
+export default function ShowStep({ showLoading }) {
   return (
     <ChildContainer isFullWidth={ true }>
+      {
+        showLoading ? <OverlayLoader /> : null
+      }
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/views/step/Show.jsx]: There is a repeated pattern here. We can make this DRY by moving this up into the Challenges/Child-Contianer.jsx

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

File: common/app/routes/Challenges/Child-Container.jsx [hunk 3]
```diff
@@ -1,20 +1,56 @@
...
-    <AppChildContainer { ...props }>
-      { children }
-      <CompletionModal />
-    </AppChildContainer>
-  );
+class ChildContainer extends PureComponent {
+  componentDidUpdate(prevProps) {
+    const { challenge = {}, challengeUpdated } = this.props;
+    if (prevProps.showLoading && !this.props.showLoading) {
+      challengeUpdated(challenge);
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/Child-Container.jsx]: Why are you dispatching a challenge updated here?

File: common/app/routes/Challenges/Child-Container.jsx [hunk 4]
```diff
@@ -1,20 +1,56 @@
...
 import AppChildContainer from '../../Child-Container.jsx';
+import { OverlayLoader } from '../../helperComponents';
+
+const mapStateToProps = createSelector(
+  challengeSelector,
+  challenge => {
+    const { description } = challenge;
+    return {
+      challenge,
+      showLoading: !description || description.length === 0
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/Child-Container.jsx]: This make the loading script brittle, as we cannot guarantee every challenge in the future will have a description. Why not use _.empty?

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Comment by BerkeleyTrue** [comment]
Can you give me steps to QA this? I can't trigger the overlay.

File: common/app/routes/Challenges/Child-Container.jsx (hunk 4 above)
Comment (Bouncey) [reply common/app/routes/Challenges/Child-Container.jsx]: I need to use some property of a challenge that will always be there for a rendered challenge, but will not be available if only the mapUi data is available. `description` seemed like the most sensible option at the time. 

Do you have another suggestion?

File: common/app/routes/Challenges/Child-Container.jsx (hunk 3 above)
Comment (Bouncey) [reply common/app/routes/Challenges/Child-Container.jsx]: Because `state.file` does not update when new challenge data is available, which means the editor doesn't render with that challenge seed (classic) or `Panes` fails to find the correct component (modern). 

This appropriately describes what is actually happening when we receive new `block` data

**Comment by Bouncey** [comment]
Steps to QA

1. Load the app
2. Throttle connection (GPRS worked best for me whilst building)
3. Select a challenge in a different block that you have not previously fetched
4. Sit amazed and in awe of my amazing loader 😆

File: common/app/routes/Challenges/Child-Container.jsx [hunk 5]
```diff
@@ -1,20 +1,57 @@
...
+import { fullBlocksSelector } from '../../entities';
+import { paramsSelector } from '../../Router/redux';
+
+const mapStateToProps = createSelector(
+  challengeSelector,
+  fullBlocksSelector,
+  paramsSelector,
+  (challenge, fullBlocks, { block }) => ({
+      challenge,
+      showLoading: !fullBlocks.includes(block)
```
Comment (Bouncey) [inline common/app/routes/Challenges/Child-Container.jsx]: @BerkeleyTrue this should be more robust

File: common/app/routes/Challenges/Child-Container.jsx (hunk 3 above)
Comment (BerkeleyTrue) [reply common/app/routes/Challenges/Child-Container.jsx]: If the goal is to update the preview plane why not add the action actually related to the event of updating blocks to the updateMain epic so we have a direct cause->effect relationship. 

https://github.com/freecodecamp/freecodecamp/blob/staging/common/app/routes/Challenges/redux/execute-challenge-epic.js#L45

File: common/app/routes/Challenges/Child-Container.jsx (hunk 5 above)
Comment (BerkeleyTrue) [reply common/app/routes/Challenges/Child-Container.jsx]: :+1:

File: common/app/routes/Challenges/Child-Container.jsx (hunk 3 above)
Comment (Bouncey) [reply common/app/routes/Challenges/Child-Container.jsx]: It is the challenge seed that is the problem, I need to dispatch an action that creates the Poly with the correct content for the editor.

Comment (BerkeleyTrue) [reply common/app/routes/Challenges/Child-Container.jsx]: Is the problem here that the action that changes the showLoading from true->false can't trigger the files reducer to also update?

File: common/app/routes/Challenges/Child-Container.jsx [hunk 6]
```diff
@@ -1,57 +1,25 @@
...
-    })
-);
-
-const mapDispatchToProps = { challengeUpdated };
 
 const propTypes = {
   challenge: PropTypes.object,
-  challengeUpdated: PropTypes.func.isRequired,
   children: PropTypes.node,
   showLoading: PropTypes.bool
```
Comment (BerkeleyTrue) [inline common/app/routes/Challenges/Child-Container.jsx]: Is `showLoading` still required here?

**Review by BerkeleyTrue — CHANGES_REQUESTED** [review]

**Comment by BerkeleyTrue** [comment]
We need to disable the tool panel buttons or use some skeleton buttons:

tool-panel

**Review by BerkeleyTrue — APPROVED** [review]

**Comment by BerkeleyTrue** [comment]
@Bouncey nice work! :champagne:

**Comment by mstellaluna** [comment]
@Bouncey as per our conversation in chat, i'll try this out and get back to you.

**Comment by mstellaluna** [comment]
@Bouncey  I gave it a try. I tried multiple scenarios while I was at it. I only have two network throttling options in my version of chrome (Fast 3G and Slow 3G)

Scenario One: closing the laptop lid while local FCC was running (no bandwidth throttling)
- I accessed a challenge I haven't looked at, got the happy coding message
- Cleared my cookies and browser history
- Accessed a different challenge, no happy coding

Scenario Two: Enabled Fast 3G Network
- Refreshed FCC after changing network settings in chrome
- Accessed another couple of challenges I haven't loaded
- No happy coding

Scenario Three : Enabled Slow 3G Network
- Refreshed FCC after changing network settings in chrome
- Local FCC takes too long to load.

**Comment by raisedadead** [comment]
@mstellaluna This might help https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions to add more profiles.

@Bouncey could we add tests (maybe using Jest or whatever alternative is preferred) to make snapshots, and automate this?

**Comment by mstellaluna** [comment]
@raisedadead thanks
