### PR TITLE
fix(dev): preserve step order during hot reload by reloading all chal…

### LINKED ISSUE #61979: in local build edited steps loose order
When you build locally, the changes to steps while the server is active are reflected in the server.

before #61459 it worked as expected.

Now, if you change one step in a workshop, this step is moved at the end of the workshop.

The url to the step is correct, but the relative order of the steps from the grid view or moving from one step to the next is wrong.

https://github.com/user-attachments/assets/e0c3ae4e-c31a-4e99-a2c5-c07025e89ff2

### PR DESCRIPTION
**Pull request by niyati34**
…lenges on change/add\n\n- Trigger a full challenges reload when a markdown file changes or is added\n- Use curriculumPath, not a hardcoded english path\n- Mark replacements as reloads to bypass duplicate-id checks in dev\n\nAddresses regression where edited steps moved to the end in maps and nav

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or Gitpod.

Closes #61979

Summary

Fixes a regression where editing a single workshop step in dev moved it to the end of the grid and broke next/prev navigation.
Ensures ordering metadata stays consistent during Gatsby hot reload.
Background

After the top‑down curriculum refactor, the source plugin replaced only the edited node on file change, leaving sorting inconsistent in dev.

Changes

- On markdown file change or add, trigger a full challenges reload via the plugin’s source function.
- Use the provided curriculumPath (no hardcoded english path).
- Mark replacements as isReloading to bypass duplicate-id checks during dev.
- File: [gatsby-node.js]

How to test

- Start the client dev server.
- Open a superblock with a step grid.
- Edit any challenge .md in that block.

Verify:

- The step remains in place; grid order is correct.
- Next/prev navigation is unchanged and correct.

Risk/Performance

- Slightly heavier dev reload (full challenges reload) in exchange for correctness. Acceptable for dev; can be optimized later if needed.

Notes
i18n-safe by honoring curriculumPath.

### CODE REVIEW

**Comment by majestic-owl448** [comment]
> Risk/Performance
> 
> * Slightly heavier dev reload (full challenges reload) in exchange for correctness. Acceptable for dev; can be optimized later if needed.

the previous version, before https://github.com/freeCodeCamp/freeCodeCamp/pull/61459, managed to only recreate the single challenge (or that was the log shown in the terminal), is that not possible?

and if that is not possible, is it necessary to recreate everything? maybe a smaller batch? like just that block?

**Comment by niyati34** [comment]
> > Risk/Performance
> > 
> > * Slightly heavier dev reload (full challenges reload) in exchange for correctness. Acceptable for dev; can be optimized later if needed.
> 
> the previous version, before #61459, managed to only recreate the single challenge (or that was the log shown in the terminal), is that not possible?
> 
> and if that is not possible, is it necessary to recreate everything? maybe a smaller batch? like just that block?

- Great point — a full reload was heavier than needed. I’ve updated the plugin to reload only the affected block on file change/add, which keeps challengeOrder consistent without rebuilding everything.
- Recreating just the edited node turned out brittle with Gatsby’s dev data layer (ordering occasionally drifted). Block-scoped reload is a safe middle ground and mirrors where ordering is defined (meta.challengeOrder).
- If we still want to try single-node reload later, I can prototype it behind a flag as a follow‑up.

File: tools/client-plugins/gatsby-source-challenges/gatsby-node.js [hunk 1]
```diff
@@ -112,6 +106,8 @@ ${e.message}
       });
   }
 
+  // Full-reload path intentionally removed in favor of block-scoped reloads.
+
```
Comment (huyenltnguyen) [inline tools/client-plugins/gatsby-source-challenges/gatsby-node.js]:
```suggestion
```

**Review by huyenltnguyen — COMMENTED** [review]
Please help address the lint issue.

File: tools/client-plugins/gatsby-source-challenges/gatsby-node.js [hunk 2]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable import/no-unresolved */
```
Comment (ojeytonwilliams) [inline tools/client-plugins/gatsby-source-challenges/gatsby-node.js]:
```suggestion
```
We need this one.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Hi @niyati34, thanks for taking this on.

It shouldn't be necessary to recreate all the files.  I've not had chance to confirm, but it's likely just that this relied on properties that are no longer returned by `replaceChallenge`.

If you take a look at https://github.com/freeCodeCamp/freeCodeCamp/pull/62056 you can see a similar bug with a similar fix. In that case the page was not getting regenerated because `superBlock` was missing from the object returned by `replaceChallenge` and the fix was simply to add it back.

**Comment by niyati34** [comment]
> Please help address the lint issue.

Hi! The lint issue is resolved. The unused eslint-disable was removed and the file now lints cleanly. The “Full‑reload path…” comment is not present in the current code.

**Comment by niyati34** [comment]
> Hi @niyati34, thanks for taking this on.
> 
> It shouldn't be necessary to recreate all the files. I've not had chance to confirm, but it's likely just that this relied on properties that are no longer returned by `replaceChallenge`.
> 
> If you take a look at #62056 you can see a similar bug with a similar fix. In that case the page was not getting regenerated because `superBlock` was missing from the object returned by `replaceChallenge` and the fix was simply to add it back.

@ojeytonwilliams

Thanks for the pointer to #62056. I’ve implemented the same approach: single-node replacement with the missing metadata (superBlock, order, superOrder) restored so ordering stays correct. Re the eslint-disable: adding /* eslint-disable import/no-unresolved */ caused an “unused directive” lint warning and CI failed, since the current imports don’t trigger that rule. I’ve removed it and the file lints cleanly. If there’s a specific import you’re seeing that needs it, I can scope-disable just that line.

**Review by ojeytonwilliams — APPROVED** [review]
> If there’s a specific import you’re seeing that needs it, I can scope-disable just that line.

No, I wasn't thinking straight. You were absolutely right to remove it, thanks!

This looks great, nice work.

The only thing I can see that could be worth doing is to create a helper function and call it on 'add' and on 'change', since the code is identical now. If you want to make that change, please do, but we can merge regardless.

**Comment by niyati34** [comment]
> > If there’s a specific import you’re seeing that needs it, I can scope-disable just that line.
> 
> No, I wasn't thinking straight. You were absolutely right to remove it, thanks!
> 
> This looks great, nice work.
> 
> The only thing I can see that could be worth doing is to create a helper function and call it on 'add' and on 'change', since the code is identical now. If you want to make that change, please do, but we can merge regardless.

Thanks for the feedback! You're absolutely right about the code duplication. 

✅ **Refactored:** Extracted the duplicate logic into a `handleChallengeUpdate()` helper function that both 'add' and 'change' events now use.

**Benefits:**
- Eliminates ~27 lines of duplicate code
- Standardizes error handling and logging format  
- Makes the code more maintainable

The PR should be ready to merge now! 🎉

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Thanks again.

**Comment by niyati34** [comment]
@huyenltnguyen 
 Hi, I’ve resolved the issue and it’s been pending review for a few days now. Could you please prioritize reviewing it at the earliest?

**Review by moT01 — APPROVED** [review]
LGTM @niyati34 🎉 Thanks for contributing to freeCodeCamp 🎉
