### PR TITLE
fix(client): convert challengeFiles->files before sending to api

### LINKED ISSUE #43201: cannot submit JavaScript certification projects
Submitting JavaScript project solution isn't saved. Api request to `/modern-challenge-completed` ends up with error.

```
Original request: POST /modern-challenge-completed
Stack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildUserUpdate (/workspace/freeCodeCamp/api-server/src/server/boot/challenge.js:86:21)
    at /workspace/freeCodeCamp/api-server/src/server/boot/challenge.js:225:48
    at tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1762:31)
    at loopRecursive (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:2760:13)
    at Rx.internals.ScheduledItem.invokeRecImmediate [as action] (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:967:7)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:896:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:884:40)
    at runTrampoline (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1125:37)
    at tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at CurrentThreadScheduler.schedule (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1141:45)

// raw
{}
```

I've found one way to fix it - to add default value to `files` either in
https://github.com/freeCodeCamp/freeCodeCamp/blob/59f17f237ba2abfdef28a3cf1b4a9dba12de0eee/api-server/src/server/boot/challenge.js#L223
or 
https://github.com/freeCodeCamp/freeCodeCamp/blob/59f17f237ba2abfdef28a3cf1b4a9dba12de0eee/api-server/src/server/boot/challenge.js#L81
i.e.:
```
files = {}
```

## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/roman-numeral-converter
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register

## Additional context

Thread with report https://forum.freecodecamp.org/t/cant-claim-certificate-for-js-and-ds/473785/4

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43201

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
might be doing something wrong. but when I submit with the fix there are not error but the palindrome challenge does not shows up as complete when refreshed on another tab.

**Review by gikf — COMMENTED** [review]
This worked for me.

There's two other places where similar operation would make js solutions displayed again from certificate/settings.
https://github.com/freeCodeCamp/freeCodeCamp/blob/1786ce36853c5ec2a4cc2366106ee3429ab84cfe/client/src/client-only-routes/show-project-links.tsx#L59
https://github.com/freeCodeCamp/freeCodeCamp/blob/1786ce36853c5ec2a4cc2366106ee3429ab84cfe/client/src/components/settings/Certification.js#L170

**Review by 3zrv — APPROVED** [review]

**Review by naomi-lgbt — DISMISSED** [review]
Testing locally, confirmed we can submit solutions, claim the cert, and view the solutions.

Confirmed a non-authenticated user can view the solutions on a public cert as well.

File: client/src/utils/ajax.ts [hunk 1]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+};
+
+type UserResponseType = {
+  user: { [username: string]: UserType };
+  result: string;
+};
+
+function parseApiResponseToClientUser<T>(
+  data: ApiUser | (T & ApiUser)
+): UserResponseType {
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:85]:
```suggestion
function parseApiResponseToClientUser(data: ApiUser): UserResponseType {
```
T doesn't seem to be used.

File: client/src/utils/ajax.ts [hunk 2]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+  }
+  return {
+    user: { [data.result]: { ...userData, completedChallenges } },
+    result: data.result
+  };
 }
 
-export function getUserProfile(username: string): Promise<UserType> {
-  return get(`/api/users/get-public-profile?username=${username}`);
+export function getSessionUser(): Promise<SessionUser | null> {
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:112]:
```suggestion
export function getSessionUser(): Promise<SessionUser> {
```

File: client/src/utils/ajax.ts [hunk 3]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+type ApiSessionResponse = Omit<SessionUser, 'user'>;
+type ApiUser = {
+  user: {
+    [username: string]: ApiUserType;
+  };
+  result: string;
+};
+
+type ApiUserType = Omit<UserType, 'completedChallenges'> & {
+  completedChallenges: challengeFilesForFiles[];
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:75]:
```suggestion
  completedChallenges?: challengeFilesForFiles[];
```
Not all user objects have completedChallenges, it seems.

File: client/src/utils/ajax.ts [hunk 4]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+};
+
+function parseApiResponseToClientUser<T>(
+  data: ApiUser | (T & ApiUser)
+): UserResponseType {
+  const userData = data.user[data.result];
+  let completedChallenges: CompletedChallenge[] = [];
+  if (userData) {
+    completedChallenges =
+      userData.completedChallenges.reduce(
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:90]:
```suggestion
      userData.completedChallenges?.reduce(
```
Handling the missing challenges.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
We can simplify a bit further by just returning `user: { [username: string]: UserType };` objects, since `data.result` just comes along for the ride.

**Comment by ojeytonwilliams** [comment]
On the plus side, Cypress caught the profile `completedChallenges.reduce` bug.

File: client/src/utils/ajax.ts [hunk 5]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+    };
+  });
+}
+
+type UserProfileResponse = {
+  entities: Omit<UserResponseType, 'result'>;
+  result: string;
+};
+export function getUserProfile(username: string): Promise<UserProfileResponse> {
+  const response: Promise<{ entities: ApiUser; result: string }> = get(
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:132]:
```suggestion
  const response: Promise<{ entities?: ApiUser; result?: string }> = get(
```
The api will return `{}` if there isn't a user.

File: client/src/utils/ajax.ts [hunk 6]
```diff
@@ -51,16 +55,93 @@ async function request<T>(
...
+    `/api/users/get-public-profile?username=${username}`
+  );
+  return response.then(data => {
+    const { result, user } = parseApiResponseToClientUser({
+      user: data.entities.user,
```
Comment (ojeytonwilliams) [inline client/src/utils/ajax.ts:137]:
```suggestion
      user: data.entities?.user,
```

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
I think our types were misleading, since they didn't account for the possibility that the api returns `{}`.  If we make sure that property from the api is optional, we should be okay.

File: client/src/utils/ajax.ts (hunk 3 above)
Comment (ShaunSHamilton) [reply client/src/utils/ajax.ts:75]: Where are you seeing/getting this? How does that come about?

File: client/src/utils/ajax.ts (hunk 1 above)
Comment (ShaunSHamilton) [reply client/src/utils/ajax.ts:85]: T is used here: `L113: const response: Promise<ApiUser & ApiSessionResponse>` -> This is passed as `data`.

Comment (ojeytonwilliams) [reply client/src/utils/ajax.ts:85]: `ApiUser & ApiSessionResponse` is passed, sure, but `T` isn't used.  There are no calls to `parseApiResponseToClientUser<AType>`.

What's happening here is just that `ApiUser & ApiSessionResponse` can be used everywhere `ApiUser` can, `parseApiResponseToClientUser` just ignores the `ApiSessionResponse` properties.

File: client/src/utils/ajax.ts (hunk 3 above)
Comment (ojeytonwilliams) [reply client/src/utils/ajax.ts:75]: Since timelines can be private, the api doesn't always return this property.  See: https://github.com/freeCodeCamp/freeCodeCamp/blob/895987007f203379f5a0829311c8c45d55959052/api-server/src/common/models/user.js#L802-L812

Comment (ShaunSHamilton) [reply client/src/utils/ajax.ts:75]: But, what I am seeing is that it is always returned. It is just sometimes an empty array?

Comment (ojeytonwilliams) [reply client/src/utils/ajax.ts]: Sorry, I saw that completedChallenges could be undefined and just skimmed this code. It's the other return above.

**Review by moT01 — COMMENTED** [review]
I am still getting this when I first claim a cert...
Screen Shot 2021-08-17 at 10 31 02 AM

After a refresh, the solution loads.

**Comment by ShaunSHamilton** [comment]
> I am still getting this when I first claim a cert...
> After a refresh, the solution loads.

This is a long-standing issue with Redux/React - store state. The DB is updated, but until the page is refreshed, the `get-session-user` data is not pulled from the DB, so the store state is stale.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by naomi-lgbt — APPROVED** [review]

**Comment by nhcarrigan** [comment]
@moT01 are you good with this too?

**Review by moT01 — APPROVED** [review]
LGTM 🎉
