### PR TITLE
Fix video challenge submission

### LINKED ISSUE #8455: Video Challenges - Computer Basics not recording completion
#### Challenge Name
Video Challenges - Computer Basics

https://www.freecodecamp.com/videos/computer-basics-how-to-measure-data-size

#### Issue Description

I have watched How to Measure Data Size and answered the questions 3 times now and it is not marking it as complete.  Same thing with Measuring Data Speed.

#### Browser Information

* Browser Name, Version: Google Chrome 50.0.2661.94 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

### PR DESCRIPTION
**Pull request by arialaurel**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.
#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (e.g. `Closes #XXXX`): Closes #8455
#### Description

I'm injecting the csrf token into the react app and sending it with ajax requests. This should fix video challenge submission.

@BerkeleyTrue Give this a look when you have a chance. If you have any feedback I'm happy to alter my approach.

### CODE REVIEW

File: server/middlewares/global-locals.js [hunk 1]
```diff
@@ -3,6 +3,9 @@ export default function globalLocals() {
     // Make user object available in templates.
     res.locals.user = req.user;
     res.locals._csrf = req.csrfToken ? req.csrfToken() : null;
+    if (req.csrfToken) {
+      res.expose({ token: res.locals._csrf }, 'csrf');
```
Comment (BerkeleyTrue) [inline server/middlewares/global-locals.js]: 👍

**Comment by BerkeleyTrue** [comment]
Nice work @ltegman, as usual! I'll pull it down later today after my meeting.

**Comment by BerkeleyTrue** [comment]
👍
